# Tarea 2 - Taller de Deep Learning

**Fecha de entrega: 16/11/2025**  
**Puntaje máximo: 15**

## Introducción

El objetivo de esta tarea es evaluar su capacidad para aplicar modelos de redes neuronales recurrentes (RNN/LSTM/GRU) en un problema de clasificación de secuencias. En particular, vamos a evaluar la performance de sus modelos en la clasificación de ritmos cardíacos usando datos de electrocardiograma (ECG).

**Dataset**

El dataset a ser utilizado es el [Heartbeat Dataset](https://www.kaggle.com/datasets/shayanfazeli/heartbeat). Este dataset contiene señales de ECG segmentadas, donde cada segmento corresponde a un latido del corazón. Cada segmento ya está preprocesado y categorizado en una de las siguientes clases:

- **N**: Normal (0)
- **S**: Arritmia supraventricular (1)
- **V**: Arritmia ventricular (2)
- **F**: Latido fusionado (3)
- **Q**: Latido desconocido (4)

Los archivos del dataset que deben utilizar son:

- **mitbih_train.csv**: Datos de entrenamiento.
- **mitbih_test.csv**: Datos de prueba.

**Tarea**

Tienen total libertad sobre cómo implementar y resolver el problema, así como las técnicas y herramientas que quieran usar. Se recomienda el uso de Google Colab para simplificar el acceso a recursos de GPU, aunque pueden trabajar en sus propias máquinas si lo prefieren. La entrega debe realizarse en formato .ipynb (Jupyter Notebook) **con las celdas ya ejecutadas**.

**Restricciones**

- No se permite utilizar modelos pre-entrenados; cada modelo debe ser implementado desde cero.
- Deben utilizar al menos un modelo basado en RNN (por ejemplo, LSTM o GRU).
- Es necesario realizar un **análisis exploratorio de los datos**, que incluya una descripción de las señales ECG, el balanceo de clases y cualquier limpieza o transformación necesaria de los datos.
- Las decisiones sobre el preprocesamiento de las señales (como normalización, segmentación, etc.) deben estar fundamentadas en una exploración inicial del dataset y explicadas en el notebook.

**Reporte**

Se requiere que reporten las siguientes métricas: accuracy, precision, recall y F1-score para la evaluación del modelo. Además, se espera ver una evolución clara del modelo durante el entrenamiento, que incluya logs y gráficas de las métricas tanto para los datos de entrenamiento como de validación.

**Evidencia de Experimentos**

Deben proporcionar evidencia de la ejecución de experimentos usando [Weights & Biases (wandb)](https://wandb.ai/). Esto incluye:

- Registros detallados de los experimentos.
- Gráficas y logs de entrenamiento.
- Comparaciones entre diferentes configuraciones de modelos.

# Librerías

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split

from torchinfo import summary

import pandas as pd
import numpy as np

import os
import sys
import tarfile
import urllib.request
import re
from pathlib import Path
from collections import Counter
from itertools import chain

# from utils import (
#     train,
# )

# Datasets

In [2]:
# pip install kagglehub

In [3]:
os.getcwd()

'c:\\Users\\Matías\\Desktop\\Rodrigo\\Repos\\ORT-AI\\Deep Learning\\Taller de DL\\Tareas\\Tarea 2'

In [4]:
# import kagglehub
# import shutil

# # Descargar dataset
# path = kagglehub.dataset_download("shayanfazeli/heartbeat")

# # Crear carpeta "data" si no existe
# os.makedirs("data", exist_ok=True)

# # Nuevo destino
# dest = os.path.join("data", os.path.basename(path))

# # Mover carpeta descargada a "data"
# shutil.move(path, dest)

# print("Dataset guardado en:", dest)

In [5]:
train_data = pd.read_csv('data/mitbih_train.csv', header=None)
test_data = pd.read_csv('data/mitbih_test.csv', header=None)

In [6]:
train_data.head()

,0,1,2,3,4,5,6,7,8,9,...,178,179,180,181,182,183,184,185,186,187
0,0.977941,0.926471,0.681373,0.245098,0.154412,0.191176,0.151961,0.085784,0.058824,0.049020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.960114,0.863248,0.461538,0.196581,0.094017,0.125356,0.099715,0.088319,0.074074,0.082621,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.000000,0.659459,0.186486,0.070270,0.070270,0.059459,0.056757,0.043243,0.054054,0.045946,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.925414,0.665746,0.541436,0.276243,0.196133,0.077348,0.071823,0.060773,0.066298,0.058011,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.967136,1.000000,0.830986,0.586854,0.356808,0.248826,0.145540,0.089202,0.117371,0.150235,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
test_data.head()

,0,1,2,3,4,5,6,7,8,9,...,178,179,180,181,182,183,184,185,186,187
0,1.000000,0.758264,0.111570,0.000000,0.080579,0.078512,0.066116,0.049587,0.047521,0.035124,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.908425,0.783883,0.531136,0.362637,0.366300,0.344322,0.333333,0.307692,0.296703,0.300366,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.730088,0.212389,0.000000,0.119469,0.101770,0.101770,0.110619,0.123894,0.115044,0.132743,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.000000,0.910417,0.681250,0.472917,0.229167,0.068750,0.000000,0.004167,0.014583,0.054167,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.570470,0.399329,0.238255,0.147651,0.000000,0.003356,0.040268,0.080537,0.070470,0.090604,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
train_data.rename(columns={187: 'class'}, inplace=True)

id_to_label = {
    0: "Normal",
    1: "Artial Premature",
    2: "Premature ventricular contraction",
    3: "Fusion of ventricular and normal",
    4: "Fusion of paced and normal"
}
train_data['label'] = train_data.iloc[:, -1].map(id_to_label)
print(train_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87554 entries, 0 to 87553
Columns: 189 entries, 0 to label
dtypes: float64(188), object(1)
memory usage: 126.2+ MB
None

In [9]:
test_data.rename(columns={187: 'class'}, inplace=True)

id_to_label = {
    0: "Normal",
    1: "Artial Premature",
    2: "Premature ventricular contraction",
    3: "Fusion of ventricular and normal",
    4: "Fusion of paced and normal"
}
test_data['label'] = test_data.iloc[:, -1].map(id_to_label)
print(test_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21892 entries, 0 to 21891
Columns: 189 entries, 0 to label
dtypes: float64(188), object(1)
memory usage: 31.6+ MB
None

In [10]:
test_data.head()

,0,1,2,3,4,5,6,7,8,9,...,179,180,181,182,183,184,185,186,class,label
0,1.000000,0.758264,0.111570,0.000000,0.080579,0.078512,0.066116,0.049587,0.047521,0.035124,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Normal
1,0.908425,0.783883,0.531136,0.362637,0.366300,0.344322,0.333333,0.307692,0.296703,0.300366,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Normal
2,0.730088,0.212389,0.000000,0.119469,0.101770,0.101770,0.110619,0.123894,0.115044,0.132743,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Normal
3,1.000000,0.910417,0.681250,0.472917,0.229167,0.068750,0.000000,0.004167,0.014583,0.054167,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Normal
4,0.570470,0.399329,0.238255,0.147651,0.000000,0.003356,0.040268,0.080537,0.070470,0.090604,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Normal

# EDA

## Distribución de clases

In [11]:
import plotly.express as px

# Crear el conteo y reset index con nombres claros
class_counts = train_data['label'].value_counts().reset_index()
class_counts.columns = ['Class', 'Count']  # Renombrar columnas explícitamente

# Calcular porcentaje y formatear como label
total = class_counts['Count'].sum()
class_counts['Percent'] = class_counts['Count'] / total * 100
class_counts['Label'] = class_counts['Percent'].map(lambda x: f'{x:.1f}%')

fig = px.bar(
    class_counts,
    x='Class',
    y='Count',
    color='Class',  # Cada clase de un color distinto
    title='Number of samples per class',
    color_discrete_sequence=px.colors.qualitative.Safe,  # Paleta de colores distinta por clase
    text='Label'  # Usar la columna de porcentaje como data label
)

fig.update_traces(
    textposition='outside',  # Ubica el label fuera (arriba) del extremo de la barra
    textfont_size=14,
    texttemplate='%{text}',  # Solo mostrar el texto (el porcentaje)
    insidetextanchor='middle'
)

fig.update_layout(
    uniformtext_minsize=12,  # Asegura tamaño uniforme
    uniformtext_mode='hide',
    xaxis_title='Class',
    yaxis_title='Count',
    height=600  # <-- Aumenta la altura del gráfico para que no se corte
)

fig.show()

## ECG por clase

In [12]:
# Seleccionar columnas de tiempo
value_columns = [col for col in train_data.columns if col not in ['class', 'label']]

num_samples = 10
dfs = []
for class_name in train_data['label'].unique():
    samples = train_data[train_data['label'] == class_name].sample(n=num_samples, random_state=42)
    samples = samples[value_columns].reset_index(drop=True)
    samples['Muestra'] = samples.index  # id de muestra correcto por fila
    df_long = samples.melt(id_vars='Muestra', var_name='Tiempo', value_name='Valor')
    df_long['Clase'] = class_name
    dfs.append(df_long)

plot_df = pd.concat(dfs, ignore_index=True)

# Asegurar tiempo numérico y ordenado
try:
    plot_df['Tiempo'] = plot_df['Tiempo'].astype(float)
except Exception:
    pass
plot_df = plot_df.sort_values(['Clase', 'Muestra', 'Tiempo'])

fig = px.line(
    plot_df,
    x='Tiempo',
    y='Valor',
    color='Muestra',
    facet_row='Clase',
    facet_row_spacing=0.07,
    line_group='Muestra',
    height=300 * len(train_data['label'].unique()),
    title="10 muestras aleatorias de cada clase",
)

fig.update_traces(opacity=0.5, showlegend=False)
fig.update_yaxes(title_text='Valor')
fig.update_xaxes(title_text='Tiempo', matches='x')
fig.update_layout(showlegend=False)
fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
fig.show()

* Valores faltantes/constantes, rango global de amplitudes.
* Estadísticos por muestra y por clase: media, mediana, std, IQR, min/max, skewness, kurtosis.
*

## Amplitud de ECG por clase

In [13]:
def analyze_ecg_amplitude_by_class(
    df,
    label_col: str = 'label',
    value_columns: list[str] | None = None,
    plot: bool = True,
    return_sample_metrics: bool = False,
):
    """
    Analiza la amplitud (pico-a-pico) de latidos ECG por clase.

    - Calcula por muestra: mínimo, máximo y amplitud pico-a-pico (max - min)
    - Agrega por clase: count, mean, std, median, p25, p75, min, max
    - Opcionalmente grafica la distribución por clase (violin y box)

    Args:
        df: DataFrame con columnas de señal (tiempo) y columna de etiqueta.
        label_col: Nombre de la columna con la clase (por defecto 'label').
        value_columns: Lista de columnas de tiempo. Si es None, se infiere
            como todas las columnas excepto {label_col, 'class'}.
        plot: Si True, muestra gráficos de distribución por clase.
        return_sample_metrics: Si True, también devuelve métricas por muestra.

    Returns:
        summary_df si return_sample_metrics == False
        (summary_df, sample_metrics_df) si return_sample_metrics == True
    """
    # Inferir columnas de señal si no se especifican
    if value_columns is None:
        excluded = {label_col, 'class'}
        value_columns = [c for c in df.columns if c not in excluded]

    # Asegurar datos numéricos y calcular métricas por muestra
    signal_matrix = df[value_columns].to_numpy(dtype=float)
    per_sample_min = signal_matrix.min(axis=1)
    per_sample_max = signal_matrix.max(axis=1)
    per_sample_ptp = per_sample_max - per_sample_min  # pico-a-pico

    sample_metrics_df = pd.DataFrame(
        {
            'min_amplitude': per_sample_min,
            'max_amplitude': per_sample_max,
            'peak_to_peak': per_sample_ptp,
            label_col: df[label_col].to_numpy(),
        }
    )

    # Agregación por clase
    def p25(series: pd.Series) -> float:
        return float(np.percentile(series, 25))

    def p75(series: pd.Series) -> float:
        return float(np.percentile(series, 75))

    summary_df = (
        sample_metrics_df.groupby(label_col)['peak_to_peak']
        .agg(
            count='count',
            mean='mean',
            std='std',
            median='median',
            p25=p25,
            p75=p75,
            min='min',
            max='max',
        )
        .reset_index()
        .sort_values(label_col)
    )

    # Gráficos opcionales, con distinción de colores por clase
    if plot:
        # Construir una paleta de colores distinta por cada clase
        unique_classes = sample_metrics_df[label_col].unique()
        color_map = px.colors.qualitative.Plotly  # O puede usarse otra paleta si hay más clases
        color_discrete_map = {
            clase: color_map[i % len(color_map)] for i, clase in enumerate(sorted(unique_classes))
        }

        violin_fig = px.violin(
            sample_metrics_df,
            x=label_col,
            y='peak_to_peak',
            box=True,
            points='outliers',
            labels={label_col: 'Clase', 'peak_to_peak': 'Amplitud pico-a-pico'},
            title='Distribución de amplitud pico-a-pico por clase',
            color=label_col,  # Esto asigna color por clase
            color_discrete_map=color_discrete_map  # Mapea clase a color de la paleta
        )
        violin_fig.show()

    return (summary_df, sample_metrics_df) if return_sample_metrics else summary_df

In [14]:
train_data["label"].unique()

array(['Normal', 'Artial Premature', 'Premature ventricular contraction',
       'Fusion of ventricular and normal', 'Fusion of paced and normal'],
      dtype=object)

In [15]:
summary = analyze_ecg_amplitude_by_class(train_data, label_col='label', plot=True)

In [16]:
def ecg_duration_by_zero_runs(
    df,
    label_col: str = 'label',
    value_columns: list[str] | None = None,
    min_zero_run: int = 5,
    zero_tol: float = 0.0,
    fs_hz: float | None = None,
    plot: bool = True,
    return_sample_metrics: bool = False,
):
    """
    Calcula la *duración* por muestra aplicando la regla:
      - Buscar el primer run de >= `min_zero_run` ceros consecutivos; la duración es
        el índice de inicio de ese run (tiempo máximo).
      - Si no existe, usar el índice del último dato disponible (último no-NaN).

    Si `fs_hz` se provee, devuelve la duración en segundos (idx / fs_hz),
    si no, en número de muestras (índice).

    Args:
        df: DataFrame con columnas de señal (tiempo) y etiqueta.
        label_col: Nombre de la columna de etiquetas.
        value_columns: Columnas de tiempo; si None, se infiere excluyendo {label_col, 'class'}.
        min_zero_run: Largo mínimo del run de ceros consecutivos a detectar.
        zero_tol: Tolerancia para considerar un valor como cero (|x| <= tol).
        fs_hz: Frecuencia de muestreo; si None, duración en muestras.
        plot: Si True, grafica histograma por clase.
        return_sample_metrics: Si True, retorna también el DataFrame por muestra.

    Returns:
        summary_df (por clase) o (summary_df, sample_df) si return_sample_metrics=True.
    """
    import numpy as np
    import pandas as pd

    if value_columns is None:
        excluded = {label_col, 'class'}
        value_columns = [c for c in df.columns if c not in excluded]

    signals = df[value_columns].to_numpy(dtype=float)

    def first_zero_run_start(vec: np.ndarray) -> int:
        is_finite = np.isfinite(vec)
        # Índices válidos (no NaN)
        valid_idx = np.where(is_finite)[0]
        if valid_idx.size == 0:
            return 0  # sin datos válidos
        # Run de ceros con tolerancia
        is_zero = is_finite & (np.abs(vec) <= zero_tol)
        if is_zero.any() and min_zero_run > 1:
            win = np.ones(min_zero_run, dtype=int)
            conv = np.convolve(is_zero.astype(int), win, mode='valid')
            hits = np.where(conv == min_zero_run)[0]
            if hits.size > 0:
                return int(hits[0])
        elif is_zero.any() and min_zero_run <= 1:
            return int(np.where(is_zero)[0][0])
        # Si no hay run suficiente, usar último índice válido (no-NaN)
        return int(valid_idx[-1])

    idxs = np.apply_along_axis(first_zero_run_start, 1, signals)

    if fs_hz is not None:
        durations = idxs.astype(float) / float(fs_hz)
        metric = 'duration_sec'
    else:
        durations = idxs.astype(int)
        metric = 'duration_samples'

    sample_df = pd.DataFrame({
        metric: durations,
        label_col: df[label_col].to_numpy(),
    })

    # Resumen por clase
    def p25(x):
        return float(np.percentile(x, 25))
    def p75(x):
        return float(np.percentile(x, 75))

    summary_df = (
        sample_df.groupby(label_col)[metric]
        .agg(count='count', mean='mean', std='std', median='median', p25=p25, p75=p75, min='min', max='max')
        .reset_index()
        .sort_values(label_col)
    )

    if plot:
        import plotly.express as px
        fig = px.histogram(
            sample_df,
            x=metric,
            color=label_col,
            barmode='overlay',
            opacity=0.65,
            nbins=40,
            labels={metric: ('Duración (s)' if fs_hz else 'Duración (muestras)'), label_col: 'Clase'},
            title='Histograma de duración por clase (regla de 5 ceros consecutivos)'
        )
        fig.show()

    return (summary_df, sample_df) if return_sample_metrics else summary_df

In [17]:
summary = ecg_duration_by_zero_runs(train_data, label_col='label', min_zero_run=5, zero_tol=0.0, fs_hz=360, plot=True)
summary

,label,count,mean,std,median,p25,p75,min,max
0,Artial Premature,2223,0.316108,0.108434,0.297222,0.263889,0.375000,0.061111,0.516667
1,Fusion of paced and normal,6431,0.328546,0.027077,0.333333,0.322222,0.341667,0.086111,0.516667
2,Fusion of ventricular and normal,641,0.218963,0.038641,0.216667,0.205556,0.225000,0.080556,0.516667
3,Normal,72471,0.307796,0.075528,0.294444,0.258333,0.352778,0.000000,0.516667
4,Premature ventricular contraction,5788,0.328157,0.096936,0.316667,0.263889,0.391667,0.069444,0.516667

## Duración de ECG por clase

In [18]:
# Duración = índice (1-based) de la última columna con valor > zero_tol; 0 si no hay valores > zero_tol
def calcular_duracion_por_ultimo_no_cero(row, zero_tol: float = 0.0):
    arr = row.values.astype(float)
    nz_idx = np.where(arr > zero_tol)[0]
    return int(nz_idx[-1] + 1) if nz_idx.size else 0

# Determinar columnas de señal si no existen previamente
try:
    signal_cols
except NameError:
    signal_cols = [c for c in train_data.columns if c not in ['class', 'label']]

# Aplicar lógica y escribir la duración
train_data['duracion_no_ceros'] = train_data[signal_cols].apply(
    calcular_duracion_por_ultimo_no_cero, axis=1
)

In [19]:
# Ajusta la opción de pandas para mostrar todas las columnas
pd.set_option('display.max_columns', None)


train_data.sort_values(by='duracion_no_ceros').head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,class,label,duracion_no_ceros
44608,1.0,0.919048,0.811905,0.473810,0.295238,0.211905,0.180952,0.135714,0.142857,0.121429,0.000000,0.128571,0.073810,0.078571,0.097619,0.090476,0.140476,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Normal,17
42566,1.0,0.988372,0.738372,0.398256,0.133721,0.101744,0.084302,0.127907,0.058140,0.040698,0.023256,0.052326,0.000000,0.017442,0.040698,0.078488,0.052326,0.063953,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Normal,18
13028,0.0,0.050505,0.333333,0.464646,0.777778,0.878788,0.868687,0.878788,0.868687,0.888889,0.919192,0.868687,0.878788,0.929293,0.919192,0.888889,0.989899,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Normal,18
18035,1.0,0.393939,0.056277,0.129870,0.095238,0.086580,0.077922,0.103896,0.086580,0.095238,0.095238,0.086580,0.082251,0.099567,0.095238,0.116883,0.099567,0.069264,0.073593,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Normal,19
10817,1.0,0.928571,0.719388,0.354592,0.130102,0.132653,0.063776,0.071429,0.000000,0.012755,0.015306,0.012755,0.012755,0.017857,0.010204,0.020408,0.035714,0.045918,0.048469,0.071429,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Normal,20

In [20]:
import plotly.express as px

fig = px.histogram(
    train_data, 
    x="duracion_no_ceros", 
    color="label", 
    barmode="overlay", 
    nbins=40,
    title="Histograma de duración ECG por clase",
    labels={"duracion_no_ceros": "Duración", "label": "Clases"}
)
fig.show()

# Balanceo de clases ??

* Oversampling de minoritarias (con reposición) + BalancedBatchSampler.

* Undersampling leve de la mayoritaria (con cuidado para no perder variabilidad).

* Augmentación 1D específica para ECG (aplicar solo a minoritarias):
    * Jitter: añadir ruido gaussiano bajo (σ≈0.01–0.05 del rango).
        def augment_ecg(signal):
            noise = np.random.normal(0, 0.01, signal.shape)
            return signal + noise

    * Escalado de amplitud: multiplicar por 0.9–1.1. (skippear casos = 1)

    * Time shift: desplazar pocos samples (con padding).

    * Permutación de 3–6 sub-segmentos cortos (muy leve).
    
    * Inversión o distorsión ligera

## Submuestra de la clase mayoritaria

In [21]:
def undersample_majority(df, label_col='label', ratio=None, target=None, random_state=42):
    """
    - Si ratio se da: reduce la mayoritaria a floor(minority_count * ratio)
    - Si target=int: reduce la mayoritaria a 'target'
    - Por defecto: balancea a la menor (target = minority_count)
    """
    counts = df[label_col].value_counts()
    if counts.empty or len(counts) == 1:
        return df.copy()

    majority_class = counts.idxmax()
    minority_count = counts.drop(majority_class).min()

    if ratio is not None:
        target_count = int(minority_count * ratio)
    elif isinstance(target, int):
        target_count = min(target, counts[majority_class])
    else:
        target_count = minority_count  # balance 1:1

    majority_df = df[df[label_col] == majority_class].sample(
        n=target_count, random_state=random_state
    )
    rest_df = df[df[label_col] != majority_class]

    out = pd.concat([rest_df, majority_df], axis=0)
    out = out.sample(frac=1, random_state=random_state).reset_index(drop=True)
    return out

In [22]:
train_data_us = undersample_majority(train_data, label_col='label', target=35000)

# Verificación
print("Antes de la sub-muestra:\n", train_data['label'].value_counts(), "\n")
print("Después de la sub-muestra:\n", train_data_us['label'].value_counts())

Antes de la sub-muestra:
 label
Normal                               72471
Fusion of paced and normal            6431
Premature ventricular contraction     5788
Artial Premature                      2223
Fusion of ventricular and normal       641
Name: count, dtype: int64

Después de la sub-muestra:
 label
Normal                               35000
Fusion of paced and normal            6431
Premature ventricular contraction     5788
Artial Premature                      2223
Fusion of ventricular and normal       641
Name: count, dtype: int64

## Oversampling de las clases minoritarias

In [23]:
def oversample_minorities(
    df: pd.DataFrame,
    label_col: str = 'label',
    strategy: str = 'to_majority',  # 'to_majority' | 'ratio' | 'fixed'
    ratio: float | None = None,     # ej. 0.8 -> 80% del tamaño de la mayoritaria
    target: int | None = None,      # ej. 12000 -> tamaño fijo por clase
    random_state: int = 42,
) -> pd.DataFrame:
    """
    Oversamplea solo las clases minoritarias.
    - strategy='to_majority': sube todas las clases al tamaño de la mayoritaria (1:1).
    - strategy='ratio': sube todas las clases a int(majority_count * ratio).
    - strategy='fixed': sube todas las clases a 'target'.
    """
    counts = df[label_col].value_counts()
    if counts.empty or len(counts) == 1:
        return df.copy()

    majority_count = counts.max()

    if strategy == 'to_majority':
        target_count = majority_count
    elif strategy == 'ratio':
        if ratio is None or ratio <= 0:
            raise ValueError("Debes pasar un 'ratio' > 0 para strategy='ratio'.")
        target_count = int(majority_count * ratio)
    elif strategy == 'fixed':
        if target is None or target <= 0:
            raise ValueError("Debes pasar 'target' > 0 para strategy='fixed'.")
        target_count = target
    else:
        raise ValueError("strategy debe ser 'to_majority', 'ratio' o 'fixed'.")

    parts = []
    for cls, cnt in counts.items():
        cls_df = df[df[label_col] == cls]
        if cnt >= target_count:
            parts.append(cls_df)
        else:
            # tomar todo lo original + muestrear con reposición lo faltante
            needed = target_count - cnt
            sampled = cls_df.sample(n=needed, replace=True, random_state=random_state)
            parts.append(pd.concat([cls_df, sampled], axis=0))

    out = pd.concat(parts, axis=0).sample(frac=1, random_state=random_state).reset_index(drop=True)
    return out

In [24]:
# Llevar todas las clases al 80% del tamaño de la mayoritaria
train_data_us_os = oversample_minorities(train_data_us, label_col='label', strategy='ratio', ratio=0.1)

# Verificación
print("Antes de over y under sampling:\n", train_data['label'].value_counts(), "\n")
print("Después de over y under sampling:\n", train_data_us_os['label'].value_counts())

Antes de over y under sampling:
 label
Normal                               72471
Fusion of paced and normal            6431
Premature ventricular contraction     5788
Artial Premature                      2223
Fusion of ventricular and normal       641
Name: count, dtype: int64

Después de over y under sampling:
 label
Normal                               35000
Fusion of paced and normal            6431
Premature ventricular contraction     5788
Artial Premature                      3500
Fusion of ventricular and normal      3500
Name: count, dtype: int64

## Data Augmentation para clases minoritarias

In [25]:
def jitter_signal(x: np.ndarray, sigma: float = 0.02, rng: np.random.Generator | None = None) -> np.ndarray:
    """Añade ruido gaussiano con desv. std relativa al std de la señal (suave)."""
    rng = np.random.default_rng(rng)
    x = np.asarray(x, dtype=float)
    noise = rng.normal(0.0, sigma * (np.std(x) + 1e-8), size=x.shape)
    return (x + noise).astype(x.dtype)


def scale_amplitude(x: np.ndarray, scale_range: tuple[float, float] = (0.9, 1.1), rng: np.random.Generator | None = None) -> np.ndarray:
    """Escala amplitud por un factor uniforme dentro de scale_range."""
    rng = np.random.default_rng(rng)
    x = np.asarray(x, dtype=float)
    factor = rng.uniform(scale_range[0], scale_range[1])
    return (x * factor).astype(x.dtype)


def time_shift_signal(
    x: np.ndarray,
    max_shift: int = 5,
    pad_mode: str = 'reflect',  # 'reflect' | 'constant'
    constant_value: float = 0.0,
    rng: np.random.Generator | None = None,
) -> np.ndarray:
    """Desplaza la señal en el tiempo (no circular)."""
    rng = np.random.default_rng(rng)
    x = np.asarray(x, dtype=float)
    n = len(x)
    if max_shift <= 0:
        return x
    shift = int(rng.integers(-max_shift, max_shift + 1))
    if shift == 0:
        return x

    if shift > 0:  # desplazar a la derecha => rellenar al inicio
        pad = x[:shift][::-1] if pad_mode == 'reflect' else np.full(shift, constant_value)
        y = np.concatenate([pad, x[:-shift]])
    else:  # desplazar a la izquierda => rellenar al final
        s = abs(shift)
        pad = x[-s:][::-1] if pad_mode == 'reflect' else np.full(s, constant_value)
        y = np.concatenate([x[s:], pad])
    return y.astype(x.dtype)


def permute_subsegments(
    x: np.ndarray,
    k_range: tuple[int, int] = (3, 6),
    min_len: int = 10,
    rng: np.random.Generator | None = None,
) -> np.ndarray:
    """Corta la señal en k trozos contiguos (k en [k_min,k_max]) y los reordena."""
    rng = np.random.default_rng(rng)
    x = np.asarray(x, dtype=float)
    n = len(x)
    k = int(rng.integers(k_range[0], k_range[1] + 1))
    # elegir k-1 cortes evitando segmentos demasiado cortos
    if n < (k * min_len):
        return x  # no hay espacio suficiente
    valid_cuts = np.arange(min_len, n - min_len)
    cuts = np.sort(rng.choice(valid_cuts, size=k - 1, replace=False))
    idxs = np.concatenate([[0], cuts, [n]])
    segs = [x[idxs[i]:idxs[i + 1]] for i in range(len(idxs) - 1) if (idxs[i + 1] - idxs[i]) >= min_len]
    if len(segs) <= 1:
        return x
    order = rng.permutation(len(segs))
    return np.concatenate([segs[i] for i in order]).astype(x.dtype)


# --------- Wrapper para aplicar a clases minoritarias en un DataFrame ---------

def augment_minority_classes(
    df: pd.DataFrame,
    label_col: str = 'label',
    value_columns: list[str] | None = None,
    strategy: str = 'to_majority',  # 'to_majority' | 'ratio' | 'fixed'
    ratio: float | None = None,
    target: int | None = None,
    transforms: list | None = None,
    random_state: int = 42,
) -> pd.DataFrame:
    """
    Genera nuevos ejemplos de las clases minoritarias aplicando aleatoriamente una
    de las transformaciones definidas arriba a filas existentes (con reposición).

    - strategy='to_majority': sube minoritarias al tamaño de la mayoritaria.
    - strategy='ratio': sube minoritarias a int(majority_count * ratio).
    - strategy='fixed': sube minoritarias a 'target'.
    """
    rng = np.random.default_rng(random_state)

    if value_columns is None:
        excluded = {label_col, 'class'}
        value_columns = [c for c in df.columns if c not in excluded]

    counts = df[label_col].value_counts()
    if counts.empty or len(counts) == 1:
        return df.copy()

    majority_count = counts.max()
    if strategy == 'to_majority':
        target_count = majority_count
    elif strategy == 'ratio':
        if ratio is None or ratio <= 0:
            raise ValueError("Debes pasar ratio>0 para strategy='ratio'.")
        target_count = int(majority_count * ratio)
    elif strategy == 'fixed':
        if target is None or target <= 0:
            raise ValueError("Debes pasar target>0 para strategy='fixed'.")
        target_count = target
    else:
        raise ValueError("strategy debe ser 'to_majority' | 'ratio' | 'fixed'.")

    if not transforms:
        transforms = [
            lambda x: jitter_signal(x, sigma=0.02, rng=rng),
            lambda x: scale_amplitude(x, scale_range=(0.9, 1.1), rng=rng),
            lambda x: time_shift_signal(x, max_shift=5, pad_mode='reflect', rng=rng),
            lambda x: permute_subsegments(x, k_range=(3, 6), min_len=10, rng=rng),
        ]

    parts = [df]

    for cls, cnt in counts.items():
        if cnt >= target_count:
            continue  # no es minoritaria con respecto al objetivo
        cls_df = df[df[label_col] == cls]
        needed = target_count - cnt
        # muestrear índices base con reposición
        base_idx = cls_df.sample(n=needed, replace=True, random_state=int(rng.integers(0, 1e9))).index
        augmented_rows = []
        for idx in base_idx:
            row = df.loc[idx]
            sig = row[value_columns].to_numpy(dtype=float)
            # elegir una transformación al azar
            t = transforms[int(rng.integers(0, len(transforms)))]
            sig_aug = t(sig)
            new_row = row.copy()
            new_row[value_columns] = sig_aug
            augmented_rows.append(new_row)
        if augmented_rows:
            parts.append(pd.DataFrame(augmented_rows))

    out = pd.concat(parts, axis=0).sample(frac=1.0, random_state=int(rng.integers(0, 1e9))).reset_index(drop=True)
    return out

In [26]:
# Ejemplos de uso:
# train_data_us_os_da = augment_minority_classes(train_data_us_os, label_col='label', strategy='to_majority')
train_data_us_os_da = augment_minority_classes(train_data_us_os, label_col='label', strategy='ratio', ratio=0.05)
# train_data_us_os_da = augment_minority_classes(train_data_us_os, label_col='label', strategy='fixed', target=10000)

In [27]:
def verify_class_balance(df_before, df_after, label_col='label'):
    before = df_before[label_col].value_counts().sort_index()
    after = df_after[label_col].value_counts().sort_index()
    comp = pd.DataFrame({
        'before': before,
        'after': after,
        'delta': (after - before)
    })
    comp['before_pct'] = (comp['before'] / comp['before'].sum() * 100).round(1)
    comp['after_pct']  = (comp['after']  / comp['after'].sum()  * 100).round(1)
    print(comp.fillna(0).astype({'before':'int64','after':'int64','delta':'int64'}))

# Ejemplos:
verify_class_balance(train_data, train_data_us_os_da)   # oversampling / augmentación

                                   before  after  delta  before_pct  after_pct
label
Artial Premature                     2223   3500   1277         2.5        6.5
Fusion of paced and normal           6431   6431      0         7.3       11.9
Fusion of ventricular and normal      641   3500   2859         0.7        6.5
Normal                              72471  35000 -37471        82.8       64.6
Premature ventricular contraction    5788   5788      0         6.6       10.7

# Entrenamientos

* Sampler ponderado (WeightedRandomSampler) para batches balanceados.
* Regularización (dropout, weight decay) para evitar overfit por oversampling.
* Class weights (https://discuss.pytorch.org/t/passing-the-weights-to-crossentropyloss-correctly/14731)

In [28]:
# Fijamos la semilla para que los resultados sean reproducibles
SEED = 23

torch.manual_seed(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

In [29]:
# definimos el dispositivo que vamos a usar
DEVICE = "cpu"  # por defecto, usamos la CPU
if torch.cuda.is_available():
    DEVICE = "cuda"  # si hay GPU, usamos la GPU
elif torch.backends.mps.is_available():
    DEVICE = "mps"  # si no hay GPU, pero hay MPS, usamos MPS
elif torch.xpu.is_available():
    DEVICE = "xpu"  # si no hay GPU, pero hay XPU, usamos XPU

print(f"Usando {DEVICE}")

NUM_WORKERS = 0 # Win y MacOS pueden tener problemas con múltiples workers
if sys.platform == 'linux':
    NUM_WORKERS = 4  # numero de workers para cargar los datos (depende de cada caso)

print(f"Usando {NUM_WORKERS}")

Usando cpu
Usando 0

In [30]:
BATCH_SIZE = 256  # tamaño del batch

## Data Loader

In [31]:
class CardiacLogDataset(Dataset):
    def __init__(self, sequences, labels, transforms=None):
        # Convert to numpy arrays so positional indexing works
        self.sequences = sequences.to_numpy(dtype=float) if hasattr(sequences, "to_numpy") else np.asarray(sequences, dtype=float)
        self.labels = labels.to_numpy(dtype=int) if hasattr(labels, "to_numpy") else np.asarray(labels, dtype=int)
        self.transforms = transforms

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        sequence = torch.tensor(self.sequences[idx], dtype=torch.float)
        label = torch.tensor(self.labels[idx], dtype=torch.long)
        if self.transforms:
            sequence = self.transforms(sequence)
        return sequence, label

In [32]:
from sklearn.model_selection import train_test_split

train_labels = train_data_us_os_da['class'] 
train_data = train_data_us_os_da.drop(columns=['class','label','duracion_no_ceros'])

# División de los datos en entrenamiento (train) y validación (val)
train_data, val_data, train_labels, val_labels = train_test_split(
    train_data, 
    train_labels, 
    test_size=0.2, 
    random_state=SEED, 
    stratify=train_labels
)

In [33]:
train_data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186
576,1.000000,0.798343,0.624309,0.417127,0.306630,0.204420,0.104972,0.069061,0.055249,0.055249,0.063536,0.055249,0.066298,0.055249,0.077348,0.063536,0.058011,0.055249,0.060773,0.044199,0.060773,0.041436,0.055249,0.038674,0.074586,0.063536,0.080110,0.085635,0.127072,0.129834,0.171271,0.190608,0.237569,0.220994,0.248619,0.229282,0.243094,0.215470,0.215470,0.198895,0.198895,0.168508,0.182320,0.160221,0.168508,0.168508,0.176796,0.160221,0.157459,0.157459,0.176796,0.171271,0.179558,0.165746,0.185083,0.162983,0.182320,0.171271,0.182320,0.168508,0.168508,0.162983,0.162983,0.146409,0.171271,0.176796,0.223757,0.223757,0.248619,0.262431,0.287293,0.287293,0.279006,0.240331,0.160221,0.107735,0.118785,0.107735,0.127072,0.121547,0.129834,0.132597,0.146409,0.116022,0.116022,0.143646,0.364641,0.698895,0.950276,0.906077,0.693370,0.450276,0.364641,0.179558,0.088398,0.024862,0.024862,0.011050,0.011050,0.011050,0.000000,0.008287,0.008287,0.000000,0.013812,0.000000,0.022099,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7304,1.000000,0.590226,0.582707,0.582707,0.578947,0.563910,0.537594,0.466165,0.308271,0.187970,0.000000,0.060150,0.112782,0.120301,0.124060,0.221805,0.195489,0.191729,0.184211,0.218045,0.206767,0.225564,0.218045,0.221805,0.214286,0.214286,0.203008,0.214286,0.195489,0.214286,0.199248,0.221805,0.225564,0.244361,0.244361,0.278196,0.281955,0.312030,0.312030,0.342105,0.342105,0.364662,0.360902,0.375940,0.330827,0.342105,0.319549,0.323308,0.312030,0.330827,0.323308,0.323308,0.296992,0.319549,0.289474,0.285714,0.263158,0.270677,0.248120,0.255639,0.236842,0.259398,0.229323,0.236842,0.218045,0.236842,0.221805,0.236842,0.210526,0.221805,0.191729,0.214286,0.195489,0.218045,0.203008,0.214286,0.203008,0.203008,0.184211,0.214286,0.191729,0.221805,0.195489,0.214286,0.187970,0.199248,0.203008,0.214286,0.187970,0.214286,0.206767,0.221805,0.229323,0.229323,0.210526,0.251880,0.248120,0.327068,0.748120,0.921053,0.571429,0.590226,0.582707,0.597744,0.552632,0.571429,0.526316,0.439850,0.300752,0.142857,0.056391,0.116541,0.071429,0.109023,0.146617,0.191729,0.154135,0.154135,0.157895,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26819,1.000000,0.701493,0.160448,0.078358,0.134328,0.130597,0.093284,0.070896,0.067164,0.070896,0.067164,0.052239,0.059701,0.078358,0.078358,0.070896,0.078358,0.093284,0.093284,0.082090,0.085821,0.100746,0.089552,0.089552,0.093284,0.108209,0.111940,0.100746,0.111940,0.130597,0.126866,0.115672,0.149254,0.175373,0.186567,0.167910,0.164179,0.167910,0.156716,0.138060,0.126866,0.130597,0.108209,0.097015,0.097015,0.108209,0.089552,0.067164,0.078358,0.097015,0.097015,0.063433,0.067164,0.085821,0.082090,0.059701,0.074627,0.078358,0.078358,0.082090,0.104478,0.126866,0.111940,0.123134,0.141791,0.123134,0.100746,0.089552,0.089552,0.089552,0.048507,0.022388,0.041045,0.055970,0.063433,0.044776,0.026119,0.000000,0.089552,0.410448,0.906716,0.947761,0.350746,0.044776,0.108209,0.126866,0.093284,0.063433,0.052239,0.059701,0.055970,0.037313,0.048507,0.063433,0.067164,0.059701,0.055970,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24605,0.937888,0.809006,0.212733,0.000000,0.242236,0.302795,0.265528,0.256211,0.270186,0.276398,0.267081,0.265528,0.277950,0.271739,0.267081,0.273292,0.277950,0.277950,0.274845,0.276398,0.281056,0.282609,0.274845,0.277950,0.288820,0.285714,0.284161,0.290373,0.290373,0.293478,0.291925,0.298137,0.305901,0.309006,0.304348,0.307453,0.315217,0.318323,0.316770,0.318323,0.318323,0.318323,0.324534,0.327640,0.326087,0.322981,0.305901,0.298137,0.287267,0.271739,0.256211,0.250000,0.254658,0.251553,0.240683,0.243789,0.246894,0.248447,0.248447,0.256211,0.262422,0.256211,0.253106,0.256211,0.265528,0.263975,0.259317,0.260870,0.267081,0.267081,0.253106,0.254658,0.260870,0.254658,0.251553,0.250000,0.256211,0.257764,0.248447,0.248447,0.254658,0.253106,0.251553,0.251553,0.256211,0.265528,0.271739,0.282609,0.296584,0.302795,0.290373,0.295031,0.301242,0.291925,0.268634,0.253106,0.256211,0.253106,0.246894,0.243789,0.251553,0.248447,0.245342,0.243789,0.253106,0.257764,0.262422,0.270186,0.315217,0.475155,0.812112,1.000000,0.568323,0.010870,0.127329,0.302795,0.299689,0.268634,0.273292,0.277950,0.287267,0.285714,0.284161,0.287267,0.295031,0.290373,0.290373,0.284161,0.296584,0.296584,0.290373,0.290373,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39117,1.000000,0.903553,0.720812,0.477157,0.279188,0.162437,0.101523,0.152284,0.157360,0.137056,0.121827,0.147208,0.177665,0.157360,0.157360,0.182741,0.192893,0.177665,0.177665,0.192893,0.203046,0.182741,0.182741,0.223350,0.218274,0.182741,0.203046,0.233503,0.233503,0.228426,0.233503,0.253807,0.269036,0.243655,0.228426,0.258883,0.243655,0.228426,0.197970,0.213198,0.192893,0.147208,0.131980,0.116751,0.111675,0.091371,0.081218,0.101523,0.081218,0.065990,0.060914,0.081218,0.076142,0.050761,0.050761,0.040609,0.050761,0.040609,0.015228,0.020305,0.025381,0.010152,0.005076,0.010152,0.020305,0.010152,0.025381,0.025381,0.035533,0.005076,0.000000,0.020305,0.040609,0.020305,0.020305,0.030457,0.045685,0.030457,0.015228,0.040609,0.045685,0.025381,0.010152,0.035533,0.040609,0.020305,0.025381,0.035533,0.050761,0.035533,0.045685,0.055838,0.055838,0.055838,0.035533,0.055838,0.060914,0.050761,0.055838,0.065990,0.076142,0.055838,0.060914,0.060914,0.086294,0.076142,0.091371,0.131980,0.142132,0.111675,0.086294,0.106599,0.126904,0.116751,0.091371,0.096447,0.081218,0.060914,0.055838,0.071066,0.091371,0.086294,0.111675,0.228426,0.487310,0.649746,0.715736,0.862944,0.847716,0.639594,0.395939,0.228426,0.13198,0.086294,0.096447,0.106599,0.116751,0.106599,0.106599,0.126904,0.147208,0.13198,0.13198,0.152284,0.167513,0.15736,0.15736,0.172589,0.162437,0.172589,0.172589,0.177665,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10842,1.000000,0.938144,0.563574,0.195876,0.190722,0.231959,0.201031,0.182131,0.171821,0.170103,0.171821,0.159794,0.154639,0.151203,0.154639,0.149485,0.139175,0.144330,0.149485,0.151203,0.144330,0.135739,0.127148,0.116838,0.108247,0.113402,0.111684,0.091065,0.068729,0.051546,0.041237,0.025773,0.000000,0.000000,0.005155,0.025773,0.048110,0.089347,0.128866,0.154639,0.173540,0.190722,0.211340,0.221649,0.221649,0.230241,0.228522,0.218213,0.218213,0.228522,0.249141,0.240550,0.231959,0.231959,0.237113,0.233677,0.221649,0.228522,0.240550,0.233677,0.221649,0.231959,0.235395,0.235395,0.230241,0.235395,0.245704,0.249141,0.254296,0.250859,0.231959,0.300687,0.522337,0.829897,0.998282,0.907216,0.510309,0.211340,0.230241,0.245704,0.209622,0.207904,0.209622,0.197595,0.187285,0.182131,0.180412,0.171821,0.168385,0.170103,0.170103,0.166667,0.164948,0.171821,0.171821,0.154639,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49021,1.000000,0.682578,0.284010,0.181384,0.157518,0.171838,0.152745,0.150358,0.138425,0.152745,0.150358,0.155131,0.157518,0.162291,0.169451,0.176611,0.186158,0.183771,0.193317,0.205251,0.217184,0.229117,0.252983,0.262530,0.293556,0.310263,0.336516,0.348449,0.365155,0.367542,0.386635,0.367542,0.350835,0.317422,0.303103,0.260143,0.250597,0.214797,0.210024,0.169451,0.186158,0.176611,0.186158,0.171838,0.188544,0.176611,0.190931,0.188544,0.186158,0.174224,0.190931,0.186158,0.183771,0.186158,0.183771,0.202864,0.212410,0.229117,0.248210,0.257757,0.245823,0.250597,0.252983,0.269690,0.317422,0.403341,0.508353,0.596659,0.696897,0.801909,0.914081,0.978520,0.926014,0.854415,0.818616,0.782816,0.780430,0.727924,0.577566,0.281623,0.081146,0.016706,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21565,1.000000,0.673653,0.476048,0.290419,0.209581,0.113772,0.062874,0.029940,0.023952,0.000000,0.020958,0.008982,0.023952,0.020958,0.023952,0.026946,0.038922,0.026946,0.041916,0.029940,0.032934,0.029940,0.062874,0.044910,0.056886,0.056886,0.080838,0.074850,0.101796,0.116766,0.152695,0.158683,0.194611,0.203593,0.215569,0.218563,0.218563,0.191617,0.182635,0.176647,0.173653,0.161677,0.158683,0.149701,0.158683,0.143713,0.164671,0.155689,0.164671,0.152695,0.158683,0.152695,0.161677,0.146707,0.164671,0.146707,0.158683,0.146707,0.149701,0.134731,0.158683,0.155689,0.149701,0.149701,0.152695,0.161677,0.227545,0.206587,0.236527,0.245509,0.299401,0.287425,0.257485,0.200599,0.134731,0.101796,0.107784,0.104790,0.113772,0.107784,0.125749,0.122754,0.134731,0.131737,0.152695,0.173653,0.383234,0.721557,0.991018,0.997006,0.619760,0.461078,0.287425,0.173653,0.128743,0.068862,0.047904,0.008982,0.035928,0.023952,0.041916,0.032934,0.047904,0.035928,0.038922,0.044910,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39460,0.990964,0.841867,0.263554,0.131024,0.293675,0.281626,0.278614,0.281626,0.277108,0.271084,0.280120,0.284639,0.287651,0.284639,0.293675,0.307229,0.311747,0.311747,0.317771,0.326807,0.328313,0.329819,0.337349,0.343374,0.349398,0.353916,0.361446,0.373494,0.373494,0.370482,0.379518,0.391566,0.400602,0.411145,0.418675,0.420181,0.399096,0.382530,0.376506,0.364458,0.346386,0.334337,0.331325,0.331325,0.329819,0.323795,0.323795,0.332831,0.329819,0.326807,0.335843,0.344880,0.343374,0.340361,0.335843,0.350904,0.349398,0.343374,0.341867,0.346386,0.337349,0.332831,0.329819,0.334337,0.337349,0.325301,0.319277,0.325301,0.323795,0.316265,0.314759,0.317771,0.314759,0.310241,0.313253,0.316265,0.311747,0.308735,0.308735,0.314759,0.308735,0.305723,0.313253,0.319277,0.322289,0.325301,0.341867,0.353916,0.355422,0.326807,0.326807,0.337349,0.329819,0.310241,0.302711,0.313253,0.325301,0.337349,0.448795,0.832831,1.000000,0.493976,0.000000,0.239458,0.289157,0.277108,0.278614,0.275602,0.275602,0.280120,0.281626,0.289157,0.290663,0.287651,0.301205,0.311747,0.311747,0.304217,0.314759,0.329819,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16879,1.000000,0.645361,0.208247,0.195876,0.142268,0.035052,0.022680,0.068041,0.171134,0.259794,0.290722,0.305155,0.315464,0.327835,0.327835,0.327835,0.336082,0.342268,0.346392,0.346392,0.344330,0.354639,0.352577,0.348454,0.358763,0.373196,0.383505,0.379381,0.381443,0.395876,0.410309,0.412371,0.408247,0.422680,0.443299,0.453608,0.457732,0.480412,0.484536,0.492784,0.488660,0.509278,0.525773,0.519588,0.519588,0.525773,0.525773,0.501031,0.480412,0.472165,0.451546,0.420619,0.395876,0.391753,0.364948,0.352577,0.346392,0.352577,0.338144,0.334021,0.338144,0.348454,0.362887,0.350515,0.344330,0.356701,0.354639,0.344330,0.340206,0.348454,0.342268,0.336082,0.334021,0.334021,0.327835,0.323711,0.319588,0.325773,0.327835,0.315464,0.307216,0.315464,0.313402,0.309278,0.307216,0.317526,0.323711,0.327835,0.336082,0.348454,0.364948,0.379381,0.377320,0.371134,0.356701,0.334021,0.311340,0.303093,0.298969,0.290722,0.286598,0.286598,0.292783,0.288660,0.286598,0.292783,0.280412,0.210309,0.247423,0.618557,0.964948,0.678351,0.230928,0.200000,0.138144,0.014433,0.000000,0.070103,0.169072,0.237113,0.265979,0.284536,0.292783,0.298969,0.301031,0.309278,0.313402,0.313402,0.313402,0.321649,0.321649,0.317526,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
test_labels = test_data['class'] 
test_data = test_data.drop(columns=['class','label'])

In [35]:
train_dataset = CardiacLogDataset(train_data, train_labels)
val_dataset   = CardiacLogDataset(val_data,   val_labels)
test_dataset  = CardiacLogDataset(test_data,  test_labels)

In [36]:
def get_data_loaders(batch_size):
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,  num_workers=NUM_WORKERS)
    val_loader   = DataLoader(val_dataset,   batch_size=batch_size, shuffle=False, num_workers=NUM_WORKERS)
    test_loader  = DataLoader(test_dataset,  batch_size=batch_size, shuffle=False, num_workers=NUM_WORKERS)
    return train_loader, val_loader, test_loader

In [37]:
train_loader, val_loader, test_loader = get_data_loaders(BATCH_SIZE)

In [38]:
class_counts = Counter(train_labels)
total = sum(class_counts.values())
class_weights = {cls: total/count for cls, count in class_counts.items()}
class_weights = torch.tensor([class_weights[0], class_weights[1]], dtype=torch.float).to(DEVICE)

print(f"Class Weights: {class_weights}")

Class Weights: tensor([ 1.5491, 15.4911])

In [39]:
class_counts.values()

dict_values([28000, 5145, 2800, 4630, 2800])

## RNN

In [55]:
CRITERION = nn.CrossEntropyLoss()  # función de pérdida con pesos para cada clase
LR = 0.0005
EPOCHS = 150

In [56]:
# Constantes
SEQUENCE_LENGTH = 120  
PADDING_VALUE = 0  # Padding value

# Example cardiac log sequence (substitute with real data)
# Ensure the sequence length matches your data
# data_indices = torch.tensor([
#     [0, 1, 2, 3, 4, 5] + [0] * (SEQUENCE_LENGTH - 6)
# ], dtype=torch.long)  # Ensure dtype is long for embedding

# Apply embedding
# embedded = embedding_layer(data_indices)

# Print results
# print(f"Data indices (first sequence): {data_indices[0]}")
# print(f"Embedded shape: {embedded.shape}")
# print(f"Embedded (first sequence): {embedded[0]}")

### Weight and Bias

In [57]:
import wandb

In [58]:
wandb.login(key="371d1ec6f09f8bd9b3f43d38d319dae857ea940f")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: C:\Users\Matías\_netrc

True

### Modelo

In [59]:
# from torchinfo import summary

# class CardiacRNNClassifier(nn.Module):
#     def __init__(self, hidden_dim, num_classes=10, rnn_type='rnn', bidirectional=False, input_dim=1):
#         super().__init__()
#         self.bidirectional = bidirectional
#         hidden_out = hidden_dim * (2 if bidirectional else 1)
#         if rnn_type == 'lstm':
#             self.rnn = nn.LSTM(input_size=input_dim, hidden_size=hidden_dim, batch_first=True, bidirectional=bidirectional)
#         elif rnn_type == 'gru':
#             self.rnn = nn.GRU(input_size=input_dim, hidden_size=hidden_dim, batch_first=True, bidirectional=bidirectional)
#         else:
#             self.rnn = nn.RNN(input_size=input_dim, hidden_size=hidden_dim, batch_first=True, bidirectional=bidirectional)
        
#         # Capa final para clasificacion
#         self.fc = nn.Linear(hidden_out, num_classes)
    
#     def forward(self, x):
#         if x.ndim == 2:
#             x = x.unsqueeze(-1)
#         x = x.float()
#         out, hidden = self.rnn(x)
#         if isinstance(hidden, tuple):  # LSTM
#             hidden = hidden[0]         # h_n
#         # hidden: (num_layers * num_directions, B, hidden_dim)
#         if self.bidirectional:
#             x = torch.cat((hidden[-2], hidden[-1]), dim=1)  # (B, hidden_dim*2)
#         else:
#             x = hidden[-1]                                   # (B, hidden_dim)
#         return self.fc(x)

In [60]:
import torch.nn.functional as F  # agregar este import

class CardiacRNNClassifier(nn.Module):
    def __init__(self, hidden_dim, num_classes=10, rnn_type='rnn', bidirectional=False, input_dim=1, seq_len=120):
        super().__init__()
        self.bidirectional = bidirectional
        self.seq_len = seq_len
        hidden_out = hidden_dim * (2 if bidirectional else 1)
        if rnn_type == 'lstm':
            self.rnn = nn.LSTM(input_size=input_dim, hidden_size=hidden_dim, batch_first=True, bidirectional=bidirectional)
        elif rnn_type == 'gru':
            self.rnn = nn.GRU(input_size=input_dim, hidden_size=hidden_dim, batch_first=True, bidirectional=bidirectional)
        else:
            self.rnn = nn.RNN(input_size=input_dim, hidden_size=hidden_dim, batch_first=True, bidirectional=bidirectional)
        
        # Capa final para clasificacion
        self.fc = nn.Linear(hidden_out, num_classes)
    
    def forward(self, x):
        if x.ndim == 2:
            x = x.unsqueeze(-1)  # (B, T) -> (B, T, 1)
        x = x.float()

        # Truncado/padding a longitud fija self.seq_len
        T = x.size(1)
        if T > self.seq_len:
            x = x[:, :self.seq_len, :]  # truncar a los primeros seq_len pasos
        elif T < self.seq_len:
            pad_t = self.seq_len - T
            x = F.pad(x, (0, 0, 0, pad_t))  # pad en dimensión temporal (derecha)

        out, hidden = self.rnn(x)
        if isinstance(hidden, tuple):  # LSTM
            hidden = hidden[0]         # h_n
        # hidden: (num_layers * num_directions, B, hidden_dim)
        if self.bidirectional:
            x = torch.cat((hidden[-2], hidden[-1]), dim=1)  # (B, hidden_dim*2)
        else:
            x = hidden[-1]                                   # (B, hidden_dim)
        return self.fc(x)

In [61]:
from torchinfo import summary

summary(CardiacRNNClassifier(hidden_dim=256, rnn_type='rnn', bidirectional=False, input_dim=1, seq_len=SEQUENCE_LENGTH),
input_size=(BATCH_SIZE, SEQUENCE_LENGTH),
dtypes=[torch.int32],
)

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
CardiacRNNClassifier                     [256, 10]                 --
├─RNN: 1-1                               [256, 120, 256]           66,304
├─Linear: 1-2                            [256, 10]                 2,570
==========================================================================================
Total params: 68,874
Trainable params: 68,874
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 2.04
==========================================================================================
Input size (MB): 0.12
Forward/backward pass size (MB): 62.94
Params size (MB): 0.28
Estimated Total Size (MB): 63.33
==========================================================================================

## Weight and Bias

In [62]:
WANDB_PROJECT = 'Entrega 2 - RNN, LSTM, GRU'

In [63]:
def train_wandb_rnn(config=None):
    import os
    import numpy as np
    from sklearn.metrics import precision_recall_fscore_support, accuracy_score

    AVERAGE = "weighted"

    def _as_int(x, default=None):
        if x is None:
            return default
        if isinstance(x, (list, tuple)):
            return int(x[0]) if len(x) > 0 else default
        try:
            import torch
            if isinstance(x, torch.Tensor):
                return int(x.item())
        except Exception:
            pass
        try:
            return int(x)
        except Exception:
            return default

    with wandb.init(config=config):
        config = wandb.config

        # Normalizar y validar rnn_type
        rnn_type = getattr(config, "rnn_type", "rnn").lower()
        assert rnn_type in {"rnn", "lstm", "gru"}, f"rnn_type no soportado: {rnn_type}"

        # Preparar loaders con el batch_size
        train_loader, val_loader, _ = get_data_loaders(
            _as_int(getattr(config, "batch_size", 64), default=64)
        )

        # Crear el modelo CardiacRNNClassifier según el sweep
        num_classes = _as_int(getattr(config, "num_classes", 10), default=10)
        model_kwargs = dict(
            hidden_dim=_as_int(config.hidden_dim),
            num_classes=num_classes,
            rnn_type=rnn_type,
            bidirectional=bool(getattr(config, "bidirectional", False)),
            input_dim=1,
        )
        if hasattr(config, "seq_len"):
            model_kwargs["seq_len"] = _as_int(getattr(config, "seq_len", 120), default=120)

        model = CardiacRNNClassifier(**model_kwargs).to(DEVICE)

        # Configurar optimizador con weight decay
        if config.optimizer == "adam":
            optimizer = optim.Adam(
                model.parameters(),
                lr=float(config.learning_rate),
                weight_decay=float(config.weight_decay)
            )
        else:
            optimizer = optim.SGD(
                model.parameters(),
                lr=float(config.learning_rate),
                momentum=0.9,
                weight_decay=float(config.weight_decay)
            )

        # Registrar el modelo en wandb
        wandb.watch(model, log="all", log_freq=100)

        # Entrenamiento
        best_val_loss = float("inf")
        best_val_acc = 0.0

        for epoch in range(EPOCHS):
            # Training phase
            model.train()
            train_loss = 0.0
            train_correct = 0
            train_total = 0

            # Acumuladores para métricas
            train_preds = []
            train_targs = []

            for inputs, targets in train_loader:
                inputs, targets = inputs.to(DEVICE), targets.to(DEVICE)

                optimizer.zero_grad()
                outputs = model(inputs)
                loss = CRITERION(outputs, targets)
                loss.backward()
                optimizer.step()

                train_loss += loss.item()
                _, predicted = outputs.max(1)
                train_total += targets.size(0)
                train_correct += predicted.eq(targets).sum().item()

                # Guardar para métricas por-época
                train_preds.append(predicted.detach().cpu())
                train_targs.append(targets.detach().cpu())

            train_loss = train_loss / len(train_loader)
            train_acc = 100. * train_correct / train_total

            # Métricas de train (weighted)
            train_preds = torch.cat(train_preds).numpy()
            train_targs = torch.cat(train_targs).numpy()
            train_precision, train_recall, train_f1, _ = precision_recall_fscore_support(
                train_targs, train_preds, average=AVERAGE, zero_division=0
            )
            train_precision *= 100.0
            train_recall *= 100.0
            train_f1 *= 100.0

            # Validation phase
            model.eval()
            val_loss = 0.0
            val_correct = 0
            val_total = 0

            val_preds = []
            val_targs = []

            with torch.no_grad():
                for inputs, targets in val_loader:
                    inputs, targets = inputs.to(DEVICE), targets.to(DEVICE)
                    outputs = model(inputs)
                    loss = CRITERION(outputs, targets)

                    val_loss += loss.item()
                    _, predicted = outputs.max(1)
                    val_total += targets.size(0)
                    val_correct += predicted.eq(targets).sum().item()

                    # Guardar para métricas por-época
                    val_preds.append(predicted.detach().cpu())
                    val_targs.append(targets.detach().cpu())

            val_loss = val_loss / len(val_loader)
            val_acc = 100. * val_correct / val_total

            # Métricas de validación (weighted)
            val_preds = torch.cat(val_preds).numpy()
            val_targs = torch.cat(val_targs).numpy()
            val_precision, val_recall, val_f1, _ = precision_recall_fscore_support(
                val_targs, val_preds, average=AVERAGE, zero_division=0
            )
            val_precision *= 100.0
            val_recall *= 100.0
            val_f1 *= 100.0

            # Logging
            wandb.log({
                "epoch": epoch,
                "train_loss": train_loss,
                "train_acc": train_acc,
                "train_precision": train_precision,
                "train_recall": train_recall,
                "train_f1": train_f1,
                "val_loss": val_loss,
                "val_acc": val_acc,
                "val_precision": val_precision,
                "val_recall": val_recall,
                "val_f1": val_f1,
                "learning_rate": optimizer.param_groups[0]['lr'],
                "rnn_type": rnn_type,
                "seq_len": model_kwargs.get("seq_len"),
            })

            # Guardar mejor modelo (evitar symlink en Windows)
            if val_acc > best_val_acc:
                best_val_acc = val_acc
                best_val_loss = val_loss
                save_path = os.path.join(wandb.run.dir, "rnn_best_model.pth")
                torch.save(model.state_dict(), save_path)

            # Print progress
            print(f'Epoch: {epoch+1}/{EPOCHS}')
            print(f'Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}% | Precision: {train_precision:.2f}% Recall: {train_recall:.2f}% F1: {train_f1:.2f}%')
            print(f'Val   Loss: {val_loss:.4f} | Val Acc: {val_acc:.2f}%   | Precision: {val_precision:.2f}% Recall: {val_recall:.2f}% F1: {val_f1:.2f}%\n')

        # Log final metrics
        wandb.run.summary.update({
            "best_val_acc": best_val_acc,
            "best_val_loss": best_val_loss,
            "weight_decay": float(config.weight_decay),
            "batch_size": _as_int(getattr(config, "batch_size", 64), default=64),
            "hidden_dim": _as_int(config.hidden_dim),
            "bidirectional": bool(getattr(config, "bidirectional", False)),
            "rnn_type": rnn_type,
            "seq_len": model_kwargs.get("seq_len"),
            "num_classes": num_classes,
        })

### RNN

In [64]:
sweep_config = {
    'name': 'RNN-ECG',
    "method": "bayes",  
    "metric": {"name": "val_loss", "goal": "minimize"},
    "parameters": {
        "rnn_type": {"value": "rnn"},
        "hidden_dim": {"values": [64, 128, 256, 512]},
        "bidirectional": {"values": [False, True]},
        "batch_size": {"values": [32, 64, 128]},
        "optimizer": {"values": ["adam", "sgd"]},
        "learning_rate": {"distribution": "uniform", "min": 0.0001, "max": 0.001},
        "weight_decay": {"values": [0.0, 1e-5, 1e-4, 1e-3]},
        "seq_len": {"values": [80,120,130,140,150,160]} 
    }
}

sweep_id = wandb.sweep(sweep_config, project=WANDB_PROJECT)

Create sweep with ID: 48ck289w
Sweep URL: https://wandb.ai/RoJo/Entrega%202%20-%20RNN%2C%20LSTM%2C%20GRU/sweeps/48ck289w

In [65]:
wandb.agent(sweep_id, train_wandb_rnn, count=10)

wandb: Agent Starting Run: guau96s1 with config:
wandb: 	batch_size: 32
wandb: 	bidirectional: False
wandb: 	hidden_dim: 64
wandb: 	learning_rate: 0.000869273886580118
wandb: 	optimizer: adam
wandb: 	rnn_type: rnn
wandb: 	seq_len: 120
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.1477 | Train Acc: 64.44% | Precision: 42.30% Recall: 64.44% F1: 50.64%
Val   Loss: 1.1297 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.1302 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1291 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1294 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1399 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.0696 | Train Acc: 64.75% | Precision: 47.98% Recall: 64.75% F1: 51.85%
Val   Loss: 1.1254 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.1282 | Train Acc: 64.56% | Precision: 52.35% Recall: 64.56% F1: 50.67%
Val   Loss: 1.1244 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.0763 | Train Acc: 64.53% | Precision: 43.74% Recall: 64.53% F1: 50.66%
Val   Loss: 1.0197 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 7/150
Train Loss: 1.0123 | Train Acc: 64.61% | Precision: 47.28% Recall: 64.61% F1: 52.31%
Val   Loss: 0.9936 | Val Acc: 64.17%   | Precision: 47.13% Recall: 64.17% F1: 53.57%

Epoch: 8/150
Train Loss: 1.0453 | Train Acc: 65.26% | Precision: 48.48% Recall: 65.26% F1: 54.38%
Val   Loss: 1.1382 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 9/150
Train Loss: 1.1312 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1275 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 10/150
Train Loss: 1.0917 | Train Acc: 64.49% | Precision: 44.48% Recall: 64.49% F1: 50.75%
Val   Loss: 1.0308 | Val Acc: 64.16%   | Precision: 46.93% Recall: 64.16% F1: 53.25%

Epoch: 11/150
Train Loss: 1.1257 | Train Acc: 64.55% | Precision: 48.79% Recall: 64.55% F1: 50.66%
Val   Loss: 1.1227 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 12/150
Train Loss: 1.1109 | Train Acc: 64.46% | Precision: 42.81% Recall: 64.46% F1: 50.65%
Val   Loss: 1.1246 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 13/150
Train Loss: 1.0844 | Train Acc: 64.57% | Precision: 46.96% Recall: 64.57% F1: 51.46%
Val   Loss: 1.0233 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 14/150
Train Loss: 1.0924 | Train Acc: 64.92% | Precision: 48.10% Recall: 64.92% F1: 52.73%
Val   Loss: 1.1295 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 15/150
Train Loss: 1.1305 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1276 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 16/150
Train Loss: 1.1201 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1719 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 17/150
Train Loss: 1.1335 | Train Acc: 64.43% | Precision: 42.07% Recall: 64.43% F1: 50.61%
Val   Loss: 1.1275 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 18/150
Train Loss: 1.1283 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1251 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 19/150
Train Loss: 1.1232 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1113 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 20/150
Train Loss: 1.1208 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1147 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 21/150
Train Loss: 1.1066 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0399 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 22/150
Train Loss: 1.0445 | Train Acc: 64.67% | Precision: 47.37% Recall: 64.67% F1: 51.73%
Val   Loss: 0.9988 | Val Acc: 64.04%   | Precision: 48.62% Recall: 64.04% F1: 55.26%

Epoch: 23/150
Train Loss: 1.1039 | Train Acc: 64.96% | Precision: 48.21% Recall: 64.96% F1: 52.82%
Val   Loss: 1.1225 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 24/150
Train Loss: 1.1177 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1219 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 25/150
Train Loss: 1.1149 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1287 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 26/150
Train Loss: 1.1204 | Train Acc: 64.54% | Precision: 41.67% Recall: 64.54% F1: 50.64%
Val   Loss: 1.1309 | Val Acc: 64.52%   | Precision: 41.66% Recall: 64.52% F1: 50.63%

Epoch: 27/150
Train Loss: 1.1004 | Train Acc: 64.54% | Precision: 41.69% Recall: 64.54% F1: 50.66%
Val   Loss: 0.9983 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 28/150
Train Loss: 1.0531 | Train Acc: 64.57% | Precision: 47.14% Recall: 64.57% F1: 52.13%
Val   Loss: 1.1298 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 29/150
Train Loss: 1.0977 | Train Acc: 64.94% | Precision: 51.24% Recall: 64.94% F1: 52.84%
Val   Loss: 1.1280 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 30/150
Train Loss: 1.1303 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1295 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 31/150
Train Loss: 1.1234 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1171 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 32/150
Train Loss: 1.1109 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0970 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 33/150
Train Loss: 1.1121 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1061 | Val Acc: 64.53%   | Precision: 41.68% Recall: 64.53% F1: 50.65%

Epoch: 34/150
Train Loss: 1.1256 | Train Acc: 64.53% | Precision: 41.70% Recall: 64.53% F1: 50.66%
Val   Loss: 1.1175 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 35/150
Train Loss: 1.1003 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0958 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 36/150
Train Loss: 1.0651 | Train Acc: 64.56% | Precision: 46.94% Recall: 64.56% F1: 51.76%
Val   Loss: 1.0106 | Val Acc: 65.17%   | Precision: 49.34% Recall: 65.17% F1: 52.97%

Epoch: 37/150
Train Loss: 1.0454 | Train Acc: 64.71% | Precision: 47.57% Recall: 64.71% F1: 52.24%
Val   Loss: 1.0450 | Val Acc: 62.98%   | Precision: 42.75% Recall: 62.98% F1: 50.62%

Epoch: 38/150
Train Loss: 1.0777 | Train Acc: 65.74% | Precision: 56.71% Recall: 65.74% F1: 54.75%
Val   Loss: 1.0816 | Val Acc: 66.75%   | Precision: 51.28% Recall: 66.75% F1: 55.51%

Epoch: 39/150
Train Loss: 1.0704 | Train Acc: 66.94% | Precision: 51.20% Recall: 66.94% F1: 55.88%
Val   Loss: 1.0853 | Val Acc: 66.82%   | Precision: 51.38% Recall: 66.82% F1: 55.53%

Epoch: 40/150
Train Loss: 1.0920 | Train Acc: 66.17% | Precision: 50.78% Recall: 66.17% F1: 54.49%
Val   Loss: 1.1159 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 41/150
Train Loss: 1.1193 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.2773 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 42/150
Train Loss: 1.1273 | Train Acc: 64.37% | Precision: 45.15% Recall: 64.37% F1: 50.64%
Val   Loss: 1.0501 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 43/150
Train Loss: 1.0830 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0580 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 44/150
Train Loss: 1.1018 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.64%
Val   Loss: 1.0535 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 45/150
Train Loss: 1.0267 | Train Acc: 64.53% | Precision: 47.05% Recall: 64.53% F1: 52.21%
Val   Loss: 0.9653 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 46/150
Train Loss: 1.0934 | Train Acc: 64.49% | Precision: 47.80% Recall: 64.49% F1: 50.88%
Val   Loss: 1.0829 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 47/150
Train Loss: 1.0825 | Train Acc: 64.52% | Precision: 44.82% Recall: 64.52% F1: 50.70%
Val   Loss: 1.0924 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 48/150
Train Loss: 1.0198 | Train Acc: 64.56% | Precision: 47.14% Recall: 64.56% F1: 51.08%
Val   Loss: 0.9817 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 49/150
Train Loss: 1.0283 | Train Acc: 64.83% | Precision: 47.80% Recall: 64.83% F1: 53.58%
Val   Loss: 1.0865 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 50/150
Train Loss: 1.0001 | Train Acc: 64.85% | Precision: 48.11% Recall: 64.85% F1: 53.94%
Val   Loss: 0.9479 | Val Acc: 67.35%   | Precision: 51.03% Recall: 67.35% F1: 57.69%

Epoch: 51/150
Train Loss: 1.1051 | Train Acc: 64.78% | Precision: 48.36% Recall: 64.78% F1: 51.80%
Val   Loss: 1.1220 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 52/150
Train Loss: 1.1050 | Train Acc: 65.04% | Precision: 54.75% Recall: 65.04% F1: 56.75%
Val   Loss: 1.0036 | Val Acc: 68.55%   | Precision: 57.88% Recall: 68.55% F1: 61.90%

Epoch: 53/150
Train Loss: 0.9142 | Train Acc: 71.29% | Precision: 61.89% Recall: 71.29% F1: 64.48%
Val   Loss: 0.8749 | Val Acc: 72.08%   | Precision: 59.79% Recall: 72.08% F1: 64.32%

Epoch: 54/150
Train Loss: 0.8057 | Train Acc: 73.56% | Precision: 62.35% Recall: 73.56% F1: 66.80%
Val   Loss: 0.7547 | Val Acc: 74.97%   | Precision: 63.88% Recall: 74.97% F1: 68.32%

Epoch: 55/150
Train Loss: 1.0242 | Train Acc: 66.86% | Precision: 55.19% Recall: 66.86% F1: 56.79%
Val   Loss: 0.9894 | Val Acc: 65.44%   | Precision: 48.60% Recall: 65.44% F1: 54.94%

Epoch: 56/150
Train Loss: 1.0194 | Train Acc: 65.26% | Precision: 51.73% Recall: 65.26% F1: 54.97%
Val   Loss: 0.8971 | Val Acc: 71.33%   | Precision: 57.13% Recall: 71.33% F1: 62.37%

Epoch: 57/150
Train Loss: 0.8682 | Train Acc: 71.60% | Precision: 60.32% Recall: 71.60% F1: 64.35%
Val   Loss: 0.7977 | Val Acc: 73.73%   | Precision: 62.86% Recall: 73.73% F1: 67.22%

Epoch: 58/150
Train Loss: 1.1097 | Train Acc: 65.24% | Precision: 55.00% Recall: 65.24% F1: 52.91%
Val   Loss: 1.1305 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 59/150
Train Loss: 1.1289 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1201 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 60/150
Train Loss: 1.1169 | Train Acc: 64.52% | Precision: 41.67% Recall: 64.52% F1: 50.63%
Val   Loss: 1.1239 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 61/150
Train Loss: 1.1185 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1193 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 62/150
Train Loss: 1.0910 | Train Acc: 64.50% | Precision: 41.67% Recall: 64.50% F1: 50.63%
Val   Loss: 0.9905 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 63/150
Train Loss: 1.0148 | Train Acc: 67.35% | Precision: 51.21% Recall: 67.35% F1: 57.48%
Val   Loss: 1.1305 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 64/150
Train Loss: 1.1269 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1253 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 65/150
Train Loss: 1.1184 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1266 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 66/150
Train Loss: 1.1194 | Train Acc: 64.51% | Precision: 44.34% Recall: 64.51% F1: 50.68%
Val   Loss: 1.1142 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 67/150
Train Loss: 1.0758 | Train Acc: 64.64% | Precision: 47.41% Recall: 64.64% F1: 51.48%
Val   Loss: 1.1321 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 68/150
Train Loss: 1.1109 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1240 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 69/150
Train Loss: 1.1218 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1244 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 70/150
Train Loss: 1.0649 | Train Acc: 64.80% | Precision: 47.82% Recall: 64.80% F1: 52.90%
Val   Loss: 1.1506 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 71/150
Train Loss: 1.1245 | Train Acc: 64.55% | Precision: 52.35% Recall: 64.55% F1: 50.66%
Val   Loss: 1.1032 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 72/150
Train Loss: 1.0643 | Train Acc: 64.65% | Precision: 47.76% Recall: 64.65% F1: 51.25%
Val   Loss: 0.9784 | Val Acc: 64.29%   | Precision: 47.83% Recall: 64.29% F1: 54.42%

Epoch: 73/150
Train Loss: 1.0999 | Train Acc: 64.78% | Precision: 47.85% Recall: 64.78% F1: 51.95%
Val   Loss: 1.1219 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 74/150
Train Loss: 1.0936 | Train Acc: 64.57% | Precision: 47.76% Recall: 64.57% F1: 50.76%
Val   Loss: 1.0276 | Val Acc: 64.64%   | Precision: 50.34% Recall: 64.64% F1: 50.96%

Epoch: 75/150
Train Loss: 1.0504 | Train Acc: 64.98% | Precision: 48.14% Recall: 64.98% F1: 53.89%
Val   Loss: 1.1259 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 76/150
Train Loss: 1.0560 | Train Acc: 64.57% | Precision: 46.96% Recall: 64.57% F1: 51.63%
Val   Loss: 0.9727 | Val Acc: 66.48%   | Precision: 50.43% Recall: 66.48% F1: 57.29%

Epoch: 77/150
Train Loss: 1.0714 | Train Acc: 64.68% | Precision: 47.63% Recall: 64.68% F1: 53.35%
Val   Loss: 1.1258 | Val Acc: 64.54%   | Precision: 41.67% Recall: 64.54% F1: 50.64%

Epoch: 78/150
Train Loss: 1.1160 | Train Acc: 64.41% | Precision: 46.10% Recall: 64.41% F1: 51.56%
Val   Loss: 1.1405 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 79/150
Train Loss: 1.1173 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1178 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 80/150
Train Loss: 1.0914 | Train Acc: 64.63% | Precision: 47.86% Recall: 64.63% F1: 51.07%
Val   Loss: 1.0769 | Val Acc: 65.46%   | Precision: 49.13% Recall: 65.46% F1: 55.71%

Epoch: 81/150
Train Loss: 1.1112 | Train Acc: 64.56% | Precision: 46.43% Recall: 64.56% F1: 50.72%
Val   Loss: 1.0903 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 82/150
Train Loss: 1.0680 | Train Acc: 64.51% | Precision: 47.21% Recall: 64.51% F1: 53.07%
Val   Loss: 1.1282 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 83/150
Train Loss: 1.1269 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1000 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 84/150
Train Loss: 1.0772 | Train Acc: 64.02% | Precision: 45.76% Recall: 64.02% F1: 51.22%
Val   Loss: 1.0534 | Val Acc: 63.25%   | Precision: 49.02% Recall: 63.25% F1: 53.48%

Epoch: 85/150
Train Loss: 1.0082 | Train Acc: 66.05% | Precision: 53.89% Recall: 66.05% F1: 55.70%
Val   Loss: 1.0178 | Val Acc: 66.87%   | Precision: 54.22% Recall: 66.87% F1: 57.65%

Epoch: 86/150
Train Loss: 1.0091 | Train Acc: 66.97% | Precision: 53.75% Recall: 66.97% F1: 56.99%
Val   Loss: 0.9952 | Val Acc: 66.28%   | Precision: 49.82% Recall: 66.28% F1: 56.55%

Epoch: 87/150
Train Loss: 0.9576 | Train Acc: 66.93% | Precision: 51.10% Recall: 66.93% F1: 56.89%
Val   Loss: 1.0089 | Val Acc: 65.58%   | Precision: 49.77% Recall: 65.58% F1: 54.14%

Epoch: 88/150
Train Loss: 0.9436 | Train Acc: 67.65% | Precision: 57.75% Recall: 67.65% F1: 58.40%
Val   Loss: 1.0117 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 89/150
Train Loss: 1.0084 | Train Acc: 64.47% | Precision: 49.21% Recall: 64.47% F1: 53.42%
Val   Loss: 1.5630 | Val Acc: 61.39%   | Precision: 47.67% Recall: 61.39% F1: 51.88%

Epoch: 90/150
Train Loss: 0.9628 | Train Acc: 68.78% | Precision: 59.40% Recall: 68.78% F1: 60.35%
Val   Loss: 0.8768 | Val Acc: 71.39%   | Precision: 60.40% Recall: 71.39% F1: 63.87%

Epoch: 91/150
Train Loss: 0.8480 | Train Acc: 72.31% | Precision: 64.60% Recall: 72.31% F1: 64.95%
Val   Loss: 0.8341 | Val Acc: 71.56%   | Precision: 65.98% Recall: 71.56% F1: 63.81%

Epoch: 92/150
Train Loss: 0.7681 | Train Acc: 74.46% | Precision: 67.43% Recall: 74.46% F1: 68.79%
Val   Loss: 0.6899 | Val Acc: 77.98%   | Precision: 71.69% Recall: 77.98% F1: 73.19%

Epoch: 93/150
Train Loss: 0.7128 | Train Acc: 75.95% | Precision: 69.24% Recall: 75.95% F1: 71.26%
Val   Loss: 0.6504 | Val Acc: 77.98%   | Precision: 71.57% Recall: 77.98% F1: 73.58%

Epoch: 94/150
Train Loss: 0.7929 | Train Acc: 72.12% | Precision: 64.90% Recall: 72.12% F1: 66.89%
Val   Loss: 0.7506 | Val Acc: 72.19%   | Precision: 66.42% Recall: 72.19% F1: 68.07%

Epoch: 95/150
Train Loss: 0.7148 | Train Acc: 75.49% | Precision: 67.93% Recall: 75.49% F1: 70.10%
Val   Loss: 0.6614 | Val Acc: 76.91%   | Precision: 70.43% Recall: 76.91% F1: 72.85%

Epoch: 96/150
Train Loss: 0.7521 | Train Acc: 73.05% | Precision: 66.07% Recall: 73.05% F1: 68.09%
Val   Loss: 0.8870 | Val Acc: 68.24%   | Precision: 59.63% Recall: 68.24% F1: 59.81%

Epoch: 97/150
Train Loss: 0.8680 | Train Acc: 69.16% | Precision: 61.73% Recall: 69.16% F1: 62.54%
Val   Loss: 0.8129 | Val Acc: 72.10%   | Precision: 64.31% Recall: 72.10% F1: 65.51%

Epoch: 98/150
Train Loss: 0.8320 | Train Acc: 71.58% | Precision: 62.84% Recall: 71.58% F1: 65.21%
Val   Loss: 0.7064 | Val Acc: 75.16%   | Precision: 64.17% Recall: 75.16% F1: 68.29%

Epoch: 99/150
Train Loss: 0.6839 | Train Acc: 76.07% | Precision: 72.05% Recall: 76.07% F1: 71.39%
Val   Loss: 0.6462 | Val Acc: 76.24%   | Precision: 70.09% Recall: 76.24% F1: 72.41%

Epoch: 100/150
Train Loss: 0.6879 | Train Acc: 75.85% | Precision: 72.41% Recall: 75.85% F1: 71.74%
Val   Loss: 0.6901 | Val Acc: 76.30%   | Precision: 68.96% Recall: 76.30% F1: 71.10%

Epoch: 101/150
Train Loss: 0.6796 | Train Acc: 76.30% | Precision: 68.66% Recall: 76.30% F1: 71.13%
Val   Loss: 0.6966 | Val Acc: 75.76%   | Precision: 67.23% Recall: 75.76% F1: 70.48%

Epoch: 102/150
Train Loss: 0.8445 | Train Acc: 72.76% | Precision: 66.06% Recall: 72.76% F1: 66.92%
Val   Loss: 1.0984 | Val Acc: 65.49%   | Precision: 48.38% Recall: 65.49% F1: 54.51%

Epoch: 103/150
Train Loss: 1.0133 | Train Acc: 66.90% | Precision: 56.86% Recall: 66.90% F1: 57.94%
Val   Loss: 0.9567 | Val Acc: 66.96%   | Precision: 57.08% Recall: 66.96% F1: 59.87%

Epoch: 104/150
Train Loss: 0.9255 | Train Acc: 68.57% | Precision: 59.25% Recall: 68.57% F1: 61.79%
Val   Loss: 0.9721 | Val Acc: 66.21%   | Precision: 49.68% Recall: 66.21% F1: 54.76%

Epoch: 105/150
Train Loss: 1.0371 | Train Acc: 65.59% | Precision: 54.71% Recall: 65.59% F1: 55.99%
Val   Loss: 1.1059 | Val Acc: 63.99%   | Precision: 46.99% Recall: 63.99% F1: 53.84%

Epoch: 106/150
Train Loss: 1.1438 | Train Acc: 63.94% | Precision: 48.19% Recall: 63.94% F1: 51.52%
Val   Loss: 1.4416 | Val Acc: 64.04%   | Precision: 45.87% Recall: 64.04% F1: 53.03%

Epoch: 107/150
Train Loss: 1.0794 | Train Acc: 65.87% | Precision: 54.49% Recall: 65.87% F1: 57.17%
Val   Loss: 1.1342 | Val Acc: 64.92%   | Precision: 48.48% Recall: 64.92% F1: 53.67%

Epoch: 108/150
Train Loss: 1.0980 | Train Acc: 64.59% | Precision: 51.70% Recall: 64.59% F1: 53.83%
Val   Loss: 1.1326 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 109/150

wandb: Agent Starting Run: xjih2nwp with config:
wandb: 	batch_size: 128
wandb: 	bidirectional: False
wandb: 	hidden_dim: 64
wandb: 	learning_rate: 0.0005745253723348714
wandb: 	optimizer: sgd
wandb: 	rnn_type: rnn
wandb: 	seq_len: 120
wandb: 	weight_decay: 0.0001

Epoch: 1/150
Train Loss: 1.4548 | Train Acc: 63.39% | Precision: 41.64% Recall: 63.39% F1: 50.26%
Val   Loss: 1.1929 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.1672 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1519 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1463 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1418 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1398 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1373 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.1363 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1350 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.1345 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1334 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 7/150
Train Loss: 1.1332 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1326 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 8/150
Train Loss: 1.1325 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1318 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 9/150
Train Loss: 1.1319 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1311 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 10/150
Train Loss: 1.1313 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1308 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 11/150
Train Loss: 1.1308 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1305 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 12/150
Train Loss: 1.1305 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1301 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 13/150
Train Loss: 1.1303 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1298 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 14/150
Train Loss: 1.1299 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1295 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 15/150
Train Loss: 1.1296 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1294 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 16/150
Train Loss: 1.1295 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1292 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 17/150
Train Loss: 1.1293 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1290 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 18/150
Train Loss: 1.1293 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1288 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 19/150
Train Loss: 1.1290 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1287 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 20/150
Train Loss: 1.1289 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1285 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 21/150
Train Loss: 1.1288 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1283 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 22/150
Train Loss: 1.1287 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1283 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 23/150
Train Loss: 1.1286 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1280 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 24/150
Train Loss: 1.1283 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1282 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 25/150
Train Loss: 1.1282 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1280 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 26/150
Train Loss: 1.1282 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1276 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 27/150
Train Loss: 1.1281 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1275 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 28/150
Train Loss: 1.1279 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1276 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 29/150
Train Loss: 1.1277 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1274 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 30/150
Train Loss: 1.1277 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1273 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 31/150
Train Loss: 1.1275 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1273 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 32/150
Train Loss: 1.1273 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1271 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 33/150
Train Loss: 1.1272 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1267 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 34/150
Train Loss: 1.1271 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1266 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 35/150
Train Loss: 1.1269 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1264 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 36/150
Train Loss: 1.1268 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1262 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 37/150
Train Loss: 1.1264 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1261 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 38/150
Train Loss: 1.1264 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1260 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 39/150
Train Loss: 1.1262 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1257 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 40/150
Train Loss: 1.1259 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1253 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 41/150
Train Loss: 1.1257 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1250 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 42/150
Train Loss: 1.1252 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1254 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 43/150
Train Loss: 1.1250 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1243 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 44/150
Train Loss: 1.1245 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1244 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 45/150
Train Loss: 1.1244 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1237 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 46/150
Train Loss: 1.1237 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1233 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 47/150
Train Loss: 1.1232 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1233 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 48/150
Train Loss: 1.1227 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1217 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 49/150
Train Loss: 1.1218 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1206 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 50/150
Train Loss: 1.1206 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1188 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 51/150
Train Loss: 1.1181 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1153 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 52/150
Train Loss: 1.1090 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0830 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 53/150
Train Loss: 1.0573 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0701 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 54/150
Train Loss: 1.0487 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0316 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 55/150
Train Loss: 1.1126 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1585 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 56/150
Train Loss: 1.1314 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1276 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 57/150
Train Loss: 1.1276 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1275 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 58/150
Train Loss: 1.1275 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1269 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 59/150
Train Loss: 1.1270 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1266 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 60/150
Train Loss: 1.1268 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1263 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 61/150
Train Loss: 1.1264 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1262 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 62/150
Train Loss: 1.1260 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1257 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 63/150
Train Loss: 1.1252 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1247 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 64/150
Train Loss: 1.1243 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1233 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 65/150
Train Loss: 1.1223 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1194 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 66/150
Train Loss: 1.0758 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0416 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 67/150
Train Loss: 1.0460 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0544 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 68/150
Train Loss: 1.0342 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0984 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 69/150
Train Loss: 1.0986 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.2254 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 70/150
Train Loss: 1.1454 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1287 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 71/150
Train Loss: 1.1290 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1287 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 72/150
Train Loss: 1.1288 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1284 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 73/150
Train Loss: 1.1286 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1283 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 74/150
Train Loss: 1.1286 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1282 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 75/150
Train Loss: 1.1284 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1281 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 76/150
Train Loss: 1.1283 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1285 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 77/150
Train Loss: 1.1283 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1278 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 78/150
Train Loss: 1.1281 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1284 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 79/150
Train Loss: 1.1281 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1276 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 80/150
Train Loss: 1.1278 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1275 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 81/150
Train Loss: 1.1278 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1276 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 82/150
Train Loss: 1.1278 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1273 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 83/150
Train Loss: 1.1277 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1272 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 84/150
Train Loss: 1.1275 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1271 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 85/150
Train Loss: 1.1274 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1270 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 86/150
Train Loss: 1.1273 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1268 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 87/150
Train Loss: 1.1273 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1273 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 88/150
Train Loss: 1.1272 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1267 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 89/150
Train Loss: 1.1270 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1266 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 90/150
Train Loss: 1.1268 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1264 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 91/150
Train Loss: 1.1267 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1261 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 92/150
Train Loss: 1.1263 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1258 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 93/150
Train Loss: 1.1263 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1260 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 94/150
Train Loss: 1.1262 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1255 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 95/150
Train Loss: 1.1258 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1252 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 96/150
Train Loss: 1.1254 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1253 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 97/150
Train Loss: 1.1252 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1248 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 98/150
Train Loss: 1.1249 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1242 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 99/150
Train Loss: 1.1246 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1238 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 100/150
Train Loss: 1.1242 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1235 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 101/150
Train Loss: 1.1239 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1232 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 102/150
Train Loss: 1.1235 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1230 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 103/150
Train Loss: 1.1232 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1224 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 104/150
Train Loss: 1.1228 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1223 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 105/150
Train Loss: 1.1223 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1217 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 106/150
Train Loss: 1.1217 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1209 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 107/150
Train Loss: 1.1212 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1207 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 108/150
Train Loss: 1.1206 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1196 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 109/150

wandb: Agent Starting Run: sfrf05a5 with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.0001600672927381994
wandb: 	optimizer: adam
wandb: 	rnn_type: rnn
wandb: 	seq_len: 120
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.1479 | Train Acc: 64.44% | Precision: 46.82% Recall: 64.44% F1: 51.23%
Val   Loss: 1.1078 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.0826 | Train Acc: 63.79% | Precision: 46.63% Recall: 63.79% F1: 51.10%
Val   Loss: 1.0945 | Val Acc: 63.18%   | Precision: 44.11% Recall: 63.18% F1: 50.96%

Epoch: 3/150
Train Loss: 1.0032 | Train Acc: 64.56% | Precision: 52.01% Recall: 64.56% F1: 52.97%
Val   Loss: 0.8944 | Val Acc: 68.31%   | Precision: 56.79% Recall: 68.31% F1: 59.92%

Epoch: 4/150
Train Loss: 0.8617 | Train Acc: 69.89% | Precision: 62.38% Recall: 69.89% F1: 63.29%
Val   Loss: 0.7671 | Val Acc: 73.21%   | Precision: 65.15% Recall: 73.21% F1: 67.00%

Epoch: 5/150
Train Loss: 0.7595 | Train Acc: 73.71% | Precision: 66.88% Recall: 73.71% F1: 67.60%
Val   Loss: 0.7083 | Val Acc: 74.96%   | Precision: 69.19% Recall: 74.96% F1: 68.49%

Epoch: 6/150
Train Loss: 0.7259 | Train Acc: 75.01% | Precision: 74.53% Recall: 75.01% F1: 69.31%
Val   Loss: 0.6570 | Val Acc: 78.48%   | Precision: 72.55% Recall: 78.48% F1: 74.46%

Epoch: 7/150
Train Loss: 0.6448 | Train Acc: 78.37% | Precision: 77.16% Recall: 78.37% F1: 73.85%
Val   Loss: 0.6045 | Val Acc: 80.28%   | Precision: 80.07% Recall: 80.28% F1: 76.37%

Epoch: 8/150
Train Loss: 0.6137 | Train Acc: 80.32% | Precision: 79.79% Recall: 80.32% F1: 77.13%
Val   Loss: 0.6950 | Val Acc: 76.95%   | Precision: 76.59% Recall: 76.95% F1: 70.33%

Epoch: 9/150
Train Loss: 0.5806 | Train Acc: 82.13% | Precision: 81.77% Recall: 82.13% F1: 79.93%
Val   Loss: 0.5108 | Val Acc: 85.79%   | Precision: 85.91% Recall: 85.79% F1: 84.49%

Epoch: 10/150
Train Loss: 0.5538 | Train Acc: 83.26% | Precision: 82.89% Recall: 83.26% F1: 81.56%
Val   Loss: 0.7280 | Val Acc: 76.60%   | Precision: 74.11% Recall: 76.60% F1: 73.36%

Epoch: 11/150
Train Loss: 0.4912 | Train Acc: 85.51% | Precision: 85.21% Recall: 85.51% F1: 84.42%
Val   Loss: 0.5908 | Val Acc: 80.74%   | Precision: 79.41% Recall: 80.74% F1: 78.11%

Epoch: 12/150
Train Loss: 0.5039 | Train Acc: 84.91% | Precision: 84.55% Recall: 84.91% F1: 83.78%
Val   Loss: 0.4493 | Val Acc: 86.71%   | Precision: 86.56% Recall: 86.71% F1: 86.00%

Epoch: 13/150
Train Loss: 0.4335 | Train Acc: 87.15% | Precision: 86.98% Recall: 87.15% F1: 86.37%
Val   Loss: 0.4174 | Val Acc: 88.09%   | Precision: 87.98% Recall: 88.09% F1: 87.31%

Epoch: 14/150
Train Loss: 0.4183 | Train Acc: 87.61% | Precision: 87.48% Recall: 87.61% F1: 86.90%
Val   Loss: 0.3987 | Val Acc: 88.14%   | Precision: 88.19% Recall: 88.14% F1: 87.21%

Epoch: 15/150
Train Loss: 0.3829 | Train Acc: 88.79% | Precision: 88.73% Recall: 88.79% F1: 88.21%
Val   Loss: 0.3611 | Val Acc: 89.29%   | Precision: 89.18% Recall: 89.29% F1: 88.70%

Epoch: 16/150
Train Loss: 0.3791 | Train Acc: 88.75% | Precision: 88.65% Recall: 88.75% F1: 88.22%
Val   Loss: 0.4157 | Val Acc: 87.70%   | Precision: 87.64% Recall: 87.70% F1: 86.87%

Epoch: 17/150
Train Loss: 0.3729 | Train Acc: 89.02% | Precision: 88.94% Recall: 89.02% F1: 88.50%
Val   Loss: 0.5192 | Val Acc: 83.89%   | Precision: 83.60% Recall: 83.89% F1: 82.58%

Epoch: 18/150
Train Loss: 0.5763 | Train Acc: 82.14% | Precision: 81.69% Recall: 82.14% F1: 80.64%
Val   Loss: 0.5526 | Val Acc: 83.87%   | Precision: 83.80% Recall: 83.87% F1: 82.04%

Epoch: 19/150
Train Loss: 0.4516 | Train Acc: 86.94% | Precision: 86.71% Recall: 86.94% F1: 86.13%
Val   Loss: 0.3899 | Val Acc: 88.22%   | Precision: 88.04% Recall: 88.22% F1: 87.48%

Epoch: 20/150
Train Loss: 0.3760 | Train Acc: 88.80% | Precision: 88.72% Recall: 88.80% F1: 88.27%
Val   Loss: 0.3551 | Val Acc: 89.91%   | Precision: 90.03% Recall: 89.91% F1: 89.29%

Epoch: 21/150
Train Loss: 0.3491 | Train Acc: 89.91% | Precision: 89.87% Recall: 89.91% F1: 89.48%
Val   Loss: 0.3382 | Val Acc: 89.68%   | Precision: 89.70% Recall: 89.68% F1: 89.30%

Epoch: 22/150
Train Loss: 0.3463 | Train Acc: 89.92% | Precision: 89.85% Recall: 89.92% F1: 89.51%
Val   Loss: 0.3347 | Val Acc: 90.12%   | Precision: 90.08% Recall: 90.12% F1: 89.69%

Epoch: 23/150
Train Loss: 0.3262 | Train Acc: 90.50% | Precision: 90.48% Recall: 90.50% F1: 90.12%
Val   Loss: 0.3336 | Val Acc: 90.27%   | Precision: 90.33% Recall: 90.27% F1: 89.94%

Epoch: 24/150
Train Loss: 0.3666 | Train Acc: 89.23% | Precision: 89.15% Recall: 89.23% F1: 88.75%
Val   Loss: 0.5337 | Val Acc: 84.99%   | Precision: 85.85% Recall: 84.99% F1: 82.60%

Epoch: 25/150
Train Loss: 0.6590 | Train Acc: 78.99% | Precision: 78.19% Recall: 78.99% F1: 76.26%
Val   Loss: 0.5389 | Val Acc: 83.48%   | Precision: 83.37% Recall: 83.48% F1: 80.50%

Epoch: 26/150
Train Loss: 0.4439 | Train Acc: 86.85% | Precision: 86.66% Recall: 86.85% F1: 85.99%
Val   Loss: 0.4021 | Val Acc: 87.59%   | Precision: 87.77% Recall: 87.59% F1: 87.27%

Epoch: 27/150
Train Loss: 0.4342 | Train Acc: 86.82% | Precision: 86.58% Recall: 86.82% F1: 86.00%
Val   Loss: 0.4621 | Val Acc: 86.12%   | Precision: 86.37% Recall: 86.12% F1: 84.87%

Epoch: 28/150
Train Loss: 0.4124 | Train Acc: 87.72% | Precision: 87.60% Recall: 87.72% F1: 87.02%
Val   Loss: 0.3560 | Val Acc: 88.87%   | Precision: 88.84% Recall: 88.87% F1: 88.43%

Epoch: 29/150
Train Loss: 0.4993 | Train Acc: 84.44% | Precision: 84.11% Recall: 84.44% F1: 83.13%
Val   Loss: 0.4605 | Val Acc: 85.78%   | Precision: 85.78% Recall: 85.78% F1: 84.12%

Epoch: 30/150
Train Loss: 0.5633 | Train Acc: 82.07% | Precision: 81.64% Recall: 82.07% F1: 80.47%
Val   Loss: 0.8870 | Val Acc: 72.43%   | Precision: 61.33% Recall: 72.43% F1: 65.92%

Epoch: 31/150
Train Loss: 0.5257 | Train Acc: 83.76% | Precision: 83.29% Recall: 83.76% F1: 82.17%
Val   Loss: 0.4311 | Val Acc: 86.94%   | Precision: 87.14% Recall: 86.94% F1: 86.35%

Epoch: 32/150
Train Loss: 0.4279 | Train Acc: 87.23% | Precision: 87.06% Recall: 87.23% F1: 86.46%
Val   Loss: 0.3912 | Val Acc: 88.51%   | Precision: 88.39% Recall: 88.51% F1: 87.82%

Epoch: 33/150
Train Loss: 0.4502 | Train Acc: 86.09% | Precision: 85.82% Recall: 86.09% F1: 85.20%
Val   Loss: 0.4441 | Val Acc: 86.92%   | Precision: 86.82% Recall: 86.92% F1: 86.10%

Epoch: 34/150
Train Loss: 0.5593 | Train Acc: 82.60% | Precision: 82.26% Recall: 82.60% F1: 80.88%
Val   Loss: 0.5303 | Val Acc: 82.74%   | Precision: 84.14% Recall: 82.74% F1: 82.64%

Epoch: 35/150
Train Loss: 0.4326 | Train Acc: 87.64% | Precision: 87.62% Recall: 87.64% F1: 86.94%
Val   Loss: 0.4130 | Val Acc: 87.51%   | Precision: 87.66% Recall: 87.51% F1: 86.67%

Epoch: 36/150
Train Loss: 0.3971 | Train Acc: 88.42% | Precision: 88.43% Recall: 88.42% F1: 87.81%
Val   Loss: 0.3826 | Val Acc: 89.10%   | Precision: 89.11% Recall: 89.10% F1: 88.54%

Epoch: 37/150
Train Loss: 0.3879 | Train Acc: 88.60% | Precision: 88.60% Recall: 88.60% F1: 88.02%
Val   Loss: 0.3747 | Val Acc: 88.93%   | Precision: 88.89% Recall: 88.93% F1: 88.42%

Epoch: 38/150
Train Loss: 0.3672 | Train Acc: 89.16% | Precision: 89.13% Recall: 89.16% F1: 88.62%
Val   Loss: 0.3684 | Val Acc: 88.58%   | Precision: 88.43% Recall: 88.58% F1: 87.93%

Epoch: 39/150
Train Loss: 0.3539 | Train Acc: 89.51% | Precision: 89.48% Recall: 89.51% F1: 88.99%
Val   Loss: 0.3539 | Val Acc: 89.52%   | Precision: 89.52% Recall: 89.52% F1: 89.12%

Epoch: 40/150
Train Loss: 0.3516 | Train Acc: 89.57% | Precision: 89.56% Recall: 89.57% F1: 89.05%
Val   Loss: 0.4099 | Val Acc: 87.38%   | Precision: 87.32% Recall: 87.38% F1: 86.52%

Epoch: 41/150
Train Loss: 0.3501 | Train Acc: 89.49% | Precision: 89.45% Recall: 89.49% F1: 88.98%
Val   Loss: 0.3386 | Val Acc: 89.49%   | Precision: 89.54% Recall: 89.49% F1: 88.79%

Epoch: 42/150
Train Loss: 0.8060 | Train Acc: 73.00% | Precision: 73.30% Recall: 73.00% F1: 69.18%
Val   Loss: 0.9094 | Val Acc: 66.84%   | Precision: 57.45% Recall: 66.84% F1: 58.94%

Epoch: 43/150
Train Loss: 0.8329 | Train Acc: 70.16% | Precision: 62.82% Recall: 70.16% F1: 64.36%
Val   Loss: 0.7726 | Val Acc: 72.22%   | Precision: 65.50% Recall: 72.22% F1: 67.97%

Epoch: 44/150
Train Loss: 0.7079 | Train Acc: 76.07% | Precision: 74.00% Recall: 76.07% F1: 70.98%
Val   Loss: 0.6940 | Val Acc: 77.96%   | Precision: 71.64% Recall: 77.96% F1: 73.90%

Epoch: 45/150
Train Loss: 0.6097 | Train Acc: 79.92% | Precision: 78.94% Recall: 79.92% F1: 75.88%
Val   Loss: 0.6097 | Val Acc: 80.75%   | Precision: 80.53% Recall: 80.75% F1: 76.76%

Epoch: 46/150
Train Loss: 0.5757 | Train Acc: 81.71% | Precision: 80.61% Recall: 81.71% F1: 78.91%
Val   Loss: 0.5157 | Val Acc: 84.26%   | Precision: 83.69% Recall: 84.26% F1: 81.85%

Epoch: 47/150
Train Loss: 0.5509 | Train Acc: 82.72% | Precision: 81.69% Recall: 82.72% F1: 80.52%
Val   Loss: 0.4988 | Val Acc: 85.10%   | Precision: 84.44% Recall: 85.10% F1: 83.48%

Epoch: 48/150
Train Loss: 0.5825 | Train Acc: 81.55% | Precision: 80.51% Recall: 81.55% F1: 79.21%
Val   Loss: 0.4570 | Val Acc: 86.32%   | Precision: 85.90% Recall: 86.32% F1: 85.04%

Epoch: 49/150
Train Loss: 0.4734 | Train Acc: 85.27% | Precision: 84.71% Recall: 85.27% F1: 84.00%
Val   Loss: 0.4691 | Val Acc: 85.45%   | Precision: 85.40% Recall: 85.45% F1: 83.81%

Epoch: 50/150
Train Loss: 0.4534 | Train Acc: 86.03% | Precision: 85.58% Recall: 86.03% F1: 84.95%
Val   Loss: 0.4103 | Val Acc: 87.25%   | Precision: 86.91% Recall: 87.25% F1: 86.05%

Epoch: 51/150
Train Loss: 0.4331 | Train Acc: 86.65% | Precision: 86.29% Recall: 86.65% F1: 85.74%
Val   Loss: 0.4158 | Val Acc: 86.86%   | Precision: 86.20% Recall: 86.86% F1: 86.13%

Epoch: 52/150
Train Loss: 0.6012 | Train Acc: 80.53% | Precision: 79.16% Recall: 80.53% F1: 77.97%
Val   Loss: 0.5320 | Val Acc: 82.94%   | Precision: 82.01% Recall: 82.94% F1: 81.22%

Epoch: 53/150
Train Loss: 0.4940 | Train Acc: 84.91% | Precision: 84.32% Recall: 84.91% F1: 83.56%
Val   Loss: 0.4815 | Val Acc: 84.70%   | Precision: 84.37% Recall: 84.70% F1: 82.79%

Epoch: 54/150
Train Loss: 0.4541 | Train Acc: 86.10% | Precision: 85.62% Recall: 86.10% F1: 85.10%
Val   Loss: 0.4404 | Val Acc: 86.74%   | Precision: 86.72% Recall: 86.74% F1: 85.67%

Epoch: 55/150
Train Loss: 0.4242 | Train Acc: 87.11% | Precision: 86.76% Recall: 87.11% F1: 86.28%
Val   Loss: 0.4151 | Val Acc: 86.79%   | Precision: 86.48% Recall: 86.79% F1: 85.70%

Epoch: 56/150
Train Loss: 0.4005 | Train Acc: 87.87% | Precision: 87.63% Recall: 87.87% F1: 87.14%
Val   Loss: 0.3735 | Val Acc: 88.92%   | Precision: 88.79% Recall: 88.92% F1: 88.28%

Epoch: 57/150
Train Loss: 0.3840 | Train Acc: 88.33% | Precision: 88.11% Recall: 88.33% F1: 87.68%
Val   Loss: 0.3986 | Val Acc: 87.26%   | Precision: 87.17% Recall: 87.26% F1: 85.59%

Epoch: 58/150
Train Loss: 0.3671 | Train Acc: 88.89% | Precision: 88.73% Recall: 88.89% F1: 88.29%
Val   Loss: 0.3563 | Val Acc: 89.20%   | Precision: 89.15% Recall: 89.20% F1: 88.61%

Epoch: 59/150
Train Loss: 0.3503 | Train Acc: 89.33% | Precision: 89.19% Recall: 89.33% F1: 88.80%
Val   Loss: 0.3203 | Val Acc: 90.19%   | Precision: 90.04% Recall: 90.19% F1: 89.62%

Epoch: 60/150
Train Loss: 0.3885 | Train Acc: 87.76% | Precision: 87.51% Recall: 87.76% F1: 87.01%
Val   Loss: 0.3326 | Val Acc: 89.84%   | Precision: 89.69% Recall: 89.84% F1: 89.28%

Epoch: 61/150
Train Loss: 0.3404 | Train Acc: 89.68% | Precision: 89.56% Recall: 89.68% F1: 89.18%
Val   Loss: 0.3446 | Val Acc: 89.24%   | Precision: 89.14% Recall: 89.24% F1: 88.75%

Epoch: 62/150
Train Loss: 0.5129 | Train Acc: 82.47% | Precision: 81.87% Recall: 82.47% F1: 81.02%
Val   Loss: 0.5359 | Val Acc: 82.82%   | Precision: 82.92% Recall: 82.82% F1: 81.94%

Epoch: 63/150
Train Loss: 0.4666 | Train Acc: 85.16% | Precision: 84.97% Recall: 85.16% F1: 84.02%
Val   Loss: 0.4100 | Val Acc: 87.36%   | Precision: 87.26% Recall: 87.36% F1: 86.51%

Epoch: 64/150
Train Loss: 0.4453 | Train Acc: 86.18% | Precision: 85.99% Recall: 86.18% F1: 85.30%
Val   Loss: 0.4205 | Val Acc: 87.09%   | Precision: 87.09% Recall: 87.09% F1: 86.28%

Epoch: 65/150
Train Loss: 0.4034 | Train Acc: 87.58% | Precision: 87.47% Recall: 87.58% F1: 86.92%
Val   Loss: 0.3782 | Val Acc: 88.33%   | Precision: 88.37% Recall: 88.33% F1: 87.64%

Epoch: 66/150
Train Loss: 0.3737 | Train Acc: 88.57% | Precision: 88.48% Recall: 88.57% F1: 87.99%
Val   Loss: 0.3646 | Val Acc: 88.82%   | Precision: 88.94% Recall: 88.82% F1: 88.41%

Epoch: 67/150
Train Loss: 0.3583 | Train Acc: 89.06% | Precision: 88.99% Recall: 89.06% F1: 88.54%
Val   Loss: 0.3915 | Val Acc: 87.81%   | Precision: 87.92% Recall: 87.81% F1: 87.09%

Epoch: 68/150
Train Loss: 0.3477 | Train Acc: 89.51% | Precision: 89.42% Recall: 89.51% F1: 89.03%
Val   Loss: 0.3135 | Val Acc: 90.45%   | Precision: 90.54% Recall: 90.45% F1: 89.92%

Epoch: 69/150
Train Loss: 0.3391 | Train Acc: 89.85% | Precision: 89.78% Recall: 89.85% F1: 89.39%
Val   Loss: 0.3715 | Val Acc: 88.57%   | Precision: 88.41% Recall: 88.57% F1: 87.94%

Epoch: 70/150
Train Loss: 0.3299 | Train Acc: 90.02% | Precision: 89.95% Recall: 90.02% F1: 89.58%
Val   Loss: 0.3341 | Val Acc: 90.06%   | Precision: 89.82% Recall: 90.06% F1: 89.62%

Epoch: 71/150
Train Loss: 0.3251 | Train Acc: 90.23% | Precision: 90.12% Recall: 90.23% F1: 89.80%
Val   Loss: 0.5358 | Val Acc: 81.89%   | Precision: 83.67% Recall: 81.89% F1: 80.41%

Epoch: 72/150
Train Loss: 0.8019 | Train Acc: 72.44% | Precision: 66.77% Recall: 72.44% F1: 68.00%
Val   Loss: 0.6267 | Val Acc: 79.01%   | Precision: 72.99% Recall: 79.01% F1: 75.20%

Epoch: 73/150
Train Loss: 0.5800 | Train Acc: 80.04% | Precision: 77.19% Recall: 80.04% F1: 76.64%
Val   Loss: 0.5884 | Val Acc: 79.81%   | Precision: 74.22% Recall: 79.81% F1: 75.67%

Epoch: 74/150
Train Loss: 0.5415 | Train Acc: 81.75% | Precision: 81.15% Recall: 81.75% F1: 78.88%
Val   Loss: 0.4942 | Val Acc: 84.74%   | Precision: 85.20% Recall: 84.74% F1: 83.21%

Epoch: 75/150
Train Loss: 0.4728 | Train Acc: 85.65% | Precision: 85.47% Recall: 85.65% F1: 84.64%
Val   Loss: 0.4516 | Val Acc: 86.20%   | Precision: 85.82% Recall: 86.20% F1: 85.39%

Epoch: 76/150
Train Loss: 0.4373 | Train Acc: 86.56% | Precision: 86.43% Recall: 86.56% F1: 85.69%
Val   Loss: 0.4176 | Val Acc: 87.28%   | Precision: 87.22% Recall: 87.28% F1: 86.25%

Epoch: 77/150
Train Loss: 0.4258 | Train Acc: 87.01% | Precision: 86.90% Recall: 87.01% F1: 86.14%
Val   Loss: 0.4471 | Val Acc: 85.85%   | Precision: 86.23% Recall: 85.85% F1: 85.37%

Epoch: 78/150
Train Loss: 0.5957 | Train Acc: 80.44% | Precision: 79.67% Recall: 80.44% F1: 77.65%
Val   Loss: 0.5166 | Val Acc: 83.94%   | Precision: 85.75% Recall: 83.94% F1: 83.95%

Epoch: 79/150
Train Loss: 0.4420 | Train Acc: 86.63% | Precision: 86.39% Recall: 86.63% F1: 85.72%
Val   Loss: 0.4358 | Val Acc: 86.88%   | Precision: 86.48% Recall: 86.88% F1: 86.08%

Epoch: 80/150
Train Loss: 0.4082 | Train Acc: 87.58% | Precision: 87.48% Recall: 87.58% F1: 86.85%
Val   Loss: 0.4273 | Val Acc: 86.19%   | Precision: 85.60% Recall: 86.19% F1: 85.35%

Epoch: 81/150
Train Loss: 0.3786 | Train Acc: 88.41% | Precision: 88.41% Recall: 88.41% F1: 87.77%
Val   Loss: 0.3961 | Val Acc: 87.27%   | Precision: 87.49% Recall: 87.27% F1: 85.99%

Epoch: 82/150
Train Loss: 0.3710 | Train Acc: 88.53% | Precision: 88.54% Recall: 88.53% F1: 87.91%
Val   Loss: 0.3590 | Val Acc: 88.14%   | Precision: 88.36% Recall: 88.14% F1: 87.31%

Epoch: 83/150
Train Loss: 0.3753 | Train Acc: 88.27% | Precision: 88.28% Recall: 88.27% F1: 87.60%
Val   Loss: 0.7302 | Val Acc: 79.74%   | Precision: 76.41% Recall: 79.74% F1: 77.18%

Epoch: 84/150
Train Loss: 0.4800 | Train Acc: 85.08% | Precision: 84.74% Recall: 85.08% F1: 83.75%
Val   Loss: 0.3989 | Val Acc: 87.27%   | Precision: 87.25% Recall: 87.27% F1: 86.58%

Epoch: 85/150
Train Loss: 0.3632 | Train Acc: 88.92% | Precision: 88.98% Recall: 88.92% F1: 88.30%
Val   Loss: 0.3553 | Val Acc: 88.99%   | Precision: 88.89% Recall: 88.99% F1: 88.31%

Epoch: 86/150
Train Loss: 0.3439 | Train Acc: 89.48% | Precision: 89.52% Recall: 89.48% F1: 88.93%
Val   Loss: 0.3456 | Val Acc: 89.25%   | Precision: 89.33% Recall: 89.25% F1: 88.81%

Epoch: 87/150
Train Loss: 0.7666 | Train Acc: 74.74% | Precision: 73.86% Recall: 74.74% F1: 70.54%
Val   Loss: 0.6696 | Val Acc: 77.14%   | Precision: 76.78% Recall: 77.14% F1: 72.68%

Epoch: 88/150
Train Loss: 0.5625 | Train Acc: 81.76% | Precision: 80.94% Recall: 81.76% F1: 79.35%
Val   Loss: 0.5122 | Val Acc: 83.72%   | Precision: 83.27% Recall: 83.72% F1: 81.41%

Epoch: 89/150
Train Loss: 0.5125 | Train Acc: 83.82% | Precision: 83.20% Recall: 83.82% F1: 82.36%
Val   Loss: 0.4800 | Val Acc: 85.01%   | Precision: 85.47% Recall: 85.01% F1: 84.06%

Epoch: 90/150
Train Loss: 0.4779 | Train Acc: 85.01% | Precision: 84.52% Recall: 85.01% F1: 83.96%
Val   Loss: 0.4545 | Val Acc: 85.94%   | Precision: 85.45% Recall: 85.94% F1: 85.32%

Epoch: 91/150
Train Loss: 0.4403 | Train Acc: 86.53% | Precision: 86.23% Recall: 86.53% F1: 85.67%
Val   Loss: 0.4348 | Val Acc: 86.36%   | Precision: 86.06% Recall: 86.36% F1: 85.27%

Epoch: 92/150
Train Loss: 0.4424 | Train Acc: 86.48% | Precision: 86.19% Recall: 86.48% F1: 85.58%
Val   Loss: 0.4016 | Val Acc: 88.46%   | Precision: 88.35% Recall: 88.46% F1: 87.76%

Epoch: 93/150
Train Loss: 0.4034 | Train Acc: 87.92% | Precision: 87.75% Recall: 87.92% F1: 87.21%
Val   Loss: 0.3719 | Val Acc: 89.17%   | Precision: 88.98% Recall: 89.17% F1: 88.54%

Epoch: 94/150
Train Loss: 0.3790 | Train Acc: 88.74% | Precision: 88.65% Recall: 88.74% F1: 88.14%
Val   Loss: 0.3662 | Val Acc: 88.93%   | Precision: 88.87% Recall: 88.93% F1: 88.11%

Epoch: 95/150
Train Loss: 0.3533 | Train Acc: 89.51% | Precision: 89.47% Recall: 89.51% F1: 88.99%
Val   Loss: 0.3490 | Val Acc: 89.48%   | Precision: 89.49% Recall: 89.48% F1: 88.70%

Epoch: 96/150
Train Loss: 0.4033 | Train Acc: 87.68% | Precision: 87.54% Recall: 87.68% F1: 87.02%
Val   Loss: 0.4704 | Val Acc: 85.15%   | Precision: 85.09% Recall: 85.15% F1: 84.46%

Epoch: 97/150
Train Loss: 0.3649 | Train Acc: 88.89% | Precision: 88.82% Recall: 88.89% F1: 88.31%
Val   Loss: 0.3490 | Val Acc: 89.63%   | Precision: 89.56% Recall: 89.63% F1: 89.04%

Epoch: 98/150
Train Loss: 0.3318 | Train Acc: 90.07% | Precision: 90.02% Recall: 90.07% F1: 89.61%
Val   Loss: 0.3343 | Val Acc: 89.83%   | Precision: 89.90% Recall: 89.83% F1: 89.20%

Epoch: 99/150
Train Loss: 0.3236 | Train Acc: 90.10% | Precision: 90.04% Recall: 90.10% F1: 89.66%
Val   Loss: 0.3367 | Val Acc: 89.52%   | Precision: 89.87% Recall: 89.52% F1: 89.34%

Epoch: 100/150
Train Loss: 0.3130 | Train Acc: 90.39% | Precision: 90.34% Recall: 90.39% F1: 89.96%
Val   Loss: 0.2849 | Val Acc: 91.53%   | Precision: 91.38% Recall: 91.53% F1: 91.16%

Epoch: 101/150
Train Loss: 0.3005 | Train Acc: 90.84% | Precision: 90.79% Recall: 90.84% F1: 90.47%
Val   Loss: 0.2843 | Val Acc: 91.41%   | Precision: 91.32% Recall: 91.41% F1: 90.99%

Epoch: 102/150
Train Loss: 0.2969 | Train Acc: 91.02% | Precision: 90.98% Recall: 91.02% F1: 90.65%
Val   Loss: 0.2949 | Val Acc: 91.16%   | Precision: 91.12% Recall: 91.16% F1: 90.88%

Epoch: 103/150
Train Loss: 0.3100 | Train Acc: 90.51% | Precision: 90.42% Recall: 90.51% F1: 90.10%
Val   Loss: 0.2887 | Val Acc: 91.10%   | Precision: 90.96% Recall: 91.10% F1: 90.73%

Epoch: 104/150
Train Loss: 0.2897 | Train Acc: 91.07% | Precision: 91.00% Recall: 91.07% F1: 90.73%
Val   Loss: 0.3032 | Val Acc: 90.88%   | Precision: 90.72% Recall: 90.88% F1: 90.47%

Epoch: 105/150
Train Loss: 0.3082 | Train Acc: 90.35% | Precision: 90.26% Recall: 90.35% F1: 89.95%
Val   Loss: 0.2642 | Val Acc: 91.99%   | Precision: 91.90% Recall: 91.99% F1: 91.66%

Epoch: 106/150
Train Loss: 0.2837 | Train Acc: 91.28% | Precision: 91.23% Recall: 91.28% F1: 90.93%
Val   Loss: 0.2517 | Val Acc: 92.28%   | Precision: 92.19% Recall: 92.28% F1: 91.98%

Epoch: 107/150
Train Loss: 0.2786 | Train Acc: 91.37% | Precision: 91.30% Recall: 91.37% F1: 91.04%
Val   Loss: 0.2501 | Val Acc: 92.38%   | Precision: 92.29% Recall: 92.38% F1: 92.06%

Epoch: 108/150
Train Loss: 0.2705 | Train Acc: 91.68% | Precision: 91.62% Recall: 91.68% F1: 91.37%
Val   Loss: 0.2474 | Val Acc: 92.00%   | Precision: 91.90% Recall: 92.00% F1: 91.68%

Epoch: 109/150

wandb: Agent Starting Run: cul69xj9 with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.0001838718600903423
wandb: 	optimizer: adam
wandb: 	rnn_type: rnn
wandb: 	seq_len: 130
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 0.9458 | Train Acc: 68.80% | Precision: 60.28% Recall: 68.80% F1: 59.95%
Val   Loss: 0.8074 | Val Acc: 71.62%   | Precision: 65.61% Recall: 71.62% F1: 64.53%

Epoch: 2/150
Train Loss: 0.7860 | Train Acc: 72.01% | Precision: 71.02% Recall: 72.01% F1: 65.63%
Val   Loss: 0.7652 | Val Acc: 73.53%   | Precision: 66.10% Recall: 73.53% F1: 68.97%

Epoch: 3/150
Train Loss: 0.6864 | Train Acc: 75.81% | Precision: 74.52% Recall: 75.81% F1: 71.25%
Val   Loss: 0.6225 | Val Acc: 77.63%   | Precision: 76.69% Recall: 77.63% F1: 73.19%

Epoch: 4/150
Train Loss: 0.5656 | Train Acc: 82.10% | Precision: 81.68% Recall: 82.10% F1: 79.87%
Val   Loss: 0.5398 | Val Acc: 83.48%   | Precision: 83.30% Recall: 83.48% F1: 81.33%

Epoch: 5/150
Train Loss: 0.5016 | Train Acc: 85.18% | Precision: 84.92% Recall: 85.18% F1: 83.94%
Val   Loss: 0.4841 | Val Acc: 85.54%   | Precision: 85.61% Recall: 85.54% F1: 85.17%

Epoch: 6/150
Train Loss: 0.4804 | Train Acc: 85.78% | Precision: 85.53% Recall: 85.78% F1: 84.68%
Val   Loss: 0.4694 | Val Acc: 85.81%   | Precision: 85.53% Recall: 85.81% F1: 85.02%

Epoch: 7/150
Train Loss: 0.4614 | Train Acc: 86.39% | Precision: 86.18% Recall: 86.39% F1: 85.47%
Val   Loss: 0.4510 | Val Acc: 86.90%   | Precision: 87.09% Recall: 86.90% F1: 86.30%

Epoch: 8/150
Train Loss: 0.4922 | Train Acc: 84.74% | Precision: 84.45% Recall: 84.74% F1: 83.60%
Val   Loss: 0.7163 | Val Acc: 75.81%   | Precision: 71.72% Recall: 75.81% F1: 70.70%

Epoch: 9/150
Train Loss: 0.5087 | Train Acc: 84.87% | Precision: 84.55% Recall: 84.87% F1: 83.41%
Val   Loss: 0.4485 | Val Acc: 87.05%   | Precision: 87.01% Recall: 87.05% F1: 86.14%

Epoch: 10/150
Train Loss: 0.4270 | Train Acc: 87.37% | Precision: 87.29% Recall: 87.37% F1: 86.53%
Val   Loss: 0.4330 | Val Acc: 87.60%   | Precision: 87.86% Recall: 87.60% F1: 86.78%

Epoch: 11/150
Train Loss: 0.7671 | Train Acc: 78.00% | Precision: 78.11% Recall: 78.00% F1: 75.67%
Val   Loss: 1.1038 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 12/150
Train Loss: 1.0810 | Train Acc: 64.25% | Precision: 44.41% Recall: 64.25% F1: 50.79%
Val   Loss: 1.0580 | Val Acc: 62.89%   | Precision: 43.28% Recall: 62.89% F1: 50.54%

Epoch: 13/150
Train Loss: 1.0500 | Train Acc: 64.35% | Precision: 49.65% Recall: 64.35% F1: 52.61%
Val   Loss: 1.0245 | Val Acc: 64.72%   | Precision: 47.61% Recall: 64.72% F1: 54.15%

Epoch: 14/150
Train Loss: 0.9359 | Train Acc: 67.11% | Precision: 57.09% Recall: 67.11% F1: 59.26%
Val   Loss: 0.8308 | Val Acc: 72.68%   | Precision: 61.75% Recall: 72.68% F1: 66.24%

Epoch: 15/150
Train Loss: 0.8127 | Train Acc: 72.37% | Precision: 64.74% Recall: 72.37% F1: 65.67%
Val   Loss: 0.8125 | Val Acc: 72.07%   | Precision: 59.95% Recall: 72.07% F1: 64.29%

Epoch: 16/150
Train Loss: 0.7948 | Train Acc: 72.95% | Precision: 65.82% Recall: 72.95% F1: 66.35%
Val   Loss: 0.7771 | Val Acc: 74.96%   | Precision: 69.83% Recall: 74.96% F1: 68.88%

Epoch: 17/150
Train Loss: 0.7736 | Train Acc: 73.88% | Precision: 66.61% Recall: 73.88% F1: 67.74%
Val   Loss: 0.7480 | Val Acc: 74.00%   | Precision: 69.84% Recall: 74.00% F1: 67.15%

Epoch: 18/150
Train Loss: 0.7746 | Train Acc: 73.86% | Precision: 66.60% Recall: 73.86% F1: 67.90%
Val   Loss: 1.0641 | Val Acc: 64.48%   | Precision: 41.66% Recall: 64.48% F1: 50.61%

Epoch: 19/150
Train Loss: 0.9682 | Train Acc: 66.64% | Precision: 55.57% Recall: 66.64% F1: 56.92%
Val   Loss: 0.8337 | Val Acc: 71.83%   | Precision: 60.27% Recall: 71.83% F1: 64.41%

Epoch: 20/150
Train Loss: 0.8028 | Train Acc: 72.60% | Precision: 65.33% Recall: 72.60% F1: 65.71%
Val   Loss: 0.7824 | Val Acc: 73.99%   | Precision: 67.25% Recall: 73.99% F1: 67.62%

Epoch: 21/150
Train Loss: 0.7726 | Train Acc: 73.83% | Precision: 66.31% Recall: 73.83% F1: 67.46%
Val   Loss: 0.7576 | Val Acc: 74.97%   | Precision: 67.33% Recall: 74.97% F1: 69.44%

Epoch: 22/150
Train Loss: 0.7485 | Train Acc: 74.81% | Precision: 67.66% Recall: 74.81% F1: 68.87%
Val   Loss: 0.7293 | Val Acc: 74.57%   | Precision: 67.53% Recall: 74.57% F1: 69.40%

Epoch: 23/150
Train Loss: 0.7155 | Train Acc: 76.12% | Precision: 68.83% Recall: 76.12% F1: 70.48%
Val   Loss: 0.7000 | Val Acc: 76.33%   | Precision: 72.86% Recall: 76.33% F1: 69.84%

Epoch: 24/150
Train Loss: 0.6841 | Train Acc: 77.76% | Precision: 71.12% Recall: 77.76% F1: 72.22%
Val   Loss: 0.7166 | Val Acc: 76.89%   | Precision: 73.10% Recall: 76.89% F1: 70.49%

Epoch: 25/150
Train Loss: 0.7227 | Train Acc: 76.11% | Precision: 68.39% Recall: 76.11% F1: 70.30%
Val   Loss: 0.6591 | Val Acc: 79.21%   | Precision: 75.48% Recall: 79.21% F1: 73.37%

Epoch: 26/150
Train Loss: 0.6646 | Train Acc: 78.72% | Precision: 77.75% Recall: 78.72% F1: 73.69%
Val   Loss: 0.6200 | Val Acc: 80.80%   | Precision: 75.30% Recall: 80.80% F1: 76.41%

Epoch: 27/150
Train Loss: 0.6341 | Train Acc: 79.67% | Precision: 78.49% Recall: 79.67% F1: 75.85%
Val   Loss: 0.6321 | Val Acc: 80.65%   | Precision: 80.17% Recall: 80.65% F1: 79.03%

Epoch: 28/150
Train Loss: 0.5591 | Train Acc: 83.27% | Precision: 82.59% Recall: 83.27% F1: 81.39%
Val   Loss: 0.5125 | Val Acc: 85.18%   | Precision: 85.19% Recall: 85.18% F1: 84.01%

Epoch: 29/150
Train Loss: 0.4875 | Train Acc: 85.73% | Precision: 85.49% Recall: 85.73% F1: 84.65%
Val   Loss: 0.4995 | Val Acc: 84.48%   | Precision: 84.51% Recall: 84.48% F1: 82.72%

Epoch: 30/150
Train Loss: 0.4602 | Train Acc: 86.37% | Precision: 86.19% Recall: 86.37% F1: 85.42%
Val   Loss: 0.5007 | Val Acc: 83.92%   | Precision: 84.71% Recall: 83.92% F1: 83.83%

Epoch: 31/150
Train Loss: 0.4813 | Train Acc: 85.76% | Precision: 85.61% Recall: 85.76% F1: 84.62%
Val   Loss: 0.4704 | Val Acc: 85.50%   | Precision: 85.81% Recall: 85.50% F1: 83.99%

Epoch: 32/150
Train Loss: 0.5456 | Train Acc: 83.54% | Precision: 83.14% Recall: 83.54% F1: 82.03%
Val   Loss: 0.6443 | Val Acc: 80.39%   | Precision: 78.60% Recall: 80.39% F1: 76.90%

Epoch: 33/150
Train Loss: 0.4973 | Train Acc: 84.75% | Precision: 84.46% Recall: 84.75% F1: 83.32%
Val   Loss: 0.4359 | Val Acc: 86.91%   | Precision: 86.85% Recall: 86.91% F1: 85.72%

Epoch: 34/150
Train Loss: 0.4158 | Train Acc: 87.49% | Precision: 87.32% Recall: 87.49% F1: 86.77%
Val   Loss: 0.4031 | Val Acc: 87.71%   | Precision: 87.89% Recall: 87.71% F1: 86.45%

Epoch: 35/150
Train Loss: 0.3933 | Train Acc: 88.11% | Precision: 87.96% Recall: 88.11% F1: 87.44%
Val   Loss: 0.3878 | Val Acc: 88.06%   | Precision: 88.03% Recall: 88.06% F1: 87.00%

Epoch: 36/150
Train Loss: 0.3871 | Train Acc: 88.51% | Precision: 88.42% Recall: 88.51% F1: 87.91%
Val   Loss: 0.3825 | Val Acc: 88.68%   | Precision: 88.58% Recall: 88.68% F1: 88.28%

Epoch: 37/150
Train Loss: 0.3590 | Train Acc: 89.26% | Precision: 89.20% Recall: 89.26% F1: 88.70%
Val   Loss: 0.3874 | Val Acc: 88.31%   | Precision: 88.10% Recall: 88.31% F1: 87.89%

Epoch: 38/150
Train Loss: 0.6453 | Train Acc: 80.56% | Precision: 80.01% Recall: 80.56% F1: 78.46%
Val   Loss: 0.7178 | Val Acc: 76.87%   | Precision: 71.85% Recall: 76.87% F1: 71.77%

Epoch: 39/150
Train Loss: 0.8975 | Train Acc: 71.82% | Precision: 68.22% Recall: 71.82% F1: 65.91%
Val   Loss: 1.0234 | Val Acc: 65.14%   | Precision: 49.09% Recall: 65.14% F1: 54.46%

Epoch: 40/150
Train Loss: 0.9261 | Train Acc: 69.05% | Precision: 59.09% Recall: 69.05% F1: 61.70%
Val   Loss: 0.9224 | Val Acc: 65.89%   | Precision: 63.85% Recall: 65.89% F1: 56.72%

Epoch: 41/150
Train Loss: 0.8451 | Train Acc: 71.35% | Precision: 66.21% Recall: 71.35% F1: 64.86%
Val   Loss: 0.8701 | Val Acc: 71.02%   | Precision: 66.87% Recall: 71.02% F1: 64.60%

Epoch: 42/150
Train Loss: 0.7844 | Train Acc: 74.49% | Precision: 67.61% Recall: 74.49% F1: 69.18%
Val   Loss: 0.7355 | Val Acc: 76.60%   | Precision: 71.10% Recall: 76.60% F1: 71.10%

Epoch: 43/150
Train Loss: 0.7823 | Train Acc: 74.33% | Precision: 67.31% Recall: 74.33% F1: 69.22%
Val   Loss: 0.8686 | Val Acc: 67.95%   | Precision: 62.69% Recall: 67.95% F1: 60.17%

Epoch: 44/150
Train Loss: 0.7754 | Train Acc: 73.92% | Precision: 67.02% Recall: 73.92% F1: 68.82%
Val   Loss: 0.6938 | Val Acc: 75.55%   | Precision: 69.63% Recall: 75.55% F1: 70.12%

Epoch: 45/150
Train Loss: 0.7357 | Train Acc: 75.58% | Precision: 69.08% Recall: 75.58% F1: 70.44%
Val   Loss: 0.7961 | Val Acc: 71.51%   | Precision: 66.56% Recall: 71.51% F1: 66.96%

Epoch: 46/150
Train Loss: 0.7189 | Train Acc: 76.25% | Precision: 74.53% Recall: 76.25% F1: 71.30%
Val   Loss: 0.7111 | Val Acc: 77.07%   | Precision: 71.49% Recall: 77.07% F1: 72.30%

Epoch: 47/150
Train Loss: 0.8507 | Train Acc: 71.96% | Precision: 65.98% Recall: 71.96% F1: 66.27%
Val   Loss: 0.6993 | Val Acc: 77.27%   | Precision: 73.01% Recall: 77.27% F1: 71.60%

Epoch: 48/150
Train Loss: 0.7051 | Train Acc: 76.96% | Precision: 75.71% Recall: 76.96% F1: 71.98%
Val   Loss: 0.6336 | Val Acc: 78.73%   | Precision: 75.98% Recall: 78.73% F1: 73.79%

Epoch: 49/150
Train Loss: 0.8822 | Train Acc: 69.50% | Precision: 66.54% Recall: 69.50% F1: 63.48%
Val   Loss: 0.8340 | Val Acc: 70.57%   | Precision: 62.81% Recall: 70.57% F1: 62.28%

Epoch: 50/150
Train Loss: 0.7769 | Train Acc: 73.46% | Precision: 68.70% Recall: 73.46% F1: 68.01%
Val   Loss: 0.6726 | Val Acc: 77.64%   | Precision: 78.65% Recall: 77.64% F1: 73.04%

Epoch: 51/150
Train Loss: 0.7614 | Train Acc: 74.34% | Precision: 71.04% Recall: 74.34% F1: 69.22%
Val   Loss: 0.7513 | Val Acc: 74.94%   | Precision: 69.00% Recall: 74.94% F1: 70.05%

Epoch: 52/150
Train Loss: 0.8661 | Train Acc: 70.10% | Precision: 65.76% Recall: 70.10% F1: 63.84%
Val   Loss: 0.7919 | Val Acc: 70.43%   | Precision: 64.22% Recall: 70.43% F1: 63.82%

Epoch: 53/150
Train Loss: 0.8590 | Train Acc: 69.72% | Precision: 63.02% Recall: 69.72% F1: 63.62%
Val   Loss: 0.8869 | Val Acc: 68.77%   | Precision: 58.38% Recall: 68.77% F1: 61.41%

Epoch: 54/150
Train Loss: 0.7589 | Train Acc: 74.03% | Precision: 69.01% Recall: 74.03% F1: 68.78%
Val   Loss: 0.6521 | Val Acc: 78.61%   | Precision: 77.38% Recall: 78.61% F1: 73.98%

Epoch: 55/150
Train Loss: 0.6740 | Train Acc: 77.35% | Precision: 74.53% Recall: 77.35% F1: 73.02%
Val   Loss: 0.6459 | Val Acc: 78.78%   | Precision: 75.37% Recall: 78.78% F1: 75.47%

Epoch: 56/150
Train Loss: 0.6716 | Train Acc: 77.05% | Precision: 74.55% Recall: 77.05% F1: 72.79%
Val   Loss: 0.6333 | Val Acc: 78.93%   | Precision: 79.01% Recall: 78.93% F1: 73.76%

Epoch: 57/150
Train Loss: 0.6172 | Train Acc: 79.36% | Precision: 78.52% Recall: 79.36% F1: 75.59%
Val   Loss: 0.6085 | Val Acc: 80.70%   | Precision: 80.20% Recall: 80.70% F1: 77.22%

Epoch: 58/150
Train Loss: 0.5666 | Train Acc: 81.76% | Precision: 81.07% Recall: 81.76% F1: 79.33%
Val   Loss: 0.5691 | Val Acc: 81.69%   | Precision: 80.74% Recall: 81.69% F1: 79.40%

Epoch: 59/150
Train Loss: 0.5572 | Train Acc: 81.95% | Precision: 81.20% Recall: 81.95% F1: 79.81%
Val   Loss: 0.4740 | Val Acc: 85.55%   | Precision: 85.39% Recall: 85.55% F1: 84.18%

Epoch: 60/150
Train Loss: 0.5303 | Train Acc: 83.06% | Precision: 82.35% Recall: 83.06% F1: 81.29%
Val   Loss: 0.5447 | Val Acc: 82.13%   | Precision: 82.48% Recall: 82.13% F1: 79.53%

Epoch: 61/150
Train Loss: 0.5922 | Train Acc: 80.68% | Precision: 79.73% Recall: 80.68% F1: 78.48%
Val   Loss: 0.5129 | Val Acc: 83.55%   | Precision: 82.94% Recall: 83.55% F1: 82.11%

Epoch: 62/150
Train Loss: 0.6391 | Train Acc: 79.25% | Precision: 77.91% Recall: 79.25% F1: 76.37%
Val   Loss: 0.5926 | Val Acc: 80.62%   | Precision: 80.25% Recall: 80.62% F1: 77.75%

Epoch: 63/150
Train Loss: 0.5526 | Train Acc: 82.51% | Precision: 81.90% Recall: 82.51% F1: 80.37%
Val   Loss: 0.4949 | Val Acc: 84.82%   | Precision: 84.47% Recall: 84.82% F1: 83.20%

Epoch: 64/150
Train Loss: 0.6249 | Train Acc: 79.92% | Precision: 79.04% Recall: 79.92% F1: 77.26%
Val   Loss: 0.4948 | Val Acc: 83.93%   | Precision: 83.69% Recall: 83.93% F1: 81.55%

Epoch: 65/150
Train Loss: 0.4626 | Train Acc: 85.67% | Precision: 85.38% Recall: 85.67% F1: 84.52%
Val   Loss: 0.4527 | Val Acc: 85.87%   | Precision: 85.51% Recall: 85.87% F1: 84.62%

Epoch: 66/150
Train Loss: 0.4470 | Train Acc: 86.03% | Precision: 85.78% Recall: 86.03% F1: 85.04%
Val   Loss: 0.4697 | Val Acc: 85.08%   | Precision: 85.40% Recall: 85.08% F1: 83.30%

Epoch: 67/150
Train Loss: 0.4098 | Train Acc: 87.38% | Precision: 87.25% Recall: 87.38% F1: 86.60%
Val   Loss: 0.3813 | Val Acc: 88.37%   | Precision: 88.32% Recall: 88.37% F1: 87.52%

Epoch: 68/150
Train Loss: 0.4083 | Train Acc: 87.19% | Precision: 87.07% Recall: 87.19% F1: 86.42%
Val   Loss: 0.3968 | Val Acc: 87.57%   | Precision: 87.33% Recall: 87.57% F1: 86.67%

Epoch: 69/150
Train Loss: 0.4007 | Train Acc: 87.50% | Precision: 87.41% Recall: 87.50% F1: 86.74%
Val   Loss: 0.4072 | Val Acc: 86.61%   | Precision: 86.60% Recall: 86.61% F1: 85.96%

Epoch: 70/150
Train Loss: 0.4077 | Train Acc: 87.15% | Precision: 86.93% Recall: 87.15% F1: 86.41%
Val   Loss: 0.4451 | Val Acc: 85.43%   | Precision: 85.17% Recall: 85.43% F1: 84.09%

Epoch: 71/150
Train Loss: 0.4232 | Train Acc: 86.67% | Precision: 86.42% Recall: 86.67% F1: 85.84%
Val   Loss: 0.4548 | Val Acc: 85.48%   | Precision: 85.54% Recall: 85.48% F1: 83.61%

Epoch: 72/150
Train Loss: 0.4584 | Train Acc: 85.45% | Precision: 85.09% Recall: 85.45% F1: 84.45%
Val   Loss: 0.4097 | Val Acc: 86.93%   | Precision: 86.75% Recall: 86.93% F1: 85.69%

Epoch: 73/150
Train Loss: 0.6597 | Train Acc: 78.84% | Precision: 79.13% Recall: 78.84% F1: 76.42%
Val   Loss: 0.7575 | Val Acc: 75.95%   | Precision: 65.38% Recall: 75.95% F1: 69.92%

Epoch: 74/150
Train Loss: 0.6688 | Train Acc: 77.94% | Precision: 78.28% Recall: 77.94% F1: 73.25%
Val   Loss: 0.5737 | Val Acc: 81.15%   | Precision: 82.18% Recall: 81.15% F1: 77.62%

Epoch: 75/150
Train Loss: 0.6192 | Train Acc: 80.14% | Precision: 80.06% Recall: 80.14% F1: 76.89%
Val   Loss: 0.5604 | Val Acc: 83.33%   | Precision: 83.74% Recall: 83.33% F1: 81.01%

Epoch: 76/150
Train Loss: 0.5972 | Train Acc: 80.32% | Precision: 79.88% Recall: 80.32% F1: 77.83%
Val   Loss: 0.5892 | Val Acc: 79.74%   | Precision: 79.44% Recall: 79.74% F1: 77.17%

Epoch: 77/150
Train Loss: 0.5518 | Train Acc: 81.52% | Precision: 81.15% Recall: 81.52% F1: 79.53%
Val   Loss: 0.9463 | Val Acc: 67.99%   | Precision: 67.82% Recall: 67.99% F1: 59.06%

Epoch: 78/150
Train Loss: 0.6476 | Train Acc: 77.62% | Precision: 77.24% Recall: 77.62% F1: 73.85%
Val   Loss: 0.6048 | Val Acc: 79.49%   | Precision: 81.59% Recall: 79.49% F1: 74.83%

Epoch: 79/150
Train Loss: 0.5390 | Train Acc: 82.72% | Precision: 82.61% Recall: 82.72% F1: 80.92%
Val   Loss: 0.4897 | Val Acc: 85.07%   | Precision: 84.84% Recall: 85.07% F1: 83.61%

Epoch: 80/150
Train Loss: 0.4747 | Train Acc: 85.09% | Precision: 84.75% Recall: 85.09% F1: 83.96%
Val   Loss: 0.4867 | Val Acc: 83.91%   | Precision: 83.55% Recall: 83.91% F1: 82.73%

Epoch: 81/150
Train Loss: 0.4405 | Train Acc: 85.92% | Precision: 85.58% Recall: 85.92% F1: 84.95%
Val   Loss: 0.4379 | Val Acc: 85.92%   | Precision: 85.59% Recall: 85.92% F1: 84.76%

Epoch: 82/150
Train Loss: 0.4101 | Train Acc: 87.03% | Precision: 86.80% Recall: 87.03% F1: 86.22%
Val   Loss: 0.4195 | Val Acc: 86.51%   | Precision: 86.61% Recall: 86.51% F1: 85.67%

Epoch: 83/150
Train Loss: 0.5145 | Train Acc: 83.34% | Precision: 83.09% Recall: 83.34% F1: 81.73%
Val   Loss: 0.4379 | Val Acc: 85.85%   | Precision: 85.62% Recall: 85.85% F1: 85.08%

Epoch: 84/150
Train Loss: 0.5089 | Train Acc: 83.91% | Precision: 83.52% Recall: 83.91% F1: 82.52%
Val   Loss: 0.4499 | Val Acc: 86.26%   | Precision: 85.99% Recall: 86.26% F1: 85.27%

Epoch: 85/150
Train Loss: 0.3995 | Train Acc: 87.93% | Precision: 87.85% Recall: 87.93% F1: 87.23%
Val   Loss: 0.3871 | Val Acc: 88.21%   | Precision: 88.19% Recall: 88.21% F1: 87.37%

Epoch: 86/150
Train Loss: 0.3651 | Train Acc: 88.94% | Precision: 88.91% Recall: 88.94% F1: 88.38%
Val   Loss: 0.3645 | Val Acc: 89.20%   | Precision: 89.10% Recall: 89.20% F1: 88.49%

Epoch: 87/150
Train Loss: 0.6512 | Train Acc: 78.44% | Precision: 78.65% Recall: 78.44% F1: 75.98%
Val   Loss: 0.7338 | Val Acc: 73.52%   | Precision: 68.35% Recall: 73.52% F1: 68.47%

Epoch: 88/150
Train Loss: 0.6356 | Train Acc: 78.54% | Precision: 77.82% Recall: 78.54% F1: 75.03%
Val   Loss: 0.6023 | Val Acc: 80.34%   | Precision: 79.33% Recall: 80.34% F1: 77.50%

Epoch: 89/150
Train Loss: 0.4983 | Train Acc: 84.93% | Precision: 84.59% Recall: 84.93% F1: 83.65%
Val   Loss: 0.4386 | Val Acc: 87.39%   | Precision: 87.41% Recall: 87.39% F1: 86.37%

Epoch: 90/150
Train Loss: 0.5075 | Train Acc: 84.21% | Precision: 83.90% Recall: 84.21% F1: 82.89%
Val   Loss: 0.4671 | Val Acc: 86.17%   | Precision: 85.89% Recall: 86.17% F1: 84.72%

Epoch: 91/150
Train Loss: 0.5490 | Train Acc: 82.74% | Precision: 82.00% Recall: 82.74% F1: 80.88%
Val   Loss: 0.4909 | Val Acc: 84.86%   | Precision: 85.56% Recall: 84.86% F1: 82.67%

Epoch: 92/150
Train Loss: 0.4689 | Train Acc: 85.72% | Precision: 85.50% Recall: 85.72% F1: 84.59%
Val   Loss: 0.4250 | Val Acc: 87.37%   | Precision: 87.56% Recall: 87.37% F1: 86.70%

Epoch: 93/150
Train Loss: 0.4239 | Train Acc: 87.06% | Precision: 86.98% Recall: 87.06% F1: 86.28%
Val   Loss: 0.4019 | Val Acc: 87.85%   | Precision: 87.96% Recall: 87.85% F1: 87.03%

Epoch: 94/150
Train Loss: 0.4037 | Train Acc: 87.72% | Precision: 87.71% Recall: 87.72% F1: 87.01%
Val   Loss: 1.1224 | Val Acc: 62.69%   | Precision: 48.39% Recall: 62.69% F1: 53.08%

Epoch: 95/150
Train Loss: 0.6507 | Train Acc: 78.01% | Precision: 77.16% Recall: 78.01% F1: 74.44%
Val   Loss: 0.5554 | Val Acc: 80.82%   | Precision: 80.74% Recall: 80.82% F1: 77.20%

Epoch: 96/150
Train Loss: 0.4701 | Train Acc: 85.62% | Precision: 85.42% Recall: 85.62% F1: 84.52%
Val   Loss: 0.4372 | Val Acc: 86.69%   | Precision: 86.94% Recall: 86.69% F1: 85.24%

Epoch: 97/150
Train Loss: 0.7014 | Train Acc: 77.71% | Precision: 77.75% Recall: 77.71% F1: 75.01%
Val   Loss: 0.7998 | Val Acc: 73.67%   | Precision: 63.03% Recall: 73.67% F1: 66.74%

Epoch: 98/150
Train Loss: 0.7162 | Train Acc: 75.37% | Precision: 73.33% Recall: 75.37% F1: 69.70%
Val   Loss: 0.6158 | Val Acc: 80.27%   | Precision: 81.31% Recall: 80.27% F1: 76.30%

Epoch: 99/150
Train Loss: 1.0409 | Train Acc: 66.28% | Precision: 64.26% Recall: 66.28% F1: 57.68%
Val   Loss: 0.9072 | Val Acc: 67.25%   | Precision: 62.95% Recall: 67.25% F1: 59.39%

Epoch: 100/150
Train Loss: 0.9039 | Train Acc: 69.17% | Precision: 61.77% Recall: 69.17% F1: 62.19%
Val   Loss: 0.8046 | Val Acc: 73.17%   | Precision: 68.89% Recall: 73.17% F1: 67.39%

Epoch: 101/150
Train Loss: 0.9140 | Train Acc: 68.27% | Precision: 60.13% Recall: 68.27% F1: 61.73%
Val   Loss: 0.9475 | Val Acc: 69.73%   | Precision: 66.54% Recall: 69.73% F1: 65.19%

Epoch: 102/150
Train Loss: 0.7657 | Train Acc: 73.36% | Precision: 71.83% Recall: 73.36% F1: 67.19%
Val   Loss: 0.6810 | Val Acc: 76.08%   | Precision: 72.77% Recall: 76.08% F1: 70.33%

Epoch: 103/150
Train Loss: 0.6441 | Train Acc: 78.43% | Precision: 77.35% Recall: 78.43% F1: 74.56%
Val   Loss: 0.6054 | Val Acc: 80.93%   | Precision: 80.29% Recall: 80.93% F1: 78.41%

Epoch: 104/150
Train Loss: 0.5857 | Train Acc: 81.07% | Precision: 80.40% Recall: 81.07% F1: 78.76%
Val   Loss: 0.5479 | Val Acc: 83.00%   | Precision: 83.10% Recall: 83.00% F1: 81.37%

Epoch: 105/150
Train Loss: 0.7223 | Train Acc: 75.87% | Precision: 75.62% Recall: 75.87% F1: 71.52%
Val   Loss: 0.6925 | Val Acc: 78.07%   | Precision: 72.90% Recall: 78.07% F1: 72.98%

Epoch: 106/150
Train Loss: 0.6680 | Train Acc: 77.83% | Precision: 75.83% Recall: 77.83% F1: 73.00%
Val   Loss: 0.6111 | Val Acc: 79.37%   | Precision: 79.47% Recall: 79.37% F1: 74.64%

Epoch: 107/150
Train Loss: 0.5862 | Train Acc: 80.83% | Precision: 80.07% Recall: 80.83% F1: 78.21%
Val   Loss: 0.5596 | Val Acc: 81.10%   | Precision: 81.19% Recall: 81.10% F1: 77.40%

Epoch: 108/150
Train Loss: 0.5163 | Train Acc: 84.01% | Precision: 83.50% Recall: 84.01% F1: 82.77%
Val   Loss: 0.4971 | Val Acc: 84.87%   | Precision: 84.48% Recall: 84.87% F1: 83.92%

Epoch: 109/150

wandb: Agent Starting Run: efcaazae with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.0003376539857102409
wandb: 	optimizer: adam
wandb: 	rnn_type: rnn
wandb: 	seq_len: 130
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.1691 | Train Acc: 63.94% | Precision: 44.16% Recall: 63.94% F1: 50.65%
Val   Loss: 1.1230 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.0154 | Train Acc: 66.55% | Precision: 56.92% Recall: 66.55% F1: 56.52%
Val   Loss: 0.8228 | Val Acc: 70.55%   | Precision: 65.98% Recall: 70.55% F1: 63.86%

Epoch: 3/150
Train Loss: 0.8861 | Train Acc: 69.41% | Precision: 61.13% Recall: 69.41% F1: 62.23%
Val   Loss: 1.1217 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 0.9674 | Train Acc: 66.40% | Precision: 59.04% Recall: 66.40% F1: 57.11%
Val   Loss: 0.8580 | Val Acc: 70.88%   | Precision: 56.45% Recall: 70.88% F1: 61.62%

Epoch: 5/150
Train Loss: 0.7929 | Train Acc: 72.24% | Precision: 65.67% Recall: 72.24% F1: 65.79%
Val   Loss: 0.8449 | Val Acc: 71.61%   | Precision: 60.63% Recall: 71.61% F1: 64.57%

Epoch: 6/150
Train Loss: 0.7817 | Train Acc: 72.94% | Precision: 66.48% Recall: 72.94% F1: 66.74%
Val   Loss: 0.7475 | Val Acc: 72.99%   | Precision: 68.34% Recall: 72.99% F1: 66.56%

Epoch: 7/150
Train Loss: 0.7201 | Train Acc: 75.62% | Precision: 69.21% Recall: 75.62% F1: 70.33%
Val   Loss: 0.6662 | Val Acc: 78.80%   | Precision: 74.89% Recall: 78.80% F1: 73.70%

Epoch: 8/150
Train Loss: 0.8694 | Train Acc: 71.79% | Precision: 65.22% Recall: 71.79% F1: 66.82%
Val   Loss: 1.1347 | Val Acc: 64.50%   | Precision: 43.31% Recall: 64.50% F1: 50.66%

Epoch: 9/150
Train Loss: 1.0491 | Train Acc: 65.61% | Precision: 54.20% Recall: 65.61% F1: 54.93%
Val   Loss: 0.9462 | Val Acc: 66.33%   | Precision: 54.26% Recall: 66.33% F1: 57.09%

Epoch: 10/150
Train Loss: 0.8426 | Train Acc: 70.76% | Precision: 60.16% Recall: 70.76% F1: 64.24%
Val   Loss: 0.7779 | Val Acc: 73.96%   | Precision: 63.39% Recall: 73.96% F1: 67.70%

Epoch: 11/150
Train Loss: 0.7478 | Train Acc: 74.58% | Precision: 68.37% Recall: 74.58% F1: 68.40%
Val   Loss: 0.7615 | Val Acc: 75.95%   | Precision: 73.29% Recall: 75.95% F1: 69.97%

Epoch: 12/150
Train Loss: 0.6735 | Train Acc: 77.14% | Precision: 70.75% Recall: 77.14% F1: 72.16%
Val   Loss: 0.6795 | Val Acc: 76.89%   | Precision: 70.29% Recall: 76.89% F1: 71.58%

Epoch: 13/150
Train Loss: 0.8344 | Train Acc: 72.40% | Precision: 65.73% Recall: 72.40% F1: 66.90%
Val   Loss: 0.8349 | Val Acc: 74.32%   | Precision: 63.93% Recall: 74.32% F1: 67.20%

Epoch: 14/150
Train Loss: 0.8243 | Train Acc: 73.38% | Precision: 67.02% Recall: 73.38% F1: 67.60%
Val   Loss: 0.7386 | Val Acc: 74.69%   | Precision: 65.48% Recall: 74.69% F1: 66.46%

Epoch: 15/150
Train Loss: 0.7701 | Train Acc: 74.29% | Precision: 68.92% Recall: 74.29% F1: 69.01%
Val   Loss: 1.2349 | Val Acc: 62.59%   | Precision: 48.72% Recall: 62.59% F1: 53.61%

Epoch: 16/150
Train Loss: 0.8472 | Train Acc: 72.31% | Precision: 66.33% Recall: 72.31% F1: 65.72%
Val   Loss: 0.7535 | Val Acc: 76.04%   | Precision: 70.52% Recall: 76.04% F1: 70.52%

Epoch: 17/150
Train Loss: 0.7292 | Train Acc: 75.87% | Precision: 76.03% Recall: 75.87% F1: 70.13%
Val   Loss: 0.6896 | Val Acc: 76.67%   | Precision: 71.99% Recall: 76.67% F1: 70.99%

Epoch: 18/150
Train Loss: 0.6834 | Train Acc: 77.95% | Precision: 75.79% Recall: 77.95% F1: 72.71%
Val   Loss: 0.6560 | Val Acc: 78.61%   | Precision: 74.40% Recall: 78.61% F1: 73.34%

Epoch: 19/150
Train Loss: 0.7058 | Train Acc: 76.78% | Precision: 74.12% Recall: 76.78% F1: 71.63%
Val   Loss: 0.8266 | Val Acc: 71.49%   | Precision: 63.41% Recall: 71.49% F1: 64.81%

Epoch: 20/150
Train Loss: 0.7153 | Train Acc: 76.12% | Precision: 73.90% Recall: 76.12% F1: 70.83%
Val   Loss: 0.6629 | Val Acc: 78.69%   | Precision: 78.44% Recall: 78.69% F1: 74.01%

Epoch: 21/150
Train Loss: 0.6385 | Train Acc: 79.21% | Precision: 78.13% Recall: 79.21% F1: 74.67%
Val   Loss: 0.6144 | Val Acc: 80.44%   | Precision: 79.43% Recall: 80.44% F1: 77.40%

Epoch: 22/150
Train Loss: 0.6177 | Train Acc: 79.94% | Precision: 78.47% Recall: 79.94% F1: 76.74%
Val   Loss: 0.6072 | Val Acc: 79.94%   | Precision: 79.70% Recall: 79.94% F1: 75.83%

Epoch: 23/150
Train Loss: 0.5987 | Train Acc: 80.85% | Precision: 79.55% Recall: 80.85% F1: 78.70%
Val   Loss: 0.6503 | Val Acc: 77.94%   | Precision: 78.29% Recall: 77.94% F1: 77.55%

Epoch: 24/150
Train Loss: 0.6086 | Train Acc: 80.45% | Precision: 79.15% Recall: 80.45% F1: 78.14%
Val   Loss: 0.6062 | Val Acc: 80.75%   | Precision: 79.66% Recall: 80.75% F1: 79.56%

Epoch: 25/150
Train Loss: 0.9770 | Train Acc: 69.02% | Precision: 66.20% Recall: 69.02% F1: 64.28%
Val   Loss: 0.8727 | Val Acc: 72.07%   | Precision: 55.08% Recall: 72.07% F1: 62.43%

Epoch: 26/150
Train Loss: 0.7767 | Train Acc: 74.00% | Precision: 68.35% Recall: 74.00% F1: 67.11%
Val   Loss: 1.4405 | Val Acc: 45.76%   | Precision: 55.73% Recall: 45.76% F1: 46.63%

Epoch: 27/150
Train Loss: 0.8627 | Train Acc: 71.18% | Precision: 64.79% Recall: 71.18% F1: 64.48%
Val   Loss: 0.7201 | Val Acc: 74.55%   | Precision: 63.95% Recall: 74.55% F1: 67.94%

Epoch: 28/150
Train Loss: 0.6943 | Train Acc: 76.85% | Precision: 73.13% Recall: 76.85% F1: 71.22%
Val   Loss: 0.6464 | Val Acc: 78.75%   | Precision: 68.54% Recall: 78.75% F1: 73.05%

Epoch: 29/150
Train Loss: 0.6580 | Train Acc: 78.19% | Precision: 76.64% Recall: 78.19% F1: 72.98%
Val   Loss: 0.6343 | Val Acc: 78.21%   | Precision: 70.31% Recall: 78.21% F1: 72.80%

Epoch: 30/150
Train Loss: 0.9364 | Train Acc: 71.73% | Precision: 66.80% Recall: 71.73% F1: 67.42%
Val   Loss: 0.9502 | Val Acc: 71.76%   | Precision: 61.01% Recall: 71.76% F1: 65.61%

Epoch: 31/150
Train Loss: 0.8472 | Train Acc: 70.99% | Precision: 60.74% Recall: 70.99% F1: 64.79%
Val   Loss: 0.8003 | Val Acc: 73.00%   | Precision: 62.20% Recall: 73.00% F1: 66.73%

Epoch: 32/150
Train Loss: 0.7836 | Train Acc: 73.12% | Precision: 65.72% Recall: 73.12% F1: 66.93%
Val   Loss: 0.7589 | Val Acc: 71.33%   | Precision: 60.73% Recall: 71.33% F1: 63.81%

Epoch: 33/150
Train Loss: 0.7545 | Train Acc: 73.60% | Precision: 71.81% Recall: 73.60% F1: 67.60%
Val   Loss: 0.7662 | Val Acc: 71.96%   | Precision: 57.70% Recall: 71.96% F1: 63.43%

Epoch: 34/150
Train Loss: 0.7359 | Train Acc: 74.47% | Precision: 67.97% Recall: 74.47% F1: 68.46%
Val   Loss: 0.6994 | Val Acc: 73.40%   | Precision: 59.29% Recall: 73.40% F1: 64.14%

Epoch: 35/150
Train Loss: 0.7001 | Train Acc: 75.78% | Precision: 72.86% Recall: 75.78% F1: 70.56%
Val   Loss: 0.6708 | Val Acc: 75.92%   | Precision: 65.16% Recall: 75.92% F1: 69.76%

Epoch: 36/150
Train Loss: 0.6686 | Train Acc: 76.96% | Precision: 73.19% Recall: 76.96% F1: 71.80%
Val   Loss: 0.6587 | Val Acc: 77.94%   | Precision: 67.62% Recall: 77.94% F1: 72.25%

Epoch: 37/150
Train Loss: 0.6631 | Train Acc: 77.53% | Precision: 73.39% Recall: 77.53% F1: 72.47%
Val   Loss: 0.6427 | Val Acc: 78.96%   | Precision: 69.09% Recall: 78.96% F1: 73.01%

Epoch: 38/150
Train Loss: 0.6320 | Train Acc: 78.52% | Precision: 75.36% Recall: 78.52% F1: 73.72%
Val   Loss: 0.6590 | Val Acc: 78.55%   | Precision: 68.75% Recall: 78.55% F1: 72.66%

Epoch: 39/150
Train Loss: 0.7188 | Train Acc: 75.26% | Precision: 70.19% Recall: 75.26% F1: 70.57%
Val   Loss: 0.6755 | Val Acc: 76.12%   | Precision: 65.97% Recall: 76.12% F1: 69.19%

Epoch: 40/150
Train Loss: 0.7327 | Train Acc: 75.29% | Precision: 68.12% Recall: 75.29% F1: 69.87%
Val   Loss: 0.7578 | Val Acc: 72.53%   | Precision: 64.76% Recall: 72.53% F1: 66.92%

Epoch: 41/150
Train Loss: 0.6512 | Train Acc: 77.84% | Precision: 74.19% Recall: 77.84% F1: 72.73%
Val   Loss: 0.6280 | Val Acc: 76.58%   | Precision: 73.21% Recall: 76.58% F1: 74.29%

Epoch: 42/150
Train Loss: 0.6150 | Train Acc: 79.09% | Precision: 76.39% Recall: 79.09% F1: 74.53%
Val   Loss: 0.6059 | Val Acc: 80.12%   | Precision: 75.24% Recall: 80.12% F1: 75.25%

Epoch: 43/150
Train Loss: 0.8530 | Train Acc: 71.74% | Precision: 67.42% Recall: 71.74% F1: 66.57%
Val   Loss: 0.6958 | Val Acc: 76.91%   | Precision: 70.20% Recall: 76.91% F1: 72.77%

Epoch: 44/150
Train Loss: 0.7467 | Train Acc: 75.83% | Precision: 69.14% Recall: 75.83% F1: 70.18%
Val   Loss: 0.7286 | Val Acc: 74.84%   | Precision: 66.06% Recall: 74.84% F1: 69.04%

Epoch: 45/150
Train Loss: 0.7496 | Train Acc: 74.78% | Precision: 66.78% Recall: 74.78% F1: 68.85%
Val   Loss: 0.7049 | Val Acc: 75.66%   | Precision: 64.56% Recall: 75.66% F1: 69.20%

Epoch: 46/150
Train Loss: 0.6996 | Train Acc: 76.83% | Precision: 71.10% Recall: 76.83% F1: 70.98%
Val   Loss: 0.7028 | Val Acc: 79.04%   | Precision: 74.25% Recall: 79.04% F1: 73.62%

Epoch: 47/150
Train Loss: 0.6581 | Train Acc: 78.23% | Precision: 76.27% Recall: 78.23% F1: 72.89%
Val   Loss: 0.6720 | Val Acc: 78.14%   | Precision: 68.59% Recall: 78.14% F1: 71.73%

Epoch: 48/150
Train Loss: 0.6452 | Train Acc: 78.85% | Precision: 75.74% Recall: 78.85% F1: 73.47%
Val   Loss: 0.6229 | Val Acc: 78.56%   | Precision: 74.64% Recall: 78.56% F1: 73.29%

Epoch: 49/150
Train Loss: 0.7087 | Train Acc: 76.36% | Precision: 73.34% Recall: 76.36% F1: 71.23%
Val   Loss: 0.7482 | Val Acc: 73.99%   | Precision: 65.48% Recall: 73.99% F1: 68.15%

Epoch: 50/150
Train Loss: 0.6985 | Train Acc: 77.05% | Precision: 70.00% Recall: 77.05% F1: 71.60%
Val   Loss: 0.6777 | Val Acc: 78.61%   | Precision: 74.80% Recall: 78.61% F1: 72.45%

Epoch: 51/150
Train Loss: 0.7667 | Train Acc: 75.70% | Precision: 71.77% Recall: 75.70% F1: 70.50%
Val   Loss: 1.1200 | Val Acc: 64.40%   | Precision: 47.31% Recall: 64.40% F1: 54.00%

Epoch: 52/150
Train Loss: 0.7692 | Train Acc: 74.35% | Precision: 68.29% Recall: 74.35% F1: 68.21%
Val   Loss: 0.6969 | Val Acc: 77.65%   | Precision: 66.93% Recall: 77.65% F1: 71.48%

Epoch: 53/150
Train Loss: 0.6818 | Train Acc: 77.03% | Precision: 74.53% Recall: 77.03% F1: 71.46%
Val   Loss: 0.6912 | Val Acc: 76.60%   | Precision: 66.37% Recall: 76.60% F1: 70.15%

Epoch: 54/150
Train Loss: 0.6907 | Train Acc: 76.91% | Precision: 73.09% Recall: 76.91% F1: 71.29%
Val   Loss: 0.6549 | Val Acc: 77.34%   | Precision: 73.55% Recall: 77.34% F1: 71.57%

Epoch: 55/150
Train Loss: 0.6500 | Train Acc: 78.30% | Precision: 76.65% Recall: 78.30% F1: 73.30%
Val   Loss: 0.6482 | Val Acc: 78.08%   | Precision: 73.69% Recall: 78.08% F1: 72.94%

Epoch: 56/150
Train Loss: 0.7261 | Train Acc: 76.43% | Precision: 76.54% Recall: 76.43% F1: 71.38%
Val   Loss: 0.6778 | Val Acc: 77.67%   | Precision: 73.86% Recall: 77.67% F1: 71.86%

Epoch: 57/150
Train Loss: 0.6352 | Train Acc: 79.95% | Precision: 79.31% Recall: 79.95% F1: 76.13%
Val   Loss: 0.6055 | Val Acc: 80.43%   | Precision: 82.41% Recall: 80.43% F1: 76.00%

Epoch: 58/150
Train Loss: 0.8457 | Train Acc: 73.70% | Precision: 72.43% Recall: 73.70% F1: 69.36%
Val   Loss: 1.0327 | Val Acc: 64.00%   | Precision: 43.61% Recall: 64.00% F1: 50.68%

Epoch: 59/150
Train Loss: 0.8748 | Train Acc: 69.48% | Precision: 59.06% Recall: 69.48% F1: 62.82%
Val   Loss: 0.8162 | Val Acc: 74.44%   | Precision: 64.82% Recall: 74.44% F1: 69.10%

Epoch: 60/150
Train Loss: 0.7702 | Train Acc: 74.33% | Precision: 68.06% Recall: 74.33% F1: 68.32%
Val   Loss: 0.7351 | Val Acc: 76.00%   | Precision: 71.67% Recall: 76.00% F1: 70.90%

Epoch: 61/150
Train Loss: 0.7262 | Train Acc: 76.28% | Precision: 70.40% Recall: 76.28% F1: 70.36%
Val   Loss: 0.7197 | Val Acc: 76.05%   | Precision: 65.99% Recall: 76.05% F1: 69.85%

Epoch: 62/150
Train Loss: 0.7031 | Train Acc: 77.44% | Precision: 78.23% Recall: 77.44% F1: 71.46%
Val   Loss: 0.7127 | Val Acc: 76.72%   | Precision: 66.54% Recall: 76.72% F1: 70.31%

Epoch: 63/150
Train Loss: 0.6572 | Train Acc: 78.53% | Precision: 76.53% Recall: 78.53% F1: 73.86%
Val   Loss: 0.7570 | Val Acc: 74.17%   | Precision: 69.31% Recall: 74.17% F1: 69.49%

Epoch: 64/150
Train Loss: 0.8199 | Train Acc: 75.35% | Precision: 71.99% Recall: 75.35% F1: 71.89%
Val   Loss: 0.8692 | Val Acc: 74.60%   | Precision: 64.05% Recall: 74.60% F1: 68.42%

Epoch: 65/150
Train Loss: 0.7336 | Train Acc: 76.28% | Precision: 68.77% Recall: 76.28% F1: 70.48%
Val   Loss: 0.6546 | Val Acc: 77.92%   | Precision: 71.37% Recall: 77.92% F1: 72.88%

Epoch: 66/150
Train Loss: 0.7324 | Train Acc: 75.64% | Precision: 70.10% Recall: 75.64% F1: 70.81%
Val   Loss: 0.7269 | Val Acc: 74.20%   | Precision: 66.94% Recall: 74.20% F1: 69.84%

Epoch: 67/150
Train Loss: 0.6986 | Train Acc: 77.01% | Precision: 69.91% Recall: 77.01% F1: 71.76%
Val   Loss: 0.6991 | Val Acc: 77.13%   | Precision: 66.56% Recall: 77.13% F1: 71.12%

Epoch: 68/150
Train Loss: 0.6970 | Train Acc: 77.78% | Precision: 72.91% Recall: 77.78% F1: 72.78%
Val   Loss: 0.6251 | Val Acc: 79.29%   | Precision: 73.65% Recall: 79.29% F1: 74.48%

Epoch: 69/150
Train Loss: 0.6187 | Train Acc: 79.52% | Precision: 73.70% Recall: 79.52% F1: 75.37%
Val   Loss: 0.5978 | Val Acc: 81.24%   | Precision: 76.16% Recall: 81.24% F1: 77.03%

Epoch: 70/150
Train Loss: 0.5925 | Train Acc: 80.41% | Precision: 79.94% Recall: 80.41% F1: 77.00%
Val   Loss: 0.5848 | Val Acc: 79.92%   | Precision: 81.38% Recall: 79.92% F1: 75.79%

Epoch: 71/150
Train Loss: 0.5655 | Train Acc: 81.52% | Precision: 80.83% Recall: 81.52% F1: 79.16%
Val   Loss: 0.5801 | Val Acc: 81.02%   | Precision: 80.51% Recall: 81.02% F1: 77.53%

Epoch: 72/150
Train Loss: 0.5484 | Train Acc: 82.19% | Precision: 81.40% Recall: 82.19% F1: 80.40%
Val   Loss: 0.5652 | Val Acc: 83.00%   | Precision: 81.99% Recall: 83.00% F1: 81.07%

Epoch: 73/150
Train Loss: 0.5880 | Train Acc: 81.18% | Precision: 80.58% Recall: 81.18% F1: 79.29%
Val   Loss: 1.0449 | Val Acc: 64.51%   | Precision: 47.40% Recall: 64.51% F1: 54.02%

Epoch: 74/150
Train Loss: 0.8317 | Train Acc: 72.65% | Precision: 65.27% Recall: 72.65% F1: 66.14%
Val   Loss: 0.7341 | Val Acc: 74.78%   | Precision: 65.29% Recall: 74.78% F1: 69.71%

Epoch: 75/150
Train Loss: 0.6917 | Train Acc: 77.41% | Precision: 70.33% Recall: 77.41% F1: 71.57%
Val   Loss: 0.6522 | Val Acc: 78.52%   | Precision: 68.17% Recall: 78.52% F1: 72.64%

Epoch: 76/150
Train Loss: 0.6579 | Train Acc: 78.71% | Precision: 76.59% Recall: 78.71% F1: 73.21%
Val   Loss: 0.6319 | Val Acc: 78.43%   | Precision: 77.03% Recall: 78.43% F1: 72.82%

Epoch: 77/150
Train Loss: 0.6342 | Train Acc: 79.24% | Precision: 76.77% Recall: 79.24% F1: 74.15%
Val   Loss: 0.6050 | Val Acc: 80.15%   | Precision: 79.84% Recall: 80.15% F1: 75.87%

Epoch: 78/150
Train Loss: 0.7100 | Train Acc: 76.53% | Precision: 74.83% Recall: 76.53% F1: 71.60%
Val   Loss: 0.9521 | Val Acc: 65.28%   | Precision: 51.72% Recall: 65.28% F1: 57.40%

Epoch: 79/150
Train Loss: 0.8218 | Train Acc: 72.19% | Precision: 64.94% Recall: 72.19% F1: 66.54%
Val   Loss: 0.7447 | Val Acc: 76.05%   | Precision: 72.83% Recall: 76.05% F1: 70.61%

Epoch: 80/150
Train Loss: 0.6790 | Train Acc: 77.33% | Precision: 76.51% Recall: 77.33% F1: 72.22%
Val   Loss: 0.6385 | Val Acc: 78.62%   | Precision: 74.95% Recall: 78.62% F1: 73.08%

Epoch: 81/150
Train Loss: 0.6026 | Train Acc: 80.37% | Precision: 79.24% Recall: 80.37% F1: 77.69%
Val   Loss: 0.5925 | Val Acc: 79.80%   | Precision: 77.87% Recall: 79.80% F1: 75.46%

Epoch: 82/150
Train Loss: 0.5632 | Train Acc: 82.53% | Precision: 81.75% Recall: 82.53% F1: 80.53%
Val   Loss: 0.6144 | Val Acc: 79.57%   | Precision: 81.10% Recall: 79.57% F1: 79.57%

Epoch: 83/150
Train Loss: 0.5144 | Train Acc: 84.26% | Precision: 83.78% Recall: 84.26% F1: 83.05%
Val   Loss: 0.4969 | Val Acc: 84.42%   | Precision: 84.18% Recall: 84.42% F1: 82.62%

Epoch: 84/150
Train Loss: 0.5175 | Train Acc: 84.19% | Precision: 83.58% Recall: 84.19% F1: 82.87%
Val   Loss: 0.5085 | Val Acc: 83.49%   | Precision: 82.67% Recall: 83.49% F1: 82.17%

Epoch: 85/150
Train Loss: 0.4837 | Train Acc: 85.36% | Precision: 85.01% Recall: 85.36% F1: 84.33%
Val   Loss: 0.4398 | Val Acc: 87.30%   | Precision: 87.15% Recall: 87.30% F1: 86.31%

Epoch: 86/150
Train Loss: 0.4544 | Train Acc: 86.24% | Precision: 85.96% Recall: 86.24% F1: 85.35%
Val   Loss: 0.4588 | Val Acc: 86.92%   | Precision: 87.32% Recall: 86.92% F1: 85.74%

Epoch: 87/150
Train Loss: 0.4626 | Train Acc: 86.11% | Precision: 85.86% Recall: 86.11% F1: 85.17%
Val   Loss: 0.4855 | Val Acc: 86.19%   | Precision: 85.80% Recall: 86.19% F1: 85.59%

Epoch: 88/150
Train Loss: 0.5400 | Train Acc: 83.26% | Precision: 82.67% Recall: 83.26% F1: 81.71%
Val   Loss: 0.4428 | Val Acc: 87.00%   | Precision: 86.97% Recall: 87.00% F1: 86.03%

Epoch: 89/150
Train Loss: 0.4395 | Train Acc: 87.11% | Precision: 86.86% Recall: 87.11% F1: 86.38%
Val   Loss: 0.4515 | Val Acc: 86.08%   | Precision: 85.93% Recall: 86.08% F1: 84.81%

Epoch: 90/150
Train Loss: 0.4355 | Train Acc: 87.14% | Precision: 86.88% Recall: 87.14% F1: 86.40%
Val   Loss: 0.4270 | Val Acc: 87.57%   | Precision: 87.24% Recall: 87.57% F1: 86.74%

Epoch: 91/150
Train Loss: 1.0444 | Train Acc: 69.21% | Precision: 67.36% Recall: 69.21% F1: 64.19%
Val   Loss: 1.0966 | Val Acc: 65.32%   | Precision: 48.27% Recall: 65.32% F1: 54.50%

Epoch: 92/150
Train Loss: 0.8812 | Train Acc: 71.52% | Precision: 61.96% Recall: 71.52% F1: 64.72%
Val   Loss: 0.7898 | Val Acc: 75.73%   | Precision: 65.76% Recall: 75.73% F1: 69.82%

Epoch: 93/150
Train Loss: 0.7739 | Train Acc: 75.40% | Precision: 68.03% Recall: 75.40% F1: 69.55%
Val   Loss: 0.7484 | Val Acc: 76.46%   | Precision: 65.87% Recall: 76.46% F1: 70.60%

Epoch: 94/150
Train Loss: 0.7343 | Train Acc: 76.41% | Precision: 70.16% Recall: 76.41% F1: 70.64%
Val   Loss: 0.7328 | Val Acc: 74.26%   | Precision: 65.23% Recall: 74.26% F1: 68.33%

Epoch: 95/150
Train Loss: 0.7417 | Train Acc: 76.21% | Precision: 70.23% Recall: 76.21% F1: 70.74%
Val   Loss: 0.7004 | Val Acc: 77.51%   | Precision: 66.99% Recall: 77.51% F1: 71.44%

Epoch: 96/150
Train Loss: 0.6927 | Train Acc: 77.60% | Precision: 70.87% Recall: 77.60% F1: 71.98%
Val   Loss: 0.6772 | Val Acc: 77.26%   | Precision: 67.30% Recall: 77.26% F1: 71.43%

Epoch: 97/150
Train Loss: 0.6402 | Train Acc: 79.60% | Precision: 77.91% Recall: 79.60% F1: 75.02%
Val   Loss: 0.5998 | Val Acc: 80.44%   | Precision: 81.93% Recall: 80.44% F1: 76.07%

Epoch: 98/150
Train Loss: 0.6004 | Train Acc: 81.21% | Precision: 79.63% Recall: 81.21% F1: 78.29%
Val   Loss: 0.6383 | Val Acc: 79.56%   | Precision: 79.55% Recall: 79.56% F1: 76.37%

Epoch: 99/150
Train Loss: 0.5725 | Train Acc: 82.38% | Precision: 81.28% Recall: 82.38% F1: 79.94%
Val   Loss: 0.5623 | Val Acc: 82.12%   | Precision: 81.62% Recall: 82.12% F1: 81.27%

Epoch: 100/150
Train Loss: 0.6170 | Train Acc: 80.47% | Precision: 78.77% Recall: 80.47% F1: 77.60%
Val   Loss: 0.6674 | Val Acc: 79.10%   | Precision: 74.86% Recall: 79.10% F1: 73.70%

Epoch: 101/150
Train Loss: 0.5939 | Train Acc: 81.29% | Precision: 79.93% Recall: 81.29% F1: 77.98%
Val   Loss: 0.5448 | Val Acc: 82.34%   | Precision: 83.06% Recall: 82.34% F1: 78.94%

Epoch: 102/150
Train Loss: 0.6626 | Train Acc: 78.79% | Precision: 77.31% Recall: 78.79% F1: 74.29%
Val   Loss: 0.6611 | Val Acc: 78.04%   | Precision: 68.59% Recall: 78.04% F1: 71.46%

Epoch: 103/150
Train Loss: 0.5885 | Train Acc: 81.25% | Precision: 80.43% Recall: 81.25% F1: 77.98%
Val   Loss: 0.5531 | Val Acc: 83.18%   | Precision: 82.32% Recall: 83.18% F1: 81.32%

Epoch: 104/150
Train Loss: 0.6630 | Train Acc: 78.07% | Precision: 76.94% Recall: 78.07% F1: 73.98%
Val   Loss: 0.6694 | Val Acc: 77.04%   | Precision: 67.30% Recall: 77.04% F1: 71.79%

Epoch: 105/150
Train Loss: 0.5894 | Train Acc: 81.55% | Precision: 80.43% Recall: 81.55% F1: 78.67%
Val   Loss: 0.5218 | Val Acc: 84.42%   | Precision: 83.97% Recall: 84.42% F1: 82.80%

Epoch: 106/150
Train Loss: 0.5172 | Train Acc: 84.20% | Precision: 83.37% Recall: 84.20% F1: 82.54%
Val   Loss: 0.5202 | Val Acc: 84.78%   | Precision: 84.51% Recall: 84.78% F1: 83.75%

Epoch: 107/150
Train Loss: 0.4612 | Train Acc: 85.95% | Precision: 85.62% Recall: 85.95% F1: 84.96%
Val   Loss: 0.4460 | Val Acc: 86.42%   | Precision: 86.57% Recall: 86.42% F1: 85.20%

Epoch: 108/150
Train Loss: 0.4568 | Train Acc: 86.10% | Precision: 85.94% Recall: 86.10% F1: 85.20%
Val   Loss: 0.5151 | Val Acc: 83.26%   | Precision: 82.81% Recall: 83.26% F1: 80.50%

Epoch: 109/150

wandb: Agent Starting Run: dz7mf7bk with config:
wandb: 	batch_size: 128
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.0001914006549043682
wandb: 	optimizer: sgd
wandb: 	rnn_type: rnn
wandb: 	seq_len: 160
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.8184 | Train Acc: 59.60% | Precision: 41.71% Recall: 59.60% F1: 49.08%
Val   Loss: 1.3386 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.2572 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1963 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1634 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1437 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1363 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1326 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.1293 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1277 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.1259 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1250 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 7/150
Train Loss: 1.1235 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1233 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 8/150
Train Loss: 1.1215 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1211 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 9/150
Train Loss: 1.1196 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1194 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 10/150
Train Loss: 1.1178 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1175 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 11/150
Train Loss: 1.1158 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1157 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 12/150
Train Loss: 1.1138 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1142 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 13/150
Train Loss: 1.1114 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1112 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 14/150
Train Loss: 1.1086 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1082 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 15/150
Train Loss: 1.1055 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1050 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 16/150
Train Loss: 1.1016 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1006 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 17/150
Train Loss: 1.0966 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0950 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 18/150
Train Loss: 1.0900 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0873 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 19/150
Train Loss: 1.0803 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0756 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 20/150
Train Loss: 1.0655 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0562 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 21/150
Train Loss: 1.0405 | Train Acc: 64.56% | Precision: 52.35% Recall: 64.56% F1: 50.67%
Val   Loss: 1.0230 | Val Acc: 64.49%   | Precision: 42.87% Recall: 64.49% F1: 50.65%

Epoch: 22/150
Train Loss: 0.9996 | Train Acc: 65.72% | Precision: 52.57% Recall: 65.72% F1: 53.63%
Val   Loss: 0.9726 | Val Acc: 69.83%   | Precision: 56.25% Recall: 69.83% F1: 59.77%

Epoch: 23/150
Train Loss: 0.9601 | Train Acc: 70.90% | Precision: 56.97% Recall: 70.90% F1: 61.25%
Val   Loss: 0.9467 | Val Acc: 71.39%   | Precision: 56.61% Recall: 71.39% F1: 61.94%

Epoch: 24/150
Train Loss: 0.9413 | Train Acc: 71.37% | Precision: 56.62% Recall: 71.37% F1: 62.07%
Val   Loss: 0.9307 | Val Acc: 71.65%   | Precision: 57.14% Recall: 71.65% F1: 62.37%

Epoch: 25/150
Train Loss: 0.9279 | Train Acc: 71.18% | Precision: 56.45% Recall: 71.18% F1: 62.10%
Val   Loss: 0.9185 | Val Acc: 71.67%   | Precision: 57.09% Recall: 71.67% F1: 62.48%

Epoch: 26/150
Train Loss: 0.9163 | Train Acc: 71.14% | Precision: 56.47% Recall: 71.14% F1: 62.14%
Val   Loss: 0.9086 | Val Acc: 71.42%   | Precision: 56.89% Recall: 71.42% F1: 62.11%

Epoch: 27/150
Train Loss: 0.9031 | Train Acc: 71.06% | Precision: 56.43% Recall: 71.06% F1: 62.00%
Val   Loss: 0.8954 | Val Acc: 71.18%   | Precision: 56.50% Recall: 71.18% F1: 62.18%

Epoch: 28/150
Train Loss: 0.8920 | Train Acc: 70.94% | Precision: 56.49% Recall: 70.94% F1: 62.13%
Val   Loss: 0.8876 | Val Acc: 71.24%   | Precision: 56.86% Recall: 71.24% F1: 62.42%

Epoch: 29/150
Train Loss: 0.8827 | Train Acc: 71.10% | Precision: 56.73% Recall: 71.10% F1: 62.38%
Val   Loss: 0.8780 | Val Acc: 71.38%   | Precision: 56.89% Recall: 71.38% F1: 62.41%

Epoch: 30/150
Train Loss: 0.8734 | Train Acc: 71.29% | Precision: 56.93% Recall: 71.29% F1: 62.57%
Val   Loss: 0.8690 | Val Acc: 71.55%   | Precision: 57.27% Recall: 71.55% F1: 62.85%

Epoch: 31/150
Train Loss: 0.8650 | Train Acc: 71.47% | Precision: 57.22% Recall: 71.47% F1: 62.82%
Val   Loss: 0.8615 | Val Acc: 71.72%   | Precision: 57.44% Recall: 71.72% F1: 62.88%

Epoch: 32/150
Train Loss: 0.8572 | Train Acc: 71.59% | Precision: 57.43% Recall: 71.59% F1: 63.00%
Val   Loss: 0.8541 | Val Acc: 72.10%   | Precision: 58.04% Recall: 72.10% F1: 63.38%

Epoch: 33/150
Train Loss: 0.8520 | Train Acc: 71.59% | Precision: 57.57% Recall: 71.59% F1: 63.08%
Val   Loss: 0.8497 | Val Acc: 71.86%   | Precision: 57.92% Recall: 71.86% F1: 63.31%

Epoch: 34/150
Train Loss: 0.8462 | Train Acc: 71.64% | Precision: 57.71% Recall: 71.64% F1: 63.18%
Val   Loss: 0.8577 | Val Acc: 71.70%   | Precision: 58.11% Recall: 71.70% F1: 63.29%

Epoch: 35/150
Train Loss: 0.8407 | Train Acc: 71.67% | Precision: 57.98% Recall: 71.67% F1: 63.34%
Val   Loss: 0.8447 | Val Acc: 71.73%   | Precision: 58.13% Recall: 71.73% F1: 63.51%

Epoch: 36/150
Train Loss: 0.8387 | Train Acc: 71.59% | Precision: 58.17% Recall: 71.59% F1: 63.43%
Val   Loss: 0.8425 | Val Acc: 71.74%   | Precision: 58.17% Recall: 71.74% F1: 63.52%

Epoch: 37/150
Train Loss: 0.8342 | Train Acc: 71.64% | Precision: 58.52% Recall: 71.64% F1: 63.57%
Val   Loss: 0.8365 | Val Acc: 71.72%   | Precision: 58.26% Recall: 71.72% F1: 63.54%

Epoch: 38/150
Train Loss: 0.8270 | Train Acc: 71.68% | Precision: 58.59% Recall: 71.68% F1: 63.66%
Val   Loss: 0.8281 | Val Acc: 71.86%   | Precision: 58.57% Recall: 71.86% F1: 63.84%

Epoch: 39/150
Train Loss: 0.8138 | Train Acc: 71.85% | Precision: 58.97% Recall: 71.85% F1: 63.92%
Val   Loss: 0.8124 | Val Acc: 72.43%   | Precision: 58.71% Recall: 72.43% F1: 64.16%

Epoch: 40/150
Train Loss: 0.8021 | Train Acc: 72.09% | Precision: 59.01% Recall: 72.09% F1: 64.18%
Val   Loss: 0.8043 | Val Acc: 72.26%   | Precision: 58.97% Recall: 72.26% F1: 64.31%

Epoch: 41/150
Train Loss: 0.7940 | Train Acc: 72.12% | Precision: 59.30% Recall: 72.12% F1: 64.39%
Val   Loss: 0.8046 | Val Acc: 72.19%   | Precision: 58.76% Recall: 72.19% F1: 64.20%

Epoch: 42/150
Train Loss: 0.7878 | Train Acc: 72.21% | Precision: 59.46% Recall: 72.21% F1: 64.54%
Val   Loss: 0.7905 | Val Acc: 72.37%   | Precision: 59.41% Recall: 72.37% F1: 64.66%

Epoch: 43/150
Train Loss: 0.7809 | Train Acc: 72.39% | Precision: 59.96% Recall: 72.39% F1: 64.90%
Val   Loss: 0.7865 | Val Acc: 72.49%   | Precision: 60.44% Recall: 72.49% F1: 65.19%

Epoch: 44/150
Train Loss: 0.7722 | Train Acc: 72.84% | Precision: 61.22% Recall: 72.84% F1: 65.73%
Val   Loss: 0.7778 | Val Acc: 72.96%   | Precision: 61.25% Recall: 72.96% F1: 65.95%

Epoch: 45/150
Train Loss: 0.7603 | Train Acc: 73.24% | Precision: 61.98% Recall: 73.24% F1: 66.34%
Val   Loss: 0.7645 | Val Acc: 73.42%   | Precision: 62.35% Recall: 73.42% F1: 66.33%

Epoch: 46/150
Train Loss: 0.7460 | Train Acc: 73.51% | Precision: 63.01% Recall: 73.51% F1: 66.71%
Val   Loss: 0.7532 | Val Acc: 73.76%   | Precision: 63.16% Recall: 73.76% F1: 66.46%

Epoch: 47/150
Train Loss: 0.7323 | Train Acc: 73.80% | Precision: 65.84% Recall: 73.80% F1: 67.55%
Val   Loss: 0.7347 | Val Acc: 74.23%   | Precision: 67.38% Recall: 74.23% F1: 68.09%

Epoch: 48/150
Train Loss: 0.7182 | Train Acc: 74.11% | Precision: 67.69% Recall: 74.11% F1: 68.39%
Val   Loss: 0.7210 | Val Acc: 74.71%   | Precision: 68.94% Recall: 74.71% F1: 69.23%

Epoch: 49/150
Train Loss: 0.7040 | Train Acc: 74.71% | Precision: 69.70% Recall: 74.71% F1: 69.69%
Val   Loss: 0.7126 | Val Acc: 75.06%   | Precision: 70.33% Recall: 75.06% F1: 70.48%

Epoch: 50/150
Train Loss: 0.6942 | Train Acc: 74.95% | Precision: 70.57% Recall: 74.95% F1: 70.49%
Val   Loss: 0.6981 | Val Acc: 75.32%   | Precision: 69.76% Recall: 75.32% F1: 69.96%

Epoch: 51/150
Train Loss: 0.6805 | Train Acc: 75.59% | Precision: 72.10% Recall: 75.59% F1: 71.60%
Val   Loss: 0.6874 | Val Acc: 75.18%   | Precision: 70.83% Recall: 75.18% F1: 71.06%

Epoch: 52/150
Train Loss: 0.6705 | Train Acc: 76.10% | Precision: 72.99% Recall: 76.10% F1: 72.66%
Val   Loss: 0.6936 | Val Acc: 74.93%   | Precision: 69.74% Recall: 74.93% F1: 70.63%

Epoch: 53/150
Train Loss: 0.6595 | Train Acc: 76.73% | Precision: 74.15% Recall: 76.73% F1: 73.77%
Val   Loss: 0.6711 | Val Acc: 75.91%   | Precision: 72.05% Recall: 75.91% F1: 72.26%

Epoch: 54/150
Train Loss: 0.6489 | Train Acc: 77.71% | Precision: 75.69% Recall: 77.71% F1: 75.37%
Val   Loss: 0.6716 | Val Acc: 75.85%   | Precision: 71.37% Recall: 75.85% F1: 71.96%

Epoch: 55/150
Train Loss: 0.6395 | Train Acc: 78.51% | Precision: 76.80% Recall: 78.51% F1: 76.44%
Val   Loss: 0.6580 | Val Acc: 77.09%   | Precision: 74.23% Recall: 77.09% F1: 74.28%

Epoch: 56/150
Train Loss: 0.6339 | Train Acc: 79.19% | Precision: 77.57% Recall: 79.19% F1: 77.26%
Val   Loss: 0.6406 | Val Acc: 79.53%   | Precision: 78.01% Recall: 79.53% F1: 78.21%

Epoch: 57/150
Train Loss: 0.6244 | Train Acc: 80.27% | Precision: 78.86% Recall: 80.27% F1: 78.57%
Val   Loss: 0.6314 | Val Acc: 80.31%   | Precision: 78.94% Recall: 80.31% F1: 78.28%

Epoch: 58/150
Train Loss: 0.6339 | Train Acc: 80.19% | Precision: 78.69% Recall: 80.19% F1: 78.42%
Val   Loss: 0.6816 | Val Acc: 75.20%   | Precision: 71.76% Recall: 75.20% F1: 72.31%

Epoch: 59/150
Train Loss: 0.6213 | Train Acc: 80.49% | Precision: 79.03% Recall: 80.49% F1: 78.50%
Val   Loss: 0.6342 | Val Acc: 80.25%   | Precision: 76.67% Recall: 80.25% F1: 76.83%

Epoch: 60/150
Train Loss: 0.6205 | Train Acc: 81.10% | Precision: 79.77% Recall: 81.10% F1: 79.32%
Val   Loss: 0.6249 | Val Acc: 80.94%   | Precision: 79.45% Recall: 80.94% F1: 78.83%

Epoch: 61/150
Train Loss: 0.6097 | Train Acc: 82.03% | Precision: 80.95% Recall: 82.03% F1: 80.27%
Val   Loss: 0.6174 | Val Acc: 82.23%   | Precision: 81.10% Recall: 82.23% F1: 80.33%

Epoch: 62/150
Train Loss: 0.6072 | Train Acc: 81.98% | Precision: 80.87% Recall: 81.98% F1: 80.10%
Val   Loss: 0.6075 | Val Acc: 83.32%   | Precision: 82.45% Recall: 83.32% F1: 81.66%

Epoch: 63/150
Train Loss: 0.5898 | Train Acc: 83.59% | Precision: 82.87% Recall: 83.59% F1: 82.07%
Val   Loss: 0.5974 | Val Acc: 84.11%   | Precision: 83.40% Recall: 84.11% F1: 82.68%

Epoch: 64/150
Train Loss: 0.5898 | Train Acc: 83.31% | Precision: 82.50% Recall: 83.31% F1: 81.74%
Val   Loss: 0.5953 | Val Acc: 83.83%   | Precision: 83.27% Recall: 83.83% F1: 82.22%

Epoch: 65/150
Train Loss: 0.5817 | Train Acc: 83.75% | Precision: 83.05% Recall: 83.75% F1: 82.29%
Val   Loss: 0.5853 | Val Acc: 84.54%   | Precision: 83.91% Recall: 84.54% F1: 83.20%

Epoch: 66/150
Train Loss: 0.5756 | Train Acc: 84.21% | Precision: 83.60% Recall: 84.21% F1: 82.83%
Val   Loss: 0.6242 | Val Acc: 82.05%   | Precision: 81.19% Recall: 82.05% F1: 79.17%

Epoch: 67/150
Train Loss: 0.5663 | Train Acc: 84.78% | Precision: 84.26% Recall: 84.78% F1: 83.52%
Val   Loss: 0.5781 | Val Acc: 84.18%   | Precision: 83.65% Recall: 84.18% F1: 82.67%

Epoch: 68/150
Train Loss: 0.5577 | Train Acc: 85.02% | Precision: 84.52% Recall: 85.02% F1: 83.84%
Val   Loss: 0.5752 | Val Acc: 84.48%   | Precision: 84.30% Recall: 84.48% F1: 82.75%

Epoch: 69/150
Train Loss: 0.5468 | Train Acc: 85.42% | Precision: 85.00% Recall: 85.42% F1: 84.32%
Val   Loss: 0.5528 | Val Acc: 85.33%   | Precision: 84.84% Recall: 85.33% F1: 84.19%

Epoch: 70/150
Train Loss: 0.5380 | Train Acc: 85.57% | Precision: 85.19% Recall: 85.57% F1: 84.50%
Val   Loss: 0.5522 | Val Acc: 84.78%   | Precision: 84.28% Recall: 84.78% F1: 83.91%

Epoch: 71/150
Train Loss: 0.5330 | Train Acc: 85.47% | Precision: 85.05% Recall: 85.47% F1: 84.39%
Val   Loss: 0.5388 | Val Acc: 85.21%   | Precision: 84.71% Recall: 85.21% F1: 84.37%

Epoch: 72/150
Train Loss: 0.5233 | Train Acc: 85.81% | Precision: 85.46% Recall: 85.81% F1: 84.75%
Val   Loss: 0.5305 | Val Acc: 85.72%   | Precision: 85.52% Recall: 85.72% F1: 84.63%

Epoch: 73/150
Train Loss: 0.5114 | Train Acc: 86.25% | Precision: 85.94% Recall: 86.25% F1: 85.31%
Val   Loss: 0.5197 | Val Acc: 86.00%   | Precision: 85.63% Recall: 86.00% F1: 84.91%

Epoch: 74/150
Train Loss: 0.5097 | Train Acc: 86.18% | Precision: 85.85% Recall: 86.18% F1: 85.23%
Val   Loss: 0.5394 | Val Acc: 84.74%   | Precision: 84.28% Recall: 84.74% F1: 83.06%

Epoch: 75/150
Train Loss: 0.4979 | Train Acc: 86.61% | Precision: 86.32% Recall: 86.61% F1: 85.71%
Val   Loss: 0.5029 | Val Acc: 86.57%   | Precision: 86.27% Recall: 86.57% F1: 85.52%

Epoch: 76/150
Train Loss: 0.4947 | Train Acc: 86.58% | Precision: 86.27% Recall: 86.58% F1: 85.70%
Val   Loss: 0.5273 | Val Acc: 85.17%   | Precision: 84.62% Recall: 85.17% F1: 83.28%

Epoch: 77/150
Train Loss: 0.4882 | Train Acc: 86.88% | Precision: 86.63% Recall: 86.88% F1: 86.00%
Val   Loss: 0.4986 | Val Acc: 86.75%   | Precision: 86.40% Recall: 86.75% F1: 85.84%

Epoch: 78/150
Train Loss: 0.4827 | Train Acc: 86.88% | Precision: 86.64% Recall: 86.88% F1: 86.03%
Val   Loss: 0.4880 | Val Acc: 86.96%   | Precision: 86.82% Recall: 86.96% F1: 85.87%

Epoch: 79/150
Train Loss: 0.4810 | Train Acc: 86.65% | Precision: 86.36% Recall: 86.65% F1: 85.81%
Val   Loss: 0.5101 | Val Acc: 85.74%   | Precision: 85.32% Recall: 85.74% F1: 84.91%

Epoch: 80/150
Train Loss: 0.4762 | Train Acc: 87.03% | Precision: 86.80% Recall: 87.03% F1: 86.20%
Val   Loss: 0.4891 | Val Acc: 86.61%   | Precision: 86.15% Recall: 86.61% F1: 85.81%

Epoch: 81/150
Train Loss: 0.4704 | Train Acc: 87.13% | Precision: 86.90% Recall: 87.13% F1: 86.30%
Val   Loss: 0.4791 | Val Acc: 86.90%   | Precision: 86.65% Recall: 86.90% F1: 86.07%

Epoch: 82/150
Train Loss: 0.4697 | Train Acc: 87.06% | Precision: 86.82% Recall: 87.06% F1: 86.25%
Val   Loss: 0.4706 | Val Acc: 87.21%   | Precision: 86.94% Recall: 87.21% F1: 86.32%

Epoch: 83/150
Train Loss: 0.4705 | Train Acc: 87.06% | Precision: 86.85% Recall: 87.06% F1: 86.19%
Val   Loss: 0.4864 | Val Acc: 86.41%   | Precision: 86.03% Recall: 86.41% F1: 85.46%

Epoch: 84/150
Train Loss: 0.4620 | Train Acc: 87.30% | Precision: 87.12% Recall: 87.30% F1: 86.51%
Val   Loss: 0.4717 | Val Acc: 86.93%   | Precision: 86.57% Recall: 86.93% F1: 86.09%

Epoch: 85/150
Train Loss: 0.4555 | Train Acc: 87.41% | Precision: 87.20% Recall: 87.41% F1: 86.63%
Val   Loss: 0.4569 | Val Acc: 87.73%   | Precision: 87.55% Recall: 87.73% F1: 86.96%

Epoch: 86/150
Train Loss: 0.4538 | Train Acc: 87.43% | Precision: 87.27% Recall: 87.43% F1: 86.65%
Val   Loss: 0.4668 | Val Acc: 86.91%   | Precision: 86.56% Recall: 86.91% F1: 86.17%

Epoch: 87/150
Train Loss: 0.4522 | Train Acc: 87.46% | Precision: 87.28% Recall: 87.46% F1: 86.67%
Val   Loss: 0.4541 | Val Acc: 87.22%   | Precision: 86.88% Recall: 87.22% F1: 86.50%

Epoch: 88/150
Train Loss: 0.4453 | Train Acc: 87.74% | Precision: 87.61% Recall: 87.74% F1: 87.00%
Val   Loss: 0.4565 | Val Acc: 87.40%   | Precision: 87.37% Recall: 87.40% F1: 86.37%

Epoch: 89/150
Train Loss: 0.4437 | Train Acc: 87.76% | Precision: 87.64% Recall: 87.76% F1: 87.02%
Val   Loss: 0.4461 | Val Acc: 87.77%   | Precision: 87.53% Recall: 87.77% F1: 86.92%

Epoch: 90/150
Train Loss: 0.4448 | Train Acc: 87.63% | Precision: 87.47% Recall: 87.63% F1: 86.89%
Val   Loss: 0.4878 | Val Acc: 85.83%   | Precision: 85.74% Recall: 85.83% F1: 84.31%

Epoch: 91/150
Train Loss: 0.4413 | Train Acc: 87.64% | Precision: 87.50% Recall: 87.64% F1: 86.88%
Val   Loss: 0.4397 | Val Acc: 87.79%   | Precision: 87.61% Recall: 87.79% F1: 86.94%

Epoch: 92/150
Train Loss: 0.4351 | Train Acc: 87.89% | Precision: 87.74% Recall: 87.89% F1: 87.18%
Val   Loss: 0.4323 | Val Acc: 88.22%   | Precision: 88.03% Recall: 88.22% F1: 87.51%

Epoch: 93/150
Train Loss: 0.4321 | Train Acc: 87.84% | Precision: 87.67% Recall: 87.84% F1: 87.14%
Val   Loss: 0.4293 | Val Acc: 88.35%   | Precision: 88.17% Recall: 88.35% F1: 87.62%

Epoch: 94/150
Train Loss: 0.4605 | Train Acc: 86.90% | Precision: 86.68% Recall: 86.90% F1: 86.03%
Val   Loss: 0.4643 | Val Acc: 86.65%   | Precision: 86.42% Recall: 86.65% F1: 85.55%

Epoch: 95/150
Train Loss: 0.4282 | Train Acc: 87.99% | Precision: 87.88% Recall: 87.99% F1: 87.28%
Val   Loss: 0.4292 | Val Acc: 88.24%   | Precision: 88.14% Recall: 88.24% F1: 87.43%

Epoch: 96/150
Train Loss: 0.4372 | Train Acc: 87.92% | Precision: 87.82% Recall: 87.92% F1: 87.16%
Val   Loss: 0.6920 | Val Acc: 78.11%   | Precision: 71.62% Recall: 78.11% F1: 72.06%

Epoch: 97/150
Train Loss: 0.4804 | Train Acc: 85.97% | Precision: 85.66% Recall: 85.97% F1: 84.86%
Val   Loss: 0.4461 | Val Acc: 87.33%   | Precision: 87.02% Recall: 87.33% F1: 86.47%

Epoch: 98/150
Train Loss: 0.4403 | Train Acc: 87.57% | Precision: 87.43% Recall: 87.57% F1: 86.72%
Val   Loss: 0.4501 | Val Acc: 87.73%   | Precision: 87.52% Recall: 87.73% F1: 87.01%

Epoch: 99/150
Train Loss: 0.4345 | Train Acc: 87.85% | Precision: 87.75% Recall: 87.85% F1: 87.05%
Val   Loss: 0.4324 | Val Acc: 87.80%   | Precision: 87.64% Recall: 87.80% F1: 86.98%

Epoch: 100/150
Train Loss: 0.4453 | Train Acc: 87.28% | Precision: 87.15% Recall: 87.28% F1: 86.38%
Val   Loss: 0.4373 | Val Acc: 87.88%   | Precision: 87.71% Recall: 87.88% F1: 87.12%

Epoch: 101/150
Train Loss: 0.4250 | Train Acc: 88.06% | Precision: 87.96% Recall: 88.06% F1: 87.29%
Val   Loss: 0.4219 | Val Acc: 88.30%   | Precision: 88.21% Recall: 88.30% F1: 87.44%

Epoch: 102/150
Train Loss: 0.4234 | Train Acc: 88.12% | Precision: 88.05% Recall: 88.12% F1: 87.35%
Val   Loss: 0.4335 | Val Acc: 87.87%   | Precision: 87.64% Recall: 87.87% F1: 86.95%

Epoch: 103/150
Train Loss: 0.4367 | Train Acc: 87.67% | Precision: 87.58% Recall: 87.67% F1: 86.84%
Val   Loss: 0.4293 | Val Acc: 88.03%   | Precision: 87.89% Recall: 88.03% F1: 87.27%

Epoch: 104/150
Train Loss: 0.4177 | Train Acc: 88.28% | Precision: 88.21% Recall: 88.28% F1: 87.54%
Val   Loss: 0.4125 | Val Acc: 88.49%   | Precision: 88.37% Recall: 88.49% F1: 87.72%

Epoch: 105/150
Train Loss: 0.4126 | Train Acc: 88.54% | Precision: 88.51% Recall: 88.54% F1: 87.81%
Val   Loss: 0.4113 | Val Acc: 88.45%   | Precision: 88.34% Recall: 88.45% F1: 87.67%

Epoch: 106/150
Train Loss: 0.4064 | Train Acc: 88.73% | Precision: 88.71% Recall: 88.73% F1: 88.02%
Val   Loss: 0.4111 | Val Acc: 88.70%   | Precision: 88.56% Recall: 88.70% F1: 88.01%

Epoch: 107/150
Train Loss: 0.4006 | Train Acc: 88.79% | Precision: 88.78% Recall: 88.79% F1: 88.10%
Val   Loss: 0.4259 | Val Acc: 88.45%   | Precision: 88.35% Recall: 88.45% F1: 87.62%

Epoch: 108/150
Train Loss: 0.4243 | Train Acc: 88.02% | Precision: 87.96% Recall: 88.02% F1: 87.23%
Val   Loss: 0.4368 | Val Acc: 87.31%   | Precision: 86.97% Recall: 87.31% F1: 86.51%

Epoch: 109/150

wandb: Agent Starting Run: 3r0ua5g5 with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.000296432768177121
wandb: 	optimizer: sgd
wandb: 	rnn_type: rnn
wandb: 	seq_len: 150
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.4060 | Train Acc: 63.96% | Precision: 43.16% Recall: 63.96% F1: 50.67%
Val   Loss: 1.1556 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.1334 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1260 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1216 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1189 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1153 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1118 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.1060 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1018 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.0876 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0717 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 7/150
Train Loss: 1.0278 | Train Acc: 65.26% | Precision: 56.28% Recall: 65.26% F1: 52.35%
Val   Loss: 0.9675 | Val Acc: 69.22%   | Precision: 56.24% Recall: 69.22% F1: 58.93%

Epoch: 8/150
Train Loss: 0.9393 | Train Acc: 71.09% | Precision: 56.98% Recall: 71.09% F1: 61.60%
Val   Loss: 0.9108 | Val Acc: 71.57%   | Precision: 57.44% Recall: 71.57% F1: 62.14%

Epoch: 9/150
Train Loss: 0.8944 | Train Acc: 71.20% | Precision: 56.74% Recall: 71.20% F1: 62.31%
Val   Loss: 0.8856 | Val Acc: 71.52%   | Precision: 57.27% Recall: 71.52% F1: 62.67%

Epoch: 10/150
Train Loss: 0.8676 | Train Acc: 71.58% | Precision: 57.42% Recall: 71.58% F1: 62.96%
Val   Loss: 0.8592 | Val Acc: 71.98%   | Precision: 58.03% Recall: 71.98% F1: 63.45%

Epoch: 11/150
Train Loss: 0.8527 | Train Acc: 71.77% | Precision: 57.90% Recall: 71.77% F1: 63.30%
Val   Loss: 0.8564 | Val Acc: 71.07%   | Precision: 57.83% Recall: 71.07% F1: 63.02%

Epoch: 12/150
Train Loss: 0.8406 | Train Acc: 71.79% | Precision: 58.43% Recall: 71.79% F1: 63.57%
Val   Loss: 0.8487 | Val Acc: 71.77%   | Precision: 58.24% Recall: 71.77% F1: 63.23%

Epoch: 13/150
Train Loss: 0.8287 | Train Acc: 71.82% | Precision: 58.78% Recall: 71.82% F1: 63.82%
Val   Loss: 0.8277 | Val Acc: 72.49%   | Precision: 58.79% Recall: 72.49% F1: 63.91%

Epoch: 14/150
Train Loss: 0.8097 | Train Acc: 71.92% | Precision: 59.79% Recall: 71.92% F1: 64.23%
Val   Loss: 0.7849 | Val Acc: 72.55%   | Precision: 66.36% Recall: 72.55% F1: 64.85%

Epoch: 15/150
Train Loss: 0.7679 | Train Acc: 73.33% | Precision: 66.83% Recall: 73.33% F1: 66.75%
Val   Loss: 0.7444 | Val Acc: 74.23%   | Precision: 67.66% Recall: 74.23% F1: 68.10%

Epoch: 16/150
Train Loss: 0.7432 | Train Acc: 74.22% | Precision: 67.02% Recall: 74.22% F1: 68.53%
Val   Loss: 0.7484 | Val Acc: 73.86%   | Precision: 65.35% Recall: 73.86% F1: 67.29%

Epoch: 17/150
Train Loss: 0.7088 | Train Acc: 75.18% | Precision: 68.29% Recall: 75.18% F1: 70.17%
Val   Loss: 0.6937 | Val Acc: 76.16%   | Precision: 69.62% Recall: 76.16% F1: 71.47%

Epoch: 18/150
Train Loss: 0.6926 | Train Acc: 75.69% | Precision: 69.00% Recall: 75.69% F1: 70.99%
Val   Loss: 0.6704 | Val Acc: 77.54%   | Precision: 71.26% Recall: 77.54% F1: 73.61%

Epoch: 19/150
Train Loss: 0.6631 | Train Acc: 77.15% | Precision: 70.95% Recall: 77.15% F1: 73.00%
Val   Loss: 0.6506 | Val Acc: 77.76%   | Precision: 71.63% Recall: 77.76% F1: 73.55%

Epoch: 20/150
Train Loss: 0.6394 | Train Acc: 78.09% | Precision: 72.05% Recall: 78.09% F1: 74.16%
Val   Loss: 0.6304 | Val Acc: 78.59%   | Precision: 72.39% Recall: 78.59% F1: 74.22%

Epoch: 21/150
Train Loss: 0.6107 | Train Acc: 79.83% | Precision: 74.00% Recall: 79.83% F1: 76.12%
Val   Loss: 0.6085 | Val Acc: 80.92%   | Precision: 75.13% Recall: 80.92% F1: 77.55%

Epoch: 22/150
Train Loss: 0.5821 | Train Acc: 80.97% | Precision: 76.11% Recall: 80.97% F1: 77.43%
Val   Loss: 0.5705 | Val Acc: 81.82%   | Precision: 76.29% Recall: 81.82% F1: 78.18%

Epoch: 23/150
Train Loss: 0.5629 | Train Acc: 82.09% | Precision: 79.45% Recall: 82.09% F1: 79.02%
Val   Loss: 0.5600 | Val Acc: 82.63%   | Precision: 80.15% Recall: 82.63% F1: 79.84%

Epoch: 24/150
Train Loss: 0.5433 | Train Acc: 83.17% | Precision: 82.01% Recall: 83.17% F1: 80.91%
Val   Loss: 0.5461 | Val Acc: 83.69%   | Precision: 82.89% Recall: 83.69% F1: 82.34%

Epoch: 25/150
Train Loss: 0.5256 | Train Acc: 84.27% | Precision: 83.67% Recall: 84.27% F1: 82.71%
Val   Loss: 0.5264 | Val Acc: 83.68%   | Precision: 83.31% Recall: 83.68% F1: 81.61%

Epoch: 26/150
Train Loss: 0.5054 | Train Acc: 85.44% | Precision: 85.07% Recall: 85.44% F1: 84.26%
Val   Loss: 0.5098 | Val Acc: 85.29%   | Precision: 84.71% Recall: 85.29% F1: 84.20%

Epoch: 27/150
Train Loss: 0.4868 | Train Acc: 86.13% | Precision: 85.86% Recall: 86.13% F1: 85.16%
Val   Loss: 0.4971 | Val Acc: 85.79%   | Precision: 85.23% Recall: 85.79% F1: 85.18%

Epoch: 28/150
Train Loss: 0.4737 | Train Acc: 86.49% | Precision: 86.25% Recall: 86.49% F1: 85.63%
Val   Loss: 0.4915 | Val Acc: 85.05%   | Precision: 85.27% Recall: 85.05% F1: 84.20%

Epoch: 29/150
Train Loss: 0.4634 | Train Acc: 86.67% | Precision: 86.48% Recall: 86.67% F1: 85.85%
Val   Loss: 0.4792 | Val Acc: 86.25%   | Precision: 86.06% Recall: 86.25% F1: 85.21%

Epoch: 30/150
Train Loss: 0.4521 | Train Acc: 86.95% | Precision: 86.79% Recall: 86.95% F1: 86.16%
Val   Loss: 0.4506 | Val Acc: 87.13%   | Precision: 86.87% Recall: 87.13% F1: 86.28%

Epoch: 31/150
Train Loss: 0.4422 | Train Acc: 87.17% | Precision: 87.02% Recall: 87.17% F1: 86.40%
Val   Loss: 0.4895 | Val Acc: 85.29%   | Precision: 85.19% Recall: 85.29% F1: 84.60%

Epoch: 32/150
Train Loss: 0.4342 | Train Acc: 87.28% | Precision: 87.14% Recall: 87.28% F1: 86.52%
Val   Loss: 0.4302 | Val Acc: 87.58%   | Precision: 87.53% Recall: 87.58% F1: 86.70%

Epoch: 33/150
Train Loss: 0.4207 | Train Acc: 87.66% | Precision: 87.56% Recall: 87.66% F1: 86.98%
Val   Loss: 0.4614 | Val Acc: 85.78%   | Precision: 85.49% Recall: 85.78% F1: 85.19%

Epoch: 34/150
Train Loss: 0.4194 | Train Acc: 87.47% | Precision: 87.34% Recall: 87.47% F1: 86.76%
Val   Loss: 0.4136 | Val Acc: 87.86%   | Precision: 87.70% Recall: 87.86% F1: 87.25%

Epoch: 35/150
Train Loss: 0.4115 | Train Acc: 87.85% | Precision: 87.74% Recall: 87.85% F1: 87.22%
Val   Loss: 0.4137 | Val Acc: 87.80%   | Precision: 87.67% Recall: 87.80% F1: 87.13%

Epoch: 36/150
Train Loss: 0.4030 | Train Acc: 88.00% | Precision: 87.87% Recall: 88.00% F1: 87.38%
Val   Loss: 0.4200 | Val Acc: 87.31%   | Precision: 87.03% Recall: 87.31% F1: 86.54%

Epoch: 37/150
Train Loss: 0.3932 | Train Acc: 88.27% | Precision: 88.16% Recall: 88.27% F1: 87.69%
Val   Loss: 0.4162 | Val Acc: 87.24%   | Precision: 87.35% Recall: 87.24% F1: 86.46%

Epoch: 38/150
Train Loss: 0.3910 | Train Acc: 88.37% | Precision: 88.26% Recall: 88.37% F1: 87.79%
Val   Loss: 0.4196 | Val Acc: 86.72%   | Precision: 86.77% Recall: 86.72% F1: 86.07%

Epoch: 39/150
Train Loss: 0.3816 | Train Acc: 88.61% | Precision: 88.53% Recall: 88.61% F1: 88.06%
Val   Loss: 0.3955 | Val Acc: 88.68%   | Precision: 88.62% Recall: 88.68% F1: 87.97%

Epoch: 40/150
Train Loss: 0.3831 | Train Acc: 88.66% | Precision: 88.58% Recall: 88.66% F1: 88.11%
Val   Loss: 0.4027 | Val Acc: 87.94%   | Precision: 87.91% Recall: 87.94% F1: 87.34%

Epoch: 41/150
Train Loss: 0.3769 | Train Acc: 88.81% | Precision: 88.74% Recall: 88.81% F1: 88.26%
Val   Loss: 0.3825 | Val Acc: 88.49%   | Precision: 88.53% Recall: 88.49% F1: 88.11%

Epoch: 42/150
Train Loss: 0.3727 | Train Acc: 88.90% | Precision: 88.83% Recall: 88.90% F1: 88.36%
Val   Loss: 0.3827 | Val Acc: 88.60%   | Precision: 88.50% Recall: 88.60% F1: 88.20%

Epoch: 43/150
Train Loss: 0.3664 | Train Acc: 89.08% | Precision: 89.00% Recall: 89.08% F1: 88.55%
Val   Loss: 0.3689 | Val Acc: 88.94%   | Precision: 88.72% Recall: 88.94% F1: 88.32%

Epoch: 44/150
Train Loss: 0.3689 | Train Acc: 88.98% | Precision: 88.88% Recall: 88.98% F1: 88.45%
Val   Loss: 0.4024 | Val Acc: 87.88%   | Precision: 87.87% Recall: 87.88% F1: 87.33%

Epoch: 45/150
Train Loss: 0.3640 | Train Acc: 89.13% | Precision: 89.05% Recall: 89.13% F1: 88.60%
Val   Loss: 0.3654 | Val Acc: 89.32%   | Precision: 89.32% Recall: 89.32% F1: 88.75%

Epoch: 46/150
Train Loss: 0.3586 | Train Acc: 89.25% | Precision: 89.18% Recall: 89.25% F1: 88.75%
Val   Loss: 0.3564 | Val Acc: 89.37%   | Precision: 89.25% Recall: 89.37% F1: 88.74%

Epoch: 47/150
Train Loss: 0.3530 | Train Acc: 89.59% | Precision: 89.55% Recall: 89.59% F1: 89.10%
Val   Loss: 0.3752 | Val Acc: 88.66%   | Precision: 88.53% Recall: 88.66% F1: 88.01%

Epoch: 48/150
Train Loss: 0.3554 | Train Acc: 89.36% | Precision: 89.29% Recall: 89.36% F1: 88.86%
Val   Loss: 0.3482 | Val Acc: 89.48%   | Precision: 89.34% Recall: 89.48% F1: 89.04%

Epoch: 49/150
Train Loss: 0.3411 | Train Acc: 89.86% | Precision: 89.80% Recall: 89.86% F1: 89.38%
Val   Loss: 0.3475 | Val Acc: 89.51%   | Precision: 89.35% Recall: 89.51% F1: 88.95%

Epoch: 50/150
Train Loss: 0.3414 | Train Acc: 89.84% | Precision: 89.79% Recall: 89.84% F1: 89.36%
Val   Loss: 0.3687 | Val Acc: 88.90%   | Precision: 88.79% Recall: 88.90% F1: 88.14%

Epoch: 51/150
Train Loss: 0.3402 | Train Acc: 89.76% | Precision: 89.69% Recall: 89.76% F1: 89.28%
Val   Loss: 0.3933 | Val Acc: 88.05%   | Precision: 87.85% Recall: 88.05% F1: 87.57%

Epoch: 52/150
Train Loss: 0.3361 | Train Acc: 89.99% | Precision: 89.94% Recall: 89.99% F1: 89.53%
Val   Loss: 0.3654 | Val Acc: 88.93%   | Precision: 88.78% Recall: 88.93% F1: 88.18%

Epoch: 53/150
Train Loss: 0.3370 | Train Acc: 89.91% | Precision: 89.85% Recall: 89.91% F1: 89.45%
Val   Loss: 0.3245 | Val Acc: 89.99%   | Precision: 89.95% Recall: 89.99% F1: 89.38%

Epoch: 54/150
Train Loss: 0.3281 | Train Acc: 90.12% | Precision: 90.07% Recall: 90.12% F1: 89.68%
Val   Loss: 0.3379 | Val Acc: 89.62%   | Precision: 89.55% Recall: 89.62% F1: 89.05%

Epoch: 55/150
Train Loss: 0.3289 | Train Acc: 90.18% | Precision: 90.13% Recall: 90.18% F1: 89.72%
Val   Loss: 0.3402 | Val Acc: 89.58%   | Precision: 89.56% Recall: 89.58% F1: 89.14%

Epoch: 56/150
Train Loss: 0.3219 | Train Acc: 90.36% | Precision: 90.32% Recall: 90.36% F1: 89.91%
Val   Loss: 0.3181 | Val Acc: 90.70%   | Precision: 90.60% Recall: 90.70% F1: 90.27%

Epoch: 57/150
Train Loss: 0.3257 | Train Acc: 90.30% | Precision: 90.22% Recall: 90.30% F1: 89.87%
Val   Loss: 0.3230 | Val Acc: 90.55%   | Precision: 90.46% Recall: 90.55% F1: 90.03%

Epoch: 58/150
Train Loss: 0.3174 | Train Acc: 90.49% | Precision: 90.44% Recall: 90.49% F1: 90.06%
Val   Loss: 0.3404 | Val Acc: 89.89%   | Precision: 89.78% Recall: 89.89% F1: 89.32%

Epoch: 59/150
Train Loss: 0.3206 | Train Acc: 90.33% | Precision: 90.27% Recall: 90.33% F1: 89.89%
Val   Loss: 0.3133 | Val Acc: 90.74%   | Precision: 90.76% Recall: 90.74% F1: 90.33%

Epoch: 60/150
Train Loss: 0.3113 | Train Acc: 90.75% | Precision: 90.73% Recall: 90.75% F1: 90.34%
Val   Loss: 0.3136 | Val Acc: 90.44%   | Precision: 90.39% Recall: 90.44% F1: 89.90%

Epoch: 61/150
Train Loss: 0.3085 | Train Acc: 90.66% | Precision: 90.60% Recall: 90.66% F1: 90.24%
Val   Loss: 0.3298 | Val Acc: 90.27%   | Precision: 90.35% Recall: 90.27% F1: 89.75%

Epoch: 62/150
Train Loss: 0.3084 | Train Acc: 90.79% | Precision: 90.75% Recall: 90.79% F1: 90.37%
Val   Loss: 0.3215 | Val Acc: 90.14%   | Precision: 90.21% Recall: 90.14% F1: 89.58%

Epoch: 63/150
Train Loss: 0.3081 | Train Acc: 90.62% | Precision: 90.57% Recall: 90.62% F1: 90.21%
Val   Loss: 0.3273 | Val Acc: 89.60%   | Precision: 89.55% Recall: 89.60% F1: 89.06%

Epoch: 64/150
Train Loss: 0.3004 | Train Acc: 90.99% | Precision: 90.96% Recall: 90.99% F1: 90.58%
Val   Loss: 0.3040 | Val Acc: 91.03%   | Precision: 90.92% Recall: 91.03% F1: 90.55%

Epoch: 65/150
Train Loss: 0.3054 | Train Acc: 90.90% | Precision: 90.86% Recall: 90.90% F1: 90.49%
Val   Loss: 0.3026 | Val Acc: 90.73%   | Precision: 90.70% Recall: 90.73% F1: 90.25%

Epoch: 66/150
Train Loss: 0.3033 | Train Acc: 90.80% | Precision: 90.77% Recall: 90.80% F1: 90.40%
Val   Loss: 0.2966 | Val Acc: 90.94%   | Precision: 91.04% Recall: 90.94% F1: 90.49%

Epoch: 67/150
Train Loss: 0.2958 | Train Acc: 91.08% | Precision: 91.05% Recall: 91.08% F1: 90.69%
Val   Loss: 0.2963 | Val Acc: 91.18%   | Precision: 91.12% Recall: 91.18% F1: 90.70%

Epoch: 68/150
Train Loss: 0.3119 | Train Acc: 90.72% | Precision: 90.67% Recall: 90.72% F1: 90.30%
Val   Loss: 0.3228 | Val Acc: 90.58%   | Precision: 90.55% Recall: 90.58% F1: 89.94%

Epoch: 69/150
Train Loss: 0.2924 | Train Acc: 91.34% | Precision: 91.32% Recall: 91.34% F1: 90.94%
Val   Loss: 0.3344 | Val Acc: 89.83%   | Precision: 89.87% Recall: 89.83% F1: 89.08%

Epoch: 70/150
Train Loss: 0.2890 | Train Acc: 91.31% | Precision: 91.29% Recall: 91.31% F1: 90.92%
Val   Loss: 0.3100 | Val Acc: 90.34%   | Precision: 90.23% Recall: 90.34% F1: 89.84%

Epoch: 71/150
Train Loss: 0.2910 | Train Acc: 91.42% | Precision: 91.42% Recall: 91.42% F1: 91.03%
Val   Loss: 0.2998 | Val Acc: 90.79%   | Precision: 90.63% Recall: 90.79% F1: 90.22%

Epoch: 72/150
Train Loss: 0.2851 | Train Acc: 91.54% | Precision: 91.51% Recall: 91.54% F1: 91.17%
Val   Loss: 0.2906 | Val Acc: 91.03%   | Precision: 91.02% Recall: 91.03% F1: 90.64%

Epoch: 73/150
Train Loss: 0.2964 | Train Acc: 91.05% | Precision: 91.00% Recall: 91.05% F1: 90.63%
Val   Loss: 0.2709 | Val Acc: 91.83%   | Precision: 91.78% Recall: 91.83% F1: 91.43%

Epoch: 74/150
Train Loss: 0.2830 | Train Acc: 91.51% | Precision: 91.50% Recall: 91.51% F1: 91.12%
Val   Loss: 0.2992 | Val Acc: 91.15%   | Precision: 91.08% Recall: 91.15% F1: 90.79%

Epoch: 75/150
Train Loss: 0.2688 | Train Acc: 92.03% | Precision: 92.02% Recall: 92.03% F1: 91.67%
Val   Loss: 0.3180 | Val Acc: 90.42%   | Precision: 90.34% Recall: 90.42% F1: 90.03%

Epoch: 76/150
Train Loss: 0.2706 | Train Acc: 91.97% | Precision: 91.95% Recall: 91.97% F1: 91.62%
Val   Loss: 0.2804 | Val Acc: 91.50%   | Precision: 91.46% Recall: 91.50% F1: 91.13%

Epoch: 77/150
Train Loss: 0.2671 | Train Acc: 92.02% | Precision: 91.99% Recall: 92.02% F1: 91.66%
Val   Loss: 0.2757 | Val Acc: 92.13%   | Precision: 91.99% Recall: 92.13% F1: 91.70%

Epoch: 78/150
Train Loss: 0.2681 | Train Acc: 92.05% | Precision: 92.00% Recall: 92.05% F1: 91.70%
Val   Loss: 0.3033 | Val Acc: 90.94%   | Precision: 90.98% Recall: 90.94% F1: 90.19%

Epoch: 79/150
Train Loss: 0.2703 | Train Acc: 91.85% | Precision: 91.80% Recall: 91.85% F1: 91.49%
Val   Loss: 0.2643 | Val Acc: 92.26%   | Precision: 92.13% Recall: 92.26% F1: 91.83%

Epoch: 80/150
Train Loss: 0.6468 | Train Acc: 79.19% | Precision: 77.78% Recall: 79.19% F1: 76.23%
Val   Loss: 0.5920 | Val Acc: 80.04%   | Precision: 80.04% Recall: 80.04% F1: 79.58%

Epoch: 81/150
Train Loss: 0.4299 | Train Acc: 86.72% | Precision: 86.26% Recall: 86.72% F1: 85.82%
Val   Loss: 0.3806 | Val Acc: 88.38%   | Precision: 88.42% Recall: 88.38% F1: 87.60%

Epoch: 82/150
Train Loss: 0.3537 | Train Acc: 89.63% | Precision: 89.55% Recall: 89.63% F1: 89.11%
Val   Loss: 0.3454 | Val Acc: 89.61%   | Precision: 89.62% Recall: 89.61% F1: 89.14%

Epoch: 83/150
Train Loss: 0.5472 | Train Acc: 82.93% | Precision: 82.44% Recall: 82.93% F1: 81.47%
Val   Loss: 0.4678 | Val Acc: 85.81%   | Precision: 85.76% Recall: 85.81% F1: 84.50%

Epoch: 84/150
Train Loss: 0.4164 | Train Acc: 87.64% | Precision: 87.57% Recall: 87.64% F1: 86.91%
Val   Loss: 0.3954 | Val Acc: 88.85%   | Precision: 88.93% Recall: 88.85% F1: 88.07%

Epoch: 85/150
Train Loss: 0.3704 | Train Acc: 89.12% | Precision: 89.13% Recall: 89.12% F1: 88.57%
Val   Loss: 0.3603 | Val Acc: 89.65%   | Precision: 89.59% Recall: 89.65% F1: 89.00%

Epoch: 86/150
Train Loss: 0.3441 | Train Acc: 89.75% | Precision: 89.70% Recall: 89.75% F1: 89.27%
Val   Loss: 0.3252 | Val Acc: 90.66%   | Precision: 90.52% Recall: 90.66% F1: 90.28%

Epoch: 87/150
Train Loss: 0.3152 | Train Acc: 90.54% | Precision: 90.47% Recall: 90.54% F1: 90.12%
Val   Loss: 0.3041 | Val Acc: 90.98%   | Precision: 90.90% Recall: 90.98% F1: 90.54%

Epoch: 88/150
Train Loss: 0.3079 | Train Acc: 90.94% | Precision: 90.86% Recall: 90.94% F1: 90.53%
Val   Loss: 0.3085 | Val Acc: 90.90%   | Precision: 90.77% Recall: 90.90% F1: 90.33%

Epoch: 89/150
Train Loss: 0.3105 | Train Acc: 90.85% | Precision: 90.76% Recall: 90.85% F1: 90.42%
Val   Loss: 0.2977 | Val Acc: 90.87%   | Precision: 90.74% Recall: 90.87% F1: 90.38%

Epoch: 90/150
Train Loss: 0.2909 | Train Acc: 91.45% | Precision: 91.37% Recall: 91.45% F1: 91.05%
Val   Loss: 0.2934 | Val Acc: 91.23%   | Precision: 91.25% Recall: 91.23% F1: 90.72%

Epoch: 91/150
Train Loss: 0.2880 | Train Acc: 91.49% | Precision: 91.42% Recall: 91.49% F1: 91.10%
Val   Loss: 0.2860 | Val Acc: 91.48%   | Precision: 91.38% Recall: 91.48% F1: 90.94%

Epoch: 92/150
Train Loss: 0.2860 | Train Acc: 91.55% | Precision: 91.45% Recall: 91.55% F1: 91.17%
Val   Loss: 0.2686 | Val Acc: 91.88%   | Precision: 91.73% Recall: 91.88% F1: 91.46%

Epoch: 93/150
Train Loss: 0.2765 | Train Acc: 91.87% | Precision: 91.80% Recall: 91.87% F1: 91.50%
Val   Loss: 0.2707 | Val Acc: 91.85%   | Precision: 91.81% Recall: 91.85% F1: 91.39%

Epoch: 94/150
Train Loss: 0.2686 | Train Acc: 92.05% | Precision: 91.98% Recall: 92.05% F1: 91.70%
Val   Loss: 0.2717 | Val Acc: 91.81%   | Precision: 91.63% Recall: 91.81% F1: 91.40%

Epoch: 95/150
Train Loss: 0.2596 | Train Acc: 92.37% | Precision: 92.29% Recall: 92.37% F1: 92.04%
Val   Loss: 0.2936 | Val Acc: 91.17%   | Precision: 91.10% Recall: 91.17% F1: 90.68%

Epoch: 96/150
Train Loss: 0.2596 | Train Acc: 92.41% | Precision: 92.32% Recall: 92.41% F1: 92.09%
Val   Loss: 0.2504 | Val Acc: 92.39%   | Precision: 92.24% Recall: 92.39% F1: 92.04%

Epoch: 97/150
Train Loss: 0.2562 | Train Acc: 92.45% | Precision: 92.39% Recall: 92.45% F1: 92.13%
Val   Loss: 0.2513 | Val Acc: 92.42%   | Precision: 92.29% Recall: 92.42% F1: 92.14%

Epoch: 98/150
Train Loss: 0.2926 | Train Acc: 91.41% | Precision: 91.31% Recall: 91.41% F1: 91.04%
Val   Loss: 0.2584 | Val Acc: 92.39%   | Precision: 92.40% Recall: 92.39% F1: 91.97%

Epoch: 99/150
Train Loss: 0.2543 | Train Acc: 92.54% | Precision: 92.47% Recall: 92.54% F1: 92.23%
Val   Loss: 0.2813 | Val Acc: 91.44%   | Precision: 91.30% Recall: 91.44% F1: 90.91%

Epoch: 100/150
Train Loss: 0.2503 | Train Acc: 92.62% | Precision: 92.55% Recall: 92.62% F1: 92.31%
Val   Loss: 0.2480 | Val Acc: 92.64%   | Precision: 92.50% Recall: 92.64% F1: 92.34%

Epoch: 101/150
Train Loss: 0.2458 | Train Acc: 92.80% | Precision: 92.74% Recall: 92.80% F1: 92.51%
Val   Loss: 0.2558 | Val Acc: 92.45%   | Precision: 92.26% Recall: 92.45% F1: 92.11%

Epoch: 102/150
Train Loss: 0.2414 | Train Acc: 92.89% | Precision: 92.82% Recall: 92.89% F1: 92.60%
Val   Loss: 0.2487 | Val Acc: 92.52%   | Precision: 92.37% Recall: 92.52% F1: 92.21%

Epoch: 103/150
Train Loss: 0.2726 | Train Acc: 91.85% | Precision: 91.72% Recall: 91.85% F1: 91.50%
Val   Loss: 0.3994 | Val Acc: 87.58%   | Precision: 87.51% Recall: 87.58% F1: 86.56%

Epoch: 104/150
Train Loss: 0.3016 | Train Acc: 91.22% | Precision: 91.20% Recall: 91.22% F1: 90.82%
Val   Loss: 0.2747 | Val Acc: 92.07%   | Precision: 92.00% Recall: 92.07% F1: 91.65%

Epoch: 105/150
Train Loss: 0.2532 | Train Acc: 92.56% | Precision: 92.50% Recall: 92.56% F1: 92.26%
Val   Loss: 0.2454 | Val Acc: 92.54%   | Precision: 92.42% Recall: 92.54% F1: 92.21%

Epoch: 106/150
Train Loss: 0.2374 | Train Acc: 93.04% | Precision: 92.97% Recall: 93.04% F1: 92.75%
Val   Loss: 0.2332 | Val Acc: 93.16%   | Precision: 93.04% Recall: 93.16% F1: 92.84%

Epoch: 107/150
Train Loss: 0.2308 | Train Acc: 93.21% | Precision: 93.16% Recall: 93.21% F1: 92.93%
Val   Loss: 0.2355 | Val Acc: 92.70%   | Precision: 92.62% Recall: 92.70% F1: 92.35%

Epoch: 108/150
Train Loss: 0.2242 | Train Acc: 93.35% | Precision: 93.30% Recall: 93.35% F1: 93.08%
Val   Loss: 0.2862 | Val Acc: 91.23%   | Precision: 90.99% Recall: 91.23% F1: 90.93%

Epoch: 109/150

wandb: Agent Starting Run: yox7k1mi with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.00018266352871623107
wandb: 	optimizer: adam
wandb: 	rnn_type: rnn
wandb: 	seq_len: 150
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.1076 | Train Acc: 64.72% | Precision: 51.83% Recall: 64.72% F1: 51.95%
Val   Loss: 0.9021 | Val Acc: 70.72%   | Precision: 58.47% Recall: 70.72% F1: 62.62%

Epoch: 2/150
Train Loss: 0.8186 | Train Acc: 71.04% | Precision: 62.10% Recall: 71.04% F1: 63.89%
Val   Loss: 0.7497 | Val Acc: 72.57%   | Precision: 67.20% Recall: 72.57% F1: 65.56%

Epoch: 3/150
Train Loss: 0.9721 | Train Acc: 69.98% | Precision: 64.65% Recall: 69.98% F1: 63.49%
Val   Loss: 1.1063 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1083 | Train Acc: 64.45% | Precision: 43.62% Recall: 64.45% F1: 50.66%
Val   Loss: 1.1175 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.0815 | Train Acc: 64.54% | Precision: 46.01% Recall: 64.54% F1: 50.86%
Val   Loss: 1.0462 | Val Acc: 64.64%   | Precision: 47.27% Recall: 64.64% F1: 53.50%

Epoch: 6/150
Train Loss: 0.9635 | Train Acc: 65.21% | Precision: 53.06% Recall: 65.21% F1: 55.77%
Val   Loss: 0.8664 | Val Acc: 68.44%   | Precision: 55.90% Recall: 68.44% F1: 60.81%

Epoch: 7/150
Train Loss: 0.9513 | Train Acc: 68.68% | Precision: 56.46% Recall: 68.68% F1: 60.71%
Val   Loss: 1.1172 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 8/150
Train Loss: 1.1145 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1002 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 9/150
Train Loss: 1.0859 | Train Acc: 64.76% | Precision: 47.58% Recall: 64.76% F1: 52.18%
Val   Loss: 1.0535 | Val Acc: 65.16%   | Precision: 48.09% Recall: 65.16% F1: 54.18%

Epoch: 10/150
Train Loss: 0.9607 | Train Acc: 66.66% | Precision: 55.89% Recall: 66.66% F1: 58.53%
Val   Loss: 0.8793 | Val Acc: 70.78%   | Precision: 59.93% Recall: 70.78% F1: 64.47%

Epoch: 11/150
Train Loss: 0.9345 | Train Acc: 69.03% | Precision: 59.16% Recall: 69.03% F1: 62.17%
Val   Loss: 1.0985 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 12/150
Train Loss: 1.0828 | Train Acc: 64.07% | Precision: 43.99% Recall: 64.07% F1: 50.77%
Val   Loss: 1.0712 | Val Acc: 63.63%   | Precision: 43.40% Recall: 63.63% F1: 50.65%

Epoch: 13/150
Train Loss: 1.0545 | Train Acc: 64.68% | Precision: 47.35% Recall: 64.68% F1: 52.92%
Val   Loss: 1.0381 | Val Acc: 64.34%   | Precision: 41.62% Recall: 64.34% F1: 50.54%

Epoch: 14/150
Train Loss: 0.9240 | Train Acc: 68.42% | Precision: 58.84% Recall: 68.42% F1: 60.90%
Val   Loss: 0.8229 | Val Acc: 73.21%   | Precision: 62.20% Recall: 73.21% F1: 66.63%

Epoch: 15/150
Train Loss: 0.7967 | Train Acc: 72.86% | Precision: 62.17% Recall: 72.86% F1: 66.49%
Val   Loss: 0.7764 | Val Acc: 74.70%   | Precision: 64.05% Recall: 74.70% F1: 68.38%

Epoch: 16/150
Train Loss: 0.7650 | Train Acc: 73.30% | Precision: 69.13% Recall: 73.30% F1: 66.88%
Val   Loss: 0.7487 | Val Acc: 74.40%   | Precision: 63.85% Recall: 74.40% F1: 68.25%

Epoch: 17/150
Train Loss: 0.7377 | Train Acc: 74.73% | Precision: 70.60% Recall: 74.73% F1: 68.43%
Val   Loss: 0.7046 | Val Acc: 76.44%   | Precision: 65.78% Recall: 76.44% F1: 70.35%

Epoch: 18/150
Train Loss: 0.6864 | Train Acc: 77.56% | Precision: 71.50% Recall: 77.56% F1: 71.64%
Val   Loss: 0.6862 | Val Acc: 78.38%   | Precision: 68.43% Recall: 78.38% F1: 72.02%

Epoch: 19/150
Train Loss: 0.7875 | Train Acc: 73.91% | Precision: 72.72% Recall: 73.91% F1: 67.14%
Val   Loss: 0.7394 | Val Acc: 74.61%   | Precision: 63.47% Recall: 74.61% F1: 68.33%

Epoch: 20/150
Train Loss: 0.9307 | Train Acc: 68.09% | Precision: 58.17% Recall: 68.09% F1: 60.48%
Val   Loss: 0.9020 | Val Acc: 69.06%   | Precision: 57.17% Recall: 69.06% F1: 61.83%

Epoch: 21/150
Train Loss: 0.8454 | Train Acc: 70.18% | Precision: 64.56% Recall: 70.18% F1: 62.86%
Val   Loss: 0.8085 | Val Acc: 71.49%   | Precision: 59.92% Recall: 71.49% F1: 64.37%

Epoch: 22/150
Train Loss: 0.7904 | Train Acc: 72.43% | Precision: 66.24% Recall: 72.43% F1: 65.85%
Val   Loss: 0.7672 | Val Acc: 73.70%   | Precision: 69.02% Recall: 73.70% F1: 67.18%

Epoch: 23/150
Train Loss: 0.7513 | Train Acc: 74.81% | Precision: 68.04% Recall: 74.81% F1: 68.75%
Val   Loss: 0.7355 | Val Acc: 75.53%   | Precision: 71.21% Recall: 75.53% F1: 69.05%

Epoch: 24/150
Train Loss: 0.7205 | Train Acc: 76.50% | Precision: 69.48% Recall: 76.50% F1: 70.69%
Val   Loss: 0.7114 | Val Acc: 76.89%   | Precision: 71.15% Recall: 76.89% F1: 71.69%

Epoch: 25/150
Train Loss: 0.6842 | Train Acc: 77.63% | Precision: 71.33% Recall: 77.63% F1: 71.71%
Val   Loss: 0.6549 | Val Acc: 78.82%   | Precision: 70.42% Recall: 78.82% F1: 72.60%

Epoch: 26/150
Train Loss: 0.6206 | Train Acc: 79.91% | Precision: 78.23% Recall: 79.91% F1: 75.05%
Val   Loss: 0.6173 | Val Acc: 81.43%   | Precision: 80.82% Recall: 81.43% F1: 78.73%

Epoch: 27/150
Train Loss: 0.5895 | Train Acc: 80.92% | Precision: 79.91% Recall: 80.92% F1: 77.34%
Val   Loss: 0.5704 | Val Acc: 82.48%   | Precision: 81.63% Recall: 82.48% F1: 80.14%

Epoch: 28/150
Train Loss: 0.5933 | Train Acc: 81.50% | Precision: 80.50% Recall: 81.50% F1: 78.87%
Val   Loss: 0.7359 | Val Acc: 75.93%   | Precision: 64.94% Recall: 75.93% F1: 68.66%

Epoch: 29/150
Train Loss: 0.6206 | Train Acc: 79.75% | Precision: 78.47% Recall: 79.75% F1: 75.75%
Val   Loss: 0.5689 | Val Acc: 80.52%   | Precision: 81.36% Recall: 80.52% F1: 75.58%

Epoch: 30/150
Train Loss: 0.5178 | Train Acc: 84.82% | Precision: 84.39% Recall: 84.82% F1: 83.34%
Val   Loss: 0.4873 | Val Acc: 86.28%   | Precision: 86.19% Recall: 86.28% F1: 85.06%

Epoch: 31/150
Train Loss: 0.4773 | Train Acc: 85.99% | Precision: 85.74% Recall: 85.99% F1: 84.90%
Val   Loss: 0.4644 | Val Acc: 86.11%   | Precision: 85.76% Recall: 86.11% F1: 84.73%

Epoch: 32/150
Train Loss: 0.8026 | Train Acc: 75.36% | Precision: 74.93% Recall: 75.36% F1: 72.30%
Val   Loss: 1.0383 | Val Acc: 66.86%   | Precision: 55.65% Recall: 66.86% F1: 60.27%

Epoch: 33/150
Train Loss: 0.7385 | Train Acc: 75.80% | Precision: 73.10% Recall: 75.80% F1: 70.79%
Val   Loss: 0.5797 | Val Acc: 82.31%   | Precision: 81.10% Recall: 82.31% F1: 80.80%

Epoch: 34/150
Train Loss: 0.5231 | Train Acc: 84.36% | Precision: 83.78% Recall: 84.36% F1: 82.87%
Val   Loss: 0.5089 | Val Acc: 84.10%   | Precision: 83.80% Recall: 84.10% F1: 81.73%

Epoch: 35/150
Train Loss: 0.4738 | Train Acc: 86.25% | Precision: 85.97% Recall: 86.25% F1: 85.20%
Val   Loss: 0.4814 | Val Acc: 85.17%   | Precision: 84.64% Recall: 85.17% F1: 83.64%

Epoch: 36/150
Train Loss: 0.4472 | Train Acc: 86.95% | Precision: 86.79% Recall: 86.95% F1: 86.01%
Val   Loss: 0.4458 | Val Acc: 86.55%   | Precision: 86.23% Recall: 86.55% F1: 85.60%

Epoch: 37/150
Train Loss: 0.4897 | Train Acc: 85.45% | Precision: 85.35% Recall: 85.45% F1: 84.42%
Val   Loss: 0.9511 | Val Acc: 73.66%   | Precision: 67.40% Recall: 73.66% F1: 68.52%

Epoch: 38/150
Train Loss: 0.7262 | Train Acc: 75.98% | Precision: 69.50% Recall: 75.98% F1: 70.74%
Val   Loss: 0.6694 | Val Acc: 78.91%   | Precision: 72.27% Recall: 78.91% F1: 75.02%

Epoch: 39/150
Train Loss: 0.6100 | Train Acc: 80.52% | Precision: 80.19% Recall: 80.52% F1: 76.19%
Val   Loss: 0.5679 | Val Acc: 82.92%   | Precision: 82.88% Recall: 82.92% F1: 79.80%

Epoch: 40/150
Train Loss: 0.5327 | Train Acc: 84.00% | Precision: 83.38% Recall: 84.00% F1: 82.22%
Val   Loss: 0.5818 | Val Acc: 82.21%   | Precision: 80.58% Recall: 82.21% F1: 80.25%

Epoch: 41/150
Train Loss: 0.5461 | Train Acc: 83.12% | Precision: 82.65% Recall: 83.12% F1: 81.22%
Val   Loss: 0.5216 | Val Acc: 83.75%   | Precision: 83.40% Recall: 83.75% F1: 80.54%

Epoch: 42/150
Train Loss: 0.4989 | Train Acc: 85.07% | Precision: 84.87% Recall: 85.07% F1: 83.74%
Val   Loss: 0.4848 | Val Acc: 85.38%   | Precision: 85.77% Recall: 85.38% F1: 84.58%

Epoch: 43/150
Train Loss: 0.4517 | Train Acc: 86.55% | Precision: 86.44% Recall: 86.55% F1: 85.68%
Val   Loss: 0.4323 | Val Acc: 87.14%   | Precision: 87.29% Recall: 87.14% F1: 86.13%

Epoch: 44/150
Train Loss: 0.4237 | Train Acc: 87.47% | Precision: 87.46% Recall: 87.47% F1: 86.70%
Val   Loss: 0.4313 | Val Acc: 86.39%   | Precision: 86.62% Recall: 86.39% F1: 84.99%

Epoch: 45/150
Train Loss: 0.4082 | Train Acc: 87.87% | Precision: 87.85% Recall: 87.87% F1: 87.16%
Val   Loss: 0.4426 | Val Acc: 86.16%   | Precision: 86.02% Recall: 86.16% F1: 84.53%

Epoch: 46/150
Train Loss: 0.3970 | Train Acc: 88.10% | Precision: 88.12% Recall: 88.10% F1: 87.41%
Val   Loss: 0.4433 | Val Acc: 85.40%   | Precision: 86.61% Recall: 85.40% F1: 85.47%

Epoch: 47/150
Train Loss: 0.5986 | Train Acc: 81.40% | Precision: 81.13% Recall: 81.40% F1: 78.79%
Val   Loss: 0.5557 | Val Acc: 82.36%   | Precision: 77.30% Recall: 82.36% F1: 78.60%

Epoch: 48/150
Train Loss: 0.4908 | Train Acc: 86.04% | Precision: 86.14% Recall: 86.04% F1: 84.89%
Val   Loss: 0.4680 | Val Acc: 86.14%   | Precision: 86.21% Recall: 86.14% F1: 84.96%

Epoch: 49/150
Train Loss: 0.4419 | Train Acc: 87.27% | Precision: 87.31% Recall: 87.27% F1: 86.43%
Val   Loss: 0.4303 | Val Acc: 87.47%   | Precision: 87.36% Recall: 87.47% F1: 86.65%

Epoch: 50/150
Train Loss: 0.4184 | Train Acc: 87.82% | Precision: 87.90% Recall: 87.82% F1: 87.04%
Val   Loss: 0.4158 | Val Acc: 88.06%   | Precision: 87.95% Recall: 88.06% F1: 87.33%

Epoch: 51/150
Train Loss: 0.4068 | Train Acc: 88.06% | Precision: 88.12% Recall: 88.06% F1: 87.34%
Val   Loss: 0.3929 | Val Acc: 88.12%   | Precision: 88.26% Recall: 88.12% F1: 87.33%

Epoch: 52/150
Train Loss: 0.3962 | Train Acc: 88.27% | Precision: 88.33% Recall: 88.27% F1: 87.57%
Val   Loss: 0.3943 | Val Acc: 87.96%   | Precision: 88.14% Recall: 87.96% F1: 87.20%

Epoch: 53/150
Train Loss: 0.3903 | Train Acc: 88.35% | Precision: 88.38% Recall: 88.35% F1: 87.69%
Val   Loss: 0.3874 | Val Acc: 88.46%   | Precision: 88.39% Recall: 88.46% F1: 87.69%

Epoch: 54/150
Train Loss: 0.3818 | Train Acc: 88.60% | Precision: 88.65% Recall: 88.60% F1: 87.97%
Val   Loss: 0.3785 | Val Acc: 88.49%   | Precision: 88.48% Recall: 88.49% F1: 87.69%

Epoch: 55/150
Train Loss: 0.3718 | Train Acc: 88.82% | Precision: 88.85% Recall: 88.82% F1: 88.22%
Val   Loss: 0.3560 | Val Acc: 89.25%   | Precision: 89.26% Recall: 89.25% F1: 88.60%

Epoch: 56/150
Train Loss: 0.3821 | Train Acc: 88.45% | Precision: 88.44% Recall: 88.45% F1: 87.83%
Val   Loss: 0.3569 | Val Acc: 89.27%   | Precision: 89.35% Recall: 89.27% F1: 88.61%

Epoch: 57/150
Train Loss: 0.3694 | Train Acc: 88.76% | Precision: 88.76% Recall: 88.76% F1: 88.16%
Val   Loss: 0.3509 | Val Acc: 89.13%   | Precision: 89.02% Recall: 89.13% F1: 88.55%

Epoch: 58/150
Train Loss: 0.6259 | Train Acc: 79.73% | Precision: 78.80% Recall: 79.73% F1: 77.59%
Val   Loss: 0.5346 | Val Acc: 83.30%   | Precision: 83.06% Recall: 83.30% F1: 81.30%

Epoch: 59/150
Train Loss: 0.5551 | Train Acc: 82.37% | Precision: 81.85% Recall: 82.37% F1: 80.60%
Val   Loss: 0.5085 | Val Acc: 84.01%   | Precision: 83.59% Recall: 84.01% F1: 82.26%

Epoch: 60/150
Train Loss: 0.5628 | Train Acc: 82.53% | Precision: 81.92% Recall: 82.53% F1: 80.74%
Val   Loss: 0.5050 | Val Acc: 85.56%   | Precision: 85.46% Recall: 85.56% F1: 84.39%

Epoch: 61/150
Train Loss: 0.4528 | Train Acc: 86.98% | Precision: 86.97% Recall: 86.98% F1: 86.12%
Val   Loss: 0.4612 | Val Acc: 86.63%   | Precision: 86.46% Recall: 86.63% F1: 85.98%

Epoch: 62/150
Train Loss: 0.4216 | Train Acc: 87.82% | Precision: 87.88% Recall: 87.82% F1: 87.07%
Val   Loss: 0.4262 | Val Acc: 87.57%   | Precision: 87.83% Recall: 87.57% F1: 86.56%

Epoch: 63/150
Train Loss: 0.4018 | Train Acc: 88.30% | Precision: 88.39% Recall: 88.30% F1: 87.60%
Val   Loss: 0.4130 | Val Acc: 87.91%   | Precision: 87.83% Recall: 87.91% F1: 87.06%

Epoch: 64/150
Train Loss: 0.3927 | Train Acc: 88.38% | Precision: 88.42% Recall: 88.38% F1: 87.72%
Val   Loss: 0.3920 | Val Acc: 88.43%   | Precision: 88.43% Recall: 88.43% F1: 87.69%

Epoch: 65/150
Train Loss: 0.3844 | Train Acc: 88.61% | Precision: 88.66% Recall: 88.61% F1: 87.98%
Val   Loss: 0.3904 | Val Acc: 88.07%   | Precision: 88.13% Recall: 88.07% F1: 87.49%

Epoch: 66/150
Train Loss: 0.3678 | Train Acc: 88.97% | Precision: 88.98% Recall: 88.97% F1: 88.39%
Val   Loss: 0.3677 | Val Acc: 88.99%   | Precision: 88.84% Recall: 88.99% F1: 88.34%

Epoch: 67/150
Train Loss: 0.3634 | Train Acc: 89.00% | Precision: 89.00% Recall: 89.00% F1: 88.43%
Val   Loss: 0.3668 | Val Acc: 88.86%   | Precision: 88.90% Recall: 88.86% F1: 88.30%

Epoch: 68/150
Train Loss: 0.3542 | Train Acc: 89.27% | Precision: 89.26% Recall: 89.27% F1: 88.72%
Val   Loss: 0.3558 | Val Acc: 88.83%   | Precision: 88.92% Recall: 88.83% F1: 88.40%

Epoch: 69/150
Train Loss: 0.3506 | Train Acc: 89.23% | Precision: 89.20% Recall: 89.23% F1: 88.69%
Val   Loss: 0.3688 | Val Acc: 88.45%   | Precision: 88.30% Recall: 88.45% F1: 87.81%

Epoch: 70/150
Train Loss: 0.3459 | Train Acc: 89.37% | Precision: 89.35% Recall: 89.37% F1: 88.85%
Val   Loss: 0.3845 | Val Acc: 87.97%   | Precision: 87.82% Recall: 87.97% F1: 87.25%

Epoch: 71/150
Train Loss: 0.3952 | Train Acc: 87.72% | Precision: 87.70% Recall: 87.72% F1: 87.15%
Val   Loss: 1.2740 | Val Acc: 64.97%   | Precision: 47.83% Recall: 64.97% F1: 53.72%

Epoch: 72/150
Train Loss: 0.6409 | Train Acc: 79.26% | Precision: 78.07% Recall: 79.26% F1: 76.75%
Val   Loss: 0.4911 | Val Acc: 85.39%   | Precision: 85.10% Recall: 85.39% F1: 84.14%

Epoch: 73/150
Train Loss: 0.5100 | Train Acc: 84.53% | Precision: 84.06% Recall: 84.53% F1: 83.36%
Val   Loss: 0.5041 | Val Acc: 84.41%   | Precision: 83.83% Recall: 84.41% F1: 82.74%

Epoch: 74/150
Train Loss: 0.4755 | Train Acc: 85.83% | Precision: 85.57% Recall: 85.83% F1: 84.94%
Val   Loss: 0.5295 | Val Acc: 84.74%   | Precision: 85.07% Recall: 84.74% F1: 84.12%

Epoch: 75/150
Train Loss: 0.5964 | Train Acc: 81.76% | Precision: 81.22% Recall: 81.76% F1: 80.14%
Val   Loss: 0.6247 | Val Acc: 79.30%   | Precision: 73.15% Recall: 79.30% F1: 74.20%

Epoch: 76/150
Train Loss: 0.4729 | Train Acc: 85.71% | Precision: 85.48% Recall: 85.71% F1: 84.34%
Val   Loss: 0.4228 | Val Acc: 87.47%   | Precision: 87.09% Recall: 87.47% F1: 86.67%

Epoch: 77/150
Train Loss: 0.3909 | Train Acc: 88.41% | Precision: 88.46% Recall: 88.41% F1: 87.76%
Val   Loss: 0.3912 | Val Acc: 87.92%   | Precision: 88.40% Recall: 87.92% F1: 87.24%

Epoch: 78/150
Train Loss: 0.3711 | Train Acc: 88.88% | Precision: 88.94% Recall: 88.88% F1: 88.28%
Val   Loss: 0.3588 | Val Acc: 88.87%   | Precision: 88.99% Recall: 88.87% F1: 88.17%

Epoch: 79/150
Train Loss: 0.3556 | Train Acc: 89.23% | Precision: 89.26% Recall: 89.23% F1: 88.68%
Val   Loss: 0.3505 | Val Acc: 89.54%   | Precision: 89.33% Recall: 89.54% F1: 89.18%

Epoch: 80/150
Train Loss: 0.3433 | Train Acc: 89.51% | Precision: 89.52% Recall: 89.51% F1: 88.98%
Val   Loss: 0.3424 | Val Acc: 89.14%   | Precision: 89.29% Recall: 89.14% F1: 88.48%

Epoch: 81/150
Train Loss: 0.3437 | Train Acc: 89.49% | Precision: 89.46% Recall: 89.49% F1: 88.96%
Val   Loss: 0.3597 | Val Acc: 88.67%   | Precision: 88.77% Recall: 88.67% F1: 87.84%

Epoch: 82/150
Train Loss: 0.3321 | Train Acc: 89.89% | Precision: 89.85% Recall: 89.89% F1: 89.40%
Val   Loss: 0.3414 | Val Acc: 89.63%   | Precision: 89.49% Recall: 89.63% F1: 89.26%

Epoch: 83/150
Train Loss: 0.3239 | Train Acc: 90.01% | Precision: 89.96% Recall: 90.01% F1: 89.50%
Val   Loss: 0.3435 | Val Acc: 89.33%   | Precision: 89.48% Recall: 89.33% F1: 88.66%

Epoch: 84/150
Train Loss: 0.3220 | Train Acc: 89.98% | Precision: 89.94% Recall: 89.98% F1: 89.48%
Val   Loss: 0.3205 | Val Acc: 89.60%   | Precision: 89.44% Recall: 89.60% F1: 89.19%

Epoch: 85/150
Train Loss: 0.3150 | Train Acc: 90.20% | Precision: 90.14% Recall: 90.20% F1: 89.71%
Val   Loss: 0.3494 | Val Acc: 89.31%   | Precision: 89.12% Recall: 89.31% F1: 88.44%

Epoch: 86/150
Train Loss: 0.3118 | Train Acc: 90.33% | Precision: 90.27% Recall: 90.33% F1: 89.86%
Val   Loss: 0.3234 | Val Acc: 89.64%   | Precision: 89.69% Recall: 89.64% F1: 88.94%

Epoch: 87/150
Train Loss: 0.3031 | Train Acc: 90.67% | Precision: 90.61% Recall: 90.67% F1: 90.21%
Val   Loss: 0.3009 | Val Acc: 90.62%   | Precision: 90.57% Recall: 90.62% F1: 90.11%

Epoch: 88/150
Train Loss: 0.2951 | Train Acc: 90.82% | Precision: 90.74% Recall: 90.82% F1: 90.37%
Val   Loss: 0.3005 | Val Acc: 90.63%   | Precision: 90.45% Recall: 90.63% F1: 90.17%

Epoch: 89/150
Train Loss: 0.2897 | Train Acc: 90.96% | Precision: 90.87% Recall: 90.96% F1: 90.52%
Val   Loss: 0.2765 | Val Acc: 91.35%   | Precision: 91.27% Recall: 91.35% F1: 90.92%

Epoch: 90/150
Train Loss: 0.2886 | Train Acc: 90.95% | Precision: 90.87% Recall: 90.95% F1: 90.50%
Val   Loss: 0.2664 | Val Acc: 91.61%   | Precision: 91.62% Recall: 91.61% F1: 91.06%

Epoch: 91/150
Train Loss: 0.2835 | Train Acc: 91.09% | Precision: 91.00% Recall: 91.09% F1: 90.67%
Val   Loss: 0.3259 | Val Acc: 89.60%   | Precision: 89.51% Recall: 89.60% F1: 89.01%

Epoch: 92/150
Train Loss: 0.3058 | Train Acc: 90.43% | Precision: 90.32% Recall: 90.43% F1: 89.95%
Val   Loss: 0.2969 | Val Acc: 90.79%   | Precision: 90.86% Recall: 90.79% F1: 90.09%

Epoch: 93/150
Train Loss: 0.2802 | Train Acc: 91.28% | Precision: 91.18% Recall: 91.28% F1: 90.87%
Val   Loss: 0.3492 | Val Acc: 88.92%   | Precision: 88.65% Recall: 88.92% F1: 88.04%

Epoch: 94/150
Train Loss: 0.2691 | Train Acc: 91.64% | Precision: 91.53% Recall: 91.64% F1: 91.25%
Val   Loss: 0.3180 | Val Acc: 89.62%   | Precision: 89.50% Recall: 89.62% F1: 89.46%

Epoch: 95/150
Train Loss: 0.2889 | Train Acc: 91.07% | Precision: 90.96% Recall: 91.07% F1: 90.64%
Val   Loss: 0.2717 | Val Acc: 91.85%   | Precision: 91.61% Recall: 91.85% F1: 91.65%

Epoch: 96/150
Train Loss: 0.3535 | Train Acc: 89.36% | Precision: 89.33% Recall: 89.36% F1: 88.76%
Val   Loss: 0.3135 | Val Acc: 90.36%   | Precision: 90.28% Recall: 90.36% F1: 89.73%

Epoch: 97/150
Train Loss: 0.3337 | Train Acc: 89.75% | Precision: 89.74% Recall: 89.75% F1: 89.16%
Val   Loss: 0.3099 | Val Acc: 90.19%   | Precision: 90.34% Recall: 90.19% F1: 89.30%

Epoch: 98/150
Train Loss: 0.2895 | Train Acc: 91.00% | Precision: 90.94% Recall: 91.00% F1: 90.53%
Val   Loss: 0.2953 | Val Acc: 90.79%   | Precision: 90.70% Recall: 90.79% F1: 90.23%

Epoch: 99/150
Train Loss: 0.2770 | Train Acc: 91.43% | Precision: 91.33% Recall: 91.43% F1: 91.02%
Val   Loss: 0.2628 | Val Acc: 91.86%   | Precision: 91.77% Recall: 91.86% F1: 91.39%

Epoch: 100/150
Train Loss: 0.5557 | Train Acc: 83.63% | Precision: 83.33% Recall: 83.63% F1: 82.68%
Val   Loss: 0.9745 | Val Acc: 64.58%   | Precision: 58.43% Recall: 64.58% F1: 54.52%

Epoch: 101/150
Train Loss: 0.9700 | Train Acc: 67.84% | Precision: 60.05% Recall: 67.84% F1: 60.83%
Val   Loss: 0.8564 | Val Acc: 72.27%   | Precision: 64.44% Recall: 72.27% F1: 66.46%

Epoch: 102/150
Train Loss: 0.7447 | Train Acc: 75.10% | Precision: 70.89% Recall: 75.10% F1: 70.50%
Val   Loss: 0.5927 | Val Acc: 80.96%   | Precision: 78.47% Recall: 80.96% F1: 78.18%

Epoch: 103/150
Train Loss: 0.6934 | Train Acc: 77.77% | Precision: 75.95% Recall: 77.77% F1: 74.36%
Val   Loss: 0.8406 | Val Acc: 72.86%   | Precision: 65.65% Recall: 72.86% F1: 68.76%

Epoch: 104/150
Train Loss: 0.5934 | Train Acc: 80.72% | Precision: 79.05% Recall: 80.72% F1: 77.91%
Val   Loss: 0.5176 | Val Acc: 84.63%   | Precision: 84.06% Recall: 84.63% F1: 83.30%

Epoch: 105/150
Train Loss: 0.5173 | Train Acc: 84.67% | Precision: 84.20% Recall: 84.67% F1: 83.35%
Val   Loss: 0.5269 | Val Acc: 84.56%   | Precision: 84.21% Recall: 84.56% F1: 83.64%

Epoch: 106/150
Train Loss: 0.4927 | Train Acc: 85.60% | Precision: 85.20% Recall: 85.60% F1: 84.60%
Val   Loss: 0.4716 | Val Acc: 85.76%   | Precision: 85.34% Recall: 85.76% F1: 84.55%

Epoch: 107/150
Train Loss: 0.6092 | Train Acc: 80.85% | Precision: 80.57% Recall: 80.85% F1: 78.77%
Val   Loss: 0.6178 | Val Acc: 80.72%   | Precision: 81.51% Recall: 80.72% F1: 75.90%

Epoch: 108/150
Train Loss: 0.4688 | Train Acc: 85.90% | Precision: 85.74% Recall: 85.90% F1: 84.69%
Val   Loss: 0.4021 | Val Acc: 87.79%   | Precision: 87.64% Recall: 87.79% F1: 87.02%

Epoch: 109/150

wandb: Agent Starting Run: l13koc4t with config:
wandb: 	batch_size: 128
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.0005963789138837363
wandb: 	optimizer: adam
wandb: 	rnn_type: rnn
wandb: 	seq_len: 150
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.2173 | Train Acc: 62.48% | Precision: 45.36% Recall: 62.48% F1: 50.63%
Val   Loss: 1.1138 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.1358 | Train Acc: 64.36% | Precision: 46.32% Recall: 64.36% F1: 52.41%
Val   Loss: 1.0958 | Val Acc: 65.17%   | Precision: 48.12% Recall: 65.17% F1: 54.50%

Epoch: 3/150
Train Loss: 1.0908 | Train Acc: 65.36% | Precision: 48.37% Recall: 65.36% F1: 54.67%
Val   Loss: 1.0998 | Val Acc: 65.14%   | Precision: 48.08% Recall: 65.14% F1: 54.48%

Epoch: 4/150
Train Loss: 1.0860 | Train Acc: 65.11% | Precision: 51.37% Recall: 65.11% F1: 54.22%
Val   Loss: 1.0945 | Val Acc: 65.35%   | Precision: 48.35% Recall: 65.35% F1: 54.55%

Epoch: 5/150
Train Loss: 1.0835 | Train Acc: 64.76% | Precision: 54.99% Recall: 64.76% F1: 54.04%
Val   Loss: 1.0434 | Val Acc: 64.60%   | Precision: 48.38% Recall: 64.60% F1: 54.26%

Epoch: 6/150
Train Loss: 0.9442 | Train Acc: 67.41% | Precision: 60.65% Recall: 67.41% F1: 59.51%
Val   Loss: 0.7757 | Val Acc: 73.15%   | Precision: 61.26% Recall: 73.15% F1: 65.99%

Epoch: 7/150
Train Loss: 0.7870 | Train Acc: 72.95% | Precision: 65.57% Recall: 72.95% F1: 66.17%
Val   Loss: 0.8126 | Val Acc: 73.93%   | Precision: 66.64% Recall: 73.93% F1: 69.22%

Epoch: 8/150
Train Loss: 0.8058 | Train Acc: 72.15% | Precision: 64.95% Recall: 72.15% F1: 65.52%
Val   Loss: 0.9641 | Val Acc: 64.68%   | Precision: 51.31% Recall: 64.68% F1: 52.39%

Epoch: 9/150
Train Loss: 0.7641 | Train Acc: 73.98% | Precision: 66.66% Recall: 73.98% F1: 67.50%
Val   Loss: 0.7268 | Val Acc: 78.20%   | Precision: 74.57% Recall: 78.20% F1: 72.03%

Epoch: 10/150
Train Loss: 0.8017 | Train Acc: 72.65% | Precision: 65.17% Recall: 72.65% F1: 66.65%
Val   Loss: 0.7765 | Val Acc: 73.87%   | Precision: 66.69% Recall: 73.87% F1: 68.47%

Epoch: 11/150
Train Loss: 0.7316 | Train Acc: 74.97% | Precision: 72.01% Recall: 74.97% F1: 69.04%
Val   Loss: 0.6892 | Val Acc: 76.25%   | Precision: 71.65% Recall: 76.25% F1: 70.12%

Epoch: 12/150
Train Loss: 0.7004 | Train Acc: 76.59% | Precision: 70.47% Recall: 76.59% F1: 70.93%
Val   Loss: 0.6763 | Val Acc: 77.56%   | Precision: 72.73% Recall: 77.56% F1: 72.76%

Epoch: 13/150
Train Loss: 0.8132 | Train Acc: 71.24% | Precision: 64.45% Recall: 71.24% F1: 65.12%
Val   Loss: 0.7372 | Val Acc: 73.11%   | Precision: 63.28% Recall: 73.11% F1: 66.78%

Epoch: 14/150
Train Loss: 0.7407 | Train Acc: 74.07% | Precision: 67.54% Recall: 74.07% F1: 67.59%
Val   Loss: 0.7544 | Val Acc: 74.22%   | Precision: 67.14% Recall: 74.22% F1: 67.89%

Epoch: 15/150
Train Loss: 0.7141 | Train Acc: 75.70% | Precision: 69.73% Recall: 75.70% F1: 69.71%
Val   Loss: 0.8105 | Val Acc: 70.97%   | Precision: 60.45% Recall: 70.97% F1: 62.87%

Epoch: 16/150
Train Loss: 0.6761 | Train Acc: 77.21% | Precision: 74.81% Recall: 77.21% F1: 71.55%
Val   Loss: 0.7983 | Val Acc: 69.27%   | Precision: 63.11% Recall: 69.27% F1: 65.06%

Epoch: 17/150
Train Loss: 0.9049 | Train Acc: 67.96% | Precision: 59.28% Recall: 67.96% F1: 61.05%
Val   Loss: 0.7901 | Val Acc: 72.18%   | Precision: 61.14% Recall: 72.18% F1: 65.71%

Epoch: 18/150
Train Loss: 0.8601 | Train Acc: 70.71% | Precision: 63.00% Recall: 70.71% F1: 64.60%
Val   Loss: 0.8311 | Val Acc: 72.00%   | Precision: 58.92% Recall: 72.00% F1: 63.84%

Epoch: 19/150
Train Loss: 0.8450 | Train Acc: 73.11% | Precision: 65.80% Recall: 73.11% F1: 67.77%
Val   Loss: 1.2642 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 20/150
Train Loss: 1.1042 | Train Acc: 64.52% | Precision: 44.53% Recall: 64.52% F1: 50.69%
Val   Loss: 1.0554 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 21/150
Train Loss: 0.9565 | Train Acc: 66.29% | Precision: 54.12% Recall: 66.29% F1: 57.05%
Val   Loss: 0.8363 | Val Acc: 73.34%   | Precision: 62.81% Recall: 73.34% F1: 66.50%

Epoch: 22/150
Train Loss: 0.9383 | Train Acc: 68.31% | Precision: 57.80% Recall: 68.31% F1: 60.32%
Val   Loss: 0.8796 | Val Acc: 71.13%   | Precision: 60.87% Recall: 71.13% F1: 64.46%

Epoch: 23/150
Train Loss: 0.8600 | Train Acc: 71.51% | Precision: 67.27% Recall: 71.51% F1: 65.08%
Val   Loss: 0.8822 | Val Acc: 72.65%   | Precision: 64.55% Recall: 72.65% F1: 65.34%

Epoch: 24/150
Train Loss: 0.7980 | Train Acc: 72.84% | Precision: 66.14% Recall: 72.84% F1: 66.65%
Val   Loss: 0.7573 | Val Acc: 72.92%   | Precision: 62.32% Recall: 72.92% F1: 66.34%

Epoch: 25/150
Train Loss: 0.7560 | Train Acc: 74.42% | Precision: 68.34% Recall: 74.42% F1: 68.43%
Val   Loss: 0.7878 | Val Acc: 72.85%   | Precision: 62.14% Recall: 72.85% F1: 66.63%

Epoch: 26/150
Train Loss: 0.9129 | Train Acc: 67.92% | Precision: 62.28% Recall: 67.92% F1: 60.68%
Val   Loss: 0.8240 | Val Acc: 72.37%   | Precision: 61.58% Recall: 72.37% F1: 66.05%

Epoch: 27/150
Train Loss: 0.8049 | Train Acc: 71.85% | Precision: 64.07% Recall: 71.85% F1: 65.80%
Val   Loss: 0.7888 | Val Acc: 71.15%   | Precision: 59.73% Recall: 71.15% F1: 63.37%

Epoch: 28/150
Train Loss: 0.8113 | Train Acc: 71.36% | Precision: 63.50% Recall: 71.36% F1: 65.38%
Val   Loss: 0.7909 | Val Acc: 71.84%   | Precision: 63.75% Recall: 71.84% F1: 62.85%

Epoch: 29/150
Train Loss: 0.7864 | Train Acc: 72.01% | Precision: 65.51% Recall: 72.01% F1: 65.87%
Val   Loss: 0.7778 | Val Acc: 72.25%   | Precision: 62.27% Recall: 72.25% F1: 66.60%

Epoch: 30/150
Train Loss: 0.7367 | Train Acc: 74.30% | Precision: 66.86% Recall: 74.30% F1: 68.38%
Val   Loss: 0.8495 | Val Acc: 69.07%   | Precision: 66.19% Recall: 69.07% F1: 65.35%

Epoch: 31/150
Train Loss: 0.7079 | Train Acc: 75.86% | Precision: 70.06% Recall: 75.86% F1: 70.13%
Val   Loss: 0.6703 | Val Acc: 77.24%   | Precision: 67.10% Recall: 77.24% F1: 71.10%

Epoch: 32/150
Train Loss: 0.7490 | Train Acc: 74.00% | Precision: 68.55% Recall: 74.00% F1: 67.89%
Val   Loss: 0.7021 | Val Acc: 75.28%   | Precision: 64.07% Recall: 75.28% F1: 68.66%

Epoch: 33/150
Train Loss: 0.7076 | Train Acc: 75.63% | Precision: 69.59% Recall: 75.63% F1: 69.97%
Val   Loss: 0.7249 | Val Acc: 75.75%   | Precision: 73.27% Recall: 75.75% F1: 70.46%

Epoch: 34/150
Train Loss: 0.6791 | Train Acc: 77.00% | Precision: 77.36% Recall: 77.00% F1: 71.77%
Val   Loss: 0.6643 | Val Acc: 78.95%   | Precision: 75.15% Recall: 78.95% F1: 72.64%

Epoch: 35/150
Train Loss: 0.6755 | Train Acc: 77.27% | Precision: 77.46% Recall: 77.27% F1: 72.14%
Val   Loss: 0.6839 | Val Acc: 75.95%   | Precision: 71.86% Recall: 75.95% F1: 70.39%

Epoch: 36/150
Train Loss: 0.6962 | Train Acc: 76.41% | Precision: 73.34% Recall: 76.41% F1: 71.33%
Val   Loss: 0.6514 | Val Acc: 78.03%   | Precision: 71.77% Recall: 78.03% F1: 73.65%

Epoch: 37/150
Train Loss: 0.7092 | Train Acc: 76.27% | Precision: 72.31% Recall: 76.27% F1: 71.43%
Val   Loss: 0.6882 | Val Acc: 77.56%   | Precision: 72.48% Recall: 77.56% F1: 72.15%

Epoch: 38/150
Train Loss: 0.7237 | Train Acc: 75.50% | Precision: 71.27% Recall: 75.50% F1: 70.44%
Val   Loss: 0.6776 | Val Acc: 77.54%   | Precision: 67.12% Recall: 77.54% F1: 71.79%

Epoch: 39/150
Train Loss: 0.6516 | Train Acc: 78.31% | Precision: 75.39% Recall: 78.31% F1: 73.22%
Val   Loss: 0.6827 | Val Acc: 77.00%   | Precision: 73.84% Recall: 77.00% F1: 72.05%

Epoch: 40/150
Train Loss: 0.6249 | Train Acc: 79.14% | Precision: 78.04% Recall: 79.14% F1: 74.54%
Val   Loss: 0.7165 | Val Acc: 78.53%   | Precision: 77.85% Recall: 78.53% F1: 73.67%

Epoch: 41/150
Train Loss: 0.6708 | Train Acc: 77.51% | Precision: 77.28% Recall: 77.51% F1: 72.52%
Val   Loss: 0.6013 | Val Acc: 79.97%   | Precision: 75.85% Recall: 79.97% F1: 74.80%

Epoch: 42/150
Train Loss: 0.7945 | Train Acc: 73.04% | Precision: 70.20% Recall: 73.04% F1: 67.81%
Val   Loss: 0.7564 | Val Acc: 73.00%   | Precision: 59.37% Recall: 73.00% F1: 64.46%

Epoch: 43/150
Train Loss: 0.6976 | Train Acc: 76.26% | Precision: 76.60% Recall: 76.26% F1: 70.48%
Val   Loss: 0.6603 | Val Acc: 78.88%   | Precision: 72.98% Recall: 78.88% F1: 74.54%

Epoch: 44/150
Train Loss: 0.6894 | Train Acc: 76.70% | Precision: 76.87% Recall: 76.70% F1: 71.18%
Val   Loss: 0.6384 | Val Acc: 78.14%   | Precision: 73.80% Recall: 78.14% F1: 72.55%

Epoch: 45/150
Train Loss: 0.7870 | Train Acc: 73.50% | Precision: 69.81% Recall: 73.50% F1: 67.77%
Val   Loss: 1.0216 | Val Acc: 64.93%   | Precision: 47.84% Recall: 64.93% F1: 54.23%

Epoch: 46/150
Train Loss: 0.7773 | Train Acc: 72.84% | Precision: 72.51% Recall: 72.84% F1: 67.20%
Val   Loss: 0.9253 | Val Acc: 68.47%   | Precision: 58.66% Recall: 68.47% F1: 62.26%

Epoch: 47/150
Train Loss: 0.7394 | Train Acc: 74.28% | Precision: 67.18% Recall: 74.28% F1: 68.41%
Val   Loss: 0.6741 | Val Acc: 76.15%   | Precision: 71.55% Recall: 76.15% F1: 71.12%

Epoch: 48/150
Train Loss: 0.7455 | Train Acc: 74.10% | Precision: 67.87% Recall: 74.10% F1: 68.17%
Val   Loss: 0.7870 | Val Acc: 74.03%   | Precision: 63.56% Recall: 74.03% F1: 68.19%

Epoch: 49/150
Train Loss: 0.7714 | Train Acc: 73.81% | Precision: 69.14% Recall: 73.81% F1: 68.19%
Val   Loss: 0.7353 | Val Acc: 76.02%   | Precision: 66.76% Recall: 76.02% F1: 71.04%

Epoch: 50/150
Train Loss: 0.7209 | Train Acc: 75.62% | Precision: 68.58% Recall: 75.62% F1: 70.35%
Val   Loss: 0.7604 | Val Acc: 74.67%   | Precision: 67.58% Recall: 74.67% F1: 69.76%

Epoch: 51/150
Train Loss: 0.7045 | Train Acc: 76.26% | Precision: 71.72% Recall: 76.26% F1: 71.29%
Val   Loss: 0.6605 | Val Acc: 76.40%   | Precision: 71.85% Recall: 76.40% F1: 71.44%

Epoch: 52/150
Train Loss: 0.6538 | Train Acc: 78.01% | Precision: 75.45% Recall: 78.01% F1: 73.48%
Val   Loss: 0.6966 | Val Acc: 76.36%   | Precision: 70.10% Recall: 76.36% F1: 71.02%

Epoch: 53/150
Train Loss: 0.7691 | Train Acc: 73.69% | Precision: 70.84% Recall: 73.69% F1: 68.54%
Val   Loss: 0.7012 | Val Acc: 75.55%   | Precision: 72.00% Recall: 75.55% F1: 69.55%

Epoch: 54/150
Train Loss: 0.6725 | Train Acc: 77.55% | Precision: 74.35% Recall: 77.55% F1: 72.50%
Val   Loss: 0.7106 | Val Acc: 76.02%   | Precision: 69.54% Recall: 76.02% F1: 71.91%

Epoch: 55/150
Train Loss: 0.9868 | Train Acc: 69.19% | Precision: 63.88% Recall: 69.19% F1: 62.15%
Val   Loss: 0.9790 | Val Acc: 63.68%   | Precision: 46.88% Recall: 63.68% F1: 53.54%

Epoch: 56/150
Train Loss: 0.9058 | Train Acc: 66.14% | Precision: 54.93% Recall: 66.14% F1: 58.55%
Val   Loss: 0.8465 | Val Acc: 70.59%   | Precision: 61.37% Recall: 70.59% F1: 64.09%

Epoch: 57/150
Train Loss: 0.7837 | Train Acc: 72.67% | Precision: 66.69% Recall: 72.67% F1: 66.46%
Val   Loss: 0.7540 | Val Acc: 74.67%   | Precision: 63.73% Recall: 74.67% F1: 67.98%

Epoch: 58/150
Train Loss: 0.7313 | Train Acc: 75.13% | Precision: 69.73% Recall: 75.13% F1: 69.20%
Val   Loss: 0.6892 | Val Acc: 77.47%   | Precision: 72.99% Recall: 77.47% F1: 72.03%

Epoch: 59/150
Train Loss: 0.7061 | Train Acc: 76.30% | Precision: 70.59% Recall: 76.30% F1: 70.73%
Val   Loss: 0.6976 | Val Acc: 78.16%   | Precision: 74.30% Recall: 78.16% F1: 71.97%

Epoch: 60/150
Train Loss: 0.6908 | Train Acc: 77.06% | Precision: 70.98% Recall: 77.06% F1: 71.76%
Val   Loss: 0.6808 | Val Acc: 78.26%   | Precision: 67.88% Recall: 78.26% F1: 72.00%

Epoch: 61/150
Train Loss: 0.6994 | Train Acc: 76.66% | Precision: 71.64% Recall: 76.66% F1: 71.43%
Val   Loss: 0.7067 | Val Acc: 76.07%   | Precision: 70.63% Recall: 76.07% F1: 72.25%

Epoch: 62/150
Train Loss: 0.6672 | Train Acc: 78.14% | Precision: 72.38% Recall: 78.14% F1: 73.04%
Val   Loss: 0.6662 | Val Acc: 78.26%   | Precision: 75.74% Recall: 78.26% F1: 71.69%

Epoch: 63/150
Train Loss: 0.6979 | Train Acc: 76.74% | Precision: 70.59% Recall: 76.74% F1: 71.52%
Val   Loss: 0.6774 | Val Acc: 77.84%   | Precision: 73.76% Recall: 77.84% F1: 72.11%

Epoch: 64/150
Train Loss: 0.6667 | Train Acc: 77.96% | Precision: 71.69% Recall: 77.96% F1: 72.93%
Val   Loss: 0.6359 | Val Acc: 79.32%   | Precision: 74.88% Recall: 79.32% F1: 73.99%

Epoch: 65/150
Train Loss: 0.6620 | Train Acc: 78.23% | Precision: 74.45% Recall: 78.23% F1: 73.31%
Val   Loss: 0.6434 | Val Acc: 78.13%   | Precision: 74.50% Recall: 78.13% F1: 72.58%

Epoch: 66/150
Train Loss: 0.6556 | Train Acc: 78.47% | Precision: 72.41% Recall: 78.47% F1: 73.63%
Val   Loss: 0.6506 | Val Acc: 78.38%   | Precision: 72.41% Recall: 78.38% F1: 75.16%

Epoch: 67/150
Train Loss: 0.8029 | Train Acc: 73.50% | Precision: 67.97% Recall: 73.50% F1: 67.57%
Val   Loss: 0.7539 | Val Acc: 75.61%   | Precision: 69.68% Recall: 75.61% F1: 68.32%

Epoch: 68/150
Train Loss: 0.7057 | Train Acc: 76.35% | Precision: 70.07% Recall: 76.35% F1: 70.29%
Val   Loss: 0.6921 | Val Acc: 76.60%   | Precision: 66.30% Recall: 76.60% F1: 70.74%

Epoch: 69/150
Train Loss: 0.7083 | Train Acc: 76.09% | Precision: 68.99% Recall: 76.09% F1: 70.35%
Val   Loss: 0.6835 | Val Acc: 78.18%   | Precision: 73.43% Recall: 78.18% F1: 72.40%

Epoch: 70/150
Train Loss: 0.7273 | Train Acc: 75.79% | Precision: 69.60% Recall: 75.79% F1: 71.01%
Val   Loss: 0.7050 | Val Acc: 76.27%   | Precision: 65.91% Recall: 76.27% F1: 70.61%

Epoch: 71/150
Train Loss: 0.7447 | Train Acc: 75.93% | Precision: 70.45% Recall: 75.93% F1: 71.14%
Val   Loss: 0.8132 | Val Acc: 75.89%   | Precision: 71.94% Recall: 75.89% F1: 70.88%

Epoch: 72/150
Train Loss: 0.6698 | Train Acc: 77.57% | Precision: 70.67% Recall: 77.57% F1: 72.63%
Val   Loss: 0.6824 | Val Acc: 77.04%   | Precision: 71.00% Recall: 77.04% F1: 72.02%

Epoch: 73/150
Train Loss: 0.6673 | Train Acc: 77.62% | Precision: 73.49% Recall: 77.62% F1: 72.85%
Val   Loss: 0.8917 | Val Acc: 67.52%   | Precision: 65.27% Recall: 67.52% F1: 59.37%

Epoch: 74/150
Train Loss: 0.6675 | Train Acc: 77.36% | Precision: 74.54% Recall: 77.36% F1: 72.47%
Val   Loss: 0.6222 | Val Acc: 79.63%   | Precision: 73.07% Recall: 79.63% F1: 75.54%

Epoch: 75/150
Train Loss: 0.6232 | Train Acc: 79.19% | Precision: 74.24% Recall: 79.19% F1: 74.67%
Val   Loss: 0.5892 | Val Acc: 80.05%   | Precision: 73.34% Recall: 80.05% F1: 75.43%

Epoch: 76/150
Train Loss: 0.6298 | Train Acc: 78.97% | Precision: 75.60% Recall: 78.97% F1: 74.70%
Val   Loss: 0.6061 | Val Acc: 80.72%   | Precision: 74.73% Recall: 80.72% F1: 76.09%

Epoch: 77/150
Train Loss: 0.6033 | Train Acc: 79.96% | Precision: 77.94% Recall: 79.96% F1: 76.03%
Val   Loss: 0.5876 | Val Acc: 80.03%   | Precision: 74.86% Recall: 80.03% F1: 75.14%

Epoch: 78/150
Train Loss: 0.6097 | Train Acc: 79.86% | Precision: 78.28% Recall: 79.86% F1: 75.98%
Val   Loss: 0.6945 | Val Acc: 77.68%   | Precision: 77.68% Recall: 77.68% F1: 72.31%

Epoch: 79/150
Train Loss: 0.6065 | Train Acc: 80.00% | Precision: 78.72% Recall: 80.00% F1: 75.92%
Val   Loss: 0.6351 | Val Acc: 79.09%   | Precision: 73.32% Recall: 79.09% F1: 75.84%

Epoch: 80/150
Train Loss: 0.5943 | Train Acc: 80.47% | Precision: 79.52% Recall: 80.47% F1: 76.79%
Val   Loss: 0.7268 | Val Acc: 73.28%   | Precision: 70.29% Recall: 73.28% F1: 70.97%

Epoch: 81/150
Train Loss: 0.5770 | Train Acc: 80.97% | Precision: 80.17% Recall: 80.97% F1: 78.03%
Val   Loss: 0.5411 | Val Acc: 82.76%   | Precision: 82.77% Recall: 82.76% F1: 79.61%

Epoch: 82/150
Train Loss: 0.6305 | Train Acc: 79.32% | Precision: 77.86% Recall: 79.32% F1: 76.02%
Val   Loss: 0.5948 | Val Acc: 80.64%   | Precision: 76.13% Recall: 80.64% F1: 75.38%

Epoch: 83/150
Train Loss: 0.6523 | Train Acc: 78.28% | Precision: 76.83% Recall: 78.28% F1: 74.02%
Val   Loss: 0.5839 | Val Acc: 80.65%   | Precision: 74.49% Recall: 80.65% F1: 76.23%

Epoch: 84/150
Train Loss: 0.6052 | Train Acc: 79.87% | Precision: 78.02% Recall: 79.87% F1: 76.19%
Val   Loss: 0.5687 | Val Acc: 80.54%   | Precision: 80.64% Recall: 80.54% F1: 76.99%

Epoch: 85/150
Train Loss: 0.5915 | Train Acc: 80.41% | Precision: 79.18% Recall: 80.41% F1: 77.30%
Val   Loss: 0.8154 | Val Acc: 70.45%   | Precision: 64.83% Recall: 70.45% F1: 67.04%

Epoch: 86/150
Train Loss: 0.6063 | Train Acc: 79.97% | Precision: 78.26% Recall: 79.97% F1: 76.83%
Val   Loss: 0.5590 | Val Acc: 82.69%   | Precision: 81.78% Recall: 82.69% F1: 81.79%

Epoch: 87/150
Train Loss: 0.5522 | Train Acc: 82.63% | Precision: 81.91% Recall: 82.63% F1: 80.60%
Val   Loss: 0.6298 | Val Acc: 79.48%   | Precision: 73.45% Recall: 79.48% F1: 75.06%

Epoch: 88/150
Train Loss: 0.6363 | Train Acc: 78.52% | Precision: 76.58% Recall: 78.52% F1: 74.95%
Val   Loss: 0.5976 | Val Acc: 79.68%   | Precision: 75.11% Recall: 79.68% F1: 73.87%

Epoch: 89/150
Train Loss: 0.5845 | Train Acc: 80.58% | Precision: 79.12% Recall: 80.58% F1: 77.29%
Val   Loss: 0.5728 | Val Acc: 80.58%   | Precision: 81.29% Recall: 80.58% F1: 77.85%

Epoch: 90/150
Train Loss: 0.7458 | Train Acc: 74.54% | Precision: 72.56% Recall: 74.54% F1: 70.21%
Val   Loss: 0.7690 | Val Acc: 74.94%   | Precision: 68.98% Recall: 74.94% F1: 68.93%

Epoch: 91/150
Train Loss: 0.6958 | Train Acc: 76.81% | Precision: 75.16% Recall: 76.81% F1: 71.25%
Val   Loss: 0.6579 | Val Acc: 79.09%   | Precision: 69.16% Recall: 79.09% F1: 72.99%

Epoch: 92/150
Train Loss: 0.6401 | Train Acc: 78.84% | Precision: 75.22% Recall: 78.84% F1: 74.35%
Val   Loss: 0.5946 | Val Acc: 81.65%   | Precision: 80.28% Recall: 81.65% F1: 79.34%

Epoch: 93/150
Train Loss: 0.5847 | Train Acc: 80.96% | Precision: 79.99% Recall: 80.96% F1: 77.81%
Val   Loss: 0.5678 | Val Acc: 80.98%   | Precision: 80.91% Recall: 80.98% F1: 77.26%

Epoch: 94/150
Train Loss: 0.5778 | Train Acc: 81.55% | Precision: 80.73% Recall: 81.55% F1: 79.22%
Val   Loss: 0.5952 | Val Acc: 80.51%   | Precision: 80.95% Recall: 80.51% F1: 77.18%

Epoch: 95/150
Train Loss: 0.5811 | Train Acc: 82.10% | Precision: 81.17% Recall: 82.10% F1: 80.19%
Val   Loss: 0.5921 | Val Acc: 79.74%   | Precision: 79.86% Recall: 79.74% F1: 78.62%

Epoch: 96/150
Train Loss: 0.5680 | Train Acc: 81.70% | Precision: 80.82% Recall: 81.70% F1: 79.86%
Val   Loss: 0.5286 | Val Acc: 84.18%   | Precision: 83.74% Recall: 84.18% F1: 82.50%

Epoch: 97/150
Train Loss: 0.5285 | Train Acc: 83.65% | Precision: 83.11% Recall: 83.65% F1: 82.18%
Val   Loss: 0.5485 | Val Acc: 82.07%   | Precision: 83.53% Recall: 82.07% F1: 82.05%

Epoch: 98/150
Train Loss: 0.5263 | Train Acc: 83.73% | Precision: 83.10% Recall: 83.73% F1: 82.41%
Val   Loss: 0.5160 | Val Acc: 84.11%   | Precision: 83.91% Recall: 84.11% F1: 82.28%

Epoch: 99/150
Train Loss: 0.5150 | Train Acc: 84.09% | Precision: 83.54% Recall: 84.09% F1: 82.84%
Val   Loss: 0.5167 | Val Acc: 83.05%   | Precision: 82.94% Recall: 83.05% F1: 81.96%

Epoch: 100/150
Train Loss: 0.5127 | Train Acc: 84.18% | Precision: 83.63% Recall: 84.18% F1: 82.88%
Val   Loss: 0.4818 | Val Acc: 85.10%   | Precision: 84.66% Recall: 85.10% F1: 83.68%

Epoch: 101/150
Train Loss: 0.5083 | Train Acc: 84.12% | Precision: 83.57% Recall: 84.12% F1: 82.89%
Val   Loss: 0.7704 | Val Acc: 72.27%   | Precision: 61.97% Recall: 72.27% F1: 66.59%

Epoch: 102/150
Train Loss: 0.5346 | Train Acc: 82.88% | Precision: 82.20% Recall: 82.88% F1: 81.37%
Val   Loss: 0.5203 | Val Acc: 83.22%   | Precision: 82.43% Recall: 83.22% F1: 81.38%

Epoch: 103/150
Train Loss: 0.5296 | Train Acc: 83.21% | Precision: 82.52% Recall: 83.21% F1: 81.93%
Val   Loss: 0.5305 | Val Acc: 82.98%   | Precision: 83.18% Recall: 82.98% F1: 80.73%

Epoch: 104/150
Train Loss: 0.5081 | Train Acc: 84.27% | Precision: 83.73% Recall: 84.27% F1: 83.18%
Val   Loss: 0.5123 | Val Acc: 83.83%   | Precision: 83.41% Recall: 83.83% F1: 82.32%

Epoch: 105/150
Train Loss: 0.5486 | Train Acc: 82.39% | Precision: 81.48% Recall: 82.39% F1: 80.76%
Val   Loss: 0.5099 | Val Acc: 83.74%   | Precision: 83.77% Recall: 83.74% F1: 81.66%

Epoch: 106/150
Train Loss: 0.4768 | Train Acc: 85.47% | Precision: 85.11% Recall: 85.47% F1: 84.52%
Val   Loss: 0.4629 | Val Acc: 85.66%   | Precision: 85.18% Recall: 85.66% F1: 84.77%

Epoch: 107/150
Train Loss: 0.4878 | Train Acc: 84.89% | Precision: 84.43% Recall: 84.89% F1: 83.93%
Val   Loss: 0.4646 | Val Acc: 85.52%   | Precision: 85.40% Recall: 85.52% F1: 84.50%

Epoch: 108/150
Train Loss: 0.4882 | Train Acc: 85.01% | Precision: 84.52% Recall: 85.01% F1: 84.06%
Val   Loss: 0.5738 | Val Acc: 80.65%   | Precision: 79.83% Recall: 80.65% F1: 79.40%

Epoch: 109/150

wandb: Agent Starting Run: iesudk06 with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.0005258404854947704
wandb: 	optimizer: sgd
wandb: 	rnn_type: rnn
wandb: 	seq_len: 150
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.2881 | Train Acc: 63.63% | Precision: 41.66% Recall: 63.63% F1: 50.35%
Val   Loss: 1.1296 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.1262 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1247 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1220 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1199 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1164 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1137 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.1081 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1030 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.0906 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0743 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 7/150
Train Loss: 1.0088 | Train Acc: 65.83% | Precision: 52.76% Recall: 65.83% F1: 54.44%
Val   Loss: 0.9174 | Val Acc: 70.31%   | Precision: 56.16% Recall: 70.31% F1: 61.49%

Epoch: 8/150
Train Loss: 0.8838 | Train Acc: 70.79% | Precision: 56.94% Recall: 70.79% F1: 62.49%
Val   Loss: 0.8542 | Val Acc: 71.93%   | Precision: 58.01% Recall: 71.93% F1: 63.51%

Epoch: 9/150
Train Loss: 0.8454 | Train Acc: 71.77% | Precision: 58.66% Recall: 71.77% F1: 63.59%
Val   Loss: 0.8338 | Val Acc: 71.97%   | Precision: 58.85% Recall: 71.97% F1: 64.07%

Epoch: 10/150
Train Loss: 0.8047 | Train Acc: 71.87% | Precision: 63.28% Recall: 71.87% F1: 64.53%
Val   Loss: 0.8046 | Val Acc: 72.15%   | Precision: 66.74% Recall: 72.15% F1: 65.70%

Epoch: 11/150
Train Loss: 0.7623 | Train Acc: 73.94% | Precision: 67.10% Recall: 73.94% F1: 67.94%
Val   Loss: 0.7362 | Val Acc: 75.66%   | Precision: 69.39% Recall: 75.66% F1: 70.47%

Epoch: 12/150
Train Loss: 0.7202 | Train Acc: 75.47% | Precision: 68.77% Recall: 75.47% F1: 70.43%
Val   Loss: 0.6825 | Val Acc: 76.59%   | Precision: 70.04% Recall: 76.59% F1: 72.03%

Epoch: 13/150
Train Loss: 0.6671 | Train Acc: 77.06% | Precision: 70.74% Recall: 77.06% F1: 72.63%
Val   Loss: 0.6397 | Val Acc: 78.30%   | Precision: 72.02% Recall: 78.30% F1: 73.51%

Epoch: 14/150
Train Loss: 0.6267 | Train Acc: 79.05% | Precision: 74.15% Recall: 79.05% F1: 75.10%
Val   Loss: 0.6784 | Val Acc: 77.77%   | Precision: 71.03% Recall: 77.77% F1: 71.46%

Epoch: 15/150
Train Loss: 0.5906 | Train Acc: 80.81% | Precision: 77.60% Recall: 80.81% F1: 77.27%
Val   Loss: 0.5591 | Val Acc: 82.31%   | Precision: 77.07% Recall: 82.31% F1: 78.74%

Epoch: 16/150
Train Loss: 0.5570 | Train Acc: 82.42% | Precision: 81.57% Recall: 82.42% F1: 80.07%
Val   Loss: 0.5656 | Val Acc: 81.69%   | Precision: 77.05% Recall: 81.69% F1: 78.08%

Epoch: 17/150
Train Loss: 0.5278 | Train Acc: 84.47% | Precision: 84.03% Recall: 84.47% F1: 83.03%
Val   Loss: 0.5507 | Val Acc: 83.61%   | Precision: 83.32% Recall: 83.61% F1: 82.60%

Epoch: 18/150
Train Loss: 0.5054 | Train Acc: 85.37% | Precision: 85.10% Recall: 85.37% F1: 84.27%
Val   Loss: 0.4842 | Val Acc: 85.54%   | Precision: 85.20% Recall: 85.54% F1: 84.46%

Epoch: 19/150
Train Loss: 0.4843 | Train Acc: 86.06% | Precision: 85.85% Recall: 86.06% F1: 85.10%
Val   Loss: 0.4676 | Val Acc: 86.29%   | Precision: 86.26% Recall: 86.29% F1: 85.37%

Epoch: 20/150
Train Loss: 0.4696 | Train Acc: 86.29% | Precision: 86.11% Recall: 86.29% F1: 85.38%
Val   Loss: 0.4663 | Val Acc: 86.40%   | Precision: 86.09% Recall: 86.40% F1: 85.63%

Epoch: 21/150
Train Loss: 0.4549 | Train Acc: 86.80% | Precision: 86.67% Recall: 86.80% F1: 85.97%
Val   Loss: 0.4882 | Val Acc: 85.27%   | Precision: 84.92% Recall: 85.27% F1: 84.27%

Epoch: 22/150
Train Loss: 0.4439 | Train Acc: 87.00% | Precision: 86.90% Recall: 87.00% F1: 86.22%
Val   Loss: 0.4417 | Val Acc: 87.11%   | Precision: 86.92% Recall: 87.11% F1: 86.24%

Epoch: 23/150
Train Loss: 0.4353 | Train Acc: 87.18% | Precision: 87.15% Recall: 87.18% F1: 86.39%
Val   Loss: 0.4625 | Val Acc: 86.04%   | Precision: 85.56% Recall: 86.04% F1: 84.81%

Epoch: 24/150
Train Loss: 0.4297 | Train Acc: 87.25% | Precision: 87.21% Recall: 87.25% F1: 86.48%
Val   Loss: 0.4417 | Val Acc: 86.74%   | Precision: 86.51% Recall: 86.74% F1: 85.71%

Epoch: 25/150
Train Loss: 0.4191 | Train Acc: 87.67% | Precision: 87.63% Recall: 87.67% F1: 86.97%
Val   Loss: 0.4435 | Val Acc: 86.45%   | Precision: 86.71% Recall: 86.45% F1: 85.64%

Epoch: 26/150
Train Loss: 0.4142 | Train Acc: 87.71% | Precision: 87.63% Recall: 87.71% F1: 87.02%
Val   Loss: 0.4161 | Val Acc: 87.50%   | Precision: 87.30% Recall: 87.50% F1: 86.81%

Epoch: 27/150
Train Loss: 0.4038 | Train Acc: 88.19% | Precision: 88.18% Recall: 88.19% F1: 87.54%
Val   Loss: 0.4082 | Val Acc: 87.82%   | Precision: 87.74% Recall: 87.82% F1: 87.03%

Epoch: 28/150
Train Loss: 0.3989 | Train Acc: 88.25% | Precision: 88.13% Recall: 88.25% F1: 87.62%
Val   Loss: 0.4014 | Val Acc: 87.87%   | Precision: 87.99% Recall: 87.87% F1: 87.19%

Epoch: 29/150
Train Loss: 0.3955 | Train Acc: 88.39% | Precision: 88.34% Recall: 88.39% F1: 87.81%
Val   Loss: 0.4120 | Val Acc: 87.51%   | Precision: 87.24% Recall: 87.51% F1: 86.69%

Epoch: 30/150
Train Loss: 0.3893 | Train Acc: 88.49% | Precision: 88.43% Recall: 88.49% F1: 87.91%
Val   Loss: 0.3815 | Val Acc: 88.97%   | Precision: 88.83% Recall: 88.97% F1: 88.40%

Epoch: 31/150
Train Loss: 0.3870 | Train Acc: 88.53% | Precision: 88.46% Recall: 88.53% F1: 87.97%
Val   Loss: 0.3797 | Val Acc: 89.13%   | Precision: 89.08% Recall: 89.13% F1: 88.45%

Epoch: 32/150
Train Loss: 0.3766 | Train Acc: 88.88% | Precision: 88.83% Recall: 88.88% F1: 88.34%
Val   Loss: 0.3662 | Val Acc: 89.25%   | Precision: 89.08% Recall: 89.25% F1: 88.70%

Epoch: 33/150
Train Loss: 0.3734 | Train Acc: 88.92% | Precision: 88.85% Recall: 88.92% F1: 88.39%
Val   Loss: 0.4080 | Val Acc: 87.85%   | Precision: 87.42% Recall: 87.85% F1: 87.07%

Epoch: 34/150
Train Loss: 0.3649 | Train Acc: 89.26% | Precision: 89.21% Recall: 89.26% F1: 88.77%
Val   Loss: 0.3830 | Val Acc: 88.86%   | Precision: 88.77% Recall: 88.86% F1: 88.11%

Epoch: 35/150
Train Loss: 0.3652 | Train Acc: 89.22% | Precision: 89.16% Recall: 89.22% F1: 88.70%
Val   Loss: 0.4170 | Val Acc: 87.21%   | Precision: 87.25% Recall: 87.21% F1: 86.89%

Epoch: 36/150
Train Loss: 0.3588 | Train Acc: 89.35% | Precision: 89.29% Recall: 89.35% F1: 88.84%
Val   Loss: 0.3538 | Val Acc: 89.55%   | Precision: 89.64% Recall: 89.55% F1: 88.86%

Epoch: 37/150
Train Loss: 0.3566 | Train Acc: 89.33% | Precision: 89.28% Recall: 89.33% F1: 88.83%
Val   Loss: 0.3772 | Val Acc: 88.80%   | Precision: 88.66% Recall: 88.80% F1: 88.09%

Epoch: 38/150
Train Loss: 0.3397 | Train Acc: 89.99% | Precision: 89.97% Recall: 89.99% F1: 89.52%
Val   Loss: 0.3377 | Val Acc: 90.26%   | Precision: 90.09% Recall: 90.26% F1: 89.77%

Epoch: 39/150
Train Loss: 0.3427 | Train Acc: 89.78% | Precision: 89.73% Recall: 89.78% F1: 89.30%
Val   Loss: 0.3510 | Val Acc: 89.77%   | Precision: 89.70% Recall: 89.77% F1: 89.23%

Epoch: 40/150
Train Loss: 0.3553 | Train Acc: 89.31% | Precision: 89.25% Recall: 89.31% F1: 88.77%
Val   Loss: 0.3486 | Val Acc: 89.48%   | Precision: 89.34% Recall: 89.48% F1: 89.01%

Epoch: 41/150
Train Loss: 0.3320 | Train Acc: 90.10% | Precision: 90.09% Recall: 90.10% F1: 89.64%
Val   Loss: 0.3272 | Val Acc: 90.24%   | Precision: 90.15% Recall: 90.24% F1: 89.71%

Epoch: 42/150
Train Loss: 0.3319 | Train Acc: 90.14% | Precision: 90.12% Recall: 90.14% F1: 89.68%
Val   Loss: 0.3298 | Val Acc: 90.62%   | Precision: 90.49% Recall: 90.62% F1: 90.24%

Epoch: 43/150
Train Loss: 0.3264 | Train Acc: 90.34% | Precision: 90.32% Recall: 90.34% F1: 89.89%
Val   Loss: 0.3201 | Val Acc: 90.32%   | Precision: 90.28% Recall: 90.32% F1: 89.76%

Epoch: 44/150
Train Loss: 0.3216 | Train Acc: 90.38% | Precision: 90.34% Recall: 90.38% F1: 89.93%
Val   Loss: 0.3392 | Val Acc: 90.02%   | Precision: 89.92% Recall: 90.02% F1: 89.44%

Epoch: 45/150
Train Loss: 0.3160 | Train Acc: 90.68% | Precision: 90.65% Recall: 90.68% F1: 90.24%
Val   Loss: 0.3575 | Val Acc: 89.28%   | Precision: 89.21% Recall: 89.28% F1: 88.67%

Epoch: 46/150
Train Loss: 0.3164 | Train Acc: 90.55% | Precision: 90.53% Recall: 90.55% F1: 90.09%
Val   Loss: 0.3144 | Val Acc: 90.28%   | Precision: 90.32% Recall: 90.28% F1: 89.87%

Epoch: 47/150
Train Loss: 0.3188 | Train Acc: 90.52% | Precision: 90.50% Recall: 90.52% F1: 90.05%
Val   Loss: 0.3311 | Val Acc: 90.06%   | Precision: 90.01% Recall: 90.06% F1: 89.58%

Epoch: 48/150
Train Loss: 0.3093 | Train Acc: 90.74% | Precision: 90.71% Recall: 90.74% F1: 90.31%
Val   Loss: 0.3053 | Val Acc: 91.12%   | Precision: 90.96% Recall: 91.12% F1: 90.64%

Epoch: 49/150
Train Loss: 0.2949 | Train Acc: 91.18% | Precision: 91.16% Recall: 91.18% F1: 90.75%
Val   Loss: 0.2964 | Val Acc: 90.91%   | Precision: 90.78% Recall: 90.91% F1: 90.39%

Epoch: 50/150
Train Loss: 0.2932 | Train Acc: 91.22% | Precision: 91.18% Recall: 91.22% F1: 90.80%
Val   Loss: 0.2815 | Val Acc: 91.66%   | Precision: 91.59% Recall: 91.66% F1: 91.18%

Epoch: 51/150
Train Loss: 0.2976 | Train Acc: 91.10% | Precision: 91.07% Recall: 91.10% F1: 90.67%
Val   Loss: 0.3027 | Val Acc: 91.05%   | Precision: 91.13% Recall: 91.05% F1: 90.51%

Epoch: 52/150
Train Loss: 0.2857 | Train Acc: 91.44% | Precision: 91.39% Recall: 91.44% F1: 91.02%
Val   Loss: 0.4039 | Val Acc: 87.64%   | Precision: 87.56% Recall: 87.64% F1: 86.18%

Epoch: 53/150
Train Loss: 0.2851 | Train Acc: 91.52% | Precision: 91.51% Recall: 91.52% F1: 91.11%
Val   Loss: 0.3073 | Val Acc: 91.50%   | Precision: 91.50% Recall: 91.50% F1: 91.10%

Epoch: 54/150
Train Loss: 0.6386 | Train Acc: 81.24% | Precision: 80.50% Recall: 81.24% F1: 79.71%
Val   Loss: 0.8013 | Val Acc: 72.89%   | Precision: 63.76% Recall: 72.89% F1: 67.10%

Epoch: 55/150
Train Loss: 0.6887 | Train Acc: 76.39% | Precision: 70.66% Recall: 76.39% F1: 71.35%
Val   Loss: 0.5871 | Val Acc: 80.89%   | Precision: 77.28% Recall: 80.89% F1: 77.19%

Epoch: 56/150
Train Loss: 0.5637 | Train Acc: 82.05% | Precision: 80.19% Recall: 82.05% F1: 79.07%
Val   Loss: 0.5343 | Val Acc: 82.80%   | Precision: 81.84% Recall: 82.80% F1: 79.90%

Epoch: 57/150
Train Loss: 0.5033 | Train Acc: 84.41% | Precision: 83.48% Recall: 84.41% F1: 83.04%
Val   Loss: 0.4886 | Val Acc: 85.10%   | Precision: 84.68% Recall: 85.10% F1: 83.73%

Epoch: 58/150
Train Loss: 0.4667 | Train Acc: 86.46% | Precision: 86.02% Recall: 86.46% F1: 85.53%
Val   Loss: 0.4417 | Val Acc: 87.30%   | Precision: 87.12% Recall: 87.30% F1: 86.50%

Epoch: 59/150
Train Loss: 0.4394 | Train Acc: 87.34% | Precision: 86.96% Recall: 87.34% F1: 86.55%
Val   Loss: 0.5028 | Val Acc: 83.76%   | Precision: 84.17% Recall: 83.76% F1: 83.50%

Epoch: 60/150
Train Loss: 0.4237 | Train Acc: 87.70% | Precision: 87.37% Recall: 87.70% F1: 86.98%
Val   Loss: 0.4030 | Val Acc: 88.37%   | Precision: 88.09% Recall: 88.37% F1: 87.61%

Epoch: 61/150
Train Loss: 0.4107 | Train Acc: 88.08% | Precision: 87.82% Recall: 88.08% F1: 87.39%
Val   Loss: 0.4141 | Val Acc: 87.78%   | Precision: 87.17% Recall: 87.78% F1: 87.20%

Epoch: 62/150
Train Loss: 0.3849 | Train Acc: 88.90% | Precision: 88.68% Recall: 88.90% F1: 88.28%
Val   Loss: 0.4098 | Val Acc: 87.82%   | Precision: 87.92% Recall: 87.82% F1: 86.62%

Epoch: 63/150
Train Loss: 0.3678 | Train Acc: 89.25% | Precision: 89.05% Recall: 89.25% F1: 88.71%
Val   Loss: 0.3552 | Val Acc: 89.92%   | Precision: 89.82% Recall: 89.92% F1: 89.17%

Epoch: 64/150
Train Loss: 0.3471 | Train Acc: 90.05% | Precision: 89.93% Recall: 90.05% F1: 89.58%
Val   Loss: 0.3486 | Val Acc: 89.88%   | Precision: 89.90% Recall: 89.88% F1: 89.19%

Epoch: 65/150
Train Loss: 0.3299 | Train Acc: 90.48% | Precision: 90.40% Recall: 90.48% F1: 90.06%
Val   Loss: 0.3288 | Val Acc: 90.67%   | Precision: 90.60% Recall: 90.67% F1: 90.13%

Epoch: 66/150
Train Loss: 0.3149 | Train Acc: 90.99% | Precision: 90.88% Recall: 90.99% F1: 90.61%
Val   Loss: 0.3248 | Val Acc: 90.27%   | Precision: 89.96% Recall: 90.27% F1: 89.83%

Epoch: 67/150
Train Loss: 0.3142 | Train Acc: 90.93% | Precision: 90.83% Recall: 90.93% F1: 90.58%
Val   Loss: 0.3200 | Val Acc: 90.79%   | Precision: 90.86% Recall: 90.79% F1: 90.25%

Epoch: 68/150
Train Loss: 0.2991 | Train Acc: 91.30% | Precision: 91.22% Recall: 91.30% F1: 90.95%
Val   Loss: 0.2987 | Val Acc: 90.83%   | Precision: 90.73% Recall: 90.83% F1: 90.30%

Epoch: 69/150
Train Loss: 0.2860 | Train Acc: 91.56% | Precision: 91.47% Recall: 91.56% F1: 91.24%
Val   Loss: 0.3400 | Val Acc: 90.18%   | Precision: 89.96% Recall: 90.18% F1: 89.92%

Epoch: 70/150
Train Loss: 0.2841 | Train Acc: 91.53% | Precision: 91.43% Recall: 91.53% F1: 91.22%
Val   Loss: 0.2665 | Val Acc: 91.96%   | Precision: 91.87% Recall: 91.96% F1: 91.56%

Epoch: 71/150
Train Loss: 0.2746 | Train Acc: 91.91% | Precision: 91.84% Recall: 91.91% F1: 91.62%
Val   Loss: 0.3177 | Val Acc: 90.18%   | Precision: 90.13% Recall: 90.18% F1: 89.48%

Epoch: 72/150
Train Loss: 0.2704 | Train Acc: 92.09% | Precision: 92.01% Recall: 92.09% F1: 91.81%
Val   Loss: 0.2704 | Val Acc: 92.06%   | Precision: 92.06% Recall: 92.06% F1: 91.63%

Epoch: 73/150
Train Loss: 0.2665 | Train Acc: 92.06% | Precision: 91.96% Recall: 92.06% F1: 91.78%
Val   Loss: 0.2486 | Val Acc: 92.47%   | Precision: 92.34% Recall: 92.47% F1: 92.17%

Epoch: 74/150
Train Loss: 0.2577 | Train Acc: 92.32% | Precision: 92.24% Recall: 92.32% F1: 92.05%
Val   Loss: 0.2425 | Val Acc: 92.53%   | Precision: 92.46% Recall: 92.53% F1: 92.21%

Epoch: 75/150
Train Loss: 0.2562 | Train Acc: 92.35% | Precision: 92.26% Recall: 92.35% F1: 92.10%
Val   Loss: 0.2560 | Val Acc: 91.80%   | Precision: 91.66% Recall: 91.80% F1: 91.53%

Epoch: 76/150
Train Loss: 0.2468 | Train Acc: 92.56% | Precision: 92.49% Recall: 92.56% F1: 92.31%
Val   Loss: 0.2412 | Val Acc: 92.52%   | Precision: 92.49% Recall: 92.52% F1: 92.21%

Epoch: 77/150
Train Loss: 0.2482 | Train Acc: 92.53% | Precision: 92.44% Recall: 92.53% F1: 92.29%
Val   Loss: 0.3245 | Val Acc: 89.86%   | Precision: 89.91% Recall: 89.86% F1: 89.47%

Epoch: 78/150
Train Loss: 0.2409 | Train Acc: 92.74% | Precision: 92.66% Recall: 92.74% F1: 92.49%
Val   Loss: 0.2744 | Val Acc: 91.65%   | Precision: 91.67% Recall: 91.65% F1: 91.34%

Epoch: 79/150
Train Loss: 0.2506 | Train Acc: 92.46% | Precision: 92.37% Recall: 92.46% F1: 92.21%
Val   Loss: 0.2570 | Val Acc: 92.14%   | Precision: 92.21% Recall: 92.14% F1: 91.70%

Epoch: 80/150
Train Loss: 0.2398 | Train Acc: 92.85% | Precision: 92.77% Recall: 92.85% F1: 92.61%
Val   Loss: 0.2467 | Val Acc: 92.50%   | Precision: 92.55% Recall: 92.50% F1: 92.08%

Epoch: 81/150
Train Loss: 0.2357 | Train Acc: 92.92% | Precision: 92.82% Recall: 92.92% F1: 92.68%
Val   Loss: 0.2334 | Val Acc: 92.78%   | Precision: 92.67% Recall: 92.78% F1: 92.47%

Epoch: 82/150
Train Loss: 0.2316 | Train Acc: 92.98% | Precision: 92.89% Recall: 92.98% F1: 92.73%
Val   Loss: 0.2318 | Val Acc: 92.60%   | Precision: 92.54% Recall: 92.60% F1: 92.37%

Epoch: 83/150
Train Loss: 0.2312 | Train Acc: 92.93% | Precision: 92.83% Recall: 92.93% F1: 92.70%
Val   Loss: 0.2635 | Val Acc: 91.75%   | Precision: 91.66% Recall: 91.75% F1: 91.57%

Epoch: 84/150
Train Loss: 0.2368 | Train Acc: 92.77% | Precision: 92.66% Recall: 92.77% F1: 92.53%
Val   Loss: 0.2891 | Val Acc: 91.28%   | Precision: 91.17% Recall: 91.28% F1: 91.20%

Epoch: 85/150
Train Loss: 0.2283 | Train Acc: 93.09% | Precision: 92.99% Recall: 93.09% F1: 92.85%
Val   Loss: 0.2401 | Val Acc: 92.44%   | Precision: 92.32% Recall: 92.44% F1: 92.12%

Epoch: 86/150
Train Loss: 0.2226 | Train Acc: 93.23% | Precision: 93.14% Recall: 93.23% F1: 93.01%
Val   Loss: 0.2119 | Val Acc: 93.32%   | Precision: 93.26% Recall: 93.32% F1: 93.07%

Epoch: 87/150
Train Loss: 0.2146 | Train Acc: 93.53% | Precision: 93.46% Recall: 93.53% F1: 93.32%
Val   Loss: 0.2159 | Val Acc: 93.26%   | Precision: 93.14% Recall: 93.26% F1: 93.06%

Epoch: 88/150
Train Loss: 0.2143 | Train Acc: 93.42% | Precision: 93.35% Recall: 93.42% F1: 93.22%
Val   Loss: 0.2408 | Val Acc: 92.39%   | Precision: 92.27% Recall: 92.39% F1: 92.06%

Epoch: 89/150
Train Loss: 0.2106 | Train Acc: 93.49% | Precision: 93.42% Recall: 93.49% F1: 93.30%
Val   Loss: 0.2682 | Val Acc: 92.29%   | Precision: 92.20% Recall: 92.29% F1: 91.91%

Epoch: 90/150
Train Loss: 0.2100 | Train Acc: 93.63% | Precision: 93.56% Recall: 93.63% F1: 93.44%
Val   Loss: 0.2620 | Val Acc: 91.93%   | Precision: 91.93% Recall: 91.93% F1: 91.56%

Epoch: 91/150
Train Loss: 0.2076 | Train Acc: 93.69% | Precision: 93.62% Recall: 93.69% F1: 93.50%
Val   Loss: 0.1916 | Val Acc: 93.99%   | Precision: 93.93% Recall: 93.99% F1: 93.73%

Epoch: 92/150
Train Loss: 0.6368 | Train Acc: 78.87% | Precision: 78.79% Recall: 78.87% F1: 77.07%
Val   Loss: 0.9480 | Val Acc: 63.28%   | Precision: 48.39% Recall: 63.28% F1: 53.06%

Epoch: 93/150
Train Loss: 0.9122 | Train Acc: 68.28% | Precision: 59.29% Recall: 68.28% F1: 61.59%
Val   Loss: 0.8308 | Val Acc: 72.20%   | Precision: 61.49% Recall: 72.20% F1: 66.08%

Epoch: 94/150
Train Loss: 0.8110 | Train Acc: 72.30% | Precision: 65.37% Recall: 72.30% F1: 66.37%
Val   Loss: 0.7533 | Val Acc: 75.69%   | Precision: 67.86% Recall: 75.69% F1: 70.41%

Epoch: 95/150
Train Loss: 0.6568 | Train Acc: 78.16% | Precision: 74.93% Recall: 78.16% F1: 73.62%
Val   Loss: 0.6235 | Val Acc: 79.97%   | Precision: 80.10% Recall: 79.97% F1: 76.42%

Epoch: 96/150
Train Loss: 0.5477 | Train Acc: 82.63% | Precision: 81.10% Recall: 82.63% F1: 80.20%
Val   Loss: 0.5277 | Val Acc: 84.02%   | Precision: 83.14% Recall: 84.02% F1: 82.75%

Epoch: 97/150
Train Loss: 0.4913 | Train Acc: 84.77% | Precision: 84.14% Recall: 84.77% F1: 83.16%
Val   Loss: 0.4923 | Val Acc: 85.41%   | Precision: 84.73% Recall: 85.41% F1: 84.36%

Epoch: 98/150
Train Loss: 0.4483 | Train Acc: 86.57% | Precision: 86.25% Recall: 86.57% F1: 85.42%
Val   Loss: 0.4292 | Val Acc: 87.61%   | Precision: 87.33% Recall: 87.61% F1: 86.72%

Epoch: 99/150
Train Loss: 0.4111 | Train Acc: 87.95% | Precision: 87.74% Recall: 87.95% F1: 87.15%
Val   Loss: 0.3962 | Val Acc: 88.18%   | Precision: 87.62% Recall: 88.18% F1: 87.45%

Epoch: 100/150
Train Loss: 0.3805 | Train Acc: 88.75% | Precision: 88.52% Recall: 88.75% F1: 88.07%
Val   Loss: 0.3583 | Val Acc: 89.80%   | Precision: 89.55% Recall: 89.80% F1: 89.28%

Epoch: 101/150
Train Loss: 0.4039 | Train Acc: 87.80% | Precision: 87.55% Recall: 87.80% F1: 87.05%
Val   Loss: 0.4118 | Val Acc: 87.65%   | Precision: 87.51% Recall: 87.65% F1: 86.80%

Epoch: 102/150
Train Loss: 0.3535 | Train Acc: 89.52% | Precision: 89.38% Recall: 89.52% F1: 88.95%
Val   Loss: 0.3469 | Val Acc: 89.89%   | Precision: 89.95% Recall: 89.89% F1: 89.22%

Epoch: 103/150
Train Loss: 0.3382 | Train Acc: 89.92% | Precision: 89.79% Recall: 89.92% F1: 89.43%
Val   Loss: 0.3368 | Val Acc: 89.87%   | Precision: 89.54% Recall: 89.87% F1: 89.40%

Epoch: 104/150
Train Loss: 0.8060 | Train Acc: 72.71% | Precision: 74.18% Recall: 72.71% F1: 68.33%
Val   Loss: 0.9164 | Val Acc: 66.26%   | Precision: 54.91% Recall: 66.26% F1: 57.66%

Epoch: 105/150
Train Loss: 0.8293 | Train Acc: 71.44% | Precision: 65.75% Recall: 71.44% F1: 64.93%
Val   Loss: 0.7849 | Val Acc: 71.84%   | Precision: 66.46% Recall: 71.84% F1: 65.01%

Epoch: 106/150
Train Loss: 0.7705 | Train Acc: 73.31% | Precision: 66.09% Recall: 73.31% F1: 66.82%
Val   Loss: 0.7448 | Val Acc: 75.14%   | Precision: 69.09% Recall: 75.14% F1: 68.91%

Epoch: 107/150
Train Loss: 0.7302 | Train Acc: 75.93% | Precision: 69.53% Recall: 75.93% F1: 69.69%
Val   Loss: 0.7031 | Val Acc: 78.52%   | Precision: 74.14% Recall: 78.52% F1: 72.83%

Epoch: 108/150
Train Loss: 0.6890 | Train Acc: 77.97% | Precision: 72.97% Recall: 77.97% F1: 72.11%
Val   Loss: 0.6628 | Val Acc: 78.73%   | Precision: 79.99% Recall: 78.73% F1: 72.99%

Epoch: 109/150

wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)

Epoch: 110/150
Train Loss: 0.5712 | Train Acc: 82.46% | Precision: 81.34% Recall: 82.46% F1: 79.93%
Val   Loss: 0.5428 | Val Acc: 83.76%   | Precision: 83.18% Recall: 83.76% F1: 81.70%

wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: Network error (HTTPError), entering retry loop.

Epoch: 111/150
Train Loss: 0.6836 | Train Acc: 77.73% | Precision: 76.62% Recall: 77.73% F1: 73.78%
Val   Loss: 0.5725 | Val Acc: 81.56%   | Precision: 81.46% Recall: 81.56% F1: 78.21%

Epoch: 112/150
Train Loss: 0.5356 | Train Acc: 83.53% | Precision: 82.72% Recall: 83.53% F1: 81.55%
Val   Loss: 0.5389 | Val Acc: 83.22%   | Precision: 82.03% Recall: 83.22% F1: 81.13%

Epoch: 113/150
Train Loss: 0.5203 | Train Acc: 83.91% | Precision: 83.22% Recall: 83.91% F1: 82.39%
Val   Loss: 0.4909 | Val Acc: 85.25%   | Precision: 84.93% Recall: 85.25% F1: 84.16%

Epoch: 114/150
Train Loss: 0.4849 | Train Acc: 85.27% | Precision: 84.88% Recall: 85.27% F1: 84.19%
Val   Loss: 0.5057 | Val Acc: 83.36%   | Precision: 83.26% Recall: 83.36% F1: 82.46%

Epoch: 115/150
Train Loss: 0.4746 | Train Acc: 85.64% | Precision: 85.32% Recall: 85.64% F1: 84.65%
Val   Loss: 0.4420 | Val Acc: 86.70%   | Precision: 86.51% Recall: 86.70% F1: 85.69%

Epoch: 116/150
Train Loss: 0.4615 | Train Acc: 85.97% | Precision: 85.73% Recall: 85.97% F1: 85.04%
Val   Loss: 0.4540 | Val Acc: 86.04%   | Precision: 86.12% Recall: 86.04% F1: 85.37%

Epoch: 117/150
Train Loss: 0.4441 | Train Acc: 86.70% | Precision: 86.62% Recall: 86.70% F1: 85.85%
Val   Loss: 0.4452 | Val Acc: 86.04%   | Precision: 86.07% Recall: 86.04% F1: 85.10%

Epoch: 118/150
Train Loss: 0.4495 | Train Acc: 86.41% | Precision: 86.26% Recall: 86.41% F1: 85.52%
Val   Loss: 0.4452 | Val Acc: 86.08%   | Precision: 85.78% Recall: 86.08% F1: 84.82%

Epoch: 119/150
Train Loss: 0.4393 | Train Acc: 86.77% | Precision: 86.69% Recall: 86.77% F1: 85.92%
Val   Loss: 0.4519 | Val Acc: 85.77%   | Precision: 85.40% Recall: 85.77% F1: 84.17%

Epoch: 120/150
Train Loss: 0.4290 | Train Acc: 87.12% | Precision: 87.04% Recall: 87.12% F1: 86.34%
Val   Loss: 0.5005 | Val Acc: 83.78%   | Precision: 84.31% Recall: 83.78% F1: 83.59%

Epoch: 121/150
Train Loss: 0.4169 | Train Acc: 87.57% | Precision: 87.55% Recall: 87.57% F1: 86.83%
Val   Loss: 0.4136 | Val Acc: 87.41%   | Precision: 87.57% Recall: 87.41% F1: 86.41%

Epoch: 122/150
Train Loss: 0.6043 | Train Acc: 79.90% | Precision: 79.45% Recall: 79.90% F1: 77.74%
Val   Loss: 0.6590 | Val Acc: 78.11%   | Precision: 72.09% Recall: 78.11% F1: 73.63%

Epoch: 123/150
Train Loss: 0.4637 | Train Acc: 85.73% | Precision: 85.54% Recall: 85.73% F1: 84.73%
Val   Loss: 0.4226 | Val Acc: 87.27%   | Precision: 87.53% Recall: 87.27% F1: 86.58%

Epoch: 124/150
Train Loss: 0.4241 | Train Acc: 87.19% | Precision: 87.16% Recall: 87.19% F1: 86.45%
Val   Loss: 0.5285 | Val Acc: 83.41%   | Precision: 82.06% Recall: 83.41% F1: 81.08%

Epoch: 125/150
Train Loss: 0.5123 | Train Acc: 83.84% | Precision: 83.83% Recall: 83.84% F1: 82.65%
Val   Loss: 0.8127 | Val Acc: 71.62%   | Precision: 60.35% Recall: 71.62% F1: 64.91%

Epoch: 126/150
Train Loss: 0.8497 | Train Acc: 71.41% | Precision: 69.23% Recall: 71.41% F1: 64.58%
Val   Loss: 0.8838 | Val Acc: 68.76%   | Precision: 55.42% Recall: 68.76% F1: 60.87%

Epoch: 127/150
Train Loss: 0.7839 | Train Acc: 73.68% | Precision: 66.36% Recall: 73.68% F1: 66.94%
Val   Loss: 0.7462 | Val Acc: 75.43%   | Precision: 68.17% Recall: 75.43% F1: 69.15%

Epoch: 128/150
Train Loss: 0.7115 | Train Acc: 76.49% | Precision: 78.16% Recall: 76.49% F1: 69.89%
Val   Loss: 0.6528 | Val Acc: 79.09%   | Precision: 80.36% Recall: 79.09% F1: 74.29%

Epoch: 129/150
Train Loss: 0.6052 | Train Acc: 81.21% | Precision: 81.97% Recall: 81.21% F1: 77.43%
Val   Loss: 0.5707 | Val Acc: 82.82%   | Precision: 83.78% Recall: 82.82% F1: 79.70%

Epoch: 130/150
Train Loss: 0.5550 | Train Acc: 82.95% | Precision: 82.89% Recall: 82.95% F1: 79.93%
Val   Loss: 0.5142 | Val Acc: 83.94%   | Precision: 83.77% Recall: 83.94% F1: 81.45%

Epoch: 131/150
Train Loss: 0.4967 | Train Acc: 84.95% | Precision: 84.51% Recall: 84.95% F1: 83.23%
Val   Loss: 0.4733 | Val Acc: 85.45%   | Precision: 84.90% Recall: 85.45% F1: 84.12%

Epoch: 132/150
Train Loss: 0.8779 | Train Acc: 74.93% | Precision: 75.05% Recall: 74.93% F1: 71.51%
Val   Loss: 1.0418 | Val Acc: 64.24%   | Precision: 44.02% Recall: 64.24% F1: 50.79%

Epoch: 133/150
Train Loss: 1.0231 | Train Acc: 66.14% | Precision: 55.90% Recall: 66.14% F1: 56.68%
Val   Loss: 0.9345 | Val Acc: 69.79%   | Precision: 61.53% Recall: 69.79% F1: 61.85%

Epoch: 134/150
Train Loss: 0.9912 | Train Acc: 66.16% | Precision: 57.98% Recall: 66.16% F1: 57.42%
Val   Loss: 0.8999 | Val Acc: 68.78%   | Precision: 64.21% Recall: 68.78% F1: 60.99%

Epoch: 135/150
Train Loss: 0.9259 | Train Acc: 67.50% | Precision: 59.54% Recall: 67.50% F1: 60.20%
Val   Loss: 0.8522 | Val Acc: 69.93%   | Precision: 66.49% Recall: 69.93% F1: 62.78%

Epoch: 136/150
Train Loss: 0.7706 | Train Acc: 75.22% | Precision: 68.89% Recall: 75.22% F1: 70.29%
Val   Loss: 0.8538 | Val Acc: 69.41%   | Precision: 65.29% Recall: 69.41% F1: 64.56%

Epoch: 137/150
Train Loss: 0.7563 | Train Acc: 76.19% | Precision: 69.65% Recall: 76.19% F1: 71.21%
Val   Loss: 0.6936 | Val Acc: 79.54%   | Precision: 73.99% Recall: 79.54% F1: 74.86%

Epoch: 138/150
Train Loss: 0.6783 | Train Acc: 78.47% | Precision: 75.57% Recall: 78.47% F1: 73.58%
Val   Loss: 0.6257 | Val Acc: 80.14%   | Precision: 76.12% Recall: 80.14% F1: 74.76%

Epoch: 139/150
Train Loss: 0.6459 | Train Acc: 79.25% | Precision: 73.02% Recall: 79.25% F1: 74.39%
Val   Loss: 0.5991 | Val Acc: 80.47%   | Precision: 76.32% Recall: 80.47% F1: 75.55%

Epoch: 140/150
Train Loss: 0.6233 | Train Acc: 79.75% | Precision: 75.23% Recall: 79.75% F1: 75.14%
Val   Loss: 0.6356 | Val Acc: 80.29%   | Precision: 74.66% Recall: 80.29% F1: 75.72%

Epoch: 141/150
Train Loss: 0.6043 | Train Acc: 80.30% | Precision: 75.84% Recall: 80.30% F1: 75.98%
Val   Loss: 0.6023 | Val Acc: 80.89%   | Precision: 75.31% Recall: 80.89% F1: 76.81%

Epoch: 142/150
Train Loss: 0.6426 | Train Acc: 78.95% | Precision: 74.38% Recall: 78.95% F1: 74.50%
Val   Loss: 0.5985 | Val Acc: 80.54%   | Precision: 77.57% Recall: 80.54% F1: 75.73%

Epoch: 143/150
Train Loss: 0.5890 | Train Acc: 80.63% | Precision: 77.23% Recall: 80.63% F1: 76.58%
Val   Loss: 0.6269 | Val Acc: 79.09%   | Precision: 80.10% Recall: 79.09% F1: 76.00%

Epoch: 144/150
Train Loss: 0.5886 | Train Acc: 80.56% | Precision: 76.48% Recall: 80.56% F1: 76.66%
Val   Loss: 0.5628 | Val Acc: 81.24%   | Precision: 77.38% Recall: 81.24% F1: 77.68%

Epoch: 145/150
Train Loss: 0.5813 | Train Acc: 80.75% | Precision: 77.32% Recall: 80.75% F1: 76.98%
Val   Loss: 0.5701 | Val Acc: 81.34%   | Precision: 81.35% Recall: 81.34% F1: 76.98%

Epoch: 146/150
Train Loss: 0.5549 | Train Acc: 81.75% | Precision: 78.55% Recall: 81.75% F1: 78.23%
Val   Loss: 0.5365 | Val Acc: 82.60%   | Precision: 79.32% Recall: 82.60% F1: 79.22%

Epoch: 147/150
Train Loss: 0.5621 | Train Acc: 81.33% | Precision: 79.19% Recall: 81.33% F1: 77.90%
Val   Loss: 0.5306 | Val Acc: 83.17%   | Precision: 80.51% Recall: 83.17% F1: 79.75%

Epoch: 148/150
Train Loss: 0.5875 | Train Acc: 80.60% | Precision: 78.62% Recall: 80.60% F1: 77.08%
Val   Loss: 0.5383 | Val Acc: 81.89%   | Precision: 76.36% Recall: 81.89% F1: 78.47%

Epoch: 149/150
Train Loss: 0.5398 | Train Acc: 82.04% | Precision: 81.49% Recall: 82.04% F1: 79.06%
Val   Loss: 0.4983 | Val Acc: 83.59%   | Precision: 82.21% Recall: 83.59% F1: 80.25%

Epoch: 150/150
Train Loss: 0.5371 | Train Acc: 82.29% | Precision: 81.60% Recall: 82.29% F1: 79.95%
Val   Loss: 0.5763 | Val Acc: 79.89%   | Precision: 77.77% Recall: 79.89% F1: 75.46%

### LSTM

In [68]:
sweep_config = {
    "name": "LSTM-ECG",
    "method": "bayes",  
    "metric": {"name": "val_loss", "goal": "minimize"},
    "parameters": {
        "rnn_type": {"value": "lstm"},
        "hidden_dim": {"values": [64, 128, 256, 512]},
        "bidirectional": {"values": [False, True]},
        "batch_size": {"values": [32, 64, 128]},
        "optimizer": {"values": ["adam", "sgd"]},
        "learning_rate": {"distribution": "uniform", "min": 0.0001, "max": 0.001},
        "weight_decay": {"values": [0.0, 1e-5, 1e-4, 1e-3]},
        "seq_len": {"values": [80,120,130,140,150,160]}
    }
}

In [69]:
wandb.agent(sweep_id, train_wandb_rnn, count=3)

wandb: Agent Starting Run: xzcgji1e with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.00011416583404421928
wandb: 	optimizer: sgd
wandb: 	rnn_type: rnn
wandb: 	seq_len: 140
wandb: 	weight_decay: 0.0001

Epoch: 1/150
Train Loss: 1.6671 | Train Acc: 62.61% | Precision: 45.70% Recall: 62.61% F1: 50.19%
Val   Loss: 1.2498 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.1810 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1464 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1381 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1332 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1310 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1292 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.1281 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1277 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.1264 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1260 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 7/150
Train Loss: 1.1252 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1247 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 8/150
Train Loss: 1.1241 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1235 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 9/150
Train Loss: 1.1231 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1229 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 10/150
Train Loss: 1.1221 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1218 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 11/150
Train Loss: 1.1212 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1211 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 12/150
Train Loss: 1.1200 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1199 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 13/150
Train Loss: 1.1190 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1200 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 14/150
Train Loss: 1.1179 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1183 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 15/150
Train Loss: 1.1169 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1171 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 16/150
Train Loss: 1.1154 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1157 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 17/150
Train Loss: 1.1140 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1143 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 18/150
Train Loss: 1.1125 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1128 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 19/150
Train Loss: 1.1107 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1109 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 20/150
Train Loss: 1.1085 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1093 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 21/150
Train Loss: 1.1064 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1064 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 22/150
Train Loss: 1.1036 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1041 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 23/150
Train Loss: 1.1002 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1004 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 24/150
Train Loss: 1.0963 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0960 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 25/150
Train Loss: 1.0912 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0905 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 26/150
Train Loss: 1.0844 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0827 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 27/150
Train Loss: 1.0757 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0726 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 28/150
Train Loss: 1.0626 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0562 | Val Acc: 64.53%   | Precision: 41.67% Recall: 64.53% F1: 50.64%

Epoch: 29/150
Train Loss: 1.0418 | Train Acc: 64.56% | Precision: 47.30% Recall: 64.56% F1: 50.69%
Val   Loss: 1.0291 | Val Acc: 64.48%   | Precision: 43.95% Recall: 64.48% F1: 50.66%

Epoch: 30/150
Train Loss: 1.0040 | Train Acc: 64.29% | Precision: 44.80% Recall: 64.29% F1: 50.98%
Val   Loss: 0.9762 | Val Acc: 64.18%   | Precision: 45.94% Recall: 64.18% F1: 51.83%

Epoch: 31/150
Train Loss: 0.9475 | Train Acc: 68.22% | Precision: 54.40% Recall: 68.22% F1: 59.16%
Val   Loss: 0.9287 | Val Acc: 70.16%   | Precision: 56.11% Recall: 70.16% F1: 61.35%

Epoch: 32/150
Train Loss: 0.9166 | Train Acc: 70.22% | Precision: 56.25% Recall: 70.22% F1: 61.65%
Val   Loss: 0.9050 | Val Acc: 70.63%   | Precision: 56.74% Recall: 70.63% F1: 62.31%

Epoch: 33/150
Train Loss: 0.8964 | Train Acc: 70.79% | Precision: 56.80% Recall: 70.79% F1: 62.32%
Val   Loss: 0.8868 | Val Acc: 70.79%   | Precision: 56.84% Recall: 70.79% F1: 62.46%

Epoch: 34/150
Train Loss: 0.8799 | Train Acc: 71.03% | Precision: 57.04% Recall: 71.03% F1: 62.61%
Val   Loss: 0.8716 | Val Acc: 71.50%   | Precision: 57.41% Recall: 71.50% F1: 62.91%

Epoch: 35/150
Train Loss: 0.8658 | Train Acc: 71.55% | Precision: 57.50% Recall: 71.55% F1: 63.03%
Val   Loss: 0.8591 | Val Acc: 71.59%   | Precision: 57.48% Recall: 71.59% F1: 63.05%

Epoch: 36/150
Train Loss: 0.8542 | Train Acc: 71.70% | Precision: 57.72% Recall: 71.70% F1: 63.24%
Val   Loss: 0.8542 | Val Acc: 71.62%   | Precision: 57.52% Recall: 71.62% F1: 63.13%

Epoch: 37/150
Train Loss: 0.8449 | Train Acc: 71.75% | Precision: 58.01% Recall: 71.75% F1: 63.44%
Val   Loss: 0.8432 | Val Acc: 71.89%   | Precision: 58.33% Recall: 71.89% F1: 63.74%

Epoch: 38/150
Train Loss: 0.8381 | Train Acc: 71.71% | Precision: 58.38% Recall: 71.71% F1: 63.56%
Val   Loss: 0.8360 | Val Acc: 72.04%   | Precision: 58.41% Recall: 72.04% F1: 63.72%

Epoch: 39/150
Train Loss: 0.8334 | Train Acc: 71.70% | Precision: 58.62% Recall: 71.70% F1: 63.69%
Val   Loss: 0.8317 | Val Acc: 72.19%   | Precision: 58.58% Recall: 72.19% F1: 63.81%

Epoch: 40/150
Train Loss: 0.8290 | Train Acc: 71.63% | Precision: 58.70% Recall: 71.63% F1: 63.70%
Val   Loss: 0.8274 | Val Acc: 71.77%   | Precision: 59.08% Recall: 71.77% F1: 63.94%

Epoch: 41/150
Train Loss: 0.8260 | Train Acc: 71.62% | Precision: 58.90% Recall: 71.62% F1: 63.85%
Val   Loss: 0.8280 | Val Acc: 71.86%   | Precision: 58.99% Recall: 71.86% F1: 63.96%

Epoch: 42/150
Train Loss: 0.8230 | Train Acc: 71.60% | Precision: 59.16% Recall: 71.60% F1: 63.89%
Val   Loss: 0.8226 | Val Acc: 71.92%   | Precision: 59.21% Recall: 71.92% F1: 64.02%

Epoch: 43/150
Train Loss: 0.8186 | Train Acc: 71.72% | Precision: 59.34% Recall: 71.72% F1: 64.05%
Val   Loss: 0.8219 | Val Acc: 71.83%   | Precision: 60.01% Recall: 71.83% F1: 64.09%

Epoch: 44/150
Train Loss: 0.8143 | Train Acc: 71.82% | Precision: 59.62% Recall: 71.82% F1: 64.19%
Val   Loss: 0.8189 | Val Acc: 71.90%   | Precision: 59.27% Recall: 71.90% F1: 64.16%

Epoch: 45/150
Train Loss: 0.8094 | Train Acc: 71.85% | Precision: 59.59% Recall: 71.85% F1: 64.24%
Val   Loss: 0.8095 | Val Acc: 72.05%   | Precision: 59.94% Recall: 72.05% F1: 64.35%

Epoch: 46/150
Train Loss: 0.8025 | Train Acc: 72.03% | Precision: 59.93% Recall: 72.03% F1: 64.44%
Val   Loss: 0.8006 | Val Acc: 72.40%   | Precision: 59.43% Recall: 72.40% F1: 64.44%

Epoch: 47/150
Train Loss: 0.7918 | Train Acc: 72.33% | Precision: 59.73% Recall: 72.33% F1: 64.52%
Val   Loss: 0.7931 | Val Acc: 72.50%   | Precision: 59.39% Recall: 72.50% F1: 64.61%

Epoch: 48/150
Train Loss: 0.7835 | Train Acc: 72.55% | Precision: 59.81% Recall: 72.55% F1: 64.72%
Val   Loss: 0.7839 | Val Acc: 72.87%   | Precision: 60.67% Recall: 72.87% F1: 65.13%

Epoch: 49/150
Train Loss: 0.7779 | Train Acc: 72.73% | Precision: 60.32% Recall: 72.73% F1: 64.97%
Val   Loss: 0.7776 | Val Acc: 73.33%   | Precision: 60.12% Recall: 73.33% F1: 65.22%

Epoch: 50/150
Train Loss: 0.7705 | Train Acc: 73.20% | Precision: 61.14% Recall: 73.20% F1: 65.58%
Val   Loss: 0.7727 | Val Acc: 73.58%   | Precision: 61.25% Recall: 73.58% F1: 65.66%

Epoch: 51/150
Train Loss: 0.7631 | Train Acc: 73.68% | Precision: 62.34% Recall: 73.68% F1: 66.29%
Val   Loss: 0.7645 | Val Acc: 74.22%   | Precision: 62.55% Recall: 74.22% F1: 66.61%

Epoch: 52/150
Train Loss: 0.7552 | Train Acc: 74.22% | Precision: 63.15% Recall: 74.22% F1: 67.08%
Val   Loss: 0.7644 | Val Acc: 74.35%   | Precision: 64.08% Recall: 74.35% F1: 67.01%

Epoch: 53/150
Train Loss: 0.7435 | Train Acc: 75.02% | Precision: 66.02% Recall: 75.02% F1: 68.39%
Val   Loss: 0.7376 | Val Acc: 75.26%   | Precision: 69.04% Recall: 75.26% F1: 68.94%

Epoch: 54/150
Train Loss: 0.7133 | Train Acc: 75.92% | Precision: 70.02% Recall: 75.92% F1: 70.18%
Val   Loss: 0.7157 | Val Acc: 76.72%   | Precision: 70.61% Recall: 76.72% F1: 71.44%

Epoch: 55/150
Train Loss: 0.6947 | Train Acc: 77.21% | Precision: 71.47% Recall: 77.21% F1: 72.19%
Val   Loss: 0.7101 | Val Acc: 77.58%   | Precision: 71.31% Recall: 77.58% F1: 72.80%

Epoch: 56/150
Train Loss: 0.6794 | Train Acc: 77.93% | Precision: 72.04% Recall: 77.93% F1: 73.19%
Val   Loss: 0.6837 | Val Acc: 78.07%   | Precision: 71.95% Recall: 78.07% F1: 73.32%

Epoch: 57/150
Train Loss: 0.6642 | Train Acc: 78.41% | Precision: 72.52% Recall: 78.41% F1: 73.91%
Val   Loss: 0.6691 | Val Acc: 78.85%   | Precision: 72.71% Recall: 78.85% F1: 74.54%

Epoch: 58/150
Train Loss: 0.6489 | Train Acc: 78.99% | Precision: 73.12% Recall: 78.99% F1: 74.78%
Val   Loss: 0.6632 | Val Acc: 79.71%   | Precision: 73.65% Recall: 79.71% F1: 75.74%

Epoch: 59/150
Train Loss: 0.6399 | Train Acc: 79.54% | Precision: 73.72% Recall: 79.54% F1: 75.56%
Val   Loss: 0.6686 | Val Acc: 78.86%   | Precision: 73.10% Recall: 78.86% F1: 73.56%

Epoch: 60/150
Train Loss: 0.6232 | Train Acc: 80.12% | Precision: 74.38% Recall: 80.12% F1: 76.28%
Val   Loss: 0.6712 | Val Acc: 78.76%   | Precision: 72.88% Recall: 78.76% F1: 73.30%

Epoch: 61/150
Train Loss: 0.6167 | Train Acc: 80.10% | Precision: 75.70% Recall: 80.10% F1: 76.39%
Val   Loss: 0.6156 | Val Acc: 81.24%   | Precision: 75.91% Recall: 81.24% F1: 77.20%

Epoch: 62/150
Train Loss: 0.6033 | Train Acc: 80.65% | Precision: 76.61% Recall: 80.65% F1: 77.16%
Val   Loss: 0.6193 | Val Acc: 80.48%   | Precision: 78.98% Recall: 80.48% F1: 78.64%

Epoch: 63/150
Train Loss: 0.5996 | Train Acc: 80.91% | Precision: 78.38% Recall: 80.91% F1: 78.00%
Val   Loss: 0.5928 | Val Acc: 81.90%   | Precision: 77.39% Recall: 81.90% F1: 78.58%

Epoch: 64/150
Train Loss: 0.5904 | Train Acc: 81.72% | Precision: 80.32% Recall: 81.72% F1: 79.28%
Val   Loss: 0.6306 | Val Acc: 79.89%   | Precision: 78.91% Recall: 79.89% F1: 78.27%

Epoch: 65/150
Train Loss: 0.5653 | Train Acc: 83.06% | Precision: 82.26% Recall: 83.06% F1: 81.20%
Val   Loss: 0.5651 | Val Acc: 84.67%   | Precision: 83.92% Recall: 84.67% F1: 83.62%

Epoch: 66/150
Train Loss: 0.5591 | Train Acc: 83.65% | Precision: 82.95% Recall: 83.65% F1: 82.10%
Val   Loss: 0.5497 | Val Acc: 85.03%   | Precision: 84.60% Recall: 85.03% F1: 83.76%

Epoch: 67/150
Train Loss: 0.5625 | Train Acc: 83.30% | Precision: 82.50% Recall: 83.30% F1: 81.79%
Val   Loss: 0.5572 | Val Acc: 84.47%   | Precision: 84.06% Recall: 84.47% F1: 83.25%

Epoch: 68/150
Train Loss: 0.5573 | Train Acc: 83.76% | Precision: 83.11% Recall: 83.76% F1: 82.38%
Val   Loss: 0.5409 | Val Acc: 85.18%   | Precision: 84.88% Recall: 85.18% F1: 83.77%

Epoch: 69/150
Train Loss: 0.5330 | Train Acc: 84.81% | Precision: 84.34% Recall: 84.81% F1: 83.65%
Val   Loss: 0.5446 | Val Acc: 85.48%   | Precision: 84.96% Recall: 85.48% F1: 84.32%

Epoch: 70/150
Train Loss: 0.5192 | Train Acc: 85.59% | Precision: 85.24% Recall: 85.59% F1: 84.55%
Val   Loss: 0.5355 | Val Acc: 84.74%   | Precision: 84.33% Recall: 84.74% F1: 83.22%

Epoch: 71/150
Train Loss: 0.5144 | Train Acc: 85.67% | Precision: 85.34% Recall: 85.67% F1: 84.62%
Val   Loss: 0.5140 | Val Acc: 86.35%   | Precision: 86.06% Recall: 86.35% F1: 85.22%

Epoch: 72/150
Train Loss: 0.5074 | Train Acc: 85.85% | Precision: 85.56% Recall: 85.85% F1: 84.84%
Val   Loss: 0.5130 | Val Acc: 85.64%   | Precision: 85.30% Recall: 85.64% F1: 84.70%

Epoch: 73/150
Train Loss: 0.4981 | Train Acc: 86.19% | Precision: 85.98% Recall: 86.19% F1: 85.21%
Val   Loss: 0.5051 | Val Acc: 86.53%   | Precision: 86.18% Recall: 86.53% F1: 85.48%

Epoch: 74/150
Train Loss: 0.4946 | Train Acc: 86.23% | Precision: 85.96% Recall: 86.23% F1: 85.26%
Val   Loss: 0.5079 | Val Acc: 86.07%   | Precision: 85.83% Recall: 86.07% F1: 85.22%

Epoch: 75/150
Train Loss: 0.4868 | Train Acc: 86.28% | Precision: 86.08% Recall: 86.28% F1: 85.33%
Val   Loss: 0.5009 | Val Acc: 86.26%   | Precision: 85.96% Recall: 86.26% F1: 85.12%

Epoch: 76/150
Train Loss: 0.4766 | Train Acc: 86.79% | Precision: 86.61% Recall: 86.79% F1: 85.84%
Val   Loss: 0.4908 | Val Acc: 86.14%   | Precision: 85.94% Recall: 86.14% F1: 85.11%

Epoch: 77/150
Train Loss: 0.4738 | Train Acc: 86.74% | Precision: 86.54% Recall: 86.74% F1: 85.80%
Val   Loss: 0.4827 | Val Acc: 86.65%   | Precision: 86.46% Recall: 86.65% F1: 85.59%

Epoch: 78/150
Train Loss: 0.4643 | Train Acc: 86.94% | Precision: 86.75% Recall: 86.94% F1: 86.01%
Val   Loss: 0.4883 | Val Acc: 86.17%   | Precision: 85.87% Recall: 86.17% F1: 84.99%

Epoch: 79/150
Train Loss: 0.4575 | Train Acc: 87.14% | Precision: 86.99% Recall: 87.14% F1: 86.25%
Val   Loss: 0.4826 | Val Acc: 86.32%   | Precision: 85.99% Recall: 86.32% F1: 85.08%

Epoch: 80/150
Train Loss: 0.4507 | Train Acc: 87.24% | Precision: 87.06% Recall: 87.24% F1: 86.37%
Val   Loss: 0.4653 | Val Acc: 86.76%   | Precision: 86.54% Recall: 86.76% F1: 85.62%

Epoch: 81/150
Train Loss: 0.4458 | Train Acc: 87.37% | Precision: 87.22% Recall: 87.37% F1: 86.52%
Val   Loss: 0.4610 | Val Acc: 86.91%   | Precision: 86.47% Recall: 86.91% F1: 85.97%

Epoch: 82/150
Train Loss: 0.4412 | Train Acc: 87.47% | Precision: 87.29% Recall: 87.47% F1: 86.64%
Val   Loss: 0.4825 | Val Acc: 85.69%   | Precision: 85.55% Recall: 85.69% F1: 85.01%

Epoch: 83/150
Train Loss: 0.4398 | Train Acc: 87.42% | Precision: 87.24% Recall: 87.42% F1: 86.61%
Val   Loss: 0.4469 | Val Acc: 87.30%   | Precision: 87.01% Recall: 87.30% F1: 86.38%

Epoch: 84/150
Train Loss: 0.4374 | Train Acc: 87.44% | Precision: 87.27% Recall: 87.44% F1: 86.62%
Val   Loss: 0.4406 | Val Acc: 87.42%   | Precision: 87.25% Recall: 87.42% F1: 86.51%

Epoch: 85/150
Train Loss: 0.4283 | Train Acc: 87.64% | Precision: 87.48% Recall: 87.64% F1: 86.86%
Val   Loss: 0.4350 | Val Acc: 87.45%   | Precision: 87.09% Recall: 87.45% F1: 86.59%

Epoch: 86/150
Train Loss: 0.4250 | Train Acc: 87.69% | Precision: 87.53% Recall: 87.69% F1: 86.92%
Val   Loss: 0.4312 | Val Acc: 87.53%   | Precision: 87.24% Recall: 87.53% F1: 86.66%

Epoch: 87/150
Train Loss: 0.4174 | Train Acc: 87.87% | Precision: 87.73% Recall: 87.87% F1: 87.11%
Val   Loss: 0.4407 | Val Acc: 87.01%   | Precision: 86.91% Recall: 87.01% F1: 85.85%

Epoch: 88/150
Train Loss: 0.4130 | Train Acc: 88.12% | Precision: 88.01% Recall: 88.12% F1: 87.38%
Val   Loss: 0.4267 | Val Acc: 87.64%   | Precision: 87.25% Recall: 87.64% F1: 86.90%

Epoch: 89/150
Train Loss: 0.4126 | Train Acc: 87.94% | Precision: 87.80% Recall: 87.94% F1: 87.19%
Val   Loss: 0.4150 | Val Acc: 87.94%   | Precision: 87.77% Recall: 87.94% F1: 87.00%

Epoch: 90/150
Train Loss: 0.4054 | Train Acc: 88.16% | Precision: 88.06% Recall: 88.16% F1: 87.43%
Val   Loss: 0.4185 | Val Acc: 87.70%   | Precision: 87.39% Recall: 87.70% F1: 86.94%

Epoch: 91/150
Train Loss: 0.4007 | Train Acc: 88.28% | Precision: 88.16% Recall: 88.28% F1: 87.58%
Val   Loss: 0.4056 | Val Acc: 88.11%   | Precision: 87.99% Recall: 88.11% F1: 87.21%

Epoch: 92/150
Train Loss: 0.3948 | Train Acc: 88.44% | Precision: 88.33% Recall: 88.44% F1: 87.75%
Val   Loss: 0.3983 | Val Acc: 88.27%   | Precision: 88.09% Recall: 88.27% F1: 87.45%

Epoch: 93/150
Train Loss: 0.3933 | Train Acc: 88.42% | Precision: 88.29% Recall: 88.42% F1: 87.73%
Val   Loss: 0.3957 | Val Acc: 88.26%   | Precision: 88.04% Recall: 88.26% F1: 87.47%

Epoch: 94/150
Train Loss: 0.3922 | Train Acc: 88.36% | Precision: 88.27% Recall: 88.36% F1: 87.67%
Val   Loss: 0.4127 | Val Acc: 87.75%   | Precision: 87.67% Recall: 87.75% F1: 86.74%

Epoch: 95/150
Train Loss: 0.3913 | Train Acc: 88.39% | Precision: 88.30% Recall: 88.39% F1: 87.68%
Val   Loss: 0.4309 | Val Acc: 87.20%   | Precision: 87.12% Recall: 87.20% F1: 86.48%

Epoch: 96/150
Train Loss: 0.3837 | Train Acc: 88.71% | Precision: 88.64% Recall: 88.71% F1: 88.04%
Val   Loss: 0.3917 | Val Acc: 88.42%   | Precision: 88.22% Recall: 88.42% F1: 87.65%

Epoch: 97/150
Train Loss: 0.3841 | Train Acc: 88.68% | Precision: 88.59% Recall: 88.68% F1: 88.02%
Val   Loss: 0.3858 | Val Acc: 88.92%   | Precision: 88.88% Recall: 88.92% F1: 88.15%

Epoch: 98/150
Train Loss: 0.3815 | Train Acc: 88.69% | Precision: 88.61% Recall: 88.69% F1: 88.01%
Val   Loss: 0.3769 | Val Acc: 89.16%   | Precision: 89.01% Recall: 89.16% F1: 88.48%

Epoch: 99/150
Train Loss: 0.3777 | Train Acc: 88.85% | Precision: 88.77% Recall: 88.85% F1: 88.21%
Val   Loss: 0.3839 | Val Acc: 88.92%   | Precision: 88.92% Recall: 88.92% F1: 88.10%

Epoch: 100/150
Train Loss: 0.3696 | Train Acc: 89.11% | Precision: 89.06% Recall: 89.11% F1: 88.46%
Val   Loss: 0.3707 | Val Acc: 89.01%   | Precision: 88.84% Recall: 89.01% F1: 88.29%

Epoch: 101/150
Train Loss: 0.3683 | Train Acc: 89.11% | Precision: 89.08% Recall: 89.11% F1: 88.48%
Val   Loss: 0.3713 | Val Acc: 89.18%   | Precision: 89.08% Recall: 89.18% F1: 88.53%

Epoch: 102/150
Train Loss: 0.3692 | Train Acc: 89.13% | Precision: 89.10% Recall: 89.13% F1: 88.52%
Val   Loss: 0.3765 | Val Acc: 89.10%   | Precision: 89.04% Recall: 89.10% F1: 88.33%

Epoch: 103/150
Train Loss: 0.3679 | Train Acc: 89.12% | Precision: 89.08% Recall: 89.12% F1: 88.49%
Val   Loss: 0.3672 | Val Acc: 89.09%   | Precision: 89.06% Recall: 89.09% F1: 88.31%

Epoch: 104/150
Train Loss: 0.3661 | Train Acc: 89.14% | Precision: 89.06% Recall: 89.14% F1: 88.52%
Val   Loss: 0.3715 | Val Acc: 89.36%   | Precision: 89.20% Recall: 89.36% F1: 88.69%

Epoch: 105/150
Train Loss: 0.3673 | Train Acc: 89.15% | Precision: 89.10% Recall: 89.15% F1: 88.53%
Val   Loss: 0.3897 | Val Acc: 88.36%   | Precision: 88.53% Recall: 88.36% F1: 87.29%

Epoch: 106/150
Train Loss: 0.3554 | Train Acc: 89.51% | Precision: 89.47% Recall: 89.51% F1: 88.91%
Val   Loss: 0.3661 | Val Acc: 89.22%   | Precision: 89.12% Recall: 89.22% F1: 88.57%

Epoch: 107/150
Train Loss: 0.3550 | Train Acc: 89.44% | Precision: 89.40% Recall: 89.44% F1: 88.84%
Val   Loss: 0.3568 | Val Acc: 89.52%   | Precision: 89.42% Recall: 89.52% F1: 88.84%

Epoch: 108/150
Train Loss: 0.3540 | Train Acc: 89.46% | Precision: 89.39% Recall: 89.46% F1: 88.87%
Val   Loss: 0.3591 | Val Acc: 89.33%   | Precision: 89.29% Recall: 89.33% F1: 88.58%

Epoch: 109/150

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: jj4276a1 with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.00010277632970153458
wandb: 	optimizer: sgd
wandb: 	rnn_type: rnn
wandb: 	seq_len: 140
wandb: 	weight_decay: 0.0001

Epoch: 1/150
Train Loss: 1.7028 | Train Acc: 62.35% | Precision: 43.57% Recall: 62.35% F1: 50.62%
Val   Loss: 1.2823 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.2103 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1615 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1459 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1367 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1334 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1310 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.1294 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1281 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.1273 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1268 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 7/150
Train Loss: 1.1260 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1252 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 8/150
Train Loss: 1.1247 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1248 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 9/150
Train Loss: 1.1238 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1236 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 10/150
Train Loss: 1.1229 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1231 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 11/150
Train Loss: 1.1219 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1222 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 12/150
Train Loss: 1.1210 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1209 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 13/150
Train Loss: 1.1199 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1201 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 14/150
Train Loss: 1.1191 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1196 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 15/150
Train Loss: 1.1182 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1183 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 16/150
Train Loss: 1.1172 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1174 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 17/150
Train Loss: 1.1162 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1164 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 18/150
Train Loss: 1.1149 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1150 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 19/150
Train Loss: 1.1136 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1140 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 20/150
Train Loss: 1.1123 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1129 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 21/150
Train Loss: 1.1108 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1109 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 22/150
Train Loss: 1.1089 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1091 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 23/150
Train Loss: 1.1070 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1074 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 24/150
Train Loss: 1.1048 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1054 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 25/150
Train Loss: 1.1022 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1027 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 26/150
Train Loss: 1.0992 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0995 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 27/150
Train Loss: 1.0955 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0955 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 28/150
Train Loss: 1.0910 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0911 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 29/150
Train Loss: 1.0854 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0845 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 30/150
Train Loss: 1.0781 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0762 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 31/150
Train Loss: 1.0679 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0639 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 32/150
Train Loss: 1.0533 | Train Acc: 64.56% | Precision: 48.08% Recall: 64.56% F1: 50.66%
Val   Loss: 1.0456 | Val Acc: 64.48%   | Precision: 41.65% Recall: 64.48% F1: 50.61%

Epoch: 33/150
Train Loss: 1.0295 | Train Acc: 64.55% | Precision: 46.37% Recall: 64.55% F1: 50.75%
Val   Loss: 1.0146 | Val Acc: 64.40%   | Precision: 45.10% Recall: 64.40% F1: 50.85%

Epoch: 34/150
Train Loss: 0.9881 | Train Acc: 64.54% | Precision: 48.90% Recall: 64.54% F1: 52.51%
Val   Loss: 0.9600 | Val Acc: 67.57%   | Precision: 54.19% Recall: 67.57% F1: 58.73%

Epoch: 35/150
Train Loss: 0.9397 | Train Acc: 68.92% | Precision: 55.37% Recall: 68.92% F1: 60.31%
Val   Loss: 0.9263 | Val Acc: 70.63%   | Precision: 56.43% Recall: 70.63% F1: 61.56%

Epoch: 36/150
Train Loss: 0.9160 | Train Acc: 70.31% | Precision: 56.44% Recall: 70.31% F1: 61.82%
Val   Loss: 0.9055 | Val Acc: 70.90%   | Precision: 56.89% Recall: 70.90% F1: 62.38%

Epoch: 37/150
Train Loss: 0.8985 | Train Acc: 70.60% | Precision: 56.77% Recall: 70.60% F1: 62.27%
Val   Loss: 0.8913 | Val Acc: 71.20%   | Precision: 56.95% Recall: 71.20% F1: 62.46%

Epoch: 38/150
Train Loss: 0.8839 | Train Acc: 71.02% | Precision: 57.11% Recall: 71.02% F1: 62.63%
Val   Loss: 0.8764 | Val Acc: 71.31%   | Precision: 57.37% Recall: 71.31% F1: 62.97%

Epoch: 39/150
Train Loss: 0.8710 | Train Acc: 71.42% | Precision: 57.44% Recall: 71.42% F1: 62.95%
Val   Loss: 0.8642 | Val Acc: 71.62%   | Precision: 57.69% Recall: 71.62% F1: 63.23%

Epoch: 40/150
Train Loss: 0.8586 | Train Acc: 71.61% | Precision: 57.71% Recall: 71.61% F1: 63.21%
Val   Loss: 0.8549 | Val Acc: 72.00%   | Precision: 58.16% Recall: 72.00% F1: 63.51%

Epoch: 41/150
Train Loss: 0.8491 | Train Acc: 71.79% | Precision: 58.00% Recall: 71.79% F1: 63.43%
Val   Loss: 0.8463 | Val Acc: 71.90%   | Precision: 58.17% Recall: 71.90% F1: 63.54%

Epoch: 42/150
Train Loss: 0.8411 | Train Acc: 71.83% | Precision: 58.24% Recall: 71.83% F1: 63.58%
Val   Loss: 0.8383 | Val Acc: 71.80%   | Precision: 58.24% Recall: 71.80% F1: 63.59%

Epoch: 43/150
Train Loss: 0.8370 | Train Acc: 71.65% | Precision: 58.50% Recall: 71.65% F1: 63.59%
Val   Loss: 0.8381 | Val Acc: 71.82%   | Precision: 58.36% Recall: 71.82% F1: 63.69%

Epoch: 44/150
Train Loss: 0.8318 | Train Acc: 71.64% | Precision: 58.65% Recall: 71.64% F1: 63.70%
Val   Loss: 0.8308 | Val Acc: 71.83%   | Precision: 58.41% Recall: 71.83% F1: 63.69%

Epoch: 45/150
Train Loss: 0.8278 | Train Acc: 71.61% | Precision: 58.72% Recall: 71.61% F1: 63.74%
Val   Loss: 0.8267 | Val Acc: 71.72%   | Precision: 58.58% Recall: 71.72% F1: 63.78%

Epoch: 46/150
Train Loss: 0.8238 | Train Acc: 71.62% | Precision: 59.04% Recall: 71.62% F1: 63.90%
Val   Loss: 0.8325 | Val Acc: 71.15%   | Precision: 58.69% Recall: 71.15% F1: 63.58%

Epoch: 47/150
Train Loss: 0.8192 | Train Acc: 71.64% | Precision: 59.16% Recall: 71.64% F1: 63.93%
Val   Loss: 0.8245 | Val Acc: 71.47%   | Precision: 59.44% Recall: 71.47% F1: 63.91%

Epoch: 48/150
Train Loss: 0.8155 | Train Acc: 71.69% | Precision: 59.21% Recall: 71.69% F1: 64.04%
Val   Loss: 0.8177 | Val Acc: 71.93%   | Precision: 59.15% Recall: 71.93% F1: 64.14%

Epoch: 49/150
Train Loss: 0.8100 | Train Acc: 71.82% | Precision: 59.50% Recall: 71.82% F1: 64.20%
Val   Loss: 0.8107 | Val Acc: 71.98%   | Precision: 58.77% Recall: 71.98% F1: 64.06%

Epoch: 50/150
Train Loss: 0.8033 | Train Acc: 71.99% | Precision: 59.49% Recall: 71.99% F1: 64.33%
Val   Loss: 0.8032 | Val Acc: 71.93%   | Precision: 59.33% Recall: 71.93% F1: 64.21%

Epoch: 51/150
Train Loss: 0.7951 | Train Acc: 72.19% | Precision: 59.46% Recall: 72.19% F1: 64.50%
Val   Loss: 0.8001 | Val Acc: 72.32%   | Precision: 59.87% Recall: 72.32% F1: 64.48%

Epoch: 52/150
Train Loss: 0.7886 | Train Acc: 72.35% | Precision: 59.84% Recall: 72.35% F1: 64.67%
Val   Loss: 0.7908 | Val Acc: 72.70%   | Precision: 59.46% Recall: 72.70% F1: 64.76%

Epoch: 53/150
Train Loss: 0.7817 | Train Acc: 72.60% | Precision: 60.12% Recall: 72.60% F1: 64.91%
Val   Loss: 0.7848 | Val Acc: 72.69%   | Precision: 60.28% Recall: 72.69% F1: 64.88%

Epoch: 54/150
Train Loss: 0.7732 | Train Acc: 72.85% | Precision: 60.72% Recall: 72.85% F1: 65.27%
Val   Loss: 0.7758 | Val Acc: 73.29%   | Precision: 60.43% Recall: 73.29% F1: 65.28%

Epoch: 55/150
Train Loss: 0.7654 | Train Acc: 73.33% | Precision: 61.98% Recall: 73.33% F1: 65.92%
Val   Loss: 0.7793 | Val Acc: 73.42%   | Precision: 62.74% Recall: 73.42% F1: 65.93%

Epoch: 56/150
Train Loss: 0.7558 | Train Acc: 73.83% | Precision: 63.20% Recall: 73.83% F1: 66.73%
Val   Loss: 0.7535 | Val Acc: 73.92%   | Precision: 66.40% Recall: 73.92% F1: 66.80%

Epoch: 57/150
Train Loss: 0.7264 | Train Acc: 74.60% | Precision: 68.11% Recall: 74.60% F1: 68.22%
Val   Loss: 0.7293 | Val Acc: 75.23%   | Precision: 69.55% Recall: 75.23% F1: 69.25%

Epoch: 58/150
Train Loss: 0.7055 | Train Acc: 75.84% | Precision: 69.77% Recall: 75.84% F1: 70.29%
Val   Loss: 0.7139 | Val Acc: 76.14%   | Precision: 69.82% Recall: 76.14% F1: 70.71%

Epoch: 59/150
Train Loss: 0.6949 | Train Acc: 76.48% | Precision: 70.36% Recall: 76.48% F1: 71.40%
Val   Loss: 0.7006 | Val Acc: 76.87%   | Precision: 70.50% Recall: 76.87% F1: 71.40%

Epoch: 60/150
Train Loss: 0.6811 | Train Acc: 77.10% | Precision: 70.96% Recall: 77.10% F1: 72.32%
Val   Loss: 0.6910 | Val Acc: 77.26%   | Precision: 70.92% Recall: 77.26% F1: 72.40%

Epoch: 61/150
Train Loss: 0.6670 | Train Acc: 77.85% | Precision: 71.70% Recall: 77.85% F1: 73.30%
Val   Loss: 0.6956 | Val Acc: 76.85%   | Precision: 70.18% Recall: 76.85% F1: 71.32%

Epoch: 62/150
Train Loss: 0.6569 | Train Acc: 78.32% | Precision: 72.25% Recall: 78.32% F1: 73.94%
Val   Loss: 0.6735 | Val Acc: 78.92%   | Precision: 72.78% Recall: 78.92% F1: 74.49%

Epoch: 63/150
Train Loss: 0.6458 | Train Acc: 78.89% | Precision: 72.91% Recall: 78.89% F1: 74.64%
Val   Loss: 0.6574 | Val Acc: 79.59%   | Precision: 73.55% Recall: 79.59% F1: 75.71%

Epoch: 64/150
Train Loss: 0.6361 | Train Acc: 79.48% | Precision: 73.57% Recall: 79.48% F1: 75.44%
Val   Loss: 0.6594 | Val Acc: 78.61%   | Precision: 72.42% Recall: 78.61% F1: 73.94%

Epoch: 65/150
Train Loss: 0.6266 | Train Acc: 80.01% | Precision: 74.21% Recall: 80.01% F1: 76.04%
Val   Loss: 0.6316 | Val Acc: 80.06%   | Precision: 74.16% Recall: 80.06% F1: 76.14%

Epoch: 66/150
Train Loss: 0.6148 | Train Acc: 80.56% | Precision: 74.85% Recall: 80.56% F1: 76.75%
Val   Loss: 0.6379 | Val Acc: 79.64%   | Precision: 74.01% Recall: 79.64% F1: 75.07%

Epoch: 67/150
Train Loss: 0.6074 | Train Acc: 81.03% | Precision: 75.40% Recall: 81.03% F1: 77.30%
Val   Loss: 0.6204 | Val Acc: 80.25%   | Precision: 74.54% Recall: 80.25% F1: 76.21%

Epoch: 68/150
Train Loss: 0.5949 | Train Acc: 81.60% | Precision: 76.04% Recall: 81.60% F1: 77.97%
Val   Loss: 0.6857 | Val Acc: 79.15%   | Precision: 73.22% Recall: 79.15% F1: 73.60%

Epoch: 69/150
Train Loss: 0.5919 | Train Acc: 81.73% | Precision: 77.02% Recall: 81.73% F1: 78.14%
Val   Loss: 0.5915 | Val Acc: 82.26%   | Precision: 78.36% Recall: 82.26% F1: 78.94%

Epoch: 70/150
Train Loss: 0.5778 | Train Acc: 82.09% | Precision: 77.99% Recall: 82.09% F1: 78.66%
Val   Loss: 0.5839 | Val Acc: 82.07%   | Precision: 77.51% Recall: 82.07% F1: 78.41%

Epoch: 71/150
Train Loss: 0.5761 | Train Acc: 82.17% | Precision: 79.35% Recall: 82.17% F1: 79.20%
Val   Loss: 0.5714 | Val Acc: 83.12%   | Precision: 79.97% Recall: 83.12% F1: 80.51%

Epoch: 72/150
Train Loss: 0.5669 | Train Acc: 82.69% | Precision: 80.76% Recall: 82.69% F1: 80.40%
Val   Loss: 0.5647 | Val Acc: 83.62%   | Precision: 81.67% Recall: 83.62% F1: 81.00%

Epoch: 73/150
Train Loss: 0.5538 | Train Acc: 83.32% | Precision: 81.95% Recall: 83.32% F1: 81.58%
Val   Loss: 0.5521 | Val Acc: 83.71%   | Precision: 82.07% Recall: 83.71% F1: 81.73%

Epoch: 74/150
Train Loss: 0.5441 | Train Acc: 84.12% | Precision: 83.10% Recall: 84.12% F1: 82.74%
Val   Loss: 0.5823 | Val Acc: 82.35%   | Precision: 78.85% Recall: 82.35% F1: 78.70%

Epoch: 75/150
Train Loss: 0.5334 | Train Acc: 84.68% | Precision: 83.90% Recall: 84.68% F1: 83.43%
Val   Loss: 0.5377 | Val Acc: 85.48%   | Precision: 84.99% Recall: 85.48% F1: 83.94%

Epoch: 76/150
Train Loss: 0.5250 | Train Acc: 85.29% | Precision: 84.68% Recall: 85.29% F1: 84.15%
Val   Loss: 0.5498 | Val Acc: 84.40%   | Precision: 84.13% Recall: 84.40% F1: 83.79%

Epoch: 77/150
Train Loss: 0.5199 | Train Acc: 85.46% | Precision: 85.01% Recall: 85.46% F1: 84.38%
Val   Loss: 0.5341 | Val Acc: 85.75%   | Precision: 85.26% Recall: 85.75% F1: 84.41%

Epoch: 78/150
Train Loss: 0.5126 | Train Acc: 85.94% | Precision: 85.59% Recall: 85.94% F1: 84.89%
Val   Loss: 0.5397 | Val Acc: 85.32%   | Precision: 84.83% Recall: 85.32% F1: 84.40%

Epoch: 79/150
Train Loss: 0.5062 | Train Acc: 85.88% | Precision: 85.53% Recall: 85.88% F1: 84.86%
Val   Loss: 0.5154 | Val Acc: 85.19%   | Precision: 84.84% Recall: 85.19% F1: 83.77%

Epoch: 80/150
Train Loss: 0.4991 | Train Acc: 86.28% | Precision: 86.00% Recall: 86.28% F1: 85.31%
Val   Loss: 0.5031 | Val Acc: 86.45%   | Precision: 86.18% Recall: 86.45% F1: 85.34%

Epoch: 81/150
Train Loss: 0.4946 | Train Acc: 86.32% | Precision: 86.09% Recall: 86.32% F1: 85.33%
Val   Loss: 0.5058 | Val Acc: 86.30%   | Precision: 85.92% Recall: 86.30% F1: 85.24%

Epoch: 82/150
Train Loss: 0.4909 | Train Acc: 86.34% | Precision: 86.12% Recall: 86.34% F1: 85.35%
Val   Loss: 0.5049 | Val Acc: 85.93%   | Precision: 85.72% Recall: 85.93% F1: 85.06%

Epoch: 83/150
Train Loss: 0.4855 | Train Acc: 86.41% | Precision: 86.20% Recall: 86.41% F1: 85.44%
Val   Loss: 0.5051 | Val Acc: 85.31%   | Precision: 85.14% Recall: 85.31% F1: 83.58%

Epoch: 84/150
Train Loss: 0.4767 | Train Acc: 86.76% | Precision: 86.57% Recall: 86.76% F1: 85.84%
Val   Loss: 0.4899 | Val Acc: 85.85%   | Precision: 85.70% Recall: 85.85% F1: 84.95%

Epoch: 85/150
Train Loss: 0.4720 | Train Acc: 86.83% | Precision: 86.67% Recall: 86.83% F1: 85.94%
Val   Loss: 0.4972 | Val Acc: 86.05%   | Precision: 85.86% Recall: 86.05% F1: 84.80%

Epoch: 86/150
Train Loss: 0.4694 | Train Acc: 86.88% | Precision: 86.73% Recall: 86.88% F1: 85.99%
Val   Loss: 0.4961 | Val Acc: 85.92%   | Precision: 85.73% Recall: 85.92% F1: 85.06%

Epoch: 87/150
Train Loss: 0.4629 | Train Acc: 86.90% | Precision: 86.75% Recall: 86.90% F1: 86.02%
Val   Loss: 0.4766 | Val Acc: 86.57%   | Precision: 86.34% Recall: 86.57% F1: 85.48%

Epoch: 88/150
Train Loss: 0.4586 | Train Acc: 87.08% | Precision: 86.91% Recall: 87.08% F1: 86.22%
Val   Loss: 0.4716 | Val Acc: 86.56%   | Precision: 86.20% Recall: 86.56% F1: 85.59%

Epoch: 89/150
Train Loss: 0.4520 | Train Acc: 87.20% | Precision: 87.04% Recall: 87.20% F1: 86.33%
Val   Loss: 0.4612 | Val Acc: 86.76%   | Precision: 86.41% Recall: 86.76% F1: 85.95%

Epoch: 90/150
Train Loss: 0.4523 | Train Acc: 87.21% | Precision: 87.05% Recall: 87.21% F1: 86.35%
Val   Loss: 0.4528 | Val Acc: 86.61%   | Precision: 86.38% Recall: 86.61% F1: 85.56%

Epoch: 91/150
Train Loss: 0.4507 | Train Acc: 87.11% | Precision: 86.97% Recall: 87.11% F1: 86.23%
Val   Loss: 0.4861 | Val Acc: 85.13%   | Precision: 84.96% Recall: 85.13% F1: 83.97%

Epoch: 92/150
Train Loss: 0.4663 | Train Acc: 86.56% | Precision: 86.34% Recall: 86.56% F1: 85.61%
Val   Loss: 0.4735 | Val Acc: 85.91%   | Precision: 85.70% Recall: 85.91% F1: 85.16%

Epoch: 93/150
Train Loss: 0.4432 | Train Acc: 87.38% | Precision: 87.27% Recall: 87.38% F1: 86.55%
Val   Loss: 0.4788 | Val Acc: 85.91%   | Precision: 85.48% Recall: 85.91% F1: 84.87%

Epoch: 94/150
Train Loss: 0.4359 | Train Acc: 87.50% | Precision: 87.38% Recall: 87.50% F1: 86.67%
Val   Loss: 0.4640 | Val Acc: 86.58%   | Precision: 86.36% Recall: 86.58% F1: 85.85%

Epoch: 95/150
Train Loss: 0.4346 | Train Acc: 87.40% | Precision: 87.29% Recall: 87.40% F1: 86.57%
Val   Loss: 0.4412 | Val Acc: 87.09%   | Precision: 86.85% Recall: 87.09% F1: 86.33%

Epoch: 96/150
Train Loss: 0.4540 | Train Acc: 86.81% | Precision: 86.66% Recall: 86.81% F1: 85.90%
Val   Loss: 0.4358 | Val Acc: 87.48%   | Precision: 87.25% Recall: 87.48% F1: 86.60%

Epoch: 97/150
Train Loss: 0.4318 | Train Acc: 87.47% | Precision: 87.35% Recall: 87.47% F1: 86.67%
Val   Loss: 0.4313 | Val Acc: 87.15%   | Precision: 87.06% Recall: 87.15% F1: 86.26%

Epoch: 98/150
Train Loss: 0.4232 | Train Acc: 87.73% | Precision: 87.62% Recall: 87.73% F1: 86.95%
Val   Loss: 0.4376 | Val Acc: 87.21%   | Precision: 87.22% Recall: 87.21% F1: 86.00%

Epoch: 99/150
Train Loss: 0.4368 | Train Acc: 87.14% | Precision: 87.00% Recall: 87.14% F1: 86.29%
Val   Loss: 0.4392 | Val Acc: 87.04%   | Precision: 86.83% Recall: 87.04% F1: 86.18%

Epoch: 100/150
Train Loss: 0.4240 | Train Acc: 87.71% | Precision: 87.62% Recall: 87.71% F1: 86.91%
Val   Loss: 0.4273 | Val Acc: 87.38%   | Precision: 87.25% Recall: 87.38% F1: 86.37%

Epoch: 101/150
Train Loss: 0.4193 | Train Acc: 87.85% | Precision: 87.73% Recall: 87.85% F1: 87.07%
Val   Loss: 0.4405 | Val Acc: 86.76%   | Precision: 86.62% Recall: 86.76% F1: 85.88%

Epoch: 102/150
Train Loss: 0.4248 | Train Acc: 87.50% | Precision: 87.37% Recall: 87.50% F1: 86.70%
Val   Loss: 0.4473 | Val Acc: 86.61%   | Precision: 86.16% Recall: 86.61% F1: 85.84%

Epoch: 103/150
Train Loss: 0.4155 | Train Acc: 87.71% | Precision: 87.58% Recall: 87.71% F1: 86.92%
Val   Loss: 0.4351 | Val Acc: 86.89%   | Precision: 86.91% Recall: 86.89% F1: 85.72%

Epoch: 104/150
Train Loss: 0.4102 | Train Acc: 87.94% | Precision: 87.83% Recall: 87.94% F1: 87.18%
Val   Loss: 0.4190 | Val Acc: 87.39%   | Precision: 87.08% Recall: 87.39% F1: 86.59%

Epoch: 105/150
Train Loss: 0.4092 | Train Acc: 87.73% | Precision: 87.60% Recall: 87.73% F1: 86.96%
Val   Loss: 0.4176 | Val Acc: 87.31%   | Precision: 87.15% Recall: 87.31% F1: 86.54%

Epoch: 106/150
Train Loss: 0.4187 | Train Acc: 87.38% | Precision: 87.15% Recall: 87.38% F1: 86.59%
Val   Loss: 0.4153 | Val Acc: 87.29%   | Precision: 87.14% Recall: 87.29% F1: 86.45%

Epoch: 107/150
Train Loss: 0.4084 | Train Acc: 87.84% | Precision: 87.73% Recall: 87.84% F1: 87.09%
Val   Loss: 0.4215 | Val Acc: 87.36%   | Precision: 87.02% Recall: 87.36% F1: 86.50%

Epoch: 108/150
Train Loss: 0.4073 | Train Acc: 87.82% | Precision: 87.68% Recall: 87.82% F1: 87.07%
Val   Loss: 0.4000 | Val Acc: 88.00%   | Precision: 87.84% Recall: 88.00% F1: 87.15%

Epoch: 109/150

wandb: Agent Starting Run: tb6h0zht with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.0003786721020285109
wandb: 	optimizer: sgd
wandb: 	rnn_type: rnn
wandb: 	seq_len: 140
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.3460 | Train Acc: 64.10% | Precision: 42.94% Recall: 64.10% F1: 50.62%
Val   Loss: 1.1324 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.1254 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1214 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1180 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1146 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1090 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1034 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.0922 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0778 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.0246 | Train Acc: 65.75% | Precision: 53.67% Recall: 65.75% F1: 53.41%
Val   Loss: 0.9506 | Val Acc: 70.54%   | Precision: 55.94% Recall: 70.54% F1: 60.92%

Epoch: 7/150
Train Loss: 0.9181 | Train Acc: 71.13% | Precision: 56.65% Recall: 71.13% F1: 62.00%
Val   Loss: 0.8900 | Val Acc: 71.44%   | Precision: 57.07% Recall: 71.44% F1: 62.56%

Epoch: 8/150
Train Loss: 0.8760 | Train Acc: 71.16% | Precision: 56.88% Recall: 71.16% F1: 62.52%
Val   Loss: 0.8636 | Val Acc: 71.50%   | Precision: 57.32% Recall: 71.50% F1: 63.00%

Epoch: 9/150
Train Loss: 0.8499 | Train Acc: 71.61% | Precision: 57.98% Recall: 71.61% F1: 63.26%
Val   Loss: 0.8396 | Val Acc: 72.09%   | Precision: 58.27% Recall: 72.09% F1: 63.63%

Epoch: 10/150
Train Loss: 0.8226 | Train Acc: 72.11% | Precision: 58.82% Recall: 72.11% F1: 63.96%
Val   Loss: 0.8096 | Val Acc: 72.53%   | Precision: 59.94% Recall: 72.53% F1: 64.56%

Epoch: 11/150
Train Loss: 0.7942 | Train Acc: 72.45% | Precision: 60.67% Recall: 72.45% F1: 64.83%
Val   Loss: 0.8061 | Val Acc: 73.01%   | Precision: 65.20% Recall: 73.01% F1: 66.23%

Epoch: 12/150
Train Loss: 0.7666 | Train Acc: 73.29% | Precision: 65.51% Recall: 73.29% F1: 66.67%
Val   Loss: 0.7510 | Val Acc: 74.43%   | Precision: 67.38% Recall: 74.43% F1: 68.64%

Epoch: 13/150
Train Loss: 0.7300 | Train Acc: 74.77% | Precision: 68.00% Recall: 74.77% F1: 69.21%
Val   Loss: 0.7827 | Val Acc: 74.17%   | Precision: 67.67% Recall: 74.17% F1: 66.95%

Epoch: 14/150
Train Loss: 0.6841 | Train Acc: 76.46% | Precision: 70.06% Recall: 76.46% F1: 71.72%
Val   Loss: 0.6628 | Val Acc: 78.07%   | Precision: 71.98% Recall: 78.07% F1: 73.47%

Epoch: 15/150
Train Loss: 0.6396 | Train Acc: 78.56% | Precision: 72.52% Recall: 78.56% F1: 74.40%
Val   Loss: 0.6319 | Val Acc: 79.60%   | Precision: 74.23% Recall: 79.60% F1: 74.86%

Epoch: 16/150
Train Loss: 0.6051 | Train Acc: 80.27% | Precision: 77.08% Recall: 80.27% F1: 76.54%
Val   Loss: 0.5867 | Val Acc: 81.40%   | Precision: 78.10% Recall: 81.40% F1: 78.39%

Epoch: 17/150
Train Loss: 0.5718 | Train Acc: 82.63% | Precision: 81.77% Recall: 82.63% F1: 80.62%
Val   Loss: 0.5487 | Val Acc: 85.23%   | Precision: 84.81% Recall: 85.23% F1: 83.96%

Epoch: 18/150
Train Loss: 0.5436 | Train Acc: 84.29% | Precision: 83.79% Recall: 84.29% F1: 82.89%
Val   Loss: 0.5826 | Val Acc: 82.74%   | Precision: 82.49% Recall: 82.74% F1: 80.26%

Epoch: 19/150
Train Loss: 0.5219 | Train Acc: 85.11% | Precision: 84.78% Recall: 85.11% F1: 83.90%
Val   Loss: 0.5138 | Val Acc: 86.20%   | Precision: 85.99% Recall: 86.20% F1: 85.15%

Epoch: 20/150
Train Loss: 0.5012 | Train Acc: 85.83% | Precision: 85.56% Recall: 85.83% F1: 84.72%
Val   Loss: 0.4871 | Val Acc: 86.78%   | Precision: 86.75% Recall: 86.78% F1: 85.63%

Epoch: 21/150
Train Loss: 0.4826 | Train Acc: 86.25% | Precision: 86.06% Recall: 86.25% F1: 85.24%
Val   Loss: 0.4995 | Val Acc: 85.54%   | Precision: 85.50% Recall: 85.54% F1: 83.93%

Epoch: 22/150
Train Loss: 0.4682 | Train Acc: 86.84% | Precision: 86.73% Recall: 86.84% F1: 85.90%
Val   Loss: 0.4746 | Val Acc: 85.92%   | Precision: 85.93% Recall: 85.92% F1: 84.59%

Epoch: 23/150
Train Loss: 0.4536 | Train Acc: 86.94% | Precision: 86.79% Recall: 86.94% F1: 86.06%
Val   Loss: 0.4683 | Val Acc: 86.51%   | Precision: 86.43% Recall: 86.51% F1: 85.71%

Epoch: 24/150
Train Loss: 0.4475 | Train Acc: 87.12% | Precision: 87.02% Recall: 87.12% F1: 86.25%
Val   Loss: 0.4819 | Val Acc: 85.19%   | Precision: 84.98% Recall: 85.19% F1: 83.83%

Epoch: 25/150
Train Loss: 0.4402 | Train Acc: 87.36% | Precision: 87.29% Recall: 87.36% F1: 86.52%
Val   Loss: 0.4527 | Val Acc: 87.17%   | Precision: 87.34% Recall: 87.17% F1: 86.03%

Epoch: 26/150
Train Loss: 0.4302 | Train Acc: 87.51% | Precision: 87.43% Recall: 87.51% F1: 86.72%
Val   Loss: 0.4723 | Val Acc: 85.88%   | Precision: 85.78% Recall: 85.88% F1: 84.67%

Epoch: 27/150
Train Loss: 0.4218 | Train Acc: 87.85% | Precision: 87.80% Recall: 87.85% F1: 87.06%
Val   Loss: 0.4180 | Val Acc: 87.86%   | Precision: 87.83% Recall: 87.86% F1: 86.98%

Epoch: 28/150
Train Loss: 0.4159 | Train Acc: 87.86% | Precision: 87.85% Recall: 87.86% F1: 87.09%
Val   Loss: 0.4162 | Val Acc: 87.86%   | Precision: 87.75% Recall: 87.86% F1: 86.97%

Epoch: 29/150
Train Loss: 0.4136 | Train Acc: 88.03% | Precision: 87.99% Recall: 88.03% F1: 87.29%
Val   Loss: 0.4419 | Val Acc: 86.66%   | Precision: 86.96% Recall: 86.66% F1: 85.30%

Epoch: 30/150
Train Loss: 0.4072 | Train Acc: 88.13% | Precision: 88.13% Recall: 88.13% F1: 87.39%
Val   Loss: 0.4157 | Val Acc: 87.83%   | Precision: 87.70% Recall: 87.83% F1: 87.00%

Epoch: 31/150
Train Loss: 0.3969 | Train Acc: 88.44% | Precision: 88.43% Recall: 88.44% F1: 87.73%
Val   Loss: 0.4059 | Val Acc: 88.06%   | Precision: 87.95% Recall: 88.06% F1: 87.36%

Epoch: 32/150
Train Loss: 0.3959 | Train Acc: 88.39% | Precision: 88.40% Recall: 88.39% F1: 87.69%
Val   Loss: 0.3932 | Val Acc: 88.57%   | Precision: 88.47% Recall: 88.57% F1: 87.75%

Epoch: 33/150
Train Loss: 0.3888 | Train Acc: 88.68% | Precision: 88.70% Recall: 88.68% F1: 87.99%
Val   Loss: 0.3862 | Val Acc: 88.42%   | Precision: 88.56% Recall: 88.42% F1: 87.69%

Epoch: 34/150
Train Loss: 0.3850 | Train Acc: 88.68% | Precision: 88.70% Recall: 88.68% F1: 88.00%
Val   Loss: 0.3845 | Val Acc: 88.60%   | Precision: 88.85% Recall: 88.60% F1: 87.71%

Epoch: 35/150
Train Loss: 0.3735 | Train Acc: 89.05% | Precision: 89.09% Recall: 89.05% F1: 88.41%
Val   Loss: 0.3672 | Val Acc: 89.08%   | Precision: 89.11% Recall: 89.08% F1: 88.32%

Epoch: 36/150
Train Loss: 0.3717 | Train Acc: 88.97% | Precision: 88.96% Recall: 88.97% F1: 88.32%
Val   Loss: 0.3784 | Val Acc: 88.73%   | Precision: 88.66% Recall: 88.73% F1: 87.96%

Epoch: 37/150
Train Loss: 0.3694 | Train Acc: 89.00% | Precision: 88.98% Recall: 89.00% F1: 88.37%
Val   Loss: 0.4396 | Val Acc: 86.73%   | Precision: 87.12% Recall: 86.73% F1: 86.16%

Epoch: 38/150
Train Loss: 0.3623 | Train Acc: 89.33% | Precision: 89.33% Recall: 89.33% F1: 88.71%
Val   Loss: 0.3580 | Val Acc: 89.28%   | Precision: 89.44% Recall: 89.28% F1: 88.49%

Epoch: 39/150
Train Loss: 0.3498 | Train Acc: 89.69% | Precision: 89.73% Recall: 89.69% F1: 89.09%
Val   Loss: 0.3817 | Val Acc: 88.39%   | Precision: 88.32% Recall: 88.39% F1: 87.94%

Epoch: 40/150
Train Loss: 0.3502 | Train Acc: 89.62% | Precision: 89.62% Recall: 89.62% F1: 89.03%
Val   Loss: 0.3594 | Val Acc: 89.47%   | Precision: 89.30% Recall: 89.47% F1: 88.85%

Epoch: 41/150
Train Loss: 0.3404 | Train Acc: 90.11% | Precision: 90.14% Recall: 90.11% F1: 89.54%
Val   Loss: 0.3566 | Val Acc: 89.49%   | Precision: 89.42% Recall: 89.49% F1: 88.97%

Epoch: 42/150
Train Loss: 0.3377 | Train Acc: 90.09% | Precision: 90.09% Recall: 90.09% F1: 89.52%
Val   Loss: 0.3562 | Val Acc: 89.11%   | Precision: 89.36% Recall: 89.11% F1: 88.22%

Epoch: 43/150
Train Loss: 0.3305 | Train Acc: 90.29% | Precision: 90.30% Recall: 90.29% F1: 89.73%
Val   Loss: 0.3356 | Val Acc: 90.23%   | Precision: 90.09% Recall: 90.23% F1: 89.68%

Epoch: 44/150
Train Loss: 0.3237 | Train Acc: 90.57% | Precision: 90.59% Recall: 90.57% F1: 90.01%
Val   Loss: 0.3165 | Val Acc: 90.56%   | Precision: 90.60% Recall: 90.56% F1: 89.89%

Epoch: 45/150
Train Loss: 0.3170 | Train Acc: 90.82% | Precision: 90.83% Recall: 90.82% F1: 90.28%
Val   Loss: 0.3369 | Val Acc: 90.10%   | Precision: 90.00% Recall: 90.10% F1: 89.51%

Epoch: 46/150
Train Loss: 0.3152 | Train Acc: 90.75% | Precision: 90.74% Recall: 90.75% F1: 90.20%
Val   Loss: 0.3056 | Val Acc: 90.60%   | Precision: 90.60% Recall: 90.60% F1: 90.06%

Epoch: 47/150
Train Loss: 0.3090 | Train Acc: 90.97% | Precision: 90.97% Recall: 90.97% F1: 90.44%
Val   Loss: 0.3260 | Val Acc: 90.52%   | Precision: 90.51% Recall: 90.52% F1: 89.85%

Epoch: 48/150
Train Loss: 0.3086 | Train Acc: 90.90% | Precision: 90.90% Recall: 90.90% F1: 90.37%
Val   Loss: 0.3151 | Val Acc: 90.41%   | Precision: 90.27% Recall: 90.41% F1: 89.80%

Epoch: 49/150
Train Loss: 0.3025 | Train Acc: 91.14% | Precision: 91.13% Recall: 91.14% F1: 90.63%
Val   Loss: 0.3070 | Val Acc: 90.65%   | Precision: 90.53% Recall: 90.65% F1: 90.01%

Epoch: 50/150
Train Loss: 0.2967 | Train Acc: 91.17% | Precision: 91.14% Recall: 91.17% F1: 90.66%
Val   Loss: 0.3055 | Val Acc: 90.77%   | Precision: 90.72% Recall: 90.77% F1: 90.26%

Epoch: 51/150
Train Loss: 0.2923 | Train Acc: 91.26% | Precision: 91.21% Recall: 91.26% F1: 90.78%
Val   Loss: 0.2949 | Val Acc: 91.01%   | Precision: 90.86% Recall: 91.01% F1: 90.49%

Epoch: 52/150
Train Loss: 0.2900 | Train Acc: 91.28% | Precision: 91.21% Recall: 91.28% F1: 90.82%
Val   Loss: 0.2847 | Val Acc: 91.23%   | Precision: 91.14% Recall: 91.23% F1: 90.60%

Epoch: 53/150
Train Loss: 0.2869 | Train Acc: 91.44% | Precision: 91.40% Recall: 91.44% F1: 90.96%
Val   Loss: 0.2739 | Val Acc: 91.98%   | Precision: 91.94% Recall: 91.98% F1: 91.44%

Epoch: 54/150
Train Loss: 0.2830 | Train Acc: 91.58% | Precision: 91.54% Recall: 91.58% F1: 91.14%
Val   Loss: 0.2864 | Val Acc: 91.39%   | Precision: 91.28% Recall: 91.39% F1: 90.98%

Epoch: 55/150
Train Loss: 0.2783 | Train Acc: 91.66% | Precision: 91.60% Recall: 91.66% F1: 91.23%
Val   Loss: 0.2801 | Val Acc: 91.52%   | Precision: 91.37% Recall: 91.52% F1: 91.03%

Epoch: 56/150
Train Loss: 0.2767 | Train Acc: 91.74% | Precision: 91.66% Recall: 91.74% F1: 91.31%
Val   Loss: 0.3042 | Val Acc: 90.45%   | Precision: 90.53% Recall: 90.45% F1: 90.17%

Epoch: 57/150
Train Loss: 0.2731 | Train Acc: 91.92% | Precision: 91.89% Recall: 91.92% F1: 91.51%
Val   Loss: 0.2668 | Val Acc: 92.02%   | Precision: 92.01% Recall: 92.02% F1: 91.44%

Epoch: 58/150
Train Loss: 0.2704 | Train Acc: 92.03% | Precision: 91.93% Recall: 92.03% F1: 91.64%
Val   Loss: 0.3022 | Val Acc: 90.46%   | Precision: 90.54% Recall: 90.46% F1: 90.08%

Epoch: 59/150
Train Loss: 0.2712 | Train Acc: 91.92% | Precision: 91.84% Recall: 91.92% F1: 91.52%
Val   Loss: 0.2925 | Val Acc: 90.80%   | Precision: 90.73% Recall: 90.80% F1: 90.38%

Epoch: 60/150
Train Loss: 0.2668 | Train Acc: 92.01% | Precision: 91.93% Recall: 92.01% F1: 91.61%
Val   Loss: 0.2541 | Val Acc: 92.28%   | Precision: 92.17% Recall: 92.28% F1: 91.85%

Epoch: 61/150
Train Loss: 0.2584 | Train Acc: 92.27% | Precision: 92.21% Recall: 92.27% F1: 91.92%
Val   Loss: 0.2705 | Val Acc: 91.58%   | Precision: 91.45% Recall: 91.58% F1: 91.10%

Epoch: 62/150
Train Loss: 0.2577 | Train Acc: 92.29% | Precision: 92.22% Recall: 92.29% F1: 91.93%
Val   Loss: 0.2646 | Val Acc: 91.75%   | Precision: 91.62% Recall: 91.75% F1: 91.37%

Epoch: 63/150
Train Loss: 0.2625 | Train Acc: 92.15% | Precision: 92.08% Recall: 92.15% F1: 91.80%
Val   Loss: 0.2506 | Val Acc: 91.92%   | Precision: 91.77% Recall: 91.92% F1: 91.59%

Epoch: 64/150
Train Loss: 0.2555 | Train Acc: 92.48% | Precision: 92.39% Recall: 92.48% F1: 92.14%
Val   Loss: 0.2407 | Val Acc: 92.56%   | Precision: 92.44% Recall: 92.56% F1: 92.20%

Epoch: 65/150
Train Loss: 0.2512 | Train Acc: 92.50% | Precision: 92.42% Recall: 92.50% F1: 92.17%
Val   Loss: 0.2462 | Val Acc: 92.44%   | Precision: 92.29% Recall: 92.44% F1: 92.07%

Epoch: 66/150
Train Loss: 0.2511 | Train Acc: 92.49% | Precision: 92.39% Recall: 92.49% F1: 92.16%
Val   Loss: 0.2550 | Val Acc: 92.01%   | Precision: 91.91% Recall: 92.01% F1: 91.56%

Epoch: 67/150
Train Loss: 0.2497 | Train Acc: 92.42% | Precision: 92.34% Recall: 92.42% F1: 92.11%
Val   Loss: 0.2572 | Val Acc: 92.03%   | Precision: 91.91% Recall: 92.03% F1: 91.67%

Epoch: 68/150
Train Loss: 0.2456 | Train Acc: 92.71% | Precision: 92.63% Recall: 92.71% F1: 92.40%
Val   Loss: 0.2518 | Val Acc: 92.48%   | Precision: 92.45% Recall: 92.48% F1: 92.05%

Epoch: 69/150
Train Loss: 0.2484 | Train Acc: 92.56% | Precision: 92.46% Recall: 92.56% F1: 92.24%
Val   Loss: 0.2487 | Val Acc: 92.38%   | Precision: 92.25% Recall: 92.38% F1: 92.00%

Epoch: 70/150
Train Loss: 0.2450 | Train Acc: 92.81% | Precision: 92.74% Recall: 92.81% F1: 92.49%
Val   Loss: 0.2543 | Val Acc: 92.47%   | Precision: 92.35% Recall: 92.47% F1: 92.08%

Epoch: 71/150
Train Loss: 0.2409 | Train Acc: 92.79% | Precision: 92.71% Recall: 92.79% F1: 92.48%
Val   Loss: 0.2656 | Val Acc: 92.00%   | Precision: 91.78% Recall: 92.00% F1: 91.77%

Epoch: 72/150
Train Loss: 0.2355 | Train Acc: 92.84% | Precision: 92.77% Recall: 92.84% F1: 92.55%
Val   Loss: 0.2401 | Val Acc: 92.53%   | Precision: 92.43% Recall: 92.53% F1: 92.17%

Epoch: 73/150
Train Loss: 0.2319 | Train Acc: 93.06% | Precision: 92.98% Recall: 93.06% F1: 92.78%
Val   Loss: 0.2838 | Val Acc: 91.30%   | Precision: 91.16% Recall: 91.30% F1: 90.86%

Epoch: 74/150
Train Loss: 0.2394 | Train Acc: 92.78% | Precision: 92.71% Recall: 92.78% F1: 92.48%
Val   Loss: 0.2288 | Val Acc: 92.95%   | Precision: 92.84% Recall: 92.95% F1: 92.66%

Epoch: 75/150
Train Loss: 0.2378 | Train Acc: 92.82% | Precision: 92.74% Recall: 92.82% F1: 92.55%
Val   Loss: 0.2392 | Val Acc: 92.62%   | Precision: 92.51% Recall: 92.62% F1: 92.27%

Epoch: 76/150
Train Loss: 0.2253 | Train Acc: 93.25% | Precision: 93.16% Recall: 93.25% F1: 92.99%
Val   Loss: 0.2792 | Val Acc: 91.71%   | Precision: 91.57% Recall: 91.71% F1: 91.34%

Epoch: 77/150
Train Loss: 0.2281 | Train Acc: 93.11% | Precision: 93.03% Recall: 93.11% F1: 92.85%
Val   Loss: 0.2359 | Val Acc: 92.72%   | Precision: 92.59% Recall: 92.72% F1: 92.44%

Epoch: 78/150
Train Loss: 0.2303 | Train Acc: 93.08% | Precision: 92.99% Recall: 93.08% F1: 92.81%
Val   Loss: 0.2364 | Val Acc: 92.79%   | Precision: 92.66% Recall: 92.79% F1: 92.52%

Epoch: 79/150
Train Loss: 0.2253 | Train Acc: 93.17% | Precision: 93.08% Recall: 93.17% F1: 92.92%
Val   Loss: 0.2273 | Val Acc: 92.90%   | Precision: 92.78% Recall: 92.90% F1: 92.59%

Epoch: 80/150
Train Loss: 0.2276 | Train Acc: 93.13% | Precision: 93.05% Recall: 93.13% F1: 92.86%
Val   Loss: 0.2250 | Val Acc: 93.17%   | Precision: 93.07% Recall: 93.17% F1: 92.87%

Epoch: 81/150
Train Loss: 0.2180 | Train Acc: 93.43% | Precision: 93.34% Recall: 93.43% F1: 93.18%
Val   Loss: 0.2272 | Val Acc: 93.25%   | Precision: 93.14% Recall: 93.25% F1: 93.05%

Epoch: 82/150
Train Loss: 0.2216 | Train Acc: 93.27% | Precision: 93.19% Recall: 93.27% F1: 93.03%
Val   Loss: 0.2291 | Val Acc: 93.05%   | Precision: 92.90% Recall: 93.05% F1: 92.78%

Epoch: 83/150
Train Loss: 0.2218 | Train Acc: 93.21% | Precision: 93.12% Recall: 93.21% F1: 92.96%
Val   Loss: 0.2445 | Val Acc: 92.12%   | Precision: 92.10% Recall: 92.12% F1: 91.73%

Epoch: 84/150
Train Loss: 0.2189 | Train Acc: 93.42% | Precision: 93.33% Recall: 93.42% F1: 93.19%
Val   Loss: 0.2346 | Val Acc: 92.74%   | Precision: 92.58% Recall: 92.74% F1: 92.48%

Epoch: 85/150
Train Loss: 0.2160 | Train Acc: 93.40% | Precision: 93.32% Recall: 93.40% F1: 93.17%
Val   Loss: 0.2207 | Val Acc: 93.19%   | Precision: 93.08% Recall: 93.19% F1: 92.91%

Epoch: 86/150
Train Loss: 0.2111 | Train Acc: 93.52% | Precision: 93.43% Recall: 93.52% F1: 93.30%
Val   Loss: 0.2211 | Val Acc: 93.19%   | Precision: 93.06% Recall: 93.19% F1: 92.92%

Epoch: 87/150
Train Loss: 0.2197 | Train Acc: 93.35% | Precision: 93.28% Recall: 93.35% F1: 93.13%
Val   Loss: 0.3582 | Val Acc: 89.21%   | Precision: 89.13% Recall: 89.21% F1: 88.65%

Epoch: 88/150
Train Loss: 0.2147 | Train Acc: 93.53% | Precision: 93.47% Recall: 93.53% F1: 93.29%
Val   Loss: 0.2183 | Val Acc: 93.07%   | Precision: 92.97% Recall: 93.07% F1: 92.78%

Epoch: 89/150
Train Loss: 0.2097 | Train Acc: 93.68% | Precision: 93.61% Recall: 93.68% F1: 93.47%
Val   Loss: 0.2293 | Val Acc: 92.76%   | Precision: 92.63% Recall: 92.76% F1: 92.49%

Epoch: 90/150
Train Loss: 0.2111 | Train Acc: 93.55% | Precision: 93.47% Recall: 93.55% F1: 93.33%
Val   Loss: 0.2101 | Val Acc: 93.54%   | Precision: 93.42% Recall: 93.54% F1: 93.33%

Epoch: 91/150
Train Loss: 0.2060 | Train Acc: 93.71% | Precision: 93.63% Recall: 93.71% F1: 93.50%
Val   Loss: 0.1982 | Val Acc: 93.87%   | Precision: 93.77% Recall: 93.87% F1: 93.65%

Epoch: 92/150
Train Loss: 0.2105 | Train Acc: 93.58% | Precision: 93.51% Recall: 93.58% F1: 93.36%
Val   Loss: 0.2269 | Val Acc: 93.21%   | Precision: 93.14% Recall: 93.21% F1: 92.93%

Epoch: 93/150
Train Loss: 0.2059 | Train Acc: 93.72% | Precision: 93.64% Recall: 93.72% F1: 93.51%
Val   Loss: 0.2243 | Val Acc: 93.14%   | Precision: 92.98% Recall: 93.14% F1: 92.96%

Epoch: 94/150
Train Loss: 0.2097 | Train Acc: 93.64% | Precision: 93.57% Recall: 93.64% F1: 93.41%
Val   Loss: 0.2178 | Val Acc: 93.24%   | Precision: 93.14% Recall: 93.24% F1: 92.93%

Epoch: 95/150
Train Loss: 0.2076 | Train Acc: 93.62% | Precision: 93.54% Recall: 93.62% F1: 93.41%
Val   Loss: 0.2080 | Val Acc: 93.49%   | Precision: 93.38% Recall: 93.49% F1: 93.26%

Epoch: 96/150
Train Loss: 0.2028 | Train Acc: 93.90% | Precision: 93.82% Recall: 93.90% F1: 93.71%
Val   Loss: 0.1991 | Val Acc: 93.90%   | Precision: 93.81% Recall: 93.90% F1: 93.68%

Epoch: 97/150
Train Loss: 0.2058 | Train Acc: 93.69% | Precision: 93.62% Recall: 93.69% F1: 93.49%
Val   Loss: 0.2138 | Val Acc: 93.50%   | Precision: 93.53% Recall: 93.50% F1: 93.18%

Epoch: 98/150
Train Loss: 0.1965 | Train Acc: 94.00% | Precision: 93.92% Recall: 94.00% F1: 93.81%
Val   Loss: 0.2268 | Val Acc: 92.71%   | Precision: 92.59% Recall: 92.71% F1: 92.43%

Epoch: 99/150
Train Loss: 0.1965 | Train Acc: 93.90% | Precision: 93.83% Recall: 93.90% F1: 93.71%
Val   Loss: 0.1998 | Val Acc: 93.65%   | Precision: 93.57% Recall: 93.65% F1: 93.39%

Epoch: 100/150
Train Loss: 0.1995 | Train Acc: 93.93% | Precision: 93.85% Recall: 93.93% F1: 93.74%
Val   Loss: 0.1929 | Val Acc: 94.06%   | Precision: 93.97% Recall: 94.06% F1: 93.85%

Epoch: 101/150
Train Loss: 0.1980 | Train Acc: 93.89% | Precision: 93.81% Recall: 93.89% F1: 93.70%
Val   Loss: 0.2001 | Val Acc: 93.76%   | Precision: 93.72% Recall: 93.76% F1: 93.67%

Epoch: 102/150
Train Loss: 0.2036 | Train Acc: 93.84% | Precision: 93.75% Recall: 93.84% F1: 93.65%
Val   Loss: 0.2379 | Val Acc: 92.48%   | Precision: 92.40% Recall: 92.48% F1: 92.10%

Epoch: 103/150
Train Loss: 0.1948 | Train Acc: 94.00% | Precision: 93.91% Recall: 94.00% F1: 93.83%
Val   Loss: 0.2021 | Val Acc: 93.55%   | Precision: 93.43% Recall: 93.55% F1: 93.30%

Epoch: 104/150
Train Loss: 0.1920 | Train Acc: 94.03% | Precision: 93.96% Recall: 94.03% F1: 93.85%
Val   Loss: 0.1867 | Val Acc: 94.02%   | Precision: 94.00% Recall: 94.02% F1: 93.85%

Epoch: 105/150
Train Loss: 0.1898 | Train Acc: 94.20% | Precision: 94.13% Recall: 94.20% F1: 94.03%
Val   Loss: 0.2154 | Val Acc: 93.15%   | Precision: 93.00% Recall: 93.15% F1: 92.92%

Epoch: 106/150
Train Loss: 0.1968 | Train Acc: 93.93% | Precision: 93.85% Recall: 93.93% F1: 93.75%
Val   Loss: 0.1923 | Val Acc: 94.14%   | Precision: 94.06% Recall: 94.14% F1: 93.95%

Epoch: 107/150
Train Loss: 0.1939 | Train Acc: 93.89% | Precision: 93.81% Recall: 93.89% F1: 93.72%
Val   Loss: 0.2040 | Val Acc: 93.68%   | Precision: 93.56% Recall: 93.68% F1: 93.49%

Epoch: 108/150
Train Loss: 0.1983 | Train Acc: 93.97% | Precision: 93.89% Recall: 93.97% F1: 93.80%
Val   Loss: 0.1989 | Val Acc: 93.65%   | Precision: 93.57% Recall: 93.65% F1: 93.53%

Epoch: 109/150

### GRU

In [70]:
sweep_config = {
    "name": "GRU-ECG",
    "method": "bayes", 
    "metric": {"name": "val_loss", "goal": "minimize"},
    "parameters": {
        "rnn_type": {"value": "gru"},
        "hidden_dim": {"values": [64, 128, 256, 512]},
        "bidirectional": {"values": [False, True]},
        "batch_size": {"values": [32, 64, 128]},
        "optimizer": {"values": ["adam", "sgd"]},
        "learning_rate": {"distribution": "uniform", "min": 0.0001, "max": 0.001},
        "weight_decay": {"values": [0.0, 1e-5, 1e-4, 1e-3]},
        "seq_len": {"values": [80,120,130,140,150,160]},
    }
}

In [71]:
wandb.agent(sweep_id, train_wandb_rnn, count=3)

wandb: Agent Starting Run: mcep5rew with config:
wandb: 	batch_size: 128
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.00022152074066599935
wandb: 	optimizer: sgd
wandb: 	rnn_type: rnn
wandb: 	seq_len: 140
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.7225 | Train Acc: 61.70% | Precision: 42.14% Recall: 61.70% F1: 50.04%
Val   Loss: 1.2989 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.2288 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1764 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1523 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1380 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1325 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1295 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.1273 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1261 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.1247 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1246 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 7/150
Train Loss: 1.1231 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1232 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 8/150
Train Loss: 1.1217 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1216 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 9/150
Train Loss: 1.1202 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1209 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 10/150
Train Loss: 1.1189 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1193 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 11/150
Train Loss: 1.1173 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1172 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 12/150
Train Loss: 1.1157 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1157 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 13/150
Train Loss: 1.1139 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1138 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 14/150
Train Loss: 1.1113 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1110 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 15/150
Train Loss: 1.1085 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1085 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 16/150
Train Loss: 1.1052 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1044 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 17/150
Train Loss: 1.1006 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0996 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 18/150
Train Loss: 1.0949 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0923 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 19/150
Train Loss: 1.0862 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0819 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 20/150
Train Loss: 1.0727 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0653 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 21/150
Train Loss: 1.0506 | Train Acc: 64.55% | Precision: 47.01% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0349 | Val Acc: 64.53%   | Precision: 41.67% Recall: 64.53% F1: 50.64%

Epoch: 22/150
Train Loss: 1.0086 | Train Acc: 65.03% | Precision: 52.93% Recall: 65.03% F1: 51.99%
Val   Loss: 0.9766 | Val Acc: 68.48%   | Precision: 55.27% Recall: 68.48% F1: 57.96%

Epoch: 23/150
Train Loss: 0.9628 | Train Acc: 70.22% | Precision: 56.51% Recall: 70.22% F1: 60.38%
Val   Loss: 0.9479 | Val Acc: 71.04%   | Precision: 56.36% Recall: 71.04% F1: 61.54%

Epoch: 24/150
Train Loss: 0.9400 | Train Acc: 71.18% | Precision: 56.59% Recall: 71.18% F1: 61.93%
Val   Loss: 0.9284 | Val Acc: 71.78%   | Precision: 57.38% Recall: 71.78% F1: 62.46%

Epoch: 25/150
Train Loss: 0.9235 | Train Acc: 71.18% | Precision: 56.57% Recall: 71.18% F1: 62.15%
Val   Loss: 0.9134 | Val Acc: 71.69%   | Precision: 57.26% Recall: 71.69% F1: 62.55%

Epoch: 26/150
Train Loss: 0.9083 | Train Acc: 71.11% | Precision: 56.54% Recall: 71.11% F1: 62.10%
Val   Loss: 0.8981 | Val Acc: 71.21%   | Precision: 56.79% Recall: 71.21% F1: 62.37%

Epoch: 27/150
Train Loss: 0.8925 | Train Acc: 71.06% | Precision: 56.64% Recall: 71.06% F1: 62.27%
Val   Loss: 0.8846 | Val Acc: 71.28%   | Precision: 56.86% Recall: 71.28% F1: 62.54%

Epoch: 28/150
Train Loss: 0.8792 | Train Acc: 71.34% | Precision: 56.97% Recall: 71.34% F1: 62.60%
Val   Loss: 0.8711 | Val Acc: 71.49%   | Precision: 57.07% Recall: 71.49% F1: 62.75%

Epoch: 29/150
Train Loss: 0.8661 | Train Acc: 71.84% | Precision: 57.50% Recall: 71.84% F1: 63.08%
Val   Loss: 0.8590 | Val Acc: 71.88%   | Precision: 57.57% Recall: 71.88% F1: 63.17%

Epoch: 30/150
Train Loss: 0.8551 | Train Acc: 72.00% | Precision: 57.76% Recall: 72.00% F1: 63.31%
Val   Loss: 0.8513 | Val Acc: 72.32%   | Precision: 58.24% Recall: 72.32% F1: 63.58%

Epoch: 31/150
Train Loss: 0.8489 | Train Acc: 72.06% | Precision: 58.08% Recall: 72.06% F1: 63.48%
Val   Loss: 0.8536 | Val Acc: 72.27%   | Precision: 58.41% Recall: 72.27% F1: 63.66%

Epoch: 32/150
Train Loss: 0.8424 | Train Acc: 71.96% | Precision: 58.11% Recall: 71.96% F1: 63.50%
Val   Loss: 0.8396 | Val Acc: 72.34%   | Precision: 58.50% Recall: 72.34% F1: 63.75%

Epoch: 33/150
Train Loss: 0.8372 | Train Acc: 71.97% | Precision: 58.28% Recall: 71.97% F1: 63.59%
Val   Loss: 0.8349 | Val Acc: 72.16%   | Precision: 58.42% Recall: 72.16% F1: 63.78%

Epoch: 34/150
Train Loss: 0.8303 | Train Acc: 71.97% | Precision: 58.72% Recall: 71.97% F1: 63.73%
Val   Loss: 0.8343 | Val Acc: 72.40%   | Precision: 58.62% Recall: 72.40% F1: 63.78%

Epoch: 35/150
Train Loss: 0.8251 | Train Acc: 71.98% | Precision: 58.94% Recall: 71.98% F1: 63.86%
Val   Loss: 0.8311 | Val Acc: 72.30%   | Precision: 58.75% Recall: 72.30% F1: 63.83%

Epoch: 36/150
Train Loss: 0.8196 | Train Acc: 72.13% | Precision: 59.25% Recall: 72.13% F1: 64.07%
Val   Loss: 0.8218 | Val Acc: 72.08%   | Precision: 58.88% Recall: 72.08% F1: 64.03%

Epoch: 37/150
Train Loss: 0.8127 | Train Acc: 72.33% | Precision: 59.46% Recall: 72.33% F1: 64.31%
Val   Loss: 0.8109 | Val Acc: 72.45%   | Precision: 59.84% Recall: 72.45% F1: 64.47%

Epoch: 38/150
Train Loss: 0.8054 | Train Acc: 72.37% | Precision: 59.58% Recall: 72.37% F1: 64.42%
Val   Loss: 0.8053 | Val Acc: 72.24%   | Precision: 59.39% Recall: 72.24% F1: 64.38%

Epoch: 39/150
Train Loss: 0.8001 | Train Acc: 72.32% | Precision: 59.59% Recall: 72.32% F1: 64.47%
Val   Loss: 0.8033 | Val Acc: 72.44%   | Precision: 59.42% Recall: 72.44% F1: 64.57%

Epoch: 40/150
Train Loss: 0.7943 | Train Acc: 72.31% | Precision: 59.59% Recall: 72.31% F1: 64.53%
Val   Loss: 0.8003 | Val Acc: 72.45%   | Precision: 59.37% Recall: 72.45% F1: 64.53%

Epoch: 41/150
Train Loss: 0.7898 | Train Acc: 72.34% | Precision: 59.68% Recall: 72.34% F1: 64.64%
Val   Loss: 0.7885 | Val Acc: 72.74%   | Precision: 59.65% Recall: 72.74% F1: 64.71%

Epoch: 42/150
Train Loss: 0.7827 | Train Acc: 72.49% | Precision: 60.07% Recall: 72.49% F1: 64.84%
Val   Loss: 0.7837 | Val Acc: 72.53%   | Precision: 60.41% Recall: 72.53% F1: 65.03%

Epoch: 43/150
Train Loss: 0.7764 | Train Acc: 72.62% | Precision: 60.54% Recall: 72.62% F1: 65.10%
Val   Loss: 0.7844 | Val Acc: 73.01%   | Precision: 59.67% Recall: 73.01% F1: 64.95%

Epoch: 44/150
Train Loss: 0.7691 | Train Acc: 72.91% | Precision: 60.87% Recall: 72.91% F1: 65.46%
Val   Loss: 0.7842 | Val Acc: 73.13%   | Precision: 62.10% Recall: 73.13% F1: 66.18%

Epoch: 45/150
Train Loss: 0.7597 | Train Acc: 73.47% | Precision: 62.26% Recall: 73.47% F1: 66.46%
Val   Loss: 0.7661 | Val Acc: 73.73%   | Precision: 61.90% Recall: 73.73% F1: 66.54%

Epoch: 46/150
Train Loss: 0.7517 | Train Acc: 73.88% | Precision: 63.11% Recall: 73.88% F1: 67.10%
Val   Loss: 0.7632 | Val Acc: 74.15%   | Precision: 64.24% Recall: 74.15% F1: 67.86%

Epoch: 47/150
Train Loss: 0.7389 | Train Acc: 74.44% | Precision: 64.89% Recall: 74.44% F1: 68.03%
Val   Loss: 0.7536 | Val Acc: 74.84%   | Precision: 69.06% Recall: 74.84% F1: 68.88%

Epoch: 48/150
Train Loss: 0.7183 | Train Acc: 75.18% | Precision: 67.97% Recall: 75.18% F1: 69.22%
Val   Loss: 0.7215 | Val Acc: 75.66%   | Precision: 69.04% Recall: 75.66% F1: 69.37%

Epoch: 49/150
Train Loss: 0.6995 | Train Acc: 76.09% | Precision: 70.05% Recall: 76.09% F1: 70.59%
Val   Loss: 0.7029 | Val Acc: 76.29%   | Precision: 70.33% Recall: 76.29% F1: 70.90%

Epoch: 50/150
Train Loss: 0.6801 | Train Acc: 76.77% | Precision: 70.45% Recall: 76.77% F1: 71.65%
Val   Loss: 0.7016 | Val Acc: 76.43%   | Precision: 69.83% Recall: 76.43% F1: 71.94%

Epoch: 51/150
Train Loss: 0.6656 | Train Acc: 77.29% | Precision: 70.92% Recall: 77.29% F1: 72.58%
Val   Loss: 0.6734 | Val Acc: 77.74%   | Precision: 71.08% Recall: 77.74% F1: 73.19%

Epoch: 52/150
Train Loss: 0.6506 | Train Acc: 78.07% | Precision: 71.84% Recall: 78.07% F1: 73.60%
Val   Loss: 0.6583 | Val Acc: 78.14%   | Precision: 71.66% Recall: 78.14% F1: 74.02%

Epoch: 53/150
Train Loss: 0.6373 | Train Acc: 78.78% | Precision: 72.67% Recall: 78.78% F1: 74.51%
Val   Loss: 0.6482 | Val Acc: 79.54%   | Precision: 73.57% Recall: 79.54% F1: 75.18%

Epoch: 54/150
Train Loss: 0.6264 | Train Acc: 79.50% | Precision: 73.58% Recall: 79.50% F1: 75.41%
Val   Loss: 0.6363 | Val Acc: 79.57%   | Precision: 73.66% Recall: 79.57% F1: 75.39%

Epoch: 55/150
Train Loss: 0.6209 | Train Acc: 79.92% | Precision: 74.13% Recall: 79.92% F1: 75.92%
Val   Loss: 0.6227 | Val Acc: 80.83%   | Precision: 75.21% Recall: 80.83% F1: 76.92%

Epoch: 56/150
Train Loss: 0.6066 | Train Acc: 80.59% | Precision: 74.95% Recall: 80.59% F1: 76.69%
Val   Loss: 0.6312 | Val Acc: 80.16%   | Precision: 74.33% Recall: 80.16% F1: 76.16%

Epoch: 57/150
Train Loss: 0.6042 | Train Acc: 80.67% | Precision: 75.05% Recall: 80.67% F1: 76.82%
Val   Loss: 0.6122 | Val Acc: 81.25%   | Precision: 82.10% Recall: 81.25% F1: 77.64%

Epoch: 58/150
Train Loss: 0.5949 | Train Acc: 80.83% | Precision: 78.46% Recall: 80.83% F1: 77.00%
Val   Loss: 0.6059 | Val Acc: 81.34%   | Precision: 75.76% Recall: 81.34% F1: 77.57%

Epoch: 59/150
Train Loss: 0.5913 | Train Acc: 80.87% | Precision: 76.88% Recall: 80.87% F1: 77.07%
Val   Loss: 0.6046 | Val Acc: 81.31%   | Precision: 76.00% Recall: 81.31% F1: 77.56%

Epoch: 60/150
Train Loss: 0.5765 | Train Acc: 81.58% | Precision: 78.57% Recall: 81.58% F1: 78.01%
Val   Loss: 0.5959 | Val Acc: 80.59%   | Precision: 75.27% Recall: 80.59% F1: 76.26%

Epoch: 61/150
Train Loss: 0.5671 | Train Acc: 82.44% | Precision: 81.47% Recall: 82.44% F1: 79.57%
Val   Loss: 0.5679 | Val Acc: 83.36%   | Precision: 82.46% Recall: 83.36% F1: 81.06%

Epoch: 62/150
Train Loss: 0.5535 | Train Acc: 83.69% | Precision: 83.03% Recall: 83.69% F1: 81.80%
Val   Loss: 0.5634 | Val Acc: 84.30%   | Precision: 83.70% Recall: 84.30% F1: 82.50%

Epoch: 63/150
Train Loss: 0.5529 | Train Acc: 83.93% | Precision: 83.33% Recall: 83.93% F1: 82.36%
Val   Loss: 0.5556 | Val Acc: 84.41%   | Precision: 83.60% Recall: 84.41% F1: 82.48%

Epoch: 64/150
Train Loss: 0.5447 | Train Acc: 84.66% | Precision: 84.09% Recall: 84.66% F1: 83.33%
Val   Loss: 0.5710 | Val Acc: 83.83%   | Precision: 83.91% Recall: 83.83% F1: 81.58%

Epoch: 65/150
Train Loss: 0.5350 | Train Acc: 85.18% | Precision: 84.77% Recall: 85.18% F1: 83.96%
Val   Loss: 0.5387 | Val Acc: 85.63%   | Precision: 85.58% Recall: 85.63% F1: 84.04%

Epoch: 66/150
Train Loss: 0.5327 | Train Acc: 84.95% | Precision: 84.45% Recall: 84.95% F1: 83.65%
Val   Loss: 0.5436 | Val Acc: 85.04%   | Precision: 84.55% Recall: 85.04% F1: 84.13%

Epoch: 67/150
Train Loss: 0.5383 | Train Acc: 84.79% | Precision: 84.35% Recall: 84.79% F1: 83.58%
Val   Loss: 0.5259 | Val Acc: 86.21%   | Precision: 86.14% Recall: 86.21% F1: 84.87%

Epoch: 68/150
Train Loss: 0.5122 | Train Acc: 86.14% | Precision: 85.92% Recall: 86.14% F1: 85.06%
Val   Loss: 0.5264 | Val Acc: 85.88%   | Precision: 85.70% Recall: 85.88% F1: 84.58%

Epoch: 69/150
Train Loss: 0.5218 | Train Acc: 85.51% | Precision: 85.25% Recall: 85.51% F1: 84.28%
Val   Loss: 0.6501 | Val Acc: 80.27%   | Precision: 77.19% Recall: 80.27% F1: 75.39%

Epoch: 70/150
Train Loss: 0.5116 | Train Acc: 85.86% | Precision: 85.58% Recall: 85.86% F1: 84.79%
Val   Loss: 0.5117 | Val Acc: 86.50%   | Precision: 86.34% Recall: 86.50% F1: 85.32%

Epoch: 71/150
Train Loss: 0.5104 | Train Acc: 85.72% | Precision: 85.47% Recall: 85.72% F1: 84.64%
Val   Loss: 0.5051 | Val Acc: 86.61%   | Precision: 86.55% Recall: 86.61% F1: 85.38%

Epoch: 72/150
Train Loss: 0.4920 | Train Acc: 86.30% | Precision: 86.08% Recall: 86.30% F1: 85.29%
Val   Loss: 0.4969 | Val Acc: 86.37%   | Precision: 86.33% Recall: 86.37% F1: 85.12%

Epoch: 73/150
Train Loss: 0.5115 | Train Acc: 85.53% | Precision: 85.21% Recall: 85.53% F1: 84.47%
Val   Loss: 0.4915 | Val Acc: 86.87%   | Precision: 86.61% Recall: 86.87% F1: 85.87%

Epoch: 74/150
Train Loss: 0.4971 | Train Acc: 86.08% | Precision: 85.86% Recall: 86.08% F1: 85.08%
Val   Loss: 0.6564 | Val Acc: 80.27%   | Precision: 76.63% Recall: 80.27% F1: 75.51%

Epoch: 75/150
Train Loss: 0.4891 | Train Acc: 86.58% | Precision: 86.43% Recall: 86.58% F1: 85.60%
Val   Loss: 0.4904 | Val Acc: 86.55%   | Precision: 86.44% Recall: 86.55% F1: 85.63%

Epoch: 76/150
Train Loss: 0.4758 | Train Acc: 86.87% | Precision: 86.72% Recall: 86.87% F1: 85.96%
Val   Loss: 0.4850 | Val Acc: 86.66%   | Precision: 86.37% Recall: 86.66% F1: 85.76%

Epoch: 77/150
Train Loss: 0.6155 | Train Acc: 81.51% | Precision: 81.17% Recall: 81.51% F1: 79.27%
Val   Loss: 0.7275 | Val Acc: 77.35%   | Precision: 71.92% Recall: 77.35% F1: 72.33%

Epoch: 78/150
Train Loss: 0.6520 | Train Acc: 78.87% | Precision: 73.68% Recall: 78.87% F1: 74.91%
Val   Loss: 0.6302 | Val Acc: 80.52%   | Precision: 74.60% Recall: 80.52% F1: 76.16%

Epoch: 79/150
Train Loss: 0.5783 | Train Acc: 81.49% | Precision: 78.56% Recall: 81.49% F1: 78.44%
Val   Loss: 0.5572 | Val Acc: 82.32%   | Precision: 78.34% Recall: 82.32% F1: 79.39%

Epoch: 80/150
Train Loss: 0.5533 | Train Acc: 83.27% | Precision: 82.30% Recall: 83.27% F1: 81.58%
Val   Loss: 0.5450 | Val Acc: 84.32%   | Precision: 83.59% Recall: 84.32% F1: 82.75%

Epoch: 81/150
Train Loss: 0.5384 | Train Acc: 84.50% | Precision: 83.93% Recall: 84.50% F1: 83.30%
Val   Loss: 0.5234 | Val Acc: 85.07%   | Precision: 84.54% Recall: 85.07% F1: 83.94%

Epoch: 82/150
Train Loss: 0.5156 | Train Acc: 85.40% | Precision: 85.02% Recall: 85.40% F1: 84.31%
Val   Loss: 0.5372 | Val Acc: 84.90%   | Precision: 84.62% Recall: 84.90% F1: 83.45%

Epoch: 83/150
Train Loss: 0.5054 | Train Acc: 85.87% | Precision: 85.62% Recall: 85.87% F1: 84.88%
Val   Loss: 0.4952 | Val Acc: 85.93%   | Precision: 85.71% Recall: 85.93% F1: 84.74%

Epoch: 84/150
Train Loss: 0.4864 | Train Acc: 86.41% | Precision: 86.22% Recall: 86.41% F1: 85.48%
Val   Loss: 0.4916 | Val Acc: 86.28%   | Precision: 86.50% Recall: 86.28% F1: 84.95%

Epoch: 85/150
Train Loss: 0.4727 | Train Acc: 86.85% | Precision: 86.73% Recall: 86.85% F1: 85.96%
Val   Loss: 0.5191 | Val Acc: 84.91%   | Precision: 85.18% Recall: 84.91% F1: 82.97%

Epoch: 86/150
Train Loss: 0.4641 | Train Acc: 86.92% | Precision: 86.82% Recall: 86.92% F1: 86.05%
Val   Loss: 0.4706 | Val Acc: 86.76%   | Precision: 86.67% Recall: 86.76% F1: 85.94%

Epoch: 87/150
Train Loss: 0.4937 | Train Acc: 86.03% | Precision: 85.70% Recall: 86.03% F1: 85.05%
Val   Loss: 0.4799 | Val Acc: 86.20%   | Precision: 85.77% Recall: 86.20% F1: 85.24%

Epoch: 88/150
Train Loss: 0.4590 | Train Acc: 87.15% | Precision: 86.89% Recall: 87.15% F1: 86.39%
Val   Loss: 0.4884 | Val Acc: 84.98%   | Precision: 84.40% Recall: 84.98% F1: 83.02%

Epoch: 89/150
Train Loss: 0.4452 | Train Acc: 87.65% | Precision: 87.48% Recall: 87.65% F1: 86.93%
Val   Loss: 0.4469 | Val Acc: 87.40%   | Precision: 87.13% Recall: 87.40% F1: 86.80%

Epoch: 90/150
Train Loss: 0.4396 | Train Acc: 87.63% | Precision: 87.44% Recall: 87.63% F1: 86.93%
Val   Loss: 0.4542 | Val Acc: 86.82%   | Precision: 86.74% Recall: 86.82% F1: 85.76%

Epoch: 91/150
Train Loss: 0.4307 | Train Acc: 87.85% | Precision: 87.68% Recall: 87.85% F1: 87.19%
Val   Loss: 0.4493 | Val Acc: 86.77%   | Precision: 86.66% Recall: 86.77% F1: 85.98%

Epoch: 92/150
Train Loss: 0.4300 | Train Acc: 87.98% | Precision: 87.85% Recall: 87.98% F1: 87.31%
Val   Loss: 0.4353 | Val Acc: 87.45%   | Precision: 87.35% Recall: 87.45% F1: 86.61%

Epoch: 93/150
Train Loss: 0.4211 | Train Acc: 88.24% | Precision: 88.11% Recall: 88.24% F1: 87.63%
Val   Loss: 0.4270 | Val Acc: 87.77%   | Precision: 87.58% Recall: 87.77% F1: 87.02%

Epoch: 94/150
Train Loss: 0.4216 | Train Acc: 88.06% | Precision: 87.92% Recall: 88.06% F1: 87.41%
Val   Loss: 0.4166 | Val Acc: 87.83%   | Precision: 87.69% Recall: 87.83% F1: 87.04%

Epoch: 95/150
Train Loss: 0.4077 | Train Acc: 88.53% | Precision: 88.39% Recall: 88.53% F1: 87.94%
Val   Loss: 0.4139 | Val Acc: 88.51%   | Precision: 88.26% Recall: 88.51% F1: 87.85%

Epoch: 96/150
Train Loss: 0.4065 | Train Acc: 88.54% | Precision: 88.41% Recall: 88.54% F1: 87.95%
Val   Loss: 0.4121 | Val Acc: 88.09%   | Precision: 88.00% Recall: 88.09% F1: 87.51%

Epoch: 97/150
Train Loss: 0.3984 | Train Acc: 88.70% | Precision: 88.58% Recall: 88.70% F1: 88.13%
Val   Loss: 0.4076 | Val Acc: 88.45%   | Precision: 88.34% Recall: 88.45% F1: 87.69%

Epoch: 98/150
Train Loss: 0.3953 | Train Acc: 88.74% | Precision: 88.60% Recall: 88.74% F1: 88.17%
Val   Loss: 0.3977 | Val Acc: 88.62%   | Precision: 88.57% Recall: 88.62% F1: 88.02%

Epoch: 99/150
Train Loss: 0.3936 | Train Acc: 88.80% | Precision: 88.67% Recall: 88.80% F1: 88.25%
Val   Loss: 0.3991 | Val Acc: 88.78%   | Precision: 88.61% Recall: 88.78% F1: 88.29%

Epoch: 100/150
Train Loss: 0.3911 | Train Acc: 88.85% | Precision: 88.73% Recall: 88.85% F1: 88.32%
Val   Loss: 0.3869 | Val Acc: 88.87%   | Precision: 88.81% Recall: 88.87% F1: 88.32%

Epoch: 101/150
Train Loss: 0.3860 | Train Acc: 88.89% | Precision: 88.80% Recall: 88.89% F1: 88.36%
Val   Loss: 0.4031 | Val Acc: 88.14%   | Precision: 87.98% Recall: 88.14% F1: 87.45%

Epoch: 102/150
Train Loss: 0.3808 | Train Acc: 89.10% | Precision: 89.00% Recall: 89.10% F1: 88.57%
Val   Loss: 0.3844 | Val Acc: 89.06%   | Precision: 88.91% Recall: 89.06% F1: 88.43%

Epoch: 103/150
Train Loss: 0.3880 | Train Acc: 88.93% | Precision: 88.83% Recall: 88.93% F1: 88.41%
Val   Loss: 0.3811 | Val Acc: 89.14%   | Precision: 89.01% Recall: 89.14% F1: 88.54%

Epoch: 104/150
Train Loss: 0.3698 | Train Acc: 89.65% | Precision: 89.54% Recall: 89.65% F1: 89.17%
Val   Loss: 0.3854 | Val Acc: 89.30%   | Precision: 89.15% Recall: 89.30% F1: 88.65%

Epoch: 105/150
Train Loss: 0.3737 | Train Acc: 89.38% | Precision: 89.27% Recall: 89.38% F1: 88.89%
Val   Loss: 0.3853 | Val Acc: 88.86%   | Precision: 88.62% Recall: 88.86% F1: 88.34%

Epoch: 106/150
Train Loss: 0.3670 | Train Acc: 89.61% | Precision: 89.53% Recall: 89.61% F1: 89.13%
Val   Loss: 0.3699 | Val Acc: 89.48%   | Precision: 89.29% Recall: 89.48% F1: 88.92%

Epoch: 107/150
Train Loss: 0.3663 | Train Acc: 89.67% | Precision: 89.57% Recall: 89.67% F1: 89.20%
Val   Loss: 0.3874 | Val Acc: 88.77%   | Precision: 88.65% Recall: 88.77% F1: 87.99%

Epoch: 108/150
Train Loss: 0.3620 | Train Acc: 89.78% | Precision: 89.71% Recall: 89.78% F1: 89.31%
Val   Loss: 0.3578 | Val Acc: 90.01%   | Precision: 89.96% Recall: 90.01% F1: 89.47%

Epoch: 109/150

wandb: Agent Starting Run: iqb627zz with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.0003428441737510262
wandb: 	optimizer: sgd
wandb: 	rnn_type: rnn
wandb: 	seq_len: 130
wandb: 	weight_decay: 0.0001

Epoch: 1/150
Train Loss: 1.3569 | Train Acc: 63.42% | Precision: 43.06% Recall: 63.42% F1: 50.71%
Val   Loss: 1.1393 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.1303 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1281 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1247 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1237 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1216 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1203 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.1184 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1185 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.1141 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1142 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 7/150
Train Loss: 1.1082 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1053 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 8/150
Train Loss: 1.0984 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0927 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 9/150
Train Loss: 1.0786 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0619 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 10/150
Train Loss: 1.0070 | Train Acc: 65.56% | Precision: 51.94% Recall: 65.56% F1: 53.51%
Val   Loss: 0.9347 | Val Acc: 69.90%   | Precision: 56.05% Recall: 69.90% F1: 61.05%

Epoch: 11/150
Train Loss: 0.9000 | Train Acc: 70.63% | Precision: 56.63% Recall: 70.63% F1: 62.13%
Val   Loss: 0.8719 | Val Acc: 71.74%   | Precision: 57.55% Recall: 71.74% F1: 62.97%

Epoch: 12/150
Train Loss: 0.8575 | Train Acc: 71.90% | Precision: 57.87% Recall: 71.90% F1: 63.35%
Val   Loss: 0.8471 | Val Acc: 71.71%   | Precision: 58.34% Recall: 71.71% F1: 63.72%

Epoch: 13/150
Train Loss: 0.8398 | Train Acc: 71.86% | Precision: 58.58% Recall: 71.86% F1: 63.68%
Val   Loss: 0.8361 | Val Acc: 71.90%   | Precision: 58.45% Recall: 71.90% F1: 63.66%

Epoch: 14/150
Train Loss: 0.8255 | Train Acc: 71.95% | Precision: 58.89% Recall: 71.95% F1: 63.96%
Val   Loss: 0.8237 | Val Acc: 71.98%   | Precision: 58.74% Recall: 71.98% F1: 63.91%

Epoch: 15/150
Train Loss: 0.8092 | Train Acc: 72.42% | Precision: 60.05% Recall: 72.42% F1: 64.53%
Val   Loss: 0.8036 | Val Acc: 72.88%   | Precision: 61.33% Recall: 72.88% F1: 65.48%

Epoch: 16/150
Train Loss: 0.7915 | Train Acc: 72.95% | Precision: 61.24% Recall: 72.95% F1: 65.22%
Val   Loss: 0.7848 | Val Acc: 73.41%   | Precision: 61.85% Recall: 73.41% F1: 65.83%

Epoch: 17/150
Train Loss: 0.7681 | Train Acc: 73.71% | Precision: 64.40% Recall: 73.71% F1: 66.60%
Val   Loss: 0.7669 | Val Acc: 74.15%   | Precision: 67.14% Recall: 74.15% F1: 68.24%

Epoch: 18/150
Train Loss: 0.7230 | Train Acc: 75.61% | Precision: 69.51% Recall: 75.61% F1: 70.41%
Val   Loss: 0.7045 | Val Acc: 76.77%   | Precision: 70.31% Recall: 76.77% F1: 72.16%

Epoch: 19/150
Train Loss: 0.6818 | Train Acc: 77.39% | Precision: 71.16% Recall: 77.39% F1: 72.83%
Val   Loss: 0.6753 | Val Acc: 78.26%   | Precision: 72.31% Recall: 78.26% F1: 73.39%

Epoch: 20/150
Train Loss: 0.6565 | Train Acc: 78.45% | Precision: 72.37% Recall: 78.45% F1: 74.13%
Val   Loss: 0.6571 | Val Acc: 79.16%   | Precision: 73.19% Recall: 79.16% F1: 74.84%

Epoch: 21/150
Train Loss: 0.6329 | Train Acc: 79.26% | Precision: 73.30% Recall: 79.26% F1: 75.22%
Val   Loss: 0.6622 | Val Acc: 78.51%   | Precision: 72.49% Recall: 78.51% F1: 73.42%

Epoch: 22/150
Train Loss: 0.6085 | Train Acc: 80.36% | Precision: 74.63% Recall: 80.36% F1: 76.50%
Val   Loss: 0.6204 | Val Acc: 81.06%   | Precision: 75.86% Recall: 81.06% F1: 77.88%

Epoch: 23/150
Train Loss: 0.5765 | Train Acc: 81.80% | Precision: 80.20% Recall: 81.80% F1: 79.02%
Val   Loss: 0.5727 | Val Acc: 83.12%   | Precision: 82.51% Recall: 83.12% F1: 81.68%

Epoch: 24/150
Train Loss: 0.5430 | Train Acc: 84.38% | Precision: 83.95% Recall: 84.38% F1: 82.95%
Val   Loss: 0.5287 | Val Acc: 85.40%   | Precision: 85.32% Recall: 85.40% F1: 83.99%

Epoch: 25/150
Train Loss: 0.5171 | Train Acc: 85.40% | Precision: 85.06% Recall: 85.40% F1: 84.26%
Val   Loss: 0.5084 | Val Acc: 86.06%   | Precision: 85.98% Recall: 86.06% F1: 84.75%

Epoch: 26/150
Train Loss: 0.4914 | Train Acc: 86.21% | Precision: 85.95% Recall: 86.21% F1: 85.21%
Val   Loss: 0.4822 | Val Acc: 86.50%   | Precision: 86.13% Recall: 86.50% F1: 85.44%

Epoch: 27/150
Train Loss: 0.4645 | Train Acc: 86.83% | Precision: 86.64% Recall: 86.83% F1: 85.91%
Val   Loss: 0.5123 | Val Acc: 84.73%   | Precision: 84.20% Recall: 84.73% F1: 83.63%

Epoch: 28/150
Train Loss: 0.4568 | Train Acc: 86.81% | Precision: 86.61% Recall: 86.81% F1: 85.90%
Val   Loss: 0.4619 | Val Acc: 87.00%   | Precision: 86.96% Recall: 87.00% F1: 85.89%

Epoch: 29/150
Train Loss: 0.4386 | Train Acc: 87.37% | Precision: 87.22% Recall: 87.37% F1: 86.54%
Val   Loss: 0.4428 | Val Acc: 86.85%   | Precision: 86.63% Recall: 86.85% F1: 86.06%

Epoch: 30/150
Train Loss: 0.4312 | Train Acc: 87.49% | Precision: 87.37% Recall: 87.49% F1: 86.67%
Val   Loss: 0.4243 | Val Acc: 87.41%   | Precision: 87.26% Recall: 87.41% F1: 86.54%

Epoch: 31/150
Train Loss: 0.4217 | Train Acc: 87.76% | Precision: 87.68% Recall: 87.76% F1: 87.00%
Val   Loss: 0.4283 | Val Acc: 87.46%   | Precision: 87.33% Recall: 87.46% F1: 86.62%

Epoch: 32/150
Train Loss: 0.4141 | Train Acc: 87.89% | Precision: 87.80% Recall: 87.89% F1: 87.15%
Val   Loss: 0.4014 | Val Acc: 88.12%   | Precision: 88.07% Recall: 88.12% F1: 87.28%

Epoch: 33/150
Train Loss: 0.4074 | Train Acc: 87.98% | Precision: 87.91% Recall: 87.98% F1: 87.25%
Val   Loss: 0.4222 | Val Acc: 87.02%   | Precision: 87.33% Recall: 87.02% F1: 85.93%

Epoch: 34/150
Train Loss: 0.3979 | Train Acc: 88.33% | Precision: 88.25% Recall: 88.33% F1: 87.64%
Val   Loss: 0.4397 | Val Acc: 86.76%   | Precision: 87.18% Recall: 86.76% F1: 85.41%

Epoch: 35/150
Train Loss: 0.3899 | Train Acc: 88.62% | Precision: 88.60% Recall: 88.62% F1: 87.98%
Val   Loss: 0.3789 | Val Acc: 88.87%   | Precision: 88.92% Recall: 88.87% F1: 88.16%

Epoch: 36/150
Train Loss: 0.3863 | Train Acc: 88.74% | Precision: 88.70% Recall: 88.74% F1: 88.11%
Val   Loss: 0.4240 | Val Acc: 87.44%   | Precision: 86.99% Recall: 87.44% F1: 86.87%

Epoch: 37/150
Train Loss: 0.3745 | Train Acc: 89.20% | Precision: 89.22% Recall: 89.20% F1: 88.62%
Val   Loss: 0.3867 | Val Acc: 88.42%   | Precision: 88.10% Recall: 88.42% F1: 87.85%

Epoch: 38/150
Train Loss: 0.3670 | Train Acc: 89.42% | Precision: 89.44% Recall: 89.42% F1: 88.84%
Val   Loss: 0.3695 | Val Acc: 89.28%   | Precision: 89.16% Recall: 89.28% F1: 88.77%

Epoch: 39/150
Train Loss: 0.3651 | Train Acc: 89.32% | Precision: 89.32% Recall: 89.32% F1: 88.74%
Val   Loss: 0.3542 | Val Acc: 89.61%   | Precision: 89.58% Recall: 89.61% F1: 89.12%

Epoch: 40/150
Train Loss: 0.3568 | Train Acc: 89.65% | Precision: 89.69% Recall: 89.65% F1: 89.10%
Val   Loss: 0.3487 | Val Acc: 89.90%   | Precision: 89.94% Recall: 89.90% F1: 89.21%

Epoch: 41/150
Train Loss: 0.3507 | Train Acc: 89.98% | Precision: 90.03% Recall: 89.98% F1: 89.45%
Val   Loss: 0.3483 | Val Acc: 90.06%   | Precision: 89.94% Recall: 90.06% F1: 89.56%

Epoch: 42/150
Train Loss: 0.3515 | Train Acc: 89.83% | Precision: 89.84% Recall: 89.83% F1: 89.29%
Val   Loss: 0.3938 | Val Acc: 88.17%   | Precision: 88.05% Recall: 88.17% F1: 87.55%

Epoch: 43/150
Train Loss: 0.3437 | Train Acc: 90.06% | Precision: 90.09% Recall: 90.06% F1: 89.54%
Val   Loss: 0.3341 | Val Acc: 90.38%   | Precision: 90.34% Recall: 90.38% F1: 89.86%

Epoch: 44/150
Train Loss: 0.3410 | Train Acc: 90.17% | Precision: 90.23% Recall: 90.17% F1: 89.66%
Val   Loss: 0.3259 | Val Acc: 90.54%   | Precision: 90.58% Recall: 90.54% F1: 89.98%

Epoch: 45/150
Train Loss: 0.3349 | Train Acc: 90.39% | Precision: 90.45% Recall: 90.39% F1: 89.89%
Val   Loss: 0.3452 | Val Acc: 90.29%   | Precision: 90.28% Recall: 90.29% F1: 89.81%

Epoch: 46/150
Train Loss: 0.3294 | Train Acc: 90.42% | Precision: 90.45% Recall: 90.42% F1: 89.92%
Val   Loss: 0.3188 | Val Acc: 90.65%   | Precision: 90.71% Recall: 90.65% F1: 90.05%

Epoch: 47/150
Train Loss: 0.3294 | Train Acc: 90.47% | Precision: 90.51% Recall: 90.47% F1: 89.98%
Val   Loss: 0.3568 | Val Acc: 89.62%   | Precision: 89.69% Recall: 89.62% F1: 88.99%

Epoch: 48/150
Train Loss: 0.3288 | Train Acc: 90.43% | Precision: 90.44% Recall: 90.43% F1: 89.95%
Val   Loss: 0.3356 | Val Acc: 90.54%   | Precision: 90.46% Recall: 90.54% F1: 90.03%

Epoch: 49/150
Train Loss: 0.3162 | Train Acc: 90.88% | Precision: 90.96% Recall: 90.88% F1: 90.42%
Val   Loss: 0.3258 | Val Acc: 90.33%   | Precision: 90.31% Recall: 90.33% F1: 89.77%

Epoch: 50/150
Train Loss: 0.3121 | Train Acc: 90.94% | Precision: 90.97% Recall: 90.94% F1: 90.49%
Val   Loss: 0.3137 | Val Acc: 90.86%   | Precision: 90.95% Recall: 90.86% F1: 90.18%

Epoch: 51/150
Train Loss: 0.3077 | Train Acc: 91.11% | Precision: 91.15% Recall: 91.11% F1: 90.66%
Val   Loss: 0.3172 | Val Acc: 90.83%   | Precision: 90.78% Recall: 90.83% F1: 90.20%

Epoch: 52/150
Train Loss: 0.3007 | Train Acc: 91.39% | Precision: 91.44% Recall: 91.39% F1: 90.96%
Val   Loss: 0.3109 | Val Acc: 90.97%   | Precision: 91.06% Recall: 90.97% F1: 90.41%

Epoch: 53/150
Train Loss: 0.2950 | Train Acc: 91.50% | Precision: 91.53% Recall: 91.50% F1: 91.08%
Val   Loss: 0.2951 | Val Acc: 91.24%   | Precision: 91.25% Recall: 91.24% F1: 90.75%

Epoch: 54/150
Train Loss: 0.2963 | Train Acc: 91.33% | Precision: 91.38% Recall: 91.33% F1: 90.91%
Val   Loss: 0.2990 | Val Acc: 91.17%   | Precision: 91.17% Recall: 91.17% F1: 90.54%

Epoch: 55/150
Train Loss: 0.2928 | Train Acc: 91.45% | Precision: 91.46% Recall: 91.45% F1: 91.04%
Val   Loss: 0.2780 | Val Acc: 91.72%   | Precision: 91.78% Recall: 91.72% F1: 91.25%

Epoch: 56/150
Train Loss: 0.2797 | Train Acc: 91.74% | Precision: 91.74% Recall: 91.74% F1: 91.35%
Val   Loss: 0.2853 | Val Acc: 91.57%   | Precision: 91.50% Recall: 91.57% F1: 91.13%

Epoch: 57/150
Train Loss: 0.2840 | Train Acc: 91.64% | Precision: 91.65% Recall: 91.64% F1: 91.25%
Val   Loss: 0.2743 | Val Acc: 91.61%   | Precision: 91.57% Recall: 91.61% F1: 91.16%

Epoch: 58/150
Train Loss: 0.2715 | Train Acc: 91.85% | Precision: 91.85% Recall: 91.85% F1: 91.46%
Val   Loss: 0.2771 | Val Acc: 91.51%   | Precision: 91.47% Recall: 91.51% F1: 91.07%

Epoch: 59/150
Train Loss: 0.2691 | Train Acc: 91.95% | Precision: 91.97% Recall: 91.95% F1: 91.58%
Val   Loss: 0.2898 | Val Acc: 91.10%   | Precision: 90.97% Recall: 91.10% F1: 90.46%

Epoch: 60/150
Train Loss: 0.2655 | Train Acc: 91.99% | Precision: 91.98% Recall: 91.99% F1: 91.61%
Val   Loss: 0.2648 | Val Acc: 91.98%   | Precision: 91.93% Recall: 91.98% F1: 91.59%

Epoch: 61/150
Train Loss: 0.2592 | Train Acc: 92.17% | Precision: 92.18% Recall: 92.17% F1: 91.83%
Val   Loss: 0.2759 | Val Acc: 91.24%   | Precision: 91.16% Recall: 91.24% F1: 90.71%

Epoch: 62/150
Train Loss: 0.2635 | Train Acc: 91.98% | Precision: 91.97% Recall: 91.98% F1: 91.62%
Val   Loss: 0.2893 | Val Acc: 90.91%   | Precision: 90.78% Recall: 90.91% F1: 90.53%

Epoch: 63/150
Train Loss: 0.2537 | Train Acc: 92.28% | Precision: 92.26% Recall: 92.28% F1: 91.96%
Val   Loss: 0.2655 | Val Acc: 91.70%   | Precision: 91.70% Recall: 91.70% F1: 91.36%

Epoch: 64/150
Train Loss: 0.2504 | Train Acc: 92.44% | Precision: 92.41% Recall: 92.44% F1: 92.12%
Val   Loss: 0.2709 | Val Acc: 91.90%   | Precision: 91.84% Recall: 91.90% F1: 91.50%

Epoch: 65/150
Train Loss: 0.2478 | Train Acc: 92.58% | Precision: 92.56% Recall: 92.58% F1: 92.26%
Val   Loss: 0.2397 | Val Acc: 92.43%   | Precision: 92.51% Recall: 92.43% F1: 91.95%

Epoch: 66/150
Train Loss: 0.2515 | Train Acc: 92.43% | Precision: 92.40% Recall: 92.43% F1: 92.10%
Val   Loss: 0.2401 | Val Acc: 92.52%   | Precision: 92.55% Recall: 92.52% F1: 92.13%

Epoch: 67/150
Train Loss: 0.2644 | Train Acc: 92.01% | Precision: 91.97% Recall: 92.01% F1: 91.66%
Val   Loss: 0.2773 | Val Acc: 90.98%   | Precision: 91.16% Recall: 90.98% F1: 90.59%

Epoch: 68/150
Train Loss: 0.2371 | Train Acc: 92.83% | Precision: 92.80% Recall: 92.83% F1: 92.54%
Val   Loss: 0.2861 | Val Acc: 91.38%   | Precision: 91.37% Recall: 91.38% F1: 90.94%

Epoch: 69/150
Train Loss: 0.2407 | Train Acc: 92.70% | Precision: 92.68% Recall: 92.70% F1: 92.41%
Val   Loss: 0.2639 | Val Acc: 92.04%   | Precision: 92.10% Recall: 92.04% F1: 91.61%

Epoch: 70/150
Train Loss: 0.2389 | Train Acc: 92.77% | Precision: 92.74% Recall: 92.77% F1: 92.49%
Val   Loss: 0.2634 | Val Acc: 91.58%   | Precision: 91.36% Recall: 91.58% F1: 91.20%

Epoch: 71/150
Train Loss: 0.2332 | Train Acc: 92.95% | Precision: 92.90% Recall: 92.95% F1: 92.69%
Val   Loss: 0.2346 | Val Acc: 92.87%   | Precision: 92.87% Recall: 92.87% F1: 92.60%

Epoch: 72/150
Train Loss: 0.2281 | Train Acc: 93.18% | Precision: 93.16% Recall: 93.18% F1: 92.92%
Val   Loss: 0.2428 | Val Acc: 92.60%   | Precision: 92.56% Recall: 92.60% F1: 92.31%

Epoch: 73/150
Train Loss: 0.2316 | Train Acc: 93.07% | Precision: 93.04% Recall: 93.07% F1: 92.81%
Val   Loss: 0.2359 | Val Acc: 92.59%   | Precision: 92.52% Recall: 92.59% F1: 92.30%

Epoch: 74/150
Train Loss: 0.2221 | Train Acc: 93.36% | Precision: 93.33% Recall: 93.36% F1: 93.12%
Val   Loss: 0.2257 | Val Acc: 93.04%   | Precision: 93.03% Recall: 93.04% F1: 92.73%

Epoch: 75/150
Train Loss: 0.2279 | Train Acc: 93.14% | Precision: 93.09% Recall: 93.14% F1: 92.90%
Val   Loss: 0.2479 | Val Acc: 91.85%   | Precision: 91.91% Recall: 91.85% F1: 91.35%

Epoch: 76/150
Train Loss: 0.2222 | Train Acc: 93.20% | Precision: 93.14% Recall: 93.20% F1: 92.97%
Val   Loss: 0.2280 | Val Acc: 92.85%   | Precision: 92.93% Recall: 92.85% F1: 92.54%

Epoch: 77/150
Train Loss: 0.2183 | Train Acc: 93.47% | Precision: 93.42% Recall: 93.47% F1: 93.25%
Val   Loss: 0.2272 | Val Acc: 92.80%   | Precision: 92.69% Recall: 92.80% F1: 92.57%

Epoch: 78/150
Train Loss: 0.2157 | Train Acc: 93.54% | Precision: 93.50% Recall: 93.54% F1: 93.32%
Val   Loss: 0.2186 | Val Acc: 93.19%   | Precision: 93.11% Recall: 93.19% F1: 92.92%

Epoch: 79/150
Train Loss: 0.2175 | Train Acc: 93.44% | Precision: 93.41% Recall: 93.44% F1: 93.22%
Val   Loss: 0.2110 | Val Acc: 93.31%   | Precision: 93.19% Recall: 93.31% F1: 93.05%

Epoch: 80/150
Train Loss: 0.2118 | Train Acc: 93.60% | Precision: 93.57% Recall: 93.60% F1: 93.40%
Val   Loss: 0.2122 | Val Acc: 93.03%   | Precision: 93.15% Recall: 93.03% F1: 92.71%

Epoch: 81/150
Train Loss: 0.2053 | Train Acc: 93.75% | Precision: 93.69% Recall: 93.75% F1: 93.55%
Val   Loss: 0.2229 | Val Acc: 93.08%   | Precision: 93.09% Recall: 93.08% F1: 92.74%

Epoch: 82/150
Train Loss: 0.2091 | Train Acc: 93.66% | Precision: 93.59% Recall: 93.66% F1: 93.45%
Val   Loss: 0.2104 | Val Acc: 93.44%   | Precision: 93.31% Recall: 93.44% F1: 93.25%

Epoch: 83/150
Train Loss: 0.1998 | Train Acc: 93.99% | Precision: 93.94% Recall: 93.99% F1: 93.80%
Val   Loss: 0.1968 | Val Acc: 94.02%   | Precision: 93.96% Recall: 94.02% F1: 93.85%

Epoch: 84/150
Train Loss: 0.1990 | Train Acc: 94.07% | Precision: 94.01% Recall: 94.07% F1: 93.89%
Val   Loss: 0.2152 | Val Acc: 93.25%   | Precision: 93.22% Recall: 93.25% F1: 93.08%

Epoch: 85/150
Train Loss: 0.2041 | Train Acc: 93.79% | Precision: 93.73% Recall: 93.79% F1: 93.60%
Val   Loss: 0.2477 | Val Acc: 92.19%   | Precision: 92.08% Recall: 92.19% F1: 91.92%

Epoch: 86/150
Train Loss: 0.2045 | Train Acc: 93.78% | Precision: 93.73% Recall: 93.78% F1: 93.58%
Val   Loss: 0.1925 | Val Acc: 93.91%   | Precision: 93.87% Recall: 93.91% F1: 93.72%

Epoch: 87/150
Train Loss: 0.1981 | Train Acc: 93.95% | Precision: 93.90% Recall: 93.95% F1: 93.76%
Val   Loss: 0.1958 | Val Acc: 93.99%   | Precision: 93.92% Recall: 93.99% F1: 93.79%

Epoch: 88/150
Train Loss: 0.1987 | Train Acc: 93.92% | Precision: 93.87% Recall: 93.92% F1: 93.74%
Val   Loss: 0.2005 | Val Acc: 93.66%   | Precision: 93.56% Recall: 93.66% F1: 93.48%

Epoch: 89/150
Train Loss: 0.1965 | Train Acc: 93.90% | Precision: 93.85% Recall: 93.90% F1: 93.72%
Val   Loss: 0.2446 | Val Acc: 92.46%   | Precision: 92.30% Recall: 92.46% F1: 92.22%

Epoch: 90/150
Train Loss: 0.1969 | Train Acc: 93.95% | Precision: 93.88% Recall: 93.95% F1: 93.77%
Val   Loss: 0.1968 | Val Acc: 94.08%   | Precision: 93.96% Recall: 94.08% F1: 93.91%

Epoch: 91/150
Train Loss: 0.2119 | Train Acc: 93.51% | Precision: 93.43% Recall: 93.51% F1: 93.31%
Val   Loss: 0.4474 | Val Acc: 85.37%   | Precision: 84.26% Recall: 85.37% F1: 84.22%

Epoch: 92/150
Train Loss: 0.2002 | Train Acc: 93.87% | Precision: 93.80% Recall: 93.87% F1: 93.69%
Val   Loss: 0.1965 | Val Acc: 93.87%   | Precision: 93.82% Recall: 93.87% F1: 93.58%

Epoch: 93/150
Train Loss: 0.1846 | Train Acc: 94.24% | Precision: 94.19% Recall: 94.24% F1: 94.08%
Val   Loss: 0.1875 | Val Acc: 94.14%   | Precision: 94.05% Recall: 94.14% F1: 93.99%

Epoch: 94/150
Train Loss: 0.1874 | Train Acc: 94.23% | Precision: 94.16% Recall: 94.23% F1: 94.06%
Val   Loss: 0.1827 | Val Acc: 94.14%   | Precision: 94.05% Recall: 94.14% F1: 93.96%

Epoch: 95/150
Train Loss: 0.1882 | Train Acc: 94.18% | Precision: 94.11% Recall: 94.18% F1: 94.01%
Val   Loss: 0.2211 | Val Acc: 93.29%   | Precision: 93.18% Recall: 93.29% F1: 93.14%

Epoch: 96/150
Train Loss: 0.1865 | Train Acc: 94.25% | Precision: 94.20% Recall: 94.25% F1: 94.10%
Val   Loss: 0.3183 | Val Acc: 90.45%   | Precision: 90.48% Recall: 90.45% F1: 89.84%

Epoch: 97/150
Train Loss: 0.1870 | Train Acc: 94.26% | Precision: 94.20% Recall: 94.26% F1: 94.09%
Val   Loss: 0.1804 | Val Acc: 94.40%   | Precision: 94.38% Recall: 94.40% F1: 94.24%

Epoch: 98/150
Train Loss: 0.1841 | Train Acc: 94.19% | Precision: 94.13% Recall: 94.19% F1: 94.02%
Val   Loss: 0.1749 | Val Acc: 94.56%   | Precision: 94.49% Recall: 94.56% F1: 94.45%

Epoch: 99/150
Train Loss: 0.1797 | Train Acc: 94.48% | Precision: 94.43% Recall: 94.48% F1: 94.32%
Val   Loss: 0.1858 | Val Acc: 93.96%   | Precision: 93.83% Recall: 93.96% F1: 93.84%

Epoch: 100/150
Train Loss: 0.1789 | Train Acc: 94.46% | Precision: 94.40% Recall: 94.46% F1: 94.31%
Val   Loss: 0.2374 | Val Acc: 92.36%   | Precision: 92.30% Recall: 92.36% F1: 92.11%

Epoch: 101/150
Train Loss: 0.1813 | Train Acc: 94.50% | Precision: 94.44% Recall: 94.50% F1: 94.35%
Val   Loss: 0.1961 | Val Acc: 93.62%   | Precision: 93.54% Recall: 93.62% F1: 93.44%

Epoch: 102/150
Train Loss: 0.1906 | Train Acc: 94.09% | Precision: 94.02% Recall: 94.09% F1: 93.92%
Val   Loss: 0.1681 | Val Acc: 94.62%   | Precision: 94.55% Recall: 94.62% F1: 94.50%

Epoch: 103/150
Train Loss: 0.1828 | Train Acc: 94.40% | Precision: 94.35% Recall: 94.40% F1: 94.25%
Val   Loss: 0.2057 | Val Acc: 93.57%   | Precision: 93.55% Recall: 93.57% F1: 93.25%

Epoch: 104/150
Train Loss: 0.1728 | Train Acc: 94.57% | Precision: 94.52% Recall: 94.57% F1: 94.43%
Val   Loss: 0.1991 | Val Acc: 93.69%   | Precision: 93.72% Recall: 93.69% F1: 93.42%

Epoch: 105/150
Train Loss: 0.1771 | Train Acc: 94.49% | Precision: 94.44% Recall: 94.49% F1: 94.35%
Val   Loss: 0.2313 | Val Acc: 93.07%   | Precision: 93.11% Recall: 93.07% F1: 92.96%

Epoch: 106/150
Train Loss: 0.1689 | Train Acc: 94.75% | Precision: 94.70% Recall: 94.75% F1: 94.62%
Val   Loss: 0.1607 | Val Acc: 94.89%   | Precision: 94.81% Recall: 94.89% F1: 94.76%

Epoch: 107/150
Train Loss: 0.3574 | Train Acc: 88.48% | Precision: 88.25% Recall: 88.48% F1: 87.85%
Val   Loss: 0.4676 | Val Acc: 85.50%   | Precision: 85.02% Recall: 85.50% F1: 84.06%

Epoch: 108/150
Train Loss: 0.4028 | Train Acc: 87.84% | Precision: 87.59% Recall: 87.84% F1: 87.13%
Val   Loss: 0.3586 | Val Acc: 89.36%   | Precision: 89.25% Recall: 89.36% F1: 88.75%

Epoch: 109/150

wandb: Agent Starting Run: pzkjib2f with config:
wandb: 	batch_size: 64
wandb: 	bidirectional: True
wandb: 	hidden_dim: 512
wandb: 	learning_rate: 0.000311396794147487
wandb: 	optimizer: sgd
wandb: 	rnn_type: rnn
wandb: 	seq_len: 150
wandb: 	weight_decay: 0.001

Epoch: 1/150
Train Loss: 1.4004 | Train Acc: 63.45% | Precision: 41.67% Recall: 63.45% F1: 50.30%
Val   Loss: 1.1423 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 2/150
Train Loss: 1.1313 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1262 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 3/150
Train Loss: 1.1245 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1243 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 4/150
Train Loss: 1.1217 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1210 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 5/150
Train Loss: 1.1184 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1194 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 6/150
Train Loss: 1.1151 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1136 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 7/150
Train Loss: 1.1098 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.1075 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 8/150
Train Loss: 1.1027 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0991 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 9/150
Train Loss: 1.0895 | Train Acc: 64.55% | Precision: 41.67% Recall: 64.55% F1: 50.65%
Val   Loss: 1.0812 | Val Acc: 64.55%   | Precision: 41.67% Recall: 64.55% F1: 50.65%

Epoch: 10/150
Train Loss: 1.0590 | Train Acc: 64.56% | Precision: 47.42% Recall: 64.56% F1: 50.68%
Val   Loss: 1.0293 | Val Acc: 64.45%   | Precision: 44.44% Recall: 64.45% F1: 50.70%

Epoch: 11/150
Train Loss: 0.9637 | Train Acc: 67.43% | Precision: 53.73% Recall: 67.43% F1: 57.63%
Val   Loss: 0.9169 | Val Acc: 70.68%   | Precision: 56.58% Recall: 70.68% F1: 61.88%

Epoch: 12/150
Train Loss: 0.8946 | Train Acc: 70.76% | Precision: 56.75% Recall: 70.76% F1: 62.32%
Val   Loss: 0.8733 | Val Acc: 72.09%   | Precision: 57.79% Recall: 72.09% F1: 63.13%

Epoch: 13/150
Train Loss: 0.8592 | Train Acc: 71.68% | Precision: 57.78% Recall: 71.68% F1: 63.24%
Val   Loss: 0.8447 | Val Acc: 71.98%   | Precision: 58.27% Recall: 71.98% F1: 63.58%

Epoch: 14/150
Train Loss: 0.8418 | Train Acc: 71.75% | Precision: 58.64% Recall: 71.75% F1: 63.67%
Val   Loss: 0.8321 | Val Acc: 72.47%   | Precision: 59.38% Recall: 72.47% F1: 64.03%

Epoch: 15/150
Train Loss: 0.8279 | Train Acc: 71.77% | Precision: 58.98% Recall: 71.77% F1: 63.88%
Val   Loss: 0.8294 | Val Acc: 71.63%   | Precision: 58.33% Recall: 71.63% F1: 63.62%

Epoch: 16/150
Train Loss: 0.8135 | Train Acc: 72.00% | Precision: 59.81% Recall: 72.00% F1: 64.25%
Val   Loss: 0.8089 | Val Acc: 72.45%   | Precision: 61.86% Recall: 72.45% F1: 64.20%

Epoch: 17/150
Train Loss: 0.7797 | Train Acc: 72.75% | Precision: 65.56% Recall: 72.75% F1: 65.77%
Val   Loss: 0.7552 | Val Acc: 73.92%   | Precision: 67.44% Recall: 73.92% F1: 67.14%

Epoch: 18/150
Train Loss: 0.7541 | Train Acc: 74.13% | Precision: 67.73% Recall: 74.13% F1: 68.19%
Val   Loss: 0.7558 | Val Acc: 74.96%   | Precision: 67.89% Recall: 74.96% F1: 70.17%

Epoch: 19/150
Train Loss: 0.7265 | Train Acc: 75.26% | Precision: 68.80% Recall: 75.26% F1: 70.03%
Val   Loss: 0.7288 | Val Acc: 75.89%   | Precision: 69.50% Recall: 75.89% F1: 71.94%

Epoch: 20/150
Train Loss: 0.7107 | Train Acc: 75.63% | Precision: 68.95% Recall: 75.63% F1: 70.84%
Val   Loss: 0.7154 | Val Acc: 74.85%   | Precision: 67.46% Recall: 74.85% F1: 68.09%

Epoch: 21/150
Train Loss: 0.6728 | Train Acc: 76.87% | Precision: 70.55% Recall: 76.87% F1: 72.46%
Val   Loss: 0.6513 | Val Acc: 77.83%   | Precision: 71.74% Recall: 77.83% F1: 73.43%

Epoch: 22/150
Train Loss: 0.6488 | Train Acc: 78.05% | Precision: 71.95% Recall: 78.05% F1: 73.84%
Val   Loss: 0.6290 | Val Acc: 78.96%   | Precision: 72.86% Recall: 78.96% F1: 75.07%

Epoch: 23/150
Train Loss: 0.6192 | Train Acc: 79.45% | Precision: 73.57% Recall: 79.45% F1: 75.57%
Val   Loss: 0.6332 | Val Acc: 79.92%   | Precision: 74.09% Recall: 79.92% F1: 75.50%

Epoch: 24/150
Train Loss: 0.5933 | Train Acc: 80.62% | Precision: 74.96% Recall: 80.62% F1: 76.95%
Val   Loss: 0.5995 | Val Acc: 81.15%   | Precision: 75.73% Recall: 81.15% F1: 77.17%

Epoch: 25/150
Train Loss: 0.5666 | Train Acc: 81.87% | Precision: 78.57% Recall: 81.87% F1: 78.62%
Val   Loss: 0.5788 | Val Acc: 81.78%   | Precision: 78.37% Recall: 81.78% F1: 79.08%

Epoch: 26/150
Train Loss: 0.5486 | Train Acc: 82.67% | Precision: 80.97% Recall: 82.67% F1: 80.09%
Val   Loss: 0.5590 | Val Acc: 83.16%   | Precision: 82.17% Recall: 83.16% F1: 81.14%

Epoch: 27/150
Train Loss: 0.5373 | Train Acc: 83.66% | Precision: 82.81% Recall: 83.66% F1: 81.80%
Val   Loss: 0.6058 | Val Acc: 78.98%   | Precision: 75.75% Recall: 78.98% F1: 74.26%

Epoch: 28/150
Train Loss: 0.5184 | Train Acc: 84.80% | Precision: 84.36% Recall: 84.80% F1: 83.46%
Val   Loss: 0.5073 | Val Acc: 85.72%   | Precision: 85.25% Recall: 85.72% F1: 84.63%

Epoch: 29/150
Train Loss: 0.4963 | Train Acc: 85.61% | Precision: 85.27% Recall: 85.61% F1: 84.52%
Val   Loss: 0.4944 | Val Acc: 86.11%   | Precision: 85.74% Recall: 86.11% F1: 84.99%

Epoch: 30/150
Train Loss: 0.4844 | Train Acc: 86.07% | Precision: 85.78% Recall: 86.07% F1: 85.12%
Val   Loss: 0.4740 | Val Acc: 86.47%   | Precision: 86.23% Recall: 86.47% F1: 85.45%

Epoch: 31/150
Train Loss: 0.4627 | Train Acc: 86.81% | Precision: 86.61% Recall: 86.81% F1: 85.97%
Val   Loss: 0.4732 | Val Acc: 86.54%   | Precision: 86.16% Recall: 86.54% F1: 85.78%

Epoch: 32/150
Train Loss: 0.4509 | Train Acc: 86.99% | Precision: 86.83% Recall: 86.99% F1: 86.19%
Val   Loss: 0.4683 | Val Acc: 86.71%   | Precision: 86.57% Recall: 86.71% F1: 85.67%

Epoch: 33/150
Train Loss: 0.4425 | Train Acc: 87.09% | Precision: 86.96% Recall: 87.09% F1: 86.31%
Val   Loss: 0.4522 | Val Acc: 86.99%   | Precision: 86.94% Recall: 86.99% F1: 85.95%

Epoch: 34/150
Train Loss: 0.4303 | Train Acc: 87.50% | Precision: 87.42% Recall: 87.50% F1: 86.75%
Val   Loss: 0.4286 | Val Acc: 87.43%   | Precision: 87.40% Recall: 87.43% F1: 86.49%

Epoch: 35/150
Train Loss: 0.4244 | Train Acc: 87.61% | Precision: 87.55% Recall: 87.61% F1: 86.91%
Val   Loss: 0.4279 | Val Acc: 87.14%   | Precision: 87.19% Recall: 87.14% F1: 86.05%

Epoch: 36/150
Train Loss: 0.4183 | Train Acc: 87.76% | Precision: 87.68% Recall: 87.76% F1: 87.06%
Val   Loss: 0.4494 | Val Acc: 86.84%   | Precision: 86.74% Recall: 86.84% F1: 86.02%

Epoch: 37/150
Train Loss: 0.4111 | Train Acc: 87.91% | Precision: 87.88% Recall: 87.91% F1: 87.22%
Val   Loss: 0.4206 | Val Acc: 87.32%   | Precision: 87.11% Recall: 87.32% F1: 86.56%

Epoch: 38/150
Train Loss: 0.4037 | Train Acc: 88.11% | Precision: 88.06% Recall: 88.11% F1: 87.45%
Val   Loss: 0.4248 | Val Acc: 87.37%   | Precision: 87.05% Recall: 87.37% F1: 86.78%

Epoch: 39/150
Train Loss: 0.3967 | Train Acc: 88.27% | Precision: 88.23% Recall: 88.27% F1: 87.64%
Val   Loss: 0.4069 | Val Acc: 87.85%   | Precision: 87.83% Recall: 87.85% F1: 86.94%

Epoch: 40/150
Train Loss: 0.3908 | Train Acc: 88.45% | Precision: 88.39% Recall: 88.45% F1: 87.86%
Val   Loss: 0.3906 | Val Acc: 88.56%   | Precision: 88.57% Recall: 88.56% F1: 87.82%

Epoch: 41/150
Train Loss: 0.3856 | Train Acc: 88.53% | Precision: 88.46% Recall: 88.53% F1: 87.95%
Val   Loss: 0.3722 | Val Acc: 88.98%   | Precision: 88.94% Recall: 88.98% F1: 88.41%

Epoch: 42/150
Train Loss: 0.3817 | Train Acc: 88.47% | Precision: 88.38% Recall: 88.47% F1: 87.90%
Val   Loss: 0.4209 | Val Acc: 87.62%   | Precision: 87.52% Recall: 87.62% F1: 86.91%

Epoch: 43/150
Train Loss: 0.3763 | Train Acc: 88.71% | Precision: 88.65% Recall: 88.71% F1: 88.15%
Val   Loss: 0.3919 | Val Acc: 88.07%   | Precision: 88.19% Recall: 88.07% F1: 87.65%

Epoch: 44/150
Train Loss: 0.3666 | Train Acc: 89.13% | Precision: 89.08% Recall: 89.13% F1: 88.60%
Val   Loss: 0.3960 | Val Acc: 88.15%   | Precision: 88.02% Recall: 88.15% F1: 87.29%

Epoch: 45/150
Train Loss: 0.3635 | Train Acc: 89.24% | Precision: 89.19% Recall: 89.24% F1: 88.72%
Val   Loss: 0.3772 | Val Acc: 88.59%   | Precision: 88.59% Recall: 88.59% F1: 88.03%

Epoch: 46/150
Train Loss: 0.3583 | Train Acc: 89.28% | Precision: 89.21% Recall: 89.28% F1: 88.76%
Val   Loss: 0.3767 | Val Acc: 88.95%   | Precision: 88.73% Recall: 88.95% F1: 88.32%

Epoch: 47/150
Train Loss: 0.3536 | Train Acc: 89.45% | Precision: 89.42% Recall: 89.45% F1: 88.95%
Val   Loss: 0.3552 | Val Acc: 89.60%   | Precision: 89.58% Recall: 89.60% F1: 89.04%

Epoch: 48/150
Train Loss: 0.3549 | Train Acc: 89.48% | Precision: 89.41% Recall: 89.48% F1: 88.97%
Val   Loss: 0.3680 | Val Acc: 88.63%   | Precision: 88.62% Recall: 88.63% F1: 88.07%

Epoch: 49/150
Train Loss: 0.3479 | Train Acc: 89.66% | Precision: 89.59% Recall: 89.66% F1: 89.17%
Val   Loss: 0.3520 | Val Acc: 89.16%   | Precision: 89.23% Recall: 89.16% F1: 88.69%

Epoch: 50/150
Train Loss: 0.3444 | Train Acc: 89.92% | Precision: 89.87% Recall: 89.92% F1: 89.44%
Val   Loss: 0.3296 | Val Acc: 90.43%   | Precision: 90.44% Recall: 90.43% F1: 89.93%

Epoch: 51/150
Train Loss: 0.3411 | Train Acc: 89.88% | Precision: 89.80% Recall: 89.88% F1: 89.40%
Val   Loss: 0.3485 | Val Acc: 89.64%   | Precision: 89.63% Recall: 89.64% F1: 88.98%

Epoch: 52/150
Train Loss: 0.3327 | Train Acc: 90.26% | Precision: 90.21% Recall: 90.26% F1: 89.81%
Val   Loss: 0.3593 | Val Acc: 89.45%   | Precision: 89.33% Recall: 89.45% F1: 88.86%

Epoch: 53/150
Train Loss: 0.3280 | Train Acc: 90.40% | Precision: 90.36% Recall: 90.40% F1: 89.97%
Val   Loss: 0.3652 | Val Acc: 89.50%   | Precision: 89.43% Recall: 89.50% F1: 88.75%

Epoch: 54/150
Train Loss: 0.3247 | Train Acc: 90.55% | Precision: 90.53% Recall: 90.55% F1: 90.13%
Val   Loss: 0.3259 | Val Acc: 90.86%   | Precision: 90.69% Recall: 90.86% F1: 90.34%

Epoch: 55/150
Train Loss: 0.3227 | Train Acc: 90.50% | Precision: 90.45% Recall: 90.50% F1: 90.06%
Val   Loss: 0.3200 | Val Acc: 90.33%   | Precision: 90.27% Recall: 90.33% F1: 89.66%

Epoch: 56/150
Train Loss: 0.3202 | Train Acc: 90.63% | Precision: 90.58% Recall: 90.63% F1: 90.21%
Val   Loss: 0.3114 | Val Acc: 90.89%   | Precision: 90.93% Recall: 90.89% F1: 90.34%

Epoch: 57/150
Train Loss: 0.3127 | Train Acc: 90.90% | Precision: 90.86% Recall: 90.90% F1: 90.48%
Val   Loss: 0.3177 | Val Acc: 90.78%   | Precision: 90.75% Recall: 90.78% F1: 90.22%

Epoch: 58/150
Train Loss: 0.3141 | Train Acc: 90.73% | Precision: 90.66% Recall: 90.73% F1: 90.32%
Val   Loss: 0.3089 | Val Acc: 91.31%   | Precision: 91.48% Recall: 91.31% F1: 90.72%

Epoch: 59/150
Train Loss: 0.3074 | Train Acc: 90.97% | Precision: 90.91% Recall: 90.97% F1: 90.56%
Val   Loss: 0.3123 | Val Acc: 90.85%   | Precision: 90.86% Recall: 90.85% F1: 90.34%

Epoch: 60/150
Train Loss: 0.3136 | Train Acc: 90.72% | Precision: 90.63% Recall: 90.72% F1: 90.28%
Val   Loss: 0.3194 | Val Acc: 90.36%   | Precision: 90.36% Recall: 90.36% F1: 89.89%

Epoch: 61/150
Train Loss: 0.2977 | Train Acc: 91.21% | Precision: 91.14% Recall: 91.21% F1: 90.82%
Val   Loss: 0.3331 | Val Acc: 90.20%   | Precision: 90.17% Recall: 90.20% F1: 89.72%

Epoch: 62/150
Train Loss: 0.2955 | Train Acc: 91.33% | Precision: 91.25% Recall: 91.33% F1: 90.94%
Val   Loss: 0.2888 | Val Acc: 91.44%   | Precision: 91.33% Recall: 91.44% F1: 91.04%

Epoch: 63/150
Train Loss: 0.2913 | Train Acc: 91.39% | Precision: 91.34% Recall: 91.39% F1: 91.01%
Val   Loss: 0.3049 | Val Acc: 90.77%   | Precision: 90.69% Recall: 90.77% F1: 90.45%

Epoch: 64/150
Train Loss: 0.2910 | Train Acc: 91.53% | Precision: 91.45% Recall: 91.53% F1: 91.16%
Val   Loss: 0.3131 | Val Acc: 90.73%   | Precision: 90.76% Recall: 90.73% F1: 90.26%

Epoch: 65/150
Train Loss: 0.2909 | Train Acc: 91.51% | Precision: 91.45% Recall: 91.51% F1: 91.14%
Val   Loss: 0.2925 | Val Acc: 91.42%   | Precision: 91.53% Recall: 91.42% F1: 90.92%

Epoch: 66/150
Train Loss: 0.2868 | Train Acc: 91.69% | Precision: 91.65% Recall: 91.69% F1: 91.32%
Val   Loss: 0.2795 | Val Acc: 92.03%   | Precision: 91.96% Recall: 92.03% F1: 91.63%

Epoch: 67/150
Train Loss: 0.2789 | Train Acc: 91.88% | Precision: 91.83% Recall: 91.88% F1: 91.53%
Val   Loss: 0.2856 | Val Acc: 91.61%   | Precision: 91.47% Recall: 91.61% F1: 91.14%

Epoch: 68/150
Train Loss: 0.2757 | Train Acc: 91.97% | Precision: 91.91% Recall: 91.97% F1: 91.63%
Val   Loss: 0.2764 | Val Acc: 91.79%   | Precision: 91.69% Recall: 91.79% F1: 91.41%

Epoch: 69/150
Train Loss: 0.2924 | Train Acc: 91.33% | Precision: 91.24% Recall: 91.33% F1: 90.96%
Val   Loss: 0.2686 | Val Acc: 91.89%   | Precision: 91.82% Recall: 91.89% F1: 91.50%

Epoch: 70/150
Train Loss: 0.2727 | Train Acc: 92.05% | Precision: 91.99% Recall: 92.05% F1: 91.71%
Val   Loss: 0.2610 | Val Acc: 92.09%   | Precision: 92.03% Recall: 92.09% F1: 91.71%

Epoch: 71/150
Train Loss: 0.2667 | Train Acc: 92.28% | Precision: 92.22% Recall: 92.28% F1: 91.94%
Val   Loss: 0.2770 | Val Acc: 91.79%   | Precision: 91.62% Recall: 91.79% F1: 91.44%

Epoch: 72/150
Train Loss: 0.2753 | Train Acc: 91.93% | Precision: 91.87% Recall: 91.93% F1: 91.58%
Val   Loss: 0.2634 | Val Acc: 92.29%   | Precision: 92.21% Recall: 92.29% F1: 91.90%

Epoch: 73/150
Train Loss: 0.2568 | Train Acc: 92.51% | Precision: 92.46% Recall: 92.51% F1: 92.19%
Val   Loss: 0.2748 | Val Acc: 91.90%   | Precision: 91.93% Recall: 91.90% F1: 91.41%

Epoch: 74/150
Train Loss: 0.2599 | Train Acc: 92.30% | Precision: 92.24% Recall: 92.30% F1: 91.98%
Val   Loss: 0.2702 | Val Acc: 91.70%   | Precision: 91.75% Recall: 91.70% F1: 91.25%

Epoch: 75/150
Train Loss: 0.2579 | Train Acc: 92.40% | Precision: 92.33% Recall: 92.40% F1: 92.09%
Val   Loss: 0.2464 | Val Acc: 92.46%   | Precision: 92.48% Recall: 92.46% F1: 92.03%

Epoch: 76/150
Train Loss: 0.2604 | Train Acc: 92.32% | Precision: 92.25% Recall: 92.32% F1: 92.00%
Val   Loss: 0.2854 | Val Acc: 91.65%   | Precision: 91.54% Recall: 91.65% F1: 91.34%

Epoch: 77/150
Train Loss: 0.2555 | Train Acc: 92.51% | Precision: 92.46% Recall: 92.51% F1: 92.21%
Val   Loss: 0.2377 | Val Acc: 92.85%   | Precision: 92.84% Recall: 92.85% F1: 92.46%

Epoch: 78/150
Train Loss: 0.2616 | Train Acc: 92.27% | Precision: 92.21% Recall: 92.27% F1: 91.95%
Val   Loss: 0.2808 | Val Acc: 91.41%   | Precision: 91.42% Recall: 91.41% F1: 90.99%

Epoch: 79/150
Train Loss: 0.2488 | Train Acc: 92.73% | Precision: 92.69% Recall: 92.73% F1: 92.43%
Val   Loss: 0.2459 | Val Acc: 92.62%   | Precision: 92.57% Recall: 92.62% F1: 92.29%

Epoch: 80/150
Train Loss: 0.2448 | Train Acc: 92.78% | Precision: 92.72% Recall: 92.78% F1: 92.48%
Val   Loss: 0.2452 | Val Acc: 92.85%   | Precision: 92.89% Recall: 92.85% F1: 92.43%

Epoch: 81/150
Train Loss: 0.2432 | Train Acc: 92.81% | Precision: 92.76% Recall: 92.81% F1: 92.52%
Val   Loss: 0.2496 | Val Acc: 92.63%   | Precision: 92.61% Recall: 92.63% F1: 92.26%

Epoch: 82/150
Train Loss: 0.2363 | Train Acc: 93.01% | Precision: 92.94% Recall: 93.01% F1: 92.73%
Val   Loss: 0.2959 | Val Acc: 91.34%   | Precision: 91.24% Recall: 91.34% F1: 90.89%

Epoch: 83/150
Train Loss: 0.2469 | Train Acc: 92.63% | Precision: 92.55% Recall: 92.63% F1: 92.34%
Val   Loss: 0.2663 | Val Acc: 91.99%   | Precision: 91.87% Recall: 91.99% F1: 91.69%

Epoch: 84/150
Train Loss: 0.2477 | Train Acc: 92.60% | Precision: 92.52% Recall: 92.60% F1: 92.31%
Val   Loss: 0.2535 | Val Acc: 92.18%   | Precision: 92.23% Recall: 92.18% F1: 91.80%

Epoch: 85/150
Train Loss: 0.2383 | Train Acc: 93.01% | Precision: 92.94% Recall: 93.01% F1: 92.73%
Val   Loss: 0.2353 | Val Acc: 92.89%   | Precision: 92.82% Recall: 92.89% F1: 92.54%

Epoch: 86/150
Train Loss: 0.2295 | Train Acc: 93.29% | Precision: 93.24% Recall: 93.29% F1: 93.03%
Val   Loss: 0.2434 | Val Acc: 92.48%   | Precision: 92.45% Recall: 92.48% F1: 92.14%

Epoch: 87/150
Train Loss: 0.2395 | Train Acc: 92.88% | Precision: 92.83% Recall: 92.88% F1: 92.60%
Val   Loss: 0.2548 | Val Acc: 92.77%   | Precision: 92.70% Recall: 92.77% F1: 92.40%

Epoch: 88/150
Train Loss: 0.2293 | Train Acc: 93.14% | Precision: 93.06% Recall: 93.14% F1: 92.88%
Val   Loss: 0.2624 | Val Acc: 92.45%   | Precision: 92.37% Recall: 92.45% F1: 92.07%

Epoch: 89/150
Train Loss: 0.2349 | Train Acc: 93.08% | Precision: 93.01% Recall: 93.08% F1: 92.81%
Val   Loss: 0.2552 | Val Acc: 92.01%   | Precision: 91.82% Recall: 92.01% F1: 91.70%

Epoch: 90/150
Train Loss: 0.2353 | Train Acc: 93.02% | Precision: 92.96% Recall: 93.02% F1: 92.75%
Val   Loss: 0.2246 | Val Acc: 92.92%   | Precision: 92.81% Recall: 92.92% F1: 92.60%

Epoch: 91/150
Train Loss: 0.2199 | Train Acc: 93.57% | Precision: 93.51% Recall: 93.57% F1: 93.34%
Val   Loss: 0.2439 | Val Acc: 92.41%   | Precision: 92.43% Recall: 92.41% F1: 92.06%

Epoch: 92/150
Train Loss: 1.1852 | Train Acc: 64.98% | Precision: 61.16% Recall: 64.98% F1: 56.18%
Val   Loss: 1.0815 | Val Acc: 63.66%   | Precision: 43.40% Recall: 63.66% F1: 50.65%

Epoch: 93/150
Train Loss: 1.0642 | Train Acc: 64.13% | Precision: 46.10% Recall: 64.13% F1: 52.10%
Val   Loss: 1.0571 | Val Acc: 64.32%   | Precision: 46.93% Recall: 64.32% F1: 53.27%

Epoch: 94/150
Train Loss: 1.0439 | Train Acc: 64.71% | Precision: 47.47% Recall: 64.71% F1: 53.68%
Val   Loss: 1.0326 | Val Acc: 64.88%   | Precision: 47.76% Recall: 64.88% F1: 54.19%

Epoch: 95/150
Train Loss: 1.0200 | Train Acc: 64.82% | Precision: 48.13% Recall: 64.82% F1: 54.07%
Val   Loss: 1.0117 | Val Acc: 64.09%   | Precision: 46.94% Recall: 64.09% F1: 53.61%

Epoch: 96/150
Train Loss: 0.9712 | Train Acc: 64.61% | Precision: 50.68% Recall: 64.61% F1: 54.51%
Val   Loss: 0.9422 | Val Acc: 64.31%   | Precision: 47.03% Recall: 64.31% F1: 53.70%

Epoch: 97/150
Train Loss: 0.9151 | Train Acc: 67.36% | Precision: 56.42% Recall: 67.36% F1: 60.00%
Val   Loss: 0.8954 | Val Acc: 66.57%   | Precision: 58.75% Recall: 66.57% F1: 58.45%

Epoch: 98/150
Train Loss: 0.8901 | Train Acc: 68.90% | Precision: 57.88% Recall: 68.90% F1: 62.16%
Val   Loss: 0.8778 | Val Acc: 69.63%   | Precision: 60.19% Recall: 69.63% F1: 63.56%

Epoch: 99/150
Train Loss: 0.8662 | Train Acc: 69.63% | Precision: 65.14% Recall: 69.63% F1: 63.07%
Val   Loss: 0.8422 | Val Acc: 70.67%   | Precision: 59.72% Recall: 70.67% F1: 63.81%

Epoch: 100/150
Train Loss: 0.8483 | Train Acc: 70.22% | Precision: 64.60% Recall: 70.22% F1: 63.82%
Val   Loss: 0.8643 | Val Acc: 70.40%   | Precision: 58.68% Recall: 70.40% F1: 63.23%

Epoch: 101/150
Train Loss: 0.8294 | Train Acc: 70.90% | Precision: 65.50% Recall: 70.90% F1: 64.78%
Val   Loss: 0.8224 | Val Acc: 71.88%   | Precision: 61.60% Recall: 71.88% F1: 65.51%

Epoch: 102/150
Train Loss: 0.8035 | Train Acc: 72.37% | Precision: 66.13% Recall: 72.37% F1: 66.35%
Val   Loss: 0.7741 | Val Acc: 74.88%   | Precision: 67.92% Recall: 74.88% F1: 68.99%

Epoch: 103/150
Train Loss: 0.7659 | Train Acc: 74.25% | Precision: 67.62% Recall: 74.25% F1: 68.51%
Val   Loss: 0.8025 | Val Acc: 72.37%   | Precision: 66.04% Recall: 72.37% F1: 66.97%

Epoch: 104/150
Train Loss: 0.7207 | Train Acc: 76.22% | Precision: 69.97% Recall: 76.22% F1: 70.77%
Val   Loss: 0.6692 | Val Acc: 77.54%   | Precision: 72.71% Recall: 77.54% F1: 71.82%

Epoch: 105/150
Train Loss: 0.7117 | Train Acc: 76.17% | Precision: 69.93% Recall: 76.17% F1: 71.05%
Val   Loss: 0.6858 | Val Acc: 77.43%   | Precision: 71.29% Recall: 77.43% F1: 72.94%

Epoch: 106/150
Train Loss: 0.6625 | Train Acc: 78.04% | Precision: 72.00% Recall: 78.04% F1: 73.37%
Val   Loss: 0.6193 | Val Acc: 80.71%   | Precision: 74.86% Recall: 80.71% F1: 77.19%

Epoch: 107/150
Train Loss: 0.6571 | Train Acc: 78.41% | Precision: 78.84% Recall: 78.41% F1: 74.07%
Val   Loss: 0.6336 | Val Acc: 79.24%   | Precision: 74.35% Recall: 79.24% F1: 73.83%

Epoch: 108/150
Train Loss: 0.6357 | Train Acc: 79.22% | Precision: 77.88% Recall: 79.22% F1: 75.19%
Val   Loss: 0.5940 | Val Acc: 80.75%   | Precision: 75.63% Recall: 80.75% F1: 76.33%

Epoch: 109/150