# Estimando distribuciones (parte 1)
El objetivo de esta notebook es explorar una primera manera de aproximar $p(y|x)$ y $p(x|y)$ en un set de datos tabular. En este set de datos $x$ tiene valores discretos, $x\in\mathbb{D}^k$, y el target $y$ es un booleano, $y\in\{0,1\}$.

## Imports

In [1]:
import numpy as np
import pandas as pd
import random

## Cargamos los datos

In [2]:
df = pd.read_csv('./tennis.csv', delimiter=',', header=0)
df

    Day   Outlook  Temp Humidity    Wind Tennis
0    D1     Sunny   Hot     High    Weak     No
1    D2     Sunny   Hot     High  Strong     No
2    D3  Overcast   Hot     High    Weak    Yes
3    D4      Rain  Mild     High    Weak    Yes
4    D5      Rain  Cool   Normal    Weak    Yes
5    D6      Rain  Cool   Normal  Strong     No
6    D7  Overcast  Cool   Normal  Strong    Yes
7    D8     Sunny  Mild     High    Weak     No
8    D9     Sunny  Cool   Normal    Weak    Yes
9   D10      Rain  Mild   Normal    Weak    Yes
10  D11     Sunny  Mild   Normal  Strong    Yes
11  D12  Overcast  Mild     High  Strong    Yes
12  D13  Overcast   Hot   Normal    Weak    Yes
13  D14      Rain  Mild     High  Strong     No

### Eliminamos la columna Day

In [3]:
df = df.drop('Day', axis=1)
df

     Outlook  Temp Humidity    Wind Tennis
0      Sunny   Hot     High    Weak     No
1      Sunny   Hot     High  Strong     No
2   Overcast   Hot     High    Weak    Yes
3       Rain  Mild     High    Weak    Yes
4       Rain  Cool   Normal    Weak    Yes
5       Rain  Cool   Normal  Strong     No
6   Overcast  Cool   Normal  Strong    Yes
7      Sunny  Mild     High    Weak     No
8      Sunny  Cool   Normal    Weak    Yes
9       Rain  Mild   Normal    Weak    Yes
10     Sunny  Mild   Normal  Strong    Yes
11  Overcast  Mild     High  Strong    Yes
12  Overcast   Hot   Normal    Weak    Yes
13      Rain  Mild     High  Strong     No

In [4]:
X_names = df.columns.to_list()[:-1]
X_names

['Outlook', 'Temp', 'Humidity', 'Wind']

Guardamos en la variable $X$ todas las features del dataset.

In [5]:
X = df.iloc[:,0:-1]
X

     Outlook  Temp Humidity    Wind
0      Sunny   Hot     High    Weak
1      Sunny   Hot     High  Strong
2   Overcast   Hot     High    Weak
3       Rain  Mild     High    Weak
4       Rain  Cool   Normal    Weak
5       Rain  Cool   Normal  Strong
6   Overcast  Cool   Normal  Strong
7      Sunny  Mild     High    Weak
8      Sunny  Cool   Normal    Weak
9       Rain  Mild   Normal    Weak
10     Sunny  Mild   Normal  Strong
11  Overcast  Mild     High  Strong
12  Overcast   Hot   Normal    Weak
13      Rain  Mild     High  Strong

In [6]:
Y_name = df.columns.to_list()[-1]
Y_name

'Tennis'

Guardamos en $Y$ el objetivo

In [7]:
Y = df.iloc[:,-1]
Y

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Tennis, dtype: str

## Construimos una tabla de observaciones

En este paso vamos a crear una tabla de observaciones. Esta tabla tiene que contener la frecuencia de cada observación. Para este ejemplo tomaremos a $x$ como **Outlook**.

Calcule las dimensiones de la tabla

In [11]:
# Cantidad total de elementos
N = X['Outlook'].count()

# Elementos únicos de la clase Outlook
xvalues = X['Outlook'].unique()
dimx = len(xvalues)

# Elementos únicos del objetivo
yvalues = Y.unique()
dimy = len(yvalues)

print(f'Cantidad total de elementos: {N}')
print(f'Elementos únicos de la clase Outlook: {xvalues}')
print(f'Elementos únicos del objetivo: {yvalues}')

Cantidad total de elementos: 14
Elementos únicos de la clase Outlook: <StringArray>
['Sunny', 'Overcast', 'Rain']
Length: 3, dtype: str
Elementos únicos del objetivo: <StringArray>
['No', 'Yes']
Length: 2, dtype: str

Calculamos la tabla de frecuencia.

In [ ]:
obs = pd.DataFrame(0, columns=yvalues, index=xvalues)

## Llene la tabla de observaciones

obs.loc['Sunny', 'No'] = len(df[(df['Outlook'] == 'Sunny') & (df['Tennis'] == 'No')])
obs.loc['Sunny', 'Yes'] = len(df[(df['Outlook'] == 'Sunny') & (df['Tennis'] == 'Yes')])

obs.loc['Overcast', 'No'] = len(df[(df['Outlook'] == 'Overcast') & (df['Tennis'] == 'No')])
obs.loc['Overcast', 'Yes'] = len(df[(df['Outlook'] == 'Overcast') & (df['Tennis'] == 'Yes')])

obs.loc['Rain', 'No'] = len(df[(df['Outlook'] == 'Rain') & (df['Tennis'] == 'No')])
obs.loc['Rain', 'Yes'] = len(df[(df['Outlook'] == 'Rain') & (df['Tennis'] == 'Yes')])

obs

          No  Yes
Sunny      3    2
Overcast   0    4
Rain       2    3

## Aproximación de la distribución conjunta $p(x,y)$

Tome a $x$ como Outlook y aproxime la distribución conjunta utilizando la tabla de observaciones.

In [19]:
joint_x_y = obs / N
joint_x_y

                No       Yes
Sunny     0.214286  0.142857
Overcast  0.000000  0.285714
Rain      0.142857  0.214286

1. ¿Qué significa el valor calculado en los índices "Sunny", "Yes"?

2. ¿Justifique el resultado de la pareja "Overcast", "No"?

## Aproximamos $p(y|x)$

Tome a $x$ como **Outlook** y estime la probabilidad condicional de $y$ dado $x$. Luego realice una muestra de 10 valores de $y$ dado $x = Sunny$.

Calculamos la cantidad de entradas por cada valor distinto de $x$.

In [ ]:
m = obs.sum(axis=1)
obs['m'] = m
m

Calculamos la cantidad de entradas por cada valor distinto de $y$.

In [ ]:
l = obs.sum(axis=0)
obs.loc['l'] = l
l

In [ ]:
obs

Calcule la probabilidad condicional de $y$ dado $x$.

In [ ]:
p_y_x = pd.DataFrame(0, columns=yvalues, index=xvalues)

## Llene la tabla de probabilidades condicionales p(y|x)

p_y_x

3. ¿La suma de cada fila siempre tiene que dar 1? ¿Por qué?

4. ¿Y si la suma de las columnas?

Realice 10 muestras de $y$ dado $x = Sunny$.

Puede utilizar la función random.choice de numpy. https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html

In [ ]:
sampled_values = ...

sampled_values

5. ¿Qué pasaría si utilizamos $x = Overcast$ en vez de $x = Sunny$? ¿Tiene sentido que pase esto? ¿Por qué?

## Aproximamos $p(x|y)$
Tome a $x$ como Outlook y estime la probabilidad condicional de $x$ dado $y$ basandose en la tabla de observaciones. Luego realice 10 muestras de $x$ dado $y = Yes$.

$p(x|y)$

In [ ]:
p_x_y = pd.DataFrame(0, columns=yvalues, index=xvalues)

## Llene la tabla de probabilidades condicionales p(x|y)

p_x_y

Muestreo

In [ ]:
sampled_values = ...

sampled_values

## Aproxime $p(y,o,h,w,t)$

Aproxime la proabilidad conjunta del Tennis (y), Outlook (o), Humidity (h), Wind (w), Temp (t).

Recuerde que $p(y,o,h,w,t)$ = $p(y)$.$p(o|y)$.$p(h|y,o)$.$p(w|y,o,h)$.$p(t|y,o,h,w)$

Calcule P(y)

In [ ]:
# P(Y)
p_y = ...
p_y

Calcule P(o|y)

In [ ]:
p_o_y = ...
p_o_y

Calcule P(h|y,o)

Recomendamos usar la función *crosstab* de pandas. En este link pueden encontrar un ejemplo de su uso: https://www.geeksforgeeks.org/pandas-crosstab-function-in-python/

In [ ]:
# Calcule la tabla de frecuencia
p_h_yo = ...

# Luego se divide cada fila por la suma de sus elementos, puede usar las funciones div y sum de pandas
p_h_yo = ...

# No se oliden de llenar los valores NaN!!!

# Cambiamos los nombres de los indices (si es que lo precisa)


p_h_yo

Calcule P(w|y,o,h)

In [ ]:
p_w_yoh = ...
p_w_yoh = ...
p_w_yoh

Calcule P(t|y,o,h,w)

In [ ]:
p_t_yohw = ...
p_t_yohw = ...
p_t_yohw

Calcule P(y,o,h,w,t)

In [ ]:
# Definimos una función que nos calcula la probabilidad conjunta usando la regla del producto.
def calculate_prob(y,o,h,w,t):
    "Calculate the probability of occurrence of a row"
    ...

In [ ]:
prob = calculate_prob('Yes','Sunny','Normal','Weak','Cool')

print(f'P(Yes|Sunny,Normal,Weak,Cool) = {prob}')
print(f"Cantidad de observaciones: {prob*N}")

Definimos el muestreo de datos completos.

Primero generamos un *y* utilizando *p(y)* y luego seguimos con las probabilidades condicionales.

In [ ]:
def sample_from_y(y):
    "Generates a sample of weather conditions based on a specific y"
    ...

def sample():
    "Generates a sample of weather conditions based on a random y"
    ...

In [ ]:
samples = np.array([sample() for _ in range(len(df))])
new_df = pd.DataFrame(samples, columns=['Tennis', 'Outlook', 'Humidity', 'Wind', 'Temp'])
new_df